# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-06 14:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0002_auto_20200706_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='segmenttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
