# Generated by Django 2.2.24 on 2021-11-22 14:22

from django.db import migrations
from django.template.defaultfilters import slugify

def set_segment_slugs(apps, schema_editor):
    Segment = apps.get_model('segments', 'Segment')

    for segment in Segment.objects.all():
        segment.slug = slugify(segment.name)
        segment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0007_segment_slug'),
    ]

    operations = [
        migrations.RunPython(set_segment_slugs, migrations.RunPython.noop)
    ]
