# Generated by Django 2.2.24 on 2021-11-23 14:33

import bluebottle.utils.fields
import bluebottle.utils.validators
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0009_auto_20211122_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='Background color'),
        ),
        migrations.AddField(
            model_name='segment',
            name='cover_image',
            field=bluebottle.utils.fields.ImageField(blank=True, help_text='Category Logo image', max_length=255, null=True, upload_to='categories/logos/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='segment',
            name='logo',
            field=bluebottle.utils.fields.ImageField(blank=True, help_text='Category Logo image', max_length=255, null=True, upload_to='categories/logos/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='segment',
            name='tag_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
