# Generated by Django 2.2.24 on 2021-12-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0014_auto_20211210_1245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together={('slug', 'segment_type')},
        ),
    ]
