# Generated by Django 2.2.24 on 2022-02-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0016_auto_20220118_1031'),
        ('segments', '0007_auto_20220119_0945'),
    ]

    operations = [
    ]
