# Generated by Django 2.2.24 on 2022-01-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0016_auto_20220118_1031'),
        ('segments', '0015_segment_closed'),
    ]

    operations = [
    ]
