# Generated by Django 2.2.24 on 2022-01-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0017_merge_20220119_1722'),
        ('segments', '0017_merge_20220119_1354'),
    ]

    operations = [
    ]
