# Generated by Django 2.2.24 on 2022-02-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0017_merge_20220202_1244'),
        ('segments', '0019_merge_20220120_1134'),
    ]

    operations = [
    ]
