# Generated by Django 2.2.24 on 2022-02-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0020_auto_20220203_1157'),
        ('segments', '0020_merge_20220203_0949'),
    ]

    operations = [
    ]
