# Generated by Django 2.2.24 on 2022-02-09 12:08

from django.db import migrations


def migrate_email_domains(apps, schema_editor):
    Segment = apps.get_model('segments', 'Segment')

    for segment in Segment.objects.filter(email_domain__gt='').all():
        segment.email_domains = [segment.email_domain]
        segment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0021_merge_20220207_1417'),
    ]

    operations = [
        migrations.RunPython(
            migrate_email_domains,
            migrations.RunPython.noop
        )
    ]
