# Generated by Django 2.2.24 on 2022-02-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0024_auto_20220210_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenttype',
            name='required',
            field=models.BooleanField(default=False, help_text='User can only use the platform is they have a value for this segment in their profile', verbose_name='Reuired'),
        ),
    ]
