# Generated by Django 2.2.24 on 2022-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0026_auto_20220215_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenttype',
            name='visibility',
            field=models.BooleanField(default=True, help_text='Show segment on the activity detail page', verbose_name='Visibility'),
        ),
    ]
