# Generated by Django 2.2.24 on 2022-06-21 11:23

from django.db import migrations


def fix_segment_names(apps, schema_editor):
    Segment = apps.get_model('segments', 'Segment')
    for segment in Segment.objects.filter(name=''):
        segment.name = segment.slug.replace('-', ' ').title()
        segment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0027_auto_20220621_1241'),
    ]

    operations = [
        migrations.RunPython(
            fix_segment_names,
            migrations.RunPython.noop
        )
    ]


