# Generated by Django 2.2.24 on 2023-06-20 13:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0029_auto_20221031_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Add a button colour to your segment page.', max_length=18, null=True, samples=None, verbose_name='Button color'),
        ),
        migrations.AddField(
            model_name='segment',
            name='button_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='Add a button text colour to your segment page.', max_length=18, null=True, samples=None, verbose_name='Button text color'),
        ),
    ]
