# Generated by Django 4.2.20 on 2025-03-20 08:50

import bluebottle.bluebottle_dashboard.quill
import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0031_auto_20250225_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='cover_image',
            field=bluebottle.utils.fields.ImageField(blank=True, help_text='The uploaded image will be cropped to fit a 16:9 rectangle.', max_length=255, null=True, upload_to='categories/logos/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='story',
            field=bluebottle.bluebottle_dashboard.quill.RichTextField(blank=True, help_text='A more detailed story for your segment. This story can be accessed via a link on the page.', null=True, verbose_name='Story'),
        ),
    ]
