# Generated by Django 4.2.20 on 2025-12-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0033_segmenttype_admin_activity_filter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ('old_name',)},
        ),
        migrations.AlterModelOptions(
            name='segmenttype',
            options={'ordering': ('old_name',)},
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='name',
            new_name='old_name',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='story',
            new_name='old_story',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='tag_line',
            new_name='old_tag_line',
        ),
        migrations.RenameField(
            model_name='segmenttype',
            old_name='name',
            new_name='old_name',
        ),
        migrations.AlterField(
            model_name='segmenttype',
            name='admin_activity_filter',
            field=models.BooleanField(default=False, help_text='When enabled, members managing this segment will only see activities linked to this segment.', verbose_name='Segment manager filter - Activities'),
        ),
        migrations.AlterField(
            model_name='segmenttype',
            name='admin_user_filter',
            field=models.BooleanField(default=False, help_text='When enabled, members managing this segment will only see members linked to this segment.', verbose_name='Segment manager filter - Members'),
        ),
    ]
