# Generated by Django 4.2.20 on 2025-12-16 13:46

from django.db import migrations, models
from django.db.migrations.operations.base import Operation
from django.db.migrations.state import ModelState
import django.db.models.deletion
import django_quill.fields
import parler.fields
import parler.models
from parler.models import TranslatableModel


class AlterModelBases(Operation):
    """
    State-only operation: change model bases in the migration state,
    but don't touch the database.
    """

    reduces_to_sql = False
    reversible = True

    def __init__(self, name, bases):
        self.name = name
        self.bases = bases  # tuple of strings

    def state_forwards(self, app_label, state):
        key = (app_label, self.name.lower())
        model_state = state.models[key]

        state.models[key] = ModelState(
            app_label=model_state.app_label,
            name=model_state.name,
            fields=model_state.fields,
            options=model_state.options,
            bases=self.bases,
            managers=model_state.managers,
        )

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # No DB changes
        pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # If you ever need to reverse, you could restore the old bases here
        pass

    def describe(self):
        return f"Alter bases for {self.name}"

    def deconstruct(self):
        return (
            self.__class__.__name__,
            [],
            {"name": self.name, "bases": self.bases},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0034_alter_segment_options_alter_segmenttype_options_and_more'),
    ]

    operations = [
        # Ensure SegmentType and Segment are recognized as TranslatableModel
        # before creating translation models
        AlterModelBases(
            name="SegmentType",
            bases=(TranslatableModel, models.Model),
        ),
        AlterModelBases(
            name="Segment",
            bases=(TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='SegmentTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='segments.segmenttype')),
            ],
            options={
                'verbose_name': 'segment type Translation',
                'db_table': 'segments_segmenttype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SegmentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slogan', models.CharField(blank=True, help_text='A short sentence to explain your segment. This sentence is directly visible on the page.', max_length=255, null=True, verbose_name='Slogan')),
                ('story', django_quill.fields.QuillField(blank=True, help_text='A more detailed story for your segment. This story can be accessed via a link on the page.', null=True, verbose_name='Story')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='segments.segment')),
            ],
            options={
                'verbose_name': 'segment Translation',
                'db_table': 'segments_segment_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
