# Generated by Django 4.2.20 on 2025-12-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0036_auto_20251216_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='segmenttype',
            options={},
        ),
        migrations.RemoveField(
            model_name='segment',
            name='old_name',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='old_story',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='old_tag_line',
        ),
        migrations.RemoveField(
            model_name='segmenttype',
            name='old_name',
        ),
    ]
