# Generated by Django 4.2.20 on 2026-02-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0037_alter_segment_options_alter_segmenttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenttype',
            name='external_url',
            field=models.URLField(blank=True, help_text='When set, GoodUp Connect will be used to retrieve the segments', null=True, verbose_name='External reference url'),
        ),
    ]
