# Generated by Django 5.2.15 on 2026-07-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0037_alter_segment_options_alter_segmenttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='segmenttype',
            options={'ordering': ['pk']},
        ),
    ]
