# Generated by Django 4.2.20 on 2026-02-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0070_alter_activitypubmodel_part_of'),
        ('segments', '0038_segmenttype_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_segment', to='activity_pub.document'),
        ),
    ]
