# Generated by Django 2.2.24 on 2021-09-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0045_auto_20210920_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Collect',
                'verbose_name_plural': 'Collects',
                'permissions': (('api_read_collect', 'Can view collect activity through the API'), ('api_add_collect', 'Can add collect activity through the API'), ('api_change_collect', 'Can change collect activity through the API'), ('api_delete_collect', 'Can delete collect activity through the API'), ('api_read_own_collect', 'Can view own collect activity through the API'), ('api_add_own_collect', 'Can add own collect activity through the API'), ('api_change_own_collect', 'Can change own collect activity through the API'), ('api_delete_own_collect', 'Can delete own collect activity through the API')),
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='CollectContributor',
            fields=[
                ('contributor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Contributor')),
            ],
            options={
                'verbose_name': 'Contributor',
                'verbose_name_plural': 'Contributors',
                'permissions': (('api_read_collectcontributor', 'Can view collect through the API'), ('api_add_collectcontributor', 'Can add collect through the API'), ('api_change_collectcontributor', 'Can change collect through the API'), ('api_delete_collectcontributor', 'Can delete collect through the API'), ('api_read_own_collectcontributor', 'Can view own collect through the API'), ('api_add_own_collectcontributor', 'Can add own collect through the API'), ('api_change_own_collectcontributor', 'Can change own collect through the API'), ('api_delete_own_collectcontributor', 'Can delete own collect through the API')),
            },
            bases=('activities.contributor',),
        ),
    ]
