# Generated by Django 2.2.24 on 2021-09-22 13:02

from django.db import migrations, connection

from bluebottle.clients import properties
from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        group_perms = {
            'Staff': {
                'perms': (
                    'add_collectactivity', 'change_collectactivity', 'delete_collectactivity',
                    'add_collectcontributor', 'change_collectcontributor', 'delete_collectcontributor',
                    'add_collecttype', 'change_collecttype', 'delete_collecttype',
                )
            },
            'Anonymous': {
                'perms': (
                    'api_read_collect', 'api_read_collecttype', 'api_read_collectcontributor'
                ) if not properties.CLOSED_SITE else ()
            },
            'Authenticated': {
                'perms': (
                    'api_read_collect', 'api_add_own_collect', 'api_change_own_collect', 'api_delete_own_collect',
                    'api_read_collectcontributor', 'api_add_own_collectcontributor',
                    'api_change_own_collectcontributor', 'api_delete_own_collectcontributor',
                    'api_read_collecttype',
                )
            }
    }

    update_group_permissions('collect', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_auto_20210922_1502'),
    ]

    operations = [
        migrations.RunPython(
            add_group_permissions,
            migrations.RunPython.noop
        )
    ]
