# Generated by Django 2.2.24 on 2021-09-27 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0027_auto_20210927_1047'),
        ('collect', '0005_auto_20210922_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectactivity',
            options={'permissions': (('api_read_collect', 'Can view collect activity through the API'), ('api_add_collect', 'Can add collect activity through the API'), ('api_change_collect', 'Can change collect activity through the API'), ('api_delete_collect', 'Can delete collect activity through the API'), ('api_read_own_collect', 'Can view own collect activity through the API'), ('api_add_own_collect', 'Can add own collect activity through the API'), ('api_change_own_collect', 'Can change own collect activity through the API'), ('api_delete_own_collect', 'Can delete own collect activity through the API')), 'verbose_name': 'Collect Activity', 'verbose_name_plural': 'Collect Activities'},
        ),
        migrations.AlterModelOptions(
            name='collectcontributor',
            options={'permissions': (('api_read_collectcontributor', 'Can view collect contributor through the API'), ('api_add_collectcontributor', 'Can add collect contributor  through the API'), ('api_change_collectcontributor', 'Can change collect contributor  through the API'), ('api_delete_collectcontributor', 'Can delete collect contributor  through the API'), ('api_read_own_collectcontributor', 'Can view own collect contributor through the API'), ('api_add_own_collectcontributor', 'Can add own collect contributor through the API'), ('api_change_own_collectcontributor', 'Can change own collect contributor through the API'), ('api_delete_own_collectcontributor', 'Can delete own collect contributor through the API')), 'verbose_name': 'Collect contributor', 'verbose_name_plural': 'Collect contributors'},
        ),
        migrations.AddField(
            model_name='collectactivity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Geolocation'),
        ),
    ]
