# Generated by Django 2.2.24 on 2021-11-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0008_collectactivity_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectcontributor',
            name='value',
        ),
        migrations.RemoveField(
            model_name='collecttypetranslation',
            name='description',
        ),
        migrations.AddField(
            model_name='collectactivity',
            name='location_hint',
            field=models.TextField(blank=True, null=True, verbose_name='location hint'),
        ),
        migrations.AddField(
            model_name='collectactivity',
            name='realized',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='collecttypetranslation',
            name='unit',
            field=models.TextField(blank=True, verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='collecttypetranslation',
            name='unit_plural',
            field=models.TextField(blank=True, verbose_name='unit_plural'),
        ),
    ]
