# Generated by Django 2.2.24 on 2021-11-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0009_auto_20211102_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectContribution',
            fields=[
                ('contribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Contribution')),
                ('value', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Collect contribution',
                'verbose_name_plural': 'Collect contributions',
            },
            bases=('activities.contribution',),
        ),
        migrations.AddField(
            model_name='collectcontributor',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
