# Generated by Django 2.2.24 on 2021-11-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0012_auto_20211103_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecttype',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='disabled'),
        ),
        migrations.AlterField(
            model_name='collecttypetranslation',
            name='name',
            field=models.CharField(help_text='E.g. "Bicycles", "Clothing" or "Groceries"', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collecttypetranslation',
            name='unit',
            field=models.CharField(help_text='Singular form of the things that are collects. E.g. "Bicycle", "Bag off clothing", "Crate of groceries', max_length=100, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='collecttypetranslation',
            name='unit_plural',
            field=models.CharField(help_text='Plural form of the things that are collects. E.g. "Bicycles", "Bags off clothing", "Crates of groceries', max_length=100, verbose_name='unit plural'),
        ),
    ]
