# Generated by Django 2.2.24 on 2021-11-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0014_create_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectcontribution',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collect.CollectType'),
        ),
        migrations.AlterField(
            model_name='collecttype',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Disable this item so it cannot be selected when creating an activity.', verbose_name='disabled'),
        ),
        migrations.AlterField(
            model_name='collecttypetranslation',
            name='name',
            field=models.CharField(help_text='The item to be collected (E.g. Bicycles, Clothing, Groceries, …)', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collecttypetranslation',
            name='unit',
            field=models.CharField(help_text='The unit in which you want to count the item (E.g. Bicycle, Bag of clothing, Crate of groceries, …)', max_length=100, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='collecttypetranslation',
            name='unit_plural',
            field=models.CharField(help_text='The unit in which you want to count the item (E.g. Bicycles, Bags of clothing, Crates of groceries, …)', max_length=100, verbose_name='unit plural'),
        ),
    ]
