# Generated by Django 3.2.20 on 2024-11-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0018_auto_20241106_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectactivity',
            name='enable_impact',
        ),
    ]
