# Generated by Django 4.2.20 on 2026-03-19 13:34

from django.db import migrations

PERMISSIONS = [
       'api_read_collect',
       'api_add_collect',
       'api_change_collect',
       'api_delete_collect',

       'api_read_own_collect',
       'api_add_own_collect',
       'api_change_own_collect',
       'api_delete_own_collect',
]

def rename_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')

    for group in Group.objects.all():
        for codename in PERMISSIONS:
            incorrect_permission = Permission.objects.get(codename=codename)
            if incorrect_permission in group.permissions.all():
                correct_permission = Permission.objects.get(
                    codename=codename.replace('_collect', '_collectactivity')
                )

                group.permissions.add(correct_permission)
                group.permissions.remove(incorrect_permission)
                group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0019_remove_collectactivity_enable_impact'),
    ]

    operations = [
        migrations.RunPython(rename_permissions)
    ]
