# Generated by Django 4.2.20 on 2025-12-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0019_remove_collectactivity_enable_impact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collecttype',
            options={'ordering': ('pk',), 'permissions': (('api_read_collecttype', 'Can view collect items through API'),), 'verbose_name': 'items', 'verbose_name_plural': 'item'},
        ),
    ]
