# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_auto_20161115_1601'),
        ('slides', '0002_auto_20161109_1024'),
    ]

    operations = [
    ]
