# Generated by Django 3.2.19 on 2023-07-19 11:30

import bluebottle.files.validators
import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0008_auto_20230322_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='background_image',
            field=bluebottle.utils.fields.ImageField(blank=True, help_text='The ideal image will have an aspect ratio of 21:9 on large screens and 4:3 on mobile (Sides of the image maybe slightly cropped on mobile screens). Image should be no larger than 2Mb.', max_length=255, null=True, upload_to='banner_slides/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='body',
            field=models.TextField(blank=True, help_text='Body text has a limit of 140 characters.', max_length=225, verbose_name='Body text'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='language',
            field=models.CharField(choices=[('en', 'English')], max_length=7, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link_text',
            field=models.CharField(blank=True, help_text='This is the text displayed on the button.', max_length=400, verbose_name='Button label'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link_url',
            field=models.CharField(blank=True, help_text='This is the URL to which the button links.', max_length=400, verbose_name='Button URL'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], db_index=True, default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=72, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='video',
            field=models.FileField(blank=True, help_text='This video will autoplay and loop in the background, without sound. Allowed formats are mp4, ogg, 3gp, avi, mov and webm. The file should be smaller than 10 MB. Adding a background video will replace the background image.', max_length=255, null=True, upload_to='banner_slides/', validators=[bluebottle.files.validators.validate_video_file_size, bluebottle.utils.validators.FileMimetypeValidator(['video/ogg', 'video/mp4', 'video/webm', 'video/3gpp', 'video/x-msvideo', 'video/quicktime'], None, 'invalid_mimetype')], verbose_name='Background video'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text="YouTube and Vimeo videos are supported, add the video by pasting their URL above. This will add a 'play' button to the slider. The video will play after the 'Play' button is selected.", max_length=100, verbose_name='Video'),
        ),
    ]
