# Generated by Django 4.2.20 on 2025-04-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_add_permissions_20230130_1255'),
        ('slides', '0010_auto_20240815_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='sub_regions',
            field=models.ManyToManyField(blank=True, help_text='Select office groups to make the slide only visible to visitors from those regions or leave empty to make the slide visible for everyone.', related_name='slides', to='offices.officesubregion', verbose_name='Office group'),
        ),
    ]
