# Generated by Django 4.2.20 on 2025-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_add_permissions_20230130_1255'),
        ('slides', '0013_remove_slide_sub_region_alter_slide_sub_regions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='sub_regions',
            field=models.ManyToManyField(blank=True, help_text='Select office groups to make the slide only visible to visitors from those regions or leave empty to make the slide visible for everyone.', related_name='slides', to='offices.officesubregion', verbose_name='Office groups'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=72, verbose_name='Title'),
        ),
    ]
