# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-12 11:19
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0008_auto_20190612_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['-activity__created', 'amount'], 'verbose_name': 'Gift', 'verbose_name_plural': 'Gifts'},
        ),
        migrations.AddField(
            model_name='donation',
            name='fundraiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='funding.Fundraiser'),
        ),
        migrations.AddField(
            model_name='donation',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='funding.Reward'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgetlines', to='funding.Funding'),
        ),
    ]
