# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-15 07:26
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('funding', '0010_auto_20190612_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingPlatformSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
                ('show_donation_amounts', models.BooleanField(default=True, verbose_name='show donation amounts')),
            ],
            options={
                'verbose_name': 'funding platform settings',
                'verbose_name_plural': 'funding platform settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[(b'default', 'Default')], default=b'default', max_length=100, verbose_name='Payment method')),
                ('currencies', multiselectfield.db.fields.MultiSelectField(choices=[(b'EUR', 'Euro')], max_length=100)),
                ('funding_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.FundingPlatformSettings')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_funding.paymentprovider_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': (('refund_payment', 'Can refund payments'),)},
        ),
   ]
