# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-10 12:55
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0012_auto_20190708_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'budget line', 'verbose_name_plural': 'budget lines'},
        ),
        migrations.AlterField(
            model_name='funding',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payouts.PayoutAccount'),
        ),
    ]
