# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-11 07:27
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0012_auto_20190708_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='amount_matching',
            field=bluebottle.utils.fields.MoneyField(blank=True, currency_choices="[('EUR', u'Euro')]", decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='funding',
            name='amount_matching_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
    ]
