# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-14 12:40
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0013_auto_20190711_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='amount_matching',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='funding',
            name='target',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), max_digits=12),
        )
    ]
