# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-17 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0013_auto_20190711_0927'),
        ('funding', '0014_auto_20190716_1636'),
    ]

    operations = [
    ]
