# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-28 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0015_auto_20190728_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funding.PayoutAccount'),
        ),
    ]
