# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-28 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0016_auto_20190728_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutaccount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payoutaccount',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payoutaccount',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
