# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-29 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0015_merge_20190717_1651'),
        ('funding', '0017_auto_20190728_1319'),
    ]

    operations = [
    ]
