# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-30 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0019_auto_20190729_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Override donor name / Name for guest donation'),
        ),
    ]
