# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-03 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0020_donation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deadline'),
        ),
    ]
