# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-04 10:00
from __future__ import unicode_literals

from django.db import migrations, connection

from bluebottle.clients import properties



class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0025_auto_20190904_1154'),
    ]

    operations = [
    ]
