# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-12 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0027_merge_20190912_1324'),
        ('funding', '0024_donation_anonymous'),
    ]

    operations = [
    ]
