# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-13 12:58
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('funding', '0028_merge_20190912_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_funding.bankaccount_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='funding',
            name='account',
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='funding.Funding'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='amount_matching',
            field=bluebottle.utils.fields.MoneyField(blank=True, currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0'), default_currency=b'EUR', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='funding',
            name='target',
            field=bluebottle.utils.fields.MoneyField(blank=True, currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0'), default_currency=b'EUR', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='funding',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funding.BankAccount'),
        ),
    ]
