# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-30 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0031_plainpayoutaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=b'EUR', max_length=3)),
                ('min_amount', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=10, null=True)),
                ('default1', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('default2', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('default3', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('default4', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.PaymentProvider')),
            ],
        ),
    ]
