# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-02 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0034_auto_20191002_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_payout_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
