# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-04 11:36
from __future__ import unicode_literals

import bluebottle.files.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0035_auto_20191002_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainpayoutaccount',
            name='document',
            field=bluebottle.files.fields.DocumentField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Document'),
        ),
    ]
