# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-14 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0037_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='funding.Payout'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='funding.Funding', verbose_name='activity'),
        ),
    ]
