# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0039_auto_20191022_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payout_amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payout_amount_currency',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='amount_donated',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='amount_donated_currency',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='amount_matched',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='amount_matched_currency',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='amount_pledged',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='amount_pledged_currency',
        ),
        migrations.AddField(
            model_name='payout',
            name='provider',
            field=models.CharField(default='stripe', max_length=100),
            preserve_default=False,
        ),
    ]
