# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0041_payout_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetline',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reward',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
