# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-06 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0042_auto_20191104_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingPlatformSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
                ('allow_anonymous_rewards', models.BooleanField(default=True, verbose_name='Allow guests to donate rewards')),
            ],
            options={
                'verbose_name': 'funding settings',
                'verbose_name_plural': 'funding settings',
            },
        ),
    ]
