# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-11 12:19
from __future__ import unicode_literals

from django.db import migrations
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'change_budgetline', 'add_budgetline',
                'delete_budgetline', 'change_donation',
                'change_bankaccount', 'add_bankaccount',
                'change_payoutaccount', 'change_payout',
                'change_plainpayoutaccount'
            )
        },
    }

    update_group_permissions('funding', group_perms, apps)


class Migration(migrations.Migration):
    dependencies = [
        ('funding', '0044_auto_20191108_1008'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
