# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-12 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0045_auto_20191111_1329'),
        ('funding', '0045_merge_20191108_1853'),
    ]

    operations = [
    ]
