# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-16 14:40
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def fix_matching_currencies(apps, schema_editor):
    Funding = apps.get_model('funding', 'Funding')
    Funding.objects.update(amount_matching_currency=F('target_currency'))


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0046_merge_20191112_1256'),
    ]

    operations = [
        migrations.RunPython(fix_matching_currencies, migrations.RunPython.noop)
    ]
