# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-18 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0048_add_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, default=b'', max_length=30, null=True),
        ),
    ]
