# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-18 15:25
from __future__ import unicode_literals

from django.db import migrations


def set_payment_methods(apps, schema_editor):

    Payment = apps.get_model('funding', 'Payment')
    for payment in Payment.objects.all():
        method = payment.polymorphic_ctype.model.\
            replace('payment', '').\
            replace('source', '')
        payment.payment_method = method
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0049_auto_20191218_1538'),
    ]

    operations = [
        migrations.RunPython(set_payment_methods, migrations.RunPython.noop)
    ]
