# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-25 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0050_auto_20191218_1625'),
        ('funding', '0052_auto_20200205_1710'),
    ]

    operations = [
    ]
