# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-02 11:21
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_status(apps, schema_editor):
    BankAccount = apps.get_model('funding', 'BankAccount')
    for bank in BankAccount.objects.all():
        if bank.reviewed:
            bank.status = 'verified'
        elif bank.connect_account and bank.connect_account.status == 'verified':
            bank.status = 'verified'
        else:
            bank.status = 'unverified'
        bank.save()


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0054_auto_20200610_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(default='unverified', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='status',
            field=models.CharField(max_length=40),
        ),
        migrations.RunPython(
            migrate_status,
            migrations.RunPython.noop
        )
    ]
