# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

import bluebottle.files.fields
import bluebottle.utils.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0055_auto_20201002_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='plainpayoutaccount',
            options={'verbose_name': 'Plain KYC account', 'verbose_name_plural': 'Plain KYC accounts'},
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default_currency='EUR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default_currency='EUR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payout_amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default_currency='EUR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default_currency='EUR', max_digits=12, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='plainpayoutaccount',
            name='document',
            field=bluebottle.files.fields.PrivateDocumentField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.PrivateDocument'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default_currency='EUR', max_digits=12, verbose_name='Amount'),
        ),
    ]
