# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-18 08:54
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0030_auto_20201117_1137'),
        ('funding', '0057_auto_20201112_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donation',
            new_name='Donor'
        ),
        migrations.AlterField(
            model_name='payment',
            name='donation',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payment', to='funding.Donor'),
        ),
    ]
