# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-27 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0059_auto_20201120_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneycontribution',
            options={'verbose_name': 'Contribution', 'verbose_name_plural': 'Contributions'},
        ),
        migrations.RenameField(
            model_name='moneycontribution',
            old_name='amount',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='moneycontribution',
            old_name='amount_currency',
            new_name='value_currency',
        ),
    ]
