# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-02 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0060_auto_20201127_0922'),
    ]

    operations = [
    ]
