# Generated by Django 3.2.20 on 2024-09-19 06:50

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0035_set_alternate_names'),
        ('funding', '0065_auto_20221223_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
