# Generated by Django 3.2.20 on 2024-10-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0066_auto_20240916_1635'),
        ('funding', '0066_auto_20240919_0850'),
    ]

    operations = [
    ]
