# Generated by Django 3.2.20 on 2024-11-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0067_auto_20241009_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.TextField(blank=True, verbose_name='Name'),
        ),
    ]
