# Generated by Django 3.2.20 on 2024-11-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_auto_20241106_1009'),
        ('funding', '0067_auto_20241009_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutaccount',
            name='partner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_accounts', to='organizations.organization', verbose_name='Partner organisation'),
        ),
    ]
