# Generated by Django 3.2.20 on 2024-11-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0067_merge_0066_auto_20240916_1635_0066_auto_20240919_0850'),
        ('funding', '0068_payoutaccount_partner_organization'),
    ]

    operations = [
    ]
