# Generated by Django 3.2.20 on 2025-01-21 10:40

import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20250113_1704'),
        ('funding', '0069_merge_20241112_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingplatformsettings',
            name='matching_name',
            field=models.CharField(blank=True, help_text='Change this if you want to use something else then the platform name for matching amounts.', max_length=60, null=True, verbose_name='Name to use for match funding'),
        ),
        migrations.AlterField(
            model_name='fundingplatformsettings',
            name='public_accounts',
            field=models.BooleanField(default=False, help_text='Allow users to select account from list of public accounts', verbose_name='Allow users to select account from list of public accounts'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=bluebottle.files.fields.ImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='public',
            field=models.BooleanField(default=False, help_text='Allow users to choose this payout account when setting up a crowdfunding campaign (only applies if crowdfunding for public payout accounts is enabled).', verbose_name='Public payout account'),
        ),
    ]
