# Generated by Django 3.2.4 on 2024-12-13 09:23

import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_relatedimage_image'),
        ('funding', '0069_merge_20241112_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingplatformsettings',
            name='matching_name',
            field=models.CharField(blank=True, help_text='Change this if you want to use something else then the platform name for matching amounts.', max_length=60, null=True, verbose_name='Name to use for match funding'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=bluebottle.files.fields.ImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
    ]
