# Generated by Django 3.2.20 on 2025-03-05 10:06

import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20250113_1704'),
        ('funding', '0069_merge_20241112_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingplatformsettings',
            name='matching_name',
            field=models.CharField(blank=True, help_text='Change this if you want to use something else then the platform name for matching amounts.', max_length=60, null=True, verbose_name='Name to use for match funding'),
        ),
        migrations.AlterField(
            model_name='fundingplatformsettings',
            name='public_accounts',
            field=models.BooleanField(default=False, help_text='When enabled, campaign initiators must select from a list of organisations with a public payout account that will receive the raised money, rather than providing the bank account details themselves.', verbose_name='Crowdfunding for verified organisations'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=bluebottle.files.fields.ImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='public',
            field=models.BooleanField(default=False, help_text='Allow users to choose this payout account when setting up a crowdfunding campaign (only applies if crowdfunding for public payout accounts is enabled).', verbose_name='Public payout account'),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='reviewed'),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
