# Generated by Django 4.2.20 on 2025-03-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0070_auto_20250121_1140'),
        ('funding', '0070_auto_20250305_1106'),
    ]

    operations = [
    ]
