# Generated by Django 4.2.20 on 2025-04-17 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geo', '0035_set_alternate_names'),
        ('funding', '0071_merge_0070_auto_20250121_1140_0070_auto_20250305_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='impact_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_activities', to='geo.geolocation'),
        ),
    ]
