# Generated by Django 4.2.20 on 2025-07-01 14:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0073_alter_payout_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingplatformsettings',
            name='business_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('company', 'Commercial company'), ('individual', 'Individual person'), ('non_profit', 'Non-profit organization')], default=['individual'], max_length=300),
        ),
    ]
