# Generated by Django 4.2.20 on 2025-07-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0073_alter_payout_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbanCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_iban', models.CharField(db_index=True, help_text='Hashed IBAN to check against', max_length=64, unique=True)),
                ('matched', models.CharField(choices=[('match', 'Match'), ('mistype', 'Almost matched'), ('no_match', 'No match')], default='no_match', help_text='Result of the IBAN check', max_length=10)),
                ('name', models.CharField(blank=True, help_text='Name of the account holder', max_length=255, null=True)),
                ('result', models.JSONField()),
            ],
        ),
    ]
