import bluebottle.utils.fields
# Generated by Django 4.2.20 on 2025-05-21 14:29

import bluebottle.fsm.triggers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('funding', '0074_auto_20250519_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantdonor',
            options={'verbose_name': 'Grant', 'verbose_name_plural': 'Grants'},
        ),
        migrations.AlterModelOptions(
            name='grantfund',
            options={'verbose_name': 'Grant fund', 'verbose_name_plural': 'Grant funds'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='payout_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='funding',
            name='amount_matching_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='fundingplatformsettings',
            name='public_accounts',
            field=models.BooleanField(default=False, help_text='When enabled, campaign initiators must select from a list of organisations with a public payout account that will receive the raised money, rather than providing the bank account details themselves.', verbose_name='Crowdfunding for verified organisations'),
        ),
        migrations.AlterField(
            model_name='grantdonor',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='funding.grantfund'),
        ),
        migrations.AlterField(
            model_name='moneycontribution',
            name='value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='LedgerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('amount', bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default=None, default_currency='EUR', max_digits=12)),
                ('type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'credit')])),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_items', to='funding.grantfund')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_item', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('amount', bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default=None, default_currency='EUR', max_digits=12)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.grantfund')),
            ],
        ),
        migrations.AddField(
            model_name='grantdonor',
            name='ledger_item',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='funding.ledgeritem'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GrantPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=40)),
                ('date_approved', models.DateTimeField(blank=True, null=True, verbose_name='approved')),
                ('date_started', models.DateTimeField(blank=True, null=True, verbose_name='started')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='completed')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='funding.grantapplication', verbose_name='Grant application')),
            ],
            options={
                'verbose_name': 'payout',
                'verbose_name_plural': 'payouts',
            },
            bases=(bluebottle.fsm.triggers.TriggerMixin, models.Model),
        ),
        migrations.AddField(
            model_name='grantdonor',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='funding.grantpayout'),
        ),
    ]
