# Generated by Django 4.2.20 on 2025-05-21 14:29

import bluebottle.fsm.triggers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('funding', '0074_auto_20250519_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantdonor',
            options={'verbose_name': 'Grant', 'verbose_name_plural': 'Grants'},
        ),
        migrations.AlterModelOptions(
            name='grantfund',
            options={'verbose_name': 'Grant fund', 'verbose_name_plural': 'Grant funds'},
        ),
        migrations.AlterField(
            model_name='grantdonor',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='funding.grantfund'),
        ),
        migrations.CreateModel(
            name='GrantPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=40)),
                ('date_approved', models.DateTimeField(blank=True, null=True, verbose_name='approved')),
                ('date_started', models.DateTimeField(blank=True, null=True, verbose_name='started')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='completed')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='funding.grantapplication', verbose_name='Grant application')),
            ],
            options={
                'verbose_name': 'payout',
                'verbose_name_plural': 'payouts',
            },
            bases=(bluebottle.fsm.triggers.TriggerMixin, models.Model),
        ),
        migrations.AddField(
            model_name='grantdonor',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='funding.grantpayout'),
        ),
    ]
