# Generated by Django 4.2.20 on 2025-07-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0075_alter_ibancheck_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibancheck',
            name='hashed_iban',
            field=models.CharField(help_text='Hashed IBAN to check against', max_length=64),
        ),
    ]
