# Generated by Django 4.2.20 on 2025-05-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0075_alter_grantdonor_options_alter_grantfund_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deposit',
            new_name='GrantDeposit',
        ),
    ]
