# Generated by Django 4.2.20 on 2025-05-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0076_rename_deposit_grantdeposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantdeposit',
            old_name='grant',
            new_name='fund',
        ),
    ]
