# Generated by Django 4.2.20 on 2025-07-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0076_alter_ibancheck_hashed_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibancheck',
            name='matched',
            field=models.CharField(choices=[('match', 'Match'), ('mistype', 'Almost matched'), ('no_match', 'No match')], default='no_match', help_text='Result of the IBAN check', max_length=100),
        ),
    ]
