# Generated by Django 4.2.20 on 2025-07-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0077_alter_ibancheck_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingplatformsettings',
            name='enable_iban_check',
            field=models.BooleanField(default=False, help_text='In the KYC flow do a check to see if bank account number and name match. This will be done by the Surepay API, and only Dutch IBANs are supported. ', verbose_name='Do IBAN bank account number vs. name checks'),
        ),
    ]
