# Generated by Django 4.2.20 on 2025-05-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0077_rename_grant_grantdeposit_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantdeposit',
            name='ledger_item',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='funding.ledgeritem'),
            preserve_default=False,
        ),
    ]
