# Generated by Django 4.2.20 on 2025-05-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0078_grantdeposit_ledger_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantdeposit',
            name='ledger_item',
        ),
        migrations.RemoveField(
            model_name='grantdonor',
            name='ledger_item',
        ),
    ]
