# Generated by Django 4.2.20 on 2025-07-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0074_fundingplatformsettings_business_types'),
        ('funding', '0078_fundingplatformsettings_enable_iban_check'),
    ]

    operations = [
    ]
