# Generated by Django 4.2.20 on 2025-08-25 09:56

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0079_merge_20250709_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibancheck',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iban_checks', to='funding.bankaccount'),
        ),
    ]
