# Generated by Django 4.2.20 on 2025-05-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0080_grantfund_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantdeposit',
            name='reference',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grantdeposit',
            name='status',
            field=models.CharField(default='finished', max_length=40),
            preserve_default=False,
        ),
    ]
