# Generated by Django 4.2.20 on 2025-08-25 12:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0081_remove_ibancheck_bank_account_ibancheck_stripe_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ibancheck',
            old_name='stripe_id',
            new_name='fingerprint',
        ),
        migrations.AlterField(
            model_name='fundingplatformsettings',
            name='business_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('individual', 'Individual person'), ('non_profit', 'Non-profit organization'), ('company', 'Commercial company')], default=['individual'], max_length=300, verbose_name='verification types'),
        ),
        migrations.AlterField(
            model_name='ibancheck',
            name='matched',
            field=models.CharField(choices=[('match', 'Match'), ('mistype', 'Mistype'), ('close_match', 'Close match'), ('no_match', 'No match')], default='no_match', help_text='Result of the IBAN check', max_length=100),
        ),
    ]
