# Generated by Django 4.2.20 on 2025-06-16 09:05

import bluebottle.fsm.triggers
import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0081_grantdeposit_reference_grantdeposit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='weekly', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grant provider',
                'verbose_name_plural': 'Grant providers',
            },
        ),
        migrations.AlterModelOptions(
            name='grantpayout',
            options={'verbose_name': 'Grant payout', 'verbose_name_plural': 'Grant payouts'},
        ),
        migrations.AlterModelOptions(
            name='payout',
            options={'verbose_name': 'Funding payout', 'verbose_name_plural': 'Funding payouts'},
        ),
        migrations.AlterField(
            model_name='grantdeposit',
            name='reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='grantdonor',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='funding.grantfund'),
        ),
        migrations.AlterField(
            model_name='grantfund',
            name='currency',
            field=bluebottle.utils.fields.CurrencyField(default="<class 'django.db.models.fields.NOT_PROVIDED'>"),
        ),
        migrations.CreateModel(
            name='GrantPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('total', bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default=None, default_currency='EUR', max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('grant_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funding.grantprovider')),
            ],
            options={
                'verbose_name': 'Grant payment',
                'verbose_name_plural': 'Grant payments',
            },
            bases=(bluebottle.fsm.triggers.TriggerMixin, models.Model),
        ),
        migrations.AddField(
            model_name='grantpayout',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='funding.grantpayment'),
        ),
    ]
