# Generated by Django 4.2.20 on 2025-11-17 00:00

from django.db import migrations, connection

from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)

    with LocalTenant(tenant):
        funding_permissions = {
            'Staff': {
                'perms': (
                    'add_donor', 'change_donor', 'delete_donor',
                )
            },
        }

        update_group_permissions('funding', funding_permissions, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0082_rename_stripe_id_ibancheck_fingerprint_and_more'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions, migrations.RunPython.noop)
    ]

