# Generated by Django 4.2.20 on 2025-06-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0082_grantprovider_alter_grantpayout_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantfund',
            name='grant_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='funding.grantprovider'),
        ),
    ]
