# Generated by Django 4.2.20 on 2025-12-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0083_add_staff_donor_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingplatformsettings',
            name='allow_exceed_target',
            field=models.BooleanField(default=True, help_text=' Stop accepting donations as soon as the target is reached.'),
        ),
    ]
