# Generated by Django 4.2.20 on 2025-06-16 11:11

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0084_grantpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantpayment',
            name='total',
            field=bluebottle.utils.fields.MoneyField(blank=True, currency_choices=[('EUR', 'Euro')], decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=12, null=True),
        ),
    ]
