# Generated by Django 4.2.20 on 2026-03-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0085_remove_fundingplatformsettings_allow_exceed_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingplatformsettings',
            name='allow_anonymous_rewards',
        ),
    ]
