# Generated by Django 4.2.20 on 2025-06-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0086_grantpayment_payment_intent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantpayment',
            old_name='payment_intent',
            new_name='checkout_id',
        ),
    ]
