# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-18 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SCIMPlatformSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
                ('bearer_token', models.CharField(max_length=32, verbose_name='Bearer Token')),
            ],
            options={
                'verbose_name': 'scim platform settings',
                'verbose_name_plural': 'scim platform settings',
            },
        ),
    ]
