# Generated by Django 2.2.24 on 2022-10-31 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0029_auto_20221031_1713'),
        ('scim', '0002_auto_20190118_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCIMSegmentSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('segment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segments.SegmentType')),
            ],
        ),
        migrations.AddField(
            model_name='scimplatformsettings',
            name='segment_settings',
            field=models.ManyToManyField(to='scim.SCIMSegmentSetting'),
        ),
    ]
