# Generated by Django 2.2.24 on 2022-11-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0003_auto_20221031_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scimplatformsettings',
            name='segment_settings',
        ),
        migrations.AddField(
            model_name='scimsegmentsetting',
            name='settings',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scim.SCIMPlatformSettings'),
            preserve_default=False,
        ),
    ]
