# Generated by Django 4.2.20 on 2025-12-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0004_auto_20221102_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scimsegmentsetting',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_settings', to='scim.scimplatformsettings'),
        ),
    ]
