# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 12:44
from __future__ import unicode_literals

from django.db import migrations
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_auto_20160921_1410'),
    ]
    operations = [
        migrations.AddField(
            model_name='aggregateanswer',
            name='list',
            field=django.contrib.postgres.fields.JSONField(default='[]', null=True),
        ),
        migrations.AddField(
            model_name='aggregateanswer',
            name='options',
            field=django.contrib.postgres.fields.JSONField(null=True),
        ),
    ]
