# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_auto_20160922_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='display_style',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
