# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_auto_20160922_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregateanswer',
            name='response_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='aggregation',
            field=models.CharField(blank=True, choices=[(b'sum', b'Sum'), (b'average', b'Average'), (b'winner', b'Winner')], max_length=200, null=True),
        ),
    ]
