# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 14:40
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_auto_20160922_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='options',
            field=django_extensions.db.fields.json.JSONField(null=True),
        ),
    ]
