# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 06:52
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_answer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='params',
            field=django_extensions.db.fields.json.JSONField(null=True),
        ),
    ]
