# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20160919_1508'),
        ('surveys', '0021_response_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregateanswer',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='aggregateanswer',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
