# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_auto_20160926_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='list',
            field=django_extensions.db.fields.json.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='aggregateanswer',
            name='aggregation_type',
            field=models.CharField(choices=[(b'project', b'Project'), (b'task', b'Task'), (b'project_tasks', b'Tasks in project'), (b'combined', b'Project and tasks')], default=b'project', max_length=20),
        ),
    ]
