# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='user_type',
            field=models.CharField(blank=True, choices=[(b'task_member', 'Task member'), (b'initiator', 'Project initiator'), (b'organization', 'Partner organisation')], max_length=200, null=True),
        ),
    ]
