# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_auto_20161115_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='display_theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
