# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_auto_20161109_1024'),
        ('surveys', '0031_question_display_theme'),
    ]

    operations = [
    ]
