# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-15 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0063_auto_20200915_1023'),
        ('surveys', '0034_survey_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregateanswer',
            name='project',
        ),
        migrations.RemoveField(
            model_name='aggregateanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='aggregateanswer',
            name='task',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='response',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='response',
            name='project',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='response',
            name='task',
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='question',
        ),
        migrations.DeleteModel(
            name='AggregateAnswer',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='SubQuestion',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
