# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 10:21
from __future__ import unicode_literals

from django.db import migrations


def clean_up_system_wallposts(apps, schema_editor):
        TextWallpost = apps.get_model('wallposts', 'TextWallpost')
        SystemWallpost = apps.get_model('wallposts', 'SystemWallpost')
        donation_ids = TextWallpost.objects.filter(donation__isnull=False).values_list('donation_id', flat=True)
        SystemWallpost.objects.filter(donation__in=donation_ids).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0005_merge_20170124_1338'),
    ]

    operations = [
        migrations.RunPython(clean_up_system_wallposts),
    ]
