# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-14 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0006_remove_duplicate_donation_wallposts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediawallpost',
            options={'permissions': (('api_read_mediawallpost', 'Can view media wallposts through the API'), ('api_add_mediawallpost', 'Can add media wallposts through the API'), ('api_change_mediawallpost', 'Can change media wallposts through the API'), ('api_delete_mediawallpost', 'Can delete media wallposts through the API'), ('api_read_mediawallpostphoto', 'Can view media wallpost photos through the API'), ('api_add_mediawallpostphoto', 'Can add media wallpost photos through the API'), ('api_change_mediawallpostphoto', 'Can change media wallpost photos through the API'), ('api_delete_mediawallpostphoto', 'Can delete media wallpost photos through the API'))},
        ),
    ]
