# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 14:14
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'add_reaction', 'change_reaction', 'delete_reaction',
                'add_wallpost', 'change_wallpost', 'delete_wallpost',
                'add_mediawallpost', 'change_mediawallpost', 'delete_mediawallpost',
                'add_textwallpost', 'change_textwallpost', 'delete_textwallpost',
                'add_systemwallpost', 'change_systemwallpost',
                'delete_systemwallpost',
                'add_mediawallpostphoto', 'change_mediawallpostphoto',
                'delete_mediawallpostphoto',
            )
        },
        'Anonymous': {
            'perms': ('api_read_mediawallpost',)
        },
        'Authenticated': {
            'perms': (
                'api_read_mediawallpost', 'api_add_mediawallpost', 'api_change_mediawallpost', 'api_delete_mediawallpost',
                'api_read_textwallpost', 'api_add_textwallpost', 'api_change_textwallpost', 'api_delete_mediawallpost',
                'api_read_mediawallpostphoto', 'api_add_mediawallpostphoto', 'api_change_mediawallpostphoto',
            )
        }
    }

    update_group_permissions('wallposts', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0007_auto_20170821_1459'),
    ]

    operations = [
            migrations.RunPython(add_group_permissions)
    ]
