# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0008_add_group_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallpost',
            options={'base_manager_name': 'objects_with_deleted', 'ordering': ('created',), 'permissions': (('api_read_wallpost', 'Can view wallposts through the API'), ('api_add_wallpost', 'Can add wallposts through the API'), ('api_change_wallpost', 'Can wallposts documents through the API'), ('api_delete_wallpost', 'Can wallposts documents through the API'))},
        ),
    ]
