# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0008_add_group_permissions'),
        ('wallposts', '0007_auto_20170814_1802'),
    ]

    operations = [
    ]
