# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 18:01
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Anonymous': {
            'perms': (
                'api_read_wallpost','api_change_wallpost',
                'api_add_wallpost', 'api_delete_wallpost',
            )
        },
        'Authenticated': {
            'perms': (
                'api_read_wallpost','api_change_wallpost',
                'api_add_wallpost', 'api_delete_wallpost',
            )
        }
    }

    update_group_permissions('wallposts', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0009_auto_20170821_2001'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
