# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 18:18
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Anonymous': {
            'perms': (
                'api_read_reaction', 'api_add_reaction',
                'api_change_reaction', 'api_delete_reaction',
            )
        },
        'Authenticated': {
            'perms': (
                'api_read_reaction', 'api_add_reaction',
                'api_change_reaction', 'api_delete_reaction',
            )
        }
    }

    update_group_permissions('wallposts', group_perms, apps)



class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0011_auto_20170821_2018'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
