# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-17 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0036_auto_20191004_1336'),
        ('wallposts', '0018_auto_20190115_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpost',
            name='funding_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallpost', to='funding.Donation', verbose_name='Donation'),
        ),
    ]
