# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0019_auto_20191017_2204'),
        ('orders', '0008_auto_20190904_0838')
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpost',
            name='donation',
        ),
        migrations.RenameField(
            model_name='wallpost',
            old_name='funding_donation',
            new_name='donation'
        ),
    ]
