# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0020_auto_20191017_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpost',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pinned posts are shown first. New posts by the initiator will unpin older posts.'),
        ),
    ]
