# Generated by Django 2.2.24 on 2022-12-05 12:13

import bluebottle.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0021_auto_20201118_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallpost_reactions', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
