# Generated by Django 2.2.24 on 2022-12-13 10:32

import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0022_auto_20221205_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpost',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallpost', to='funding.Donor', verbose_name='Donor'),
        ),
    ]
