#
# Generated by Django 3.2.20 on 2024-03-27 10:20

from django.db import migrations


def migrate_periodic_wallposts(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    PeriodicActivity = apps.get_model("time_based", "PeriodicActivity")
    PeriodActivity = apps.get_model("time_based", "PeriodActivity")

    MediaWallpost = apps.get_model("wallposts", "MediaWallpost")
    SystemWallpost = apps.get_model("wallposts", "SystemWallpost")
    TextWallpost = apps.get_model("wallposts", "TextWallpost")

    periodic_activity_ctype = ContentType.objects.get_for_model(PeriodicActivity)
    period_activity_ctype = ContentType.objects.get_for_model(PeriodActivity)

    media_wallposts = MediaWallpost.objects.filter(
        content_type=period_activity_ctype, object_id__in=PeriodicActivity.objects.all()
    )
    media_wallposts.update(content_type_id=periodic_activity_ctype)

    text_wallposts = TextWallpost.objects.filter(
        content_type=period_activity_ctype, object_id__in=PeriodicActivity.objects.all()
    )
    text_wallposts.update(content_type_id=periodic_activity_ctype)

    system_wallposts = SystemWallpost.objects.filter(
        content_type=period_activity_ctype, object_id__in=PeriodicActivity.objects.all()
    )
    system_wallposts.update(content_type_id=periodic_activity_ctype)


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0101_auto_20240304_1439"),
        ("wallposts", "0024_migrate_deadline_wallposts"),
    ]

    operations = [
        migrations.RunPython(migrate_periodic_wallposts, migrations.RunPython.noop)
    ]
