# Generated by Django 3.2.20 on 2024-08-13 07:22

from django.db import migrations


def remove_old_wallposts(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Wallpost = apps.get_model('wallposts', 'Wallpost')
    MediaWallpost = apps.get_model('wallposts', 'MediaWallpost')

    modelnames= ['deed', 'periodactivity', 'scheduleactivity', 'deadlineactivity', 'periodicactivity', 'dateactivity']

    for modelname in modelnames:
        if modelname == 'deed':
            content_type = ContentType.objects.get(app_label='deeds', model=modelname)
        else:
            content_type = ContentType.objects.get(app_label='time_based', model=modelname)
        posts = MediaWallpost.objects.filter(content_type=content_type)
        print(f"Deleting {posts.count()} media wallposts for {modelname}")
        posts.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0026_migrate_team_wallposts'),
    ]

    operations = [
        migrations.RunPython(remove_old_wallposts, migrations.RunPython.noop),
    ]
