# Generated by Django 3.2.4 on 2024-12-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0028_auto_20241018_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediawallpostphoto',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mediawallpostphoto',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='mediawallpostphoto',
            name='mediawallpost',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='wallpost',
        ),
        migrations.RemoveField(
            model_name='systemwallpost',
            name='related_type',
        ),
        migrations.RemoveField(
            model_name='systemwallpost',
            name='wallpost_ptr',
        ),
        migrations.RemoveField(
            model_name='textwallpost',
            name='wallpost_ptr',
        ),
        migrations.RemoveField(
            model_name='wallpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='wallpost',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='wallpost',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='wallpost',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='wallpost',
            name='polymorphic_ctype',
        ),
        migrations.DeleteModel(
            name='MediaWallpost',
        ),
        migrations.DeleteModel(
            name='MediaWallpostPhoto',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='SystemWallpost',
        ),
        migrations.DeleteModel(
            name='TextWallpost',
        ),
        migrations.DeleteModel(
            name='Wallpost',
        ),
    ]
