# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20160929_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('_name', models.CharField(max_length=100, verbose_name='name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='geo.Country')),
            ],
            options={
                'managed': True,
                'db_table': 'geo_country_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'country Translation',
            },
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('_name', models.CharField(max_length=100, verbose_name='name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='geo.Region')),
            ],
            options={
                'managed': True,
                'db_table': 'geo_region_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'region Translation',
            },
        ),
        migrations.CreateModel(
            name='SubRegionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('_name', models.CharField(max_length=100, verbose_name='name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='geo.SubRegion')),
            ],
            options={
                'managed': True,
                'db_table': 'geo_subregion_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'sub region Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='subregiontranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='regiontranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='countrytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
