# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-29 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_remove_translated_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['translations__name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
    ]
