# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-18 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geo', '0007_remove_translated_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Number')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street')),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal Code')),
                ('locality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Locality')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='Province')),
                ('formatted_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['translations__name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Country'),
        ),
    ]
