# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-20 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_initiativeplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Number')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street')),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal Code')),
                ('locality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Locality')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='Province')),
                ('formatted_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Country')),
            ],
        ),
    ]
