# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-22 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0013_auto_20190524_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'office location', 'verbose_name_plural': 'office locations'},
        ),
    ]
