# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-01 14:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0015_add_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
    ]
