# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-29 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0018_auto_20201229_1038'),
    ]

    operations = [
    ]
