# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-05 09:50
from __future__ import unicode_literals

import bluebottle.geo.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0020_auto_20210105_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeplace',
            name='position',
            field=bluebottle.geo.fields.PointField(max_length=42),
        ),
        migrations.AlterField(
            model_name='place',
            name='position',
            field=bluebottle.geo.fields.PointField(max_length=42),
        ),
    ]
