# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-29 08:51
from __future__ import unicode_literals

import bluebottle.geo.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0021_auto_20210105_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'office', 'verbose_name_plural': 'offices'},
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Office picture', max_length=255, null=True, upload_to='location_images/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='location',
            name='subregion',
            field=models.ForeignKey(blank=True, help_text='The organisational group this office belongs too.', null=True, on_delete=django.db.models.deletion.CASCADE, to='offices.OfficeSubRegion', verbose_name='office group'),
        ),
        migrations.AlterField(
            model_name='place',
            name='position',
            field=bluebottle.geo.fields.PointField(max_length=42, null=True),
        ),
    ]
