# Generated by Django 3.0.14 on 2021-04-14 13:07

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import bluebottle.geo.fields

class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_auto_20210414_1507'),
        ('geo', '0022_auto_20210129_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geolocation',
            old_name='position',
            new_name='old_position',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='position',
            new_name='old_position',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='position',
            new_name='old_position',
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='old_position',
            field=bluebottle.geo.fields.PointField(max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='initiativeplace',
            name='old_position',
            field=bluebottle.geo.fields.PointField(max_length=42, null=True),
        ),
        migrations.RemoveField(
            model_name='initiativeplace',
            name='country',
        ),
        migrations.DeleteModel(
            name='InitiativePlace',
        ),

    ]
