# Generated by Django 2.2.24 on 2021-10-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0048_auto_20211012_1256'),
        ('geo', '0027_auto_20211012_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='place',
            name='object_id',
        ),
    ]
