# Generated by Django 2.2.24 on 2021-10-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0028_auto_20211012_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Country'),
        ),
    ]
