# Generated by Django 3.2.20 on 2023-12-11 14:41
from django.db import migrations

def set_mapbox_id_unkown(apps, schema_editor):
    DateActivity = apps.get_model('geo', 'GeoLocation')
    DateActivity.objects.filter(mapbox_id__isnull=True).update(mapbox_id='unknown')


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0032_geolocation_mapbox_id'),
    ]

    operations = [
        migrations.RunPython(set_mapbox_id_unkown)
    ]
