# Generated by Django 3.2.20 on 2024-05-13 13:36

from django.db import migrations


def save_locations(apps, schema_editor):
    Location = apps.get_model("geo", "Location")

    for location in Location.objects.all():
        location.alternate_names = [location.name, location.slug]
        location.save()
        print(location.alternate_names)


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0034_location_alternate_names"),
    ]

    operations = [migrations.RunPython(save_locations, migrations.RunPython.noop)]
