# Generated by Django 4.2.20 on 2026-01-15 11:12

import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0005_alter_officeregion_options_and_more'),
        ('geo', '0035_set_alternate_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'work location', 'verbose_name_plural': 'work locations'},
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(blank=True, help_text='The (geographic) country this work location is located in.', null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Work location picture', max_length=255, null=True, upload_to='location_images/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='location',
            name='subregion',
            field=models.ForeignKey(blank=True, help_text='The organisational group this work location belongs too.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.officesubregion', verbose_name='work location group'),
        ),
    ]
