# Generated by Django 4.2.20 on 2025-09-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0031_crowdfunding_location_alter_crowdfunding_target_and_more'),
        ('geo', '0035_set_alternate_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activity_pub.image'),
        ),
    ]
