# Generated by Django 4.2.20 on 2025-10-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0032_alter_address_address_country_and_more'),
        ('geo', '0036_geolocation_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='activity_pub.place'),
        ),
    ]
