# Generated by Django 4.2.20 on 2026-01-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0036_alter_location_options_alter_location_country_and_more'),
        ('geo', '0038_alter_geolocation_country'),
    ]

    operations = [
    ]
