# Generated by Django 4.2.20 on 2026-02-25 15:36

import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0005_alter_officeregion_options_and_more'),
        ('geo', '0038_alter_geolocation_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(choices=[('country', 'Country'), ('region', 'Region'), ('postcode', 'Postcode'), ('district', 'District'), ('place', 'Place'), ('locality', 'Locality'), ('neighborhou', 'Neighborhood'), ('street', 'Street'), ('block', 'Block'), ('country', 'Address'), ('country', 'Secondary address')], verbose_name='Level')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='Level')),
                ('mapbox_id', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'work location', 'verbose_name_plural': 'work locations'},
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(blank=True, help_text='The (geographic) country this work location is located in.', null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Work location picture', max_length=255, null=True, upload_to='location_images/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='location',
            name='subregion',
            field=models.ForeignKey(blank=True, help_text='The organisational group this work location belongs too.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.officesubregion', verbose_name='work location group'),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='features',
            field=models.ManyToManyField(to='geo.geofeature'),
        ),
        migrations.CreateModel(
            name='GeoFeatureTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='geo.geofeature')),
            ],
            options={
                'verbose_name': 'geo feature Translation',
                'db_table': 'geo_geofeature_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
