# Generated by Django 5.2.15 on 2026-07-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0039_merge_20260116_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='mapbox_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='mapbox_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
