# Generated by Django 5.2.13 on 2026-06-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0039_merge_20260116_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='origin',
        ),
    ]
