# Generated by Django 5.2.15 on 2026-07-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0040_alter_geolocation_mapbox_id_alter_place_mapbox_id'),
        ('geo', '0040_remove_geolocation_origin'),
    ]

    operations = [
    ]
