# Generated by Django 4.2.20 on 2026-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0040_alter_geolocation_mapbox_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofeature',
            name='mapbox_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geofeaturetranslation',
            name='name',
            field=models.CharField(max_length=512, verbose_name='name'),
        ),
    ]
