# Generated by Django 4.2.20 on 2026-04-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0039_merge_20260116_1155'),
        ('geo', '0041_alter_geofeature_mapbox_id_and_more'),
    ]

    operations = [
    ]
