# Generated by Django 5.2.13 on 2026-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0042_remove_geofeature_place_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='location_name',
            field=models.CharField(blank=True, help_text='The name of the location, e.g. the name of the community center.', max_length=255, null=True, verbose_name='Location name'),
        ),
    ]
