# Generated by Django 4.2.20 on 2026-04-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0042_merge_20260414_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofeaturetranslation',
            name='place_name',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='place name'),
        ),
    ]
