# Generated by Django 4.2.20 on 2026-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0043_geofeaturetranslation_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofeature',
            name='address',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='place_type',
            field=models.CharField(choices=[('country', 'Country'), ('region', 'Region'), ('postcode', 'Postcode'), ('district', 'District'), ('place', 'Place'), ('locality', 'Locality'), ('neighborhou', 'Neighborhood'), ('street', 'Street'), ('block', 'Block'), ('country', 'Address'), ('country', 'Secondary address')], verbose_name='Place type'),
        ),
        migrations.AlterField(
            model_name='geofeaturetranslation',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='geofeaturetranslation',
            name='place_name',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Place name'),
        ),
    ]
