# Generated by Django 4.2.20 on 2026-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0044_geofeature_address_alter_geofeature_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='mapbox_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
