# Generated by Django 5.2.13 on 2026-09-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0041_merge_20260717_1346'),
        ('geo', '0044_merge_20260713_1539'),
    ]

    operations = [
    ]
