# Generated by Django 4.2.20 on 2026-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0045_alter_geolocation_mapbox_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofeature',
            name='mapbox_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
