# Generated by Django 4.2.20 on 2026-04-20 15:02
#
# Data work moved to scripts/get_geofeatures.py (run per tenant via runscript).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0046_alter_geofeature_mapbox_id'),
    ]

    operations = []
