# Generated by Django 4.2.30 on 2026-05-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0048_merge_duplicate_geolocations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geofeature',
            options={'verbose_name': 'Geo feature', 'verbose_name_plural': 'Geo features'},
        ),
        migrations.AlterModelOptions(
            name='geofeaturetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Geo feature Translation'},
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='address',
        ),
    ]
