# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0003_auto_20161025_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.Payment')),
            ],
            options={
                'abstract': False,
            },
            bases=('payments.payment',),
        ),
    ]
