# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20160718_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(blank=True, default=b'', max_length=60),
        ),
    ]
