# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-19 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20161025_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpayment',
            options={'permissions': (('refund_orderpayment', 'Can refund order payments'),)},
        ),
    ]
