# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-19 14:21
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Financial': {
            'perms': (
                'refund_orderpayment',
            )
        },
    }
    update_group_permissions('payments', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20170919_1621'),
    ]

    operations = [
    ]
