# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20181115_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='integration_data',
        ),
    ]
