# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 12:14
from __future__ import unicode_literals
import json

from django.db import migrations, connection
from bluebottle.clients import properties


def migrate_payment_settings(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    properties.set_tenant(tenant)
    PaymentPlatformSettings = apps.get_model("payments", "PaymentPlatformSettings")
    PaymentMethodSettings = apps.get_model("payments", "PaymentMethodSettings")
    PaymentMethodCurrencySettings = apps.get_model("payments", "PaymentMethodCurrencySettings")
    PaymentProviderSettings = apps.get_model("payments", "PaymentProviderSettings")

    settings, created = PaymentPlatformSettings.objects.get_or_create()

    providers = properties.MERCHANT_ACCOUNTS
    for provider in providers:
        name = provider['merchant']
        PaymentProviderSettings.objects.get_or_create(
            name=name,
            settings=json.dumps(provider)
        )

    methods = properties.PAYMENT_METHODS
    for method in methods:
        provider = PaymentProviderSettings.objects.get(name=method['provider'])
        payment_method = PaymentMethodSettings.objects.create(
            settings=settings,
            provider=provider,
            name=method['name'],
            profile=method['profile'],
        )
        currencies = method['currencies']
        for currency in currencies:
            PaymentMethodCurrencySettings.objects.create(
                payment_method=payment_method,
                currency=currency,
                min_amount=currencies[currency].get('min_amount', None),
                max_amount=currencies[currency].get('max_amount', None),
            )
    settings.save()


def dummy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20180206_1312'),
    ]

    operations = [
        migrations.RunPython(migrate_payment_settings, dummy)
    ]
