# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-28 08:10
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def migrate_json(apps, schema_editor):
    OrderPayment = apps.get_model('payments', 'OrderPayment')
    for payment in OrderPayment.objects.all():
        payment.new_integration_data = payment.integration_data
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20181128_0910'),
    ]

    operations = [
        migrations.RunPython(migrate_json)
    ]
