# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-02 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_telesom', '0002_auto_20210302_1417'),
        ('payments_external', '0002_auto_20210302_1417'),
        ('payments_docdata', '0005_auto_20210302_1417'),
        ('payments', '0007_auto_20210302_1417'),
        ('payments_lipisha', '0003_auto_20210302_1417'),
        ('payments_vitepay', '0002_auto_20210302_1417'),
        ('payments_logger', '0002_auto_20210302_1417'),
        ('payments_pledge', '0002_auto_20210302_1417'),
        ('payments_voucher', '0002_auto_20210302_1417'),
        ('payments_flutterwave', '0009_auto_20210302_1417'),
        ('payments_beyonic', '0002_auto_20210302_1417'),
        ('payments_interswitch', '0004_auto_20210302_1417'),
        ('payments_stripe', '0004_auto_20210302_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
