# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-28 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_orderpayment_integration_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpayment',
            old_name='new_integration_data',
            new_name='integration_data',
        ),
    ]
