# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-23 12:44


from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationplatformsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(choices=[(b'bluebottle.members.messages.AccountActivationMessage', 'Member activated')], max_length=500, unique=True, verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MessageTemplateTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('body_html', models.TextField(blank=True, verbose_name='Body (html)')),
                ('body_txt', models.TextField(blank=True, verbose_name='Body (plain)')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='notifications.MessageTemplate')),
            ],
            options={
                'managed': True,
                'db_table': 'notifications_messagetemplate_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'message template Translation',
            },
        ),
        migrations.AlterModelOptions(
            name='notificationplatformsettings',
            options={'verbose_name': 'notification settings', 'verbose_name_plural': 'notification settings'},
        ),
        migrations.AlterField(
            model_name='notificationplatformsettings',
            name='share_options',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'twitter', 'Twitter'), (b'facebook', 'Facebook'), (b'facebookAtWork', 'Facebook at Work'), (b'linkedin', 'LinkedIn'), (b'whatsapp', 'Whatsapp'), (b'yammer', 'Yammer'), (b'email', 'Email')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplatetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
