# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-24 14:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20200123_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='body_txt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
