# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20200124_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplatetranslation',
            name='body_txt',
            field=models.TextField(blank=True, verbose_name='Body (text)'),
        ),
    ]
