# Generated by Django 2.2.20 on 2021-08-30 11:31

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20210423_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationplatformsettings',
            name='default_yammer_group_id',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
