# Generated by Django 3.2.20 on 2023-08-18 10:12

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0099_auto_20240304_1341"),
        ("notifications", "0012_auto_20230629_0854"),
    ]

    operations = [
    ]
