# Generated by Django 3.2.20 on 2023-08-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0013_migrate_deadline_messages"),
        ("time_based", "0101_auto_20240304_1439"),
    ]

    operations = [
    ]
