# Generated by Django 4.2.20 on 2025-03-20 08:50

import bluebottle.bluebottle_dashboard.quill
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_auto_20250225_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='bcc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='messagetemplatetranslation',
            name='body_html',
            field=bluebottle.bluebottle_dashboard.quill.RichTextField(blank=True, verbose_name='Body (html)'),
        ),
    ]
