# Generated by Django 4.2.20 on 2025-08-05 11:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django_quill.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_auto_20250225_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplatetranslation',
            name='body_txt',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='insert_method',
            field=models.CharField(choices=[('replace', 'Replace the entire message'), ('append', 'Append this to the original message')], default='append', max_length=20, verbose_name='Insert method'),
        ),
        migrations.AlterField(
            model_name='message',
            name='bcc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='message',
            field=models.CharField(choices=[('bluebottle.members.messages.AccountActivationMessage', 'Member activated'), ('bluebottle.grant_management.messages.activity_manager.GrantApplicationApprovedMessage', 'Grant application approved')], max_length=500, unique=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='messagetemplatetranslation',
            name='body_html',
            field=django_quill.fields.QuillField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notificationplatformsettings',
            name='share_options',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('facebookAtWork', 'Facebook at Work'), ('linkedin', 'LinkedIn'), ('whatsapp', 'Whatsapp'), ('teams', 'Teams'), ('email', 'Email')], max_length=100),
        ),
    ]
