# Generated by Django 4.2.20 on 2025-08-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_remove_messagetemplatetranslation_body_txt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body_txt',
        ),
        migrations.AddField(
            model_name='message',
            name='insert_method',
            field=models.CharField(default='append', max_length=10),
        ),
    ]
