# Generated by Django 3.2.19 on 2023-07-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_update_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='updates.update', verbose_name='Parent'),
        ),
    ]
