# Generated by Django 3.2.19 on 2023-07-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0005_auto_20230724_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='update',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='updates.update', verbose_name='Reply to'),
        ),
    ]
