# Generated by Django 3.2.19 on 2023-07-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0007_update_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned'),
        ),
    ]
