# Generated by Django 3.2.20 on 2023-08-09 06:30

import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20201117_1137'),
        ('updates', '0008_alter_update_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', bluebottle.files.fields.ImageField(on_delete=django.db.models.deletion.CASCADE, to='files.image')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='updates.update')),
            ],
        ),
    ]
