# Generated by Django 3.2.20 on 2023-08-12 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0068_auto_20230719_1325'),
        ('updates', '0009_updateimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='activities.activity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='update',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='update',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='updates.update', verbose_name='Reply to'),
        ),
    ]
