# Generated by Django 3.2.20 on 2024-07-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0013_migrate_funding_wallposts'),
        ('updates', '0014_migrate_periodic_wallposts'),
    ]

    operations = [
    ]
