# Generated by Django 3.2.20 on 2024-07-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0015_merge_20240707_1006'),
        ('updates', '0015_team_wallposts'),
    ]

    operations = [
    ]
