# Generated by Django 3.2.20 on 2024-12-04 11:57

import bluebottle.files.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_relatedimage_image'),
        ('updates', '0018_migrate_funding_wallposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='image',
            field=bluebottle.files.fields.ImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
        migrations.AlterField(
            model_name='updateimage',
            name='image',
            field=bluebottle.files.fields.ImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
    ]
