# Generated by Django 4.2.20 on 2025-12-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0098_alter_activityquestion_visibility_and_more'),
        ('updates', '0019_auto_20241204_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='contribution',
            field=models.ForeignKey(blank=True, help_text='The contribution this update is related to, e.g. the donation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='activities.contributor', verbose_name='Related contribution'),
        ),
    ]
