# Generated by Django 4.2.20 on 2025-03-21 07:57
import json

from django.db import migrations



def convert_to_quill(apps, schema_editor):
    Update = apps.get_model('updates', 'Update')

    for update in Update.objects.all():
        update.message = json.dumps({"html": update.message, "delta": ""})
        update.save()



class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0019_auto_20241204_1257'),
    ]

    operations = [
        migrations.RunPython(convert_to_quill, migrations.RunPython.noop)
    ]
