# Generated by Django 5.2.13 on 2026-06-11 13:02

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0103_alter_confirmationanswer_options_and_more'),
        ('updates', '0019_auto_20241204_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='update',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='update'),
        ),
    ]
