# Generated by Django 3.2.4 on 2024-12-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_event'),
        ('updates', '0019_auto_20241204_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='events.event', verbose_name='Triggered event'),
        ),
    ]
