# Generated by Django 5.2.13 on 2026-06-12 07:05

from django.db import migrations
from django.db.models import Value
from django.db.models.functions import JSONObject


def migrate_messages(apps, schema_editor):
    schema_editor.execute("""
        UPDATE updates_update
        SET update = json_build_object(
            'html', message,
            'delta', ''
        )::text
    """)

class Migration(migrations.Migration):
    dependencies = [
        ('updates', '0020_update_richtext_field'),
    ]

    operations = [
        migrations.RunPython(migrate_messages, reverse_code=migrations.RunPython.noop),
    ]
