# Generated by Django 5.2.13 on 2026-06-12 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0103_alter_confirmationanswer_options_and_more'),
        ('updates', '0021_auto_20260612_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='message',
        ),
    ]
