version: "3.7"
services:
  bluebottle:
    build: .
    working_dir: /source 
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    container_name: bluebottle 
    depends_on:
      elasticsearch:
        condition: service_started
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./:/source 
      - ./docker/bluebottle:/opt/data

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    ports:
      - 9200:9200
    restart: always
    volumes:
      - ./docker/elasticsearch:/var/lib/elasticsearch/data
    environment:
      - discovery.type=single-node
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reef
    image: postgis/postgis:latest # postgres + postgis
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
