# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0002_webhooklog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebHookLog',
            new_name='SignalLog',
        ),
    ]
