# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0003_auto_20210329_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='signallog',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
