# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 10:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0004_signallog_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=55)),
                ('channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
            ],
        ),
    ]
