# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-30 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0005_slacksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='signallog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
