# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 10:21
from __future__ import unicode_literals

from django.db import migrations, connection
from django.core.management import call_command


def remove_old_dashboard(apps, schema_editor):
    migrations.DeleteModel('dashboard.DashboardPreferences')
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM django_migrations WHERE app='dashboard'")


def dummy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_old_dashboard, dummy)
    ]
