# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 10:42
from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('bluebottle_dashboard', '0001_initial'),
    ]

    run_before = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
    ]
