# Generated by Django 3.2.4 on 2024-12-17 10:23

from django.db import migrations



def remove_wp(apps, schema_editor):
    UserDashboardModule = apps.get_model('dashboard', 'UserDashboardModule')
    UserDashboardModule.objects.filter(
        children='[{"title": "Recent wallposts"}]'
    ).all().delete()
    UserDashboardModule.objects.filter(
        title='Recent wallposts'
    ).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bluebottle_dashboard', '0003_auto_20240410_1044'),
    ]

    operations = [
        migrations.RunPython(remove_wp, migrations.RunPython.noop)
    ]
