# Generated by Django 3.2.4 on 2024-12-17 11:31

from django.db import migrations


def remove_wp(apps, schema_editor):
    UserDashboardModule = apps.get_model('dashboard', 'UserDashboardModule')
    UserDashboardModule.objects.filter(
        module__startswith='bluebottle.wallposts'
    ).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bluebottle_dashboard', '0004_auto_20241217_1123'),
    ]

    operations = [
        migrations.RunPython(remove_wp, migrations.RunPython.noop)
    ]
