# Generated by Django 4.2.20 on 2025-03-17 10:04
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bluebottle_dashboard", "0006_auto_20250116_1610"),
    ]

    operations = []
