# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-06 07:39
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count


def fix_duplicates(apps, schema_editor):
    FlutterwavePayment = apps.get_model('funding_flutterwave', 'FlutterwavePayment')
    for duplicate in FlutterwavePayment.objects.values('tx_ref').annotate(count=Count('id')).filter(count__gt=1):
        payments = FlutterwavePayment.objects.filter(tx_ref=duplicate['tx_ref'])
        successful = payments.filter(status='succeeded').first()
        t = 0
        for payment in payments.all():
            if payment != successful:
                t = t + 1
                payment.tx_ref = "{}-{}".format(payment.tx_ref, t)
                if payment.status == 'succeeded':
                    payment.status = 'failed'
                    payment.donation.status = 'failed'
                    payment.donation.save()
                    print 'Donation {} is now failed!'.format(payment.donation.id)
                payment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('funding_flutterwave', '0006_auto_20191111_1332'),
    ]

    operations = [
        migrations.RunPython(fix_duplicates)
    ]
