# Generated by Django 4.2.20 on 2025-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_flutterwave', '0008_auto_20200106_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flutterwavepayment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='flutterwavebankaccount',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('', 'Select bank'), ('044', 'Access Bank'), ('063', 'Access Bank PLC (Diamond)'), ('023', 'Citi Bank'), ('050', 'EcoBank PLC'), ('070', 'Fidelity Bank'), ('608', 'FINATRUST MICROFINANCE BANK'), ('011', 'First Bank PLC'), ('214', 'First City Monument Bank'), ('058', 'Guaranty Trust Bank'), ('030', 'Heritage Bank'), ('090175', 'Highstreet Microfinance Bank'), ('301', 'Jaiz Bank'), ('082', 'Keystone Bank'), ('090267', 'Kudimoney MF Bank'), ('076', 'Polaris bank'), ('101', 'ProvidusBank PLC'), ('221', 'Stanbic IBTC Bank'), ('068', 'Standard Chaterted bank PLC'), ('232', 'Sterling Bank PLC'), ('100', 'Suntrust Bank'), ('032', 'Union Bank PLC'), ('033', 'United Bank for Africa'), ('215', 'Unity Bank PLC'), ('035', 'Wema Bank PLC'), ('057', 'Zenith bank PLC'), ('01', 'Kenya Commercial Bank Limited'), ('11', 'Co-operative Bank of Kenya Limited'), ('31', 'CFC Stanbic Bank Kenya Limited'), ('41', 'NIC Bank Limited'), ('51', 'Jamii Bora Bank'), ('61', 'Housing Finance Bank'), ('14', 'Oriental Commercial Bank Limited'), ('54', 'Victoria Commercial Bank Limited'), ('07', 'Commercial Bank of Africa Limited'), ('49', 'Equatorial Commercial Bank Limited'), ('57', 'Investments n Mortgages Bank Limited'), ('39', 'Imperial Bank Limited'), ('12', 'National Bank of Kenya Limited'), ('72', 'Gulf African Bank Ltd'), ('25', 'Credit Bank Limited'), ('35', 'African Banking Corp. Bank Ltd'), ('74', 'First Community Bank'), ('55', 'Guardian Bank Limited'), ('10', 'Prime Bank Limited'), ('20', 'Dubai Bank Kenya Limited'), ('30', 'Chase Bank Limited'), ('50', 'Paramount Universal Bank Limited'), ('70', 'Family Bank Ltd'), ('23', 'Consolidated Bank of Kenya Limited'), ('18', 'Middle East Bank Kenya Limited'), ('63', 'Diamond Trust Bank Limited'), ('16', 'Citibank N.A.'), ('26', 'Trans-National Bank Limited'), ('68', 'Equity Bank Limited'), ('66', 'K-Rep Bank Limited'), ('76', 'UBA Kenya Bank Ltd'), ('19', 'Bank of  Africa Kenya Limited'), ('10276', 'ABSA Bank Kenya PLC'), ('02', 'Standard Chartered Bank Limited')], max_length=100, null=True, verbose_name='bank'),
        ),
        migrations.AlterField(
            model_name='flutterwavebankaccount',
            name='bank_country_code',
            field=models.CharField(blank=True, default='NG', max_length=2, null=True, verbose_name='bank country code'),
        ),
        migrations.AlterField(
            model_name='flutterwavepaymentprovider',
            name='prefix',
            field=models.CharField(default='goodup', max_length=100),
        ),
    ]
