# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0013_auto_20190524_0958'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('automatically_accept', models.BooleanField(default=True)),
                ('location_hint', models.TextField(blank=True, null=True, verbose_name='location hint')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('registration_deadline', models.DateTimeField(verbose_name='registration deadline')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Geolocation', verbose_name='location')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'permissions': (('api_read_event', 'Can view event through the API'), ('api_add_event', 'Can add event through the API'), ('api_change_event', 'Can change event through the API'), ('api_delete_event', 'Can delete event through the API'), ('api_read_own_event', 'Can view own event through the API'), ('api_add_own_event', 'Can add own event through the API'), ('api_change_own_event', 'Can change own event through the API'), ('api_delete_own_event', 'Can delete own event through the API')),
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('contribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Contribution')),
                ('time_spent', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=('activities.contribution',),
        ),
    ]
