# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-15 10:40
from __future__ import unicode_literals

from bluebottle.utils.utils import update_group_permissions
from django.db import migrations


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'add_participant', 'change_participant', 'delete_participant',
            )
        },
        'Anonymous': {
            'perms': (
                'api_read_event',
            )
        },
        'Authenticated': {
            'perms': (
                'api_read_participant',
                'api_add_participant',
                'api_change_own_participant',
            )
        }
    }

    update_group_permissions('events', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190522_1329'),
    ]

    operations = [
        migrations.RunPython(
            add_group_permissions,
            migrations.RunPython.noop
        )
    ]
