# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-27 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='participant',
            name='time_spent',
            field=models.FloatField(default=0),
        ),
    ]
