# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-12 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190605_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='registration deadline'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='start'),
        ),
    ]
