# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-29 12:34

import datetime

from django.db import migrations
from django.utils.timezone import get_current_timezone

def migrate_events(apps, schema_editor):
    Participant = apps.get_model('events', 'Participant')

    for participant in Participant.objects.all():
        participant.contribution_date=get_current_timezone().localize(
            datetime.datetime.combine(
                participant.activity.event.start_date,participant.activity.event.start_time
            )
        )
        participant.save()

class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0015_auto_20200128_1045'),
        ('events', '0010_auto_20190816_1327'),
    ]

    operations = [
        migrations.RunPython(migrate_events,migrations.RunPython.noop)
    ]
