# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-17 10:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_update_contribution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='attendee limit'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_online',
            field=models.NullBooleanField(default=None, verbose_name='is online'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='deadline to apply'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='start time'),
        ),
    ]
