# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-28 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200226_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='automatically_accept',
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date and time'),
        ),
    ]
