# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-12 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20200928_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online_meeting_url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Online Meeting URL'),
        ),
    ]
