# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-13 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_online_meeting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='online_meeting_url',
            field=models.TextField(blank=True, default='', verbose_name='Online Meeting URL'),
        ),
    ]
