# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-01 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0038_auto_20210127_1358'),
        ('events', '0020_auto_20201112_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='activity_ptr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='contributor_ptr',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
