# Generated by Django 3.2.4 on 2024-12-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20241209_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256)),
            ],
            options={
                'verbose_name': 'Event webhook',
                'verbose_name_plural': 'Event webhooks',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('deed-participant.succeeded', 'Participant succeeded'), ('deed.succeeded', 'Deed succeeded'), ('deed.published', 'Deed published'), ('donation.succeeded', 'Donation done'), ('funding.approved', 'Funding campaign published'), ('funding.succeeded', 'Funding campaign succeeded'), ('funding.50%', 'Funding campaign at 50%'), ('funding.100%', 'Funding campaign at 100%')], max_length=40),
        ),
    ]
