# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 12:15
from __future__ import unicode_literals

import django_extensions.db.fields.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0006_auto_20181115_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.Payment')),
                ('source_token', models.CharField(blank=True, help_text='Source token obtained in front-end.', max_length=100, null=True)),
                ('charge_token', models.CharField(blank=True, help_text='Charge token at Stripe.', max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, help_text='Payment amount in smallest units (e.g. cents).', null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('data', django_extensions.db.fields.json.JSONField(blank=True, max_length=5000, verbose_name='Integration data')),
            ],
            options={
                'abstract': False,
            },
            bases=('payments.payment',),
        ),
    ]
