# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 22:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_stripe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
