# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-17 09:36


from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('impact', '0008_impacttype_icon'),
        ('statistics', '0007_auto_20171114_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Should this be shown or hidden.')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DatabaseStatisticTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'managed': True,
                'db_table': 'statistics_databasestatistic_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'database statistic Translation',
            },
        ),
        migrations.CreateModel(
            name='ImpactStatisticTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
            ],
            options={
                'managed': True,
                'db_table': 'statistics_impactstatistic_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'impact statistic Translation',
            },
        ),
        migrations.CreateModel(
            name='ManualStatisticTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'managed': True,
                'db_table': 'statistics_manualstatistic_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'manual statistic Translation',
            },
        ),
        migrations.CreateModel(
            name='DatabaseStatistic',
            fields=[
                ('basestatistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistics.BaseStatistic')),
                ('query', models.CharField(choices=[(b'manual', 'Manual input'), (b'people_involved', 'People involved'), (b'participants', 'Participants'), (b'activities_succeeded', 'Activities succeeded'), (b'assignments_succeeded', 'Tasks succeeded'), (b'events_succeeded', 'Events succeeded'), (b'fundings_succeeded', 'Funding activities succeeded'), (b'assignment_members', 'Task applicants'), (b'event_members', 'Event participants'), (b'assignments_online', 'Tasks online'), (b'events_online', 'Events online'), (b'fundings_online', 'Funding activities online'), (b'donations', 'Donations'), (b'donated_total', 'Donated total'), (b'pledged_total', 'Pledged total'), (b'amount_matched', 'Amount matched'), (b'activities_online', 'Activities Online'), (b'votes_cast', 'Votes casts'), (b'time_spent', 'Time spent'), (b'members', 'Number of members')], db_index=True, max_length=20, verbose_name='query')),
            ],
            options={
                'abstract': False,
            },
            bases=('statistics.basestatistic',),
        ),
        migrations.CreateModel(
            name='ImpactStatistic',
            fields=[
                ('basestatistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistics.BaseStatistic')),
                ('impact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impact.ImpactType')),
            ],
            options={
                'abstract': False,
            },
            bases=('statistics.basestatistic',),
        ),
        migrations.CreateModel(
            name='ManualStatistic',
            fields=[
                ('basestatistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistics.BaseStatistic')),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('statistics.basestatistic',),
        ),
        migrations.AddField(
            model_name='basestatistic',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_statistics.basestatistic_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='manualstatistictranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='statistics.ManualStatistic'),
        ),
        migrations.AddField(
            model_name='impactstatistictranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='statistics.ImpactStatistic'),
        ),
        migrations.AddField(
            model_name='databasestatistictranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='statistics.DatabaseStatistic'),
        ),
        migrations.AlterUniqueTogether(
            name='manualstatistictranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='impactstatistictranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='databasestatistictranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
