# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-14 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('impact', '0007_auto_20200714_1647'),
        ('statistics', '0007_auto_20171114_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Should this be shown or hidden.')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BaseStatisticTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'managed': True,
                'db_table': 'statistics_basestatistic_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'base statistic Translation',
            },
        ),
        migrations.CreateModel(
            name='DatabaseStatistic',
            fields=[
                ('basestatistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistics.BaseStatistic')),
                ('query', models.CharField(choices=[(b'manual', 'Manual'), (b'donated_total', 'Donated total'), (b'pledged_total', 'Pledged total'), (b'projects_online', 'Projects online'), (b'projects_realized', 'Projects realized'), (b'projects_complete', 'Projects complete'), (b'tasks_realized', 'Tasks realized'), (b'task_members', 'Taskmembers'), (b'people_involved', 'People involved'), (b'participants', 'Participants'), (b'amount_matched', 'Amount Matched'), (b'votes_cast', 'Number of votes cast'), (b'members', 'Number of members')], db_index=True, default=b'manual', max_length=20, verbose_name='query')),
            ],
            options={
                'abstract': False,
            },
            bases=('statistics.basestatistic',),
        ),
        migrations.CreateModel(
            name='ImpactStatistic',
            fields=[
                ('basestatistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistics.BaseStatistic')),
                ('impact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impact.ImpactType')),
            ],
            options={
                'abstract': False,
            },
            bases=('statistics.basestatistic',),
        ),
        migrations.CreateModel(
            name='ManualStatistic',
            fields=[
                ('basestatistic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='statistics.BaseStatistic')),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('statistics.basestatistic',),
        ),
        migrations.AddField(
            model_name='basestatistictranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='statistics.BaseStatistic'),
        ),
        migrations.AddField(
            model_name='basestatistic',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_statistics.basestatistic_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='basestatistictranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
