# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-15 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0008_auto_20200714_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseStatisticTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'managed': True,
                'db_table': 'statistics_databasestatistic_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'database statistic Translation',
            },
        ),
        migrations.CreateModel(
            name='ManualStatisticTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='statistics.ManualStatistic')),
            ],
            options={
                'managed': True,
                'db_table': 'statistics_manualstatistic_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'manual statistic Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='basestatistictranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='basestatistictranslation',
            name='master',
        ),
        migrations.AlterField(
            model_name='databasestatistic',
            name='query',
            field=models.CharField(choices=[(b'manual', 'Manual input'), (b'people_involved', 'People involved'), (b'participants', 'Participants'), (b'activities_succeeded', 'Activities succeeded'), (b'assignments_succeeded', 'Tasks succeeded'), (b'events_succeeded', 'Events succeeded'), (b'fundings_succeeded', 'Funding activities succeeded'), (b'assignment_members', 'Task applicants'), (b'event_members', 'Event participants'), (b'assignments_online', 'Tasks online'), (b'events_online', 'Events online'), (b'fundings_online', 'Funding activities online'), (b'donations', 'Donations'), (b'donated_total', 'Donated total'), (b'pledged_total', 'Pledged total'), (b'amount_matched', 'Amount matched'), (b'activities_online', 'Activities Online'), (b'votes_cast', 'Votes casts'), (b'time_spent', 'Time spent'), (b'members', 'Number of members')], db_index=True, max_length=20, verbose_name='query'),
        ),
        migrations.DeleteModel(
            name='BaseStatisticTranslation',
        ),
        migrations.AddField(
            model_name='databasestatistictranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='statistics.DatabaseStatistic'),
        ),
        migrations.AlterUniqueTogether(
            name='manualstatistictranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='databasestatistictranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
