# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-15 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0009_auto_20200715_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStatisticTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='statistics.ImpactStatistic')),
            ],
            options={
                'managed': True,
                'db_table': 'statistics_impactstatistic_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'impact statistic Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='impactstatistictranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
