# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-29 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'office region',
                'verbose_name_plural': 'office rgion',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeSubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offices.OfficeRegion', verbose_name='region')),
            ],
            options={
                'verbose_name': 'office subregion',
                'verbose_name_plural': 'office subregion',
                'ordering': ['name'],
            },
        ),
    ]
