# Generated by Django 3.0.14 on 2021-04-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_auto_20210203_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officeregion',
            options={'ordering': ['name'], 'verbose_name': 'office region', 'verbose_name_plural': 'office regions'},
        ),
        migrations.AlterModelOptions(
            name='officesubregion',
            options={'ordering': ['name'], 'verbose_name': 'office group', 'verbose_name_plural': 'office groups'},
        ),
        migrations.AlterField(
            model_name='officesubregion',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offices.OfficeRegion', verbose_name='office region'),
        ),
    ]
