# Generated by Django 4.2.20 on 2026-01-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_add_permissions_20230130_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officeregion',
            options={'ordering': ['name'], 'verbose_name': 'Work location region', 'verbose_name_plural': 'Work location regions'},
        ),
        migrations.AlterModelOptions(
            name='officesubregion',
            options={'ordering': ['name'], 'verbose_name': 'Work location group', 'verbose_name_plural': 'Work location groups'},
        ),
        migrations.AlterField(
            model_name='officesubregion',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offices.officeregion', verbose_name='Work location region'),
        ),
    ]
