# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-12 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonPlatformSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
                ('lockdown', models.BooleanField(default=True, help_text='Checking this will lockdown the site with the provided password.')),
                ('lockdown_password', models.CharField(blank=True, help_text='This is the password clients need to enter to view the site.', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'main platform settings',
                'verbose_name_plural': 'main platform settings',
            },
        ),
    ]
