# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 14:14
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'add_pictureitem', 'change_pictureitem', 'delete_pictureitem',
                'add_contenttype', 'change_contenttype', 'delete_contenttype',
                'add_oembeditem', 'change_oembeditem', 'delete_oembeditem',
                'add_rawhtmlitem', 'change_rawhtmlitem', 'delete_rawhtmlitem',
                'add_textitem', 'change_textitem', 'delete_textitem',
                'add_placeholder', 'change_placeholder', 'delete_placeholder',
                'add_contentitem', 'change_contentitem', 'delete_contentitem',
                'add_placeholder', 'change_placeholder', 'delete_placeholder',
                'add_textitem', 'change_textitem', 'delete_textitem',
            )
        }
    }

    update_group_permissions('common', group_perms)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_permission_groups'),
    ]

    operations = [
            migrations.RunPython(add_group_permissions)
    ]
