# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_docdata', '0003_merge_20170118_1533'),
        ('payments_docdata', '0003_merge_20170106_1627'),
    ]

    operations = [
    ]
