# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_logger', '0002_auto_20201103_1028'),
        ('payments', '0007_auto_20201103_1028'),
        ('payments_docdata', '0004_merge_20170124_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docdatadirectdebitpayment',
            name='payment_ptr',
        ),
        migrations.RemoveField(
            model_name='docdatapayment',
            name='payment_ptr',
        ),
        migrations.RemoveField(
            model_name='docdatatransaction',
            name='transaction_ptr',
        ),
        migrations.DeleteModel(
            name='DocdataDirectdebitPayment',
        ),
        migrations.DeleteModel(
            name='DocdataPayment',
        ),
        migrations.DeleteModel(
            name='DocdataTransaction',
        ),
    ]
