# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 13:40
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160718_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='amount_donated',
        ),
        migrations.RemoveField(
            model_name='project',
            name='amount_needed',
        ),
        migrations.AddField(
            model_name='project',
            name='amount_asked_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='amount_extra_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='projectbudgetline',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount_asked',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0'), default_currency=b'EUR', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount_extra',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0'), default_currency=b'EUR', help_text='Amount pledged by organisation (matching fund).', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='projectbudgetline',
            name='amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', max_digits=12),
        ),
    ]
