# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 11:15
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160718_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount_asked_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='amount_donated_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='amount_extra_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='amount_needed_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        )
    ]
