# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbudgetline',
            name='currency',
        ),
    ]
