# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_merge'),
        ('projects', '0007_auto_20160929_0817'),
    ]

    # Get the projects with no project_type defined and then set the type
    # based on:
    #   1) amount_asked > 0 + tasks > 0 == 'both'
    #   2) task > 0 == 'sourcing'
    #   3) amount_asked > 0 == 'funding'
    #   else) keep as null or ''
    query = """
    UPDATE projects_project SET project_type = project_types.calculated_type
    FROM (
        SELECT p.id, CASE 
            WHEN (p.amount_asked > 0 AND count(t.id) > 0) THEN 'both'
            WHEN count(t.id) > 0 THEN 'sourcing' 
            WHEN p.amount_asked > 0 THEN 'funding' 
            ELSE p.project_type END as calculated_type
        FROM projects_project as p
        LEFT JOIN tasks_task as t
        ON t.project_id = p.id
        GROUP BY p.id, p.amount_asked, p.project_type) project_types
    WHERE projects_project.id = project_types.id
    AND (projects_project.project_type IS NULL 
    OR projects_project.project_type = '');
    """

    operations = [
        migrations.RunSQL(query)
    ]
