# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 07:59
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currencies',
            field=select_multiple_field.models.SelectMultipleField(choices=[(b'EUR', b'Euro')], default='EUR', max_length=100),
            preserve_default=False,
        ),
    ]
