# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_fix_project_type'),
        ('projects', '0008_merge'),
    ]

    operations = [
    ]
