# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 12:03
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def fix_budget_line_amounts(apps, schema_editor):
    ProjectBudgetLine = apps.get_model('projects', 'ProjectBudgetLine')

    ProjectBudgetLine.objects.all().update(amount=F('amount') / 100)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_merge'),
    ]

    operations = [
        migrations.RunPython(fix_budget_line_amounts)
    ]
