# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160929_0817'),
        ('projects', '0009_auto_20160909_0959'),
    ]

    operations = [
    ]
