# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20160719_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='amount_donated',
        ),
        migrations.RemoveField(
            model_name='project',
            name='amount_donated_currency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='amount_needed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='amount_needed_currency',
        ),
    ]
