# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_merge'),
        ('projects', '0009_auto_20160909_0959'),
        ('projects', '0007_project_currencies'),
        ('projects', '0007_remove_projectbudgetline_currency'),
    ]

    operations = [
    ]
