# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 07:46
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20161019_1403'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),

        migrations.AlterField(
            model_name='project',
            name='amount_asked',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0'), default_currency=b'EUR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount_donated',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0'), default_currency=b'EUR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount_extra',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0'), default_currency=b'EUR', help_text='Amount pledged by organisation (matching fund).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount_needed',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0'), default_currency=b'EUR', max_digits=12),
        ),
    ]
