# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 14:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20161006_1149'),
        ('projects', '0010_auto_20161019_1403'),
    ]

    operations = [
    ]
