# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_merge'),
        ('projects', '0011_auto_20161028_0946'),
    ]

    operations = [
    ]
