# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 09:41
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currencies',
            field=multiselectfield.MultiSelectField(choices=[(b'EUR', 'Euro')], default=[], max_length=100, null=True),
        ),
    ]
