# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20161109_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payout_status',
            field=models.CharField(choices=[(b'created', 'Created'), (b'in_progress', 'In progress'), (b'partial', 'Partial'), (b'success', 'Success'), (b'failed', 'Failed')], max_length=50, null=True),
        ),
    ]
