# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_payout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='campaign_payed_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Campaign Payed Out'),
        ),
    ]
