# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_campaign_payed_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='payout_status',
            field=models.CharField(choices=[(b'needs_approval', 'Needs approval'), (b'approved', 'Approved'), (b'created', 'Created'), (b'in_progress', 'In progress'), (b'partial', 'Partial'), (b'success', 'Success'), (b'failed', 'Failed')], max_length=50, null=True),
        ),
    ]
