# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20161207_0900'),
        ('projects', '0017_auto_20161121_1053'),
    ]

    operations = [
    ]
