# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_merge_20170106_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currencies',
            field=multiselctfield.db.fields.SelectMultipleField(choices=[(b'EUR', 'Euro')], default=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='payout_status',
            field=models.CharField(blank=True, choices=[(b'needs_approval', 'Needs approval'), (b'approved', 'Approved'), (b'created', 'Created'), (b'in_progress', 'In progress'), (b'partial', 'Partial'), (b'success', 'Success'), (b'failed', 'Failed')], max_length=50, null=True),
        ),
    ]
