# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20170106_1657'),
    ]

    operations = [
    ]
