# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20170118_1537'),
        ('projects', '0020_merge_20170124_1338'),
    ]

    operations = [
    ]
