# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20170323_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'permissions': (('approve_payout', 'Can approve payouts for projects'),), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='campaign_payed_out',
            new_name='campaign_paid_out',
        ),
        migrations.AlterField(
            model_name='project',
            name='payout_status',
            field=models.CharField(blank=True, choices=[(b'needs_approval', 'Needs approval'), (b'approved', 'Approved'), (b'scheduled', 'Scheduled'), (b're_scheduled', 'Re-scheduled'), (b'in_progress', 'In progress'), (b'partial', 'Partially paid'), (b'success', 'Success'), (b'failed', 'Failed')], max_length=50, null=True),
        ),
    ]
