# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20170404_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='campaign_paid_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Campaign Paid Out'),
        ),
    ]
