# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-02 20:40
from __future__ import unicode_literals

from django.db import migrations


def add_phaselogs_to_old_projects(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ProjectPhaseLog = apps.get_model('projects', 'ProjectPhaseLog')

    for project in Project.objects.filter(projectphaselog__isnull=True):
        log = ProjectPhaseLog.objects.create(project=project, status=project.status, start=project.deadline)
        log.save()


def dummy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20170424_1653'),
    ]

    operations = [
        migrations.RunPython(add_phaselogs_to_old_projects, dummy),
    ]
