# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-28 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20170523_1422'),
        ('projects', '0028_auto_20170619_1555'),
    ]

    operations = [
    ]
