# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_merge_20170628_0905'),
    ]

    operations = [
        migrations.AlterField(model_name='Project',
                              name='account_bic',
                              field=models.CharField(max_length=255, blank=True, null=True)),
        migrations.RenameField(model_name='Project',
                               old_name='account_bic',
                               new_name='account_details')
    ]
