# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 10:04
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_rename_account_bic_20170705_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'permissions': (('approve_payout', 'Can approve payouts for projects'), ('api_read_project', 'Can view projects through the API'), ('api_add_project', 'Can add projects through the API'), ('api_change_project', 'Can change projects through the API'), ('api_delete_project', 'Can delete projects through the API'), ('api_read_projectdocument', 'Can view project documents through the API'), ('api_add_projectdocument', 'Can add project documents through the API'), ('api_change_projectdocument', 'Can change project documents through the API'), ('api_delete_projectdocument', 'Can delete project documents through the API'), ('api_read_projectbudgetline', 'Can view project budget lines through the API'), ('api_add_projectbudgetline', 'Can add project budget lines through the API'), ('api_change_projectbudgetline', 'Can change project budget lines through the API'), ('api_delete_projectbudgetline', 'Can delete project budget lines through the API')), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='account_details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='account details'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=bluebottle.utils.fields.PrivateFileField(max_length=110, upload_to=b'private/private/private/projects/documents'),
        ),
    ]
