# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-11 06:39
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F

def set_task_manager_to_owner(apps, schema_editor):
    Project = apps.get_model('projects', 'project')
    Project.objects.update(task_manager=F('owner'))

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_add_project_roles'),
    ]

    operations = [
        migrations.RunPython(set_task_manager_to_owner),
    ]
