# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_set_owner_permissions'),
        ('projects', '0031_fix_migration_projectstatuslog_creation_20170721_1637'),
    ]

    operations = [
    ]
