# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 09:29
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_merge_20170831_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='place',
            field=models.CharField(blank=True, help_text='Geographical location', max_length=200, null=True),
        ),
    ]
