# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-20 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20170914_1503'),
        ('projects', '0041_auto_20170918_1201'),
    ]

    operations = [
    ]
