# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 09:58
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20171110_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb_projects.ProjectTheme'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=bluebottle.utils.fields.PrivateFileField(max_length=110, upload_to=b'private/projects/documents'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='file',
            field=models.FileField(upload_to=b'project_images/'),
        ),
    ]
