# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 18:13
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20171023_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsearchfilter',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='projectsearchfilter',
            name='sequence',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='projectplatformsettings',
            name='project_contact_method',
            field=models.CharField(choices=[(b'email', 'E-mail'), (b'phone', 'Phone')], max_length=100),
        ),
    ]
