# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 18:47
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20171023_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectplatformsettings',
            old_name='project_contact_method',
            new_name='contact_method',
        ),
        migrations.RenameField(
            model_name='projectplatformsettings',
            old_name='project_create_flow',
            new_name='create_flow',
        ),
        migrations.RenameField(
            model_name='projectplatformsettings',
            old_name='project_create_types',
            new_name='create_types',
        ),
        migrations.RenameField(
            model_name='projectplatformsettings',
            old_name='project_suggestions',
            new_name='suggestions',
        ),
        migrations.AlterField(
            model_name='projectsearchfilter',
            name='project_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='projects.ProjectPlatformSettings'),
        ),
    ]
