# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 08:16
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20171023_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectplatformsettings',
            name='suggestions',
        ),
    ]
