# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 08:52
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20171024_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplatformsettings',
            name='contact_types',
            field=multiselectfield.MultiSelectField(choices=[(b'organization', 'Organization'), (b'personal', 'Personal')], default=['organization'], max_length=100),
            preserve_default=False,
        ),
    ]
