# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20171025_1253'),
        ('projects', '0049_auto_20171024_1018'),
    ]

    operations = [
    ]
