# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 15:37
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_merge_20171110_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectplatformsettings',
            options={'verbose_name': 'project platform settings', 'verbose_name_plural': 'project platform settings'},
        ),
        migrations.AddField(
            model_name='projectplatformsettings',
            name='allow_anonymous_rewards',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb_projects.ProjectTheme'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=bluebottle.utils.fields.PrivateFileField(max_length=110, upload_to=b'private/private/private/projects/documents'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='file',
            field=models.FileField(upload_to=b'project_images/'),
        ),
        migrations.AlterField(
            model_name='projectsearchfilter',
            name='name',
            field=models.CharField(choices=[(b'location', 'Location'), (b'theme', 'Theme'), (b'skills', 'Skill'), (b'date', 'Date'), (b'status', 'Status'), (b'type', 'Type'), (b'category', 'Category')], max_length=100),
        ),
    ]
