# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-23 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_merge_20171113_1230'),
        ('projects', '0045_auto_20171114_1058'),
    ]

    operations = [
    ]
