# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-27 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_merge_20171124_0022'),
        ('projects', '0051_merge_20171124_0021'),
    ]

    operations = [
    ]
