# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-28 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_merge_20171124_0022'),
        ('projects', '0053_merge_20171122_1001'),
    ]

    operations = [
    ]
