# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_merge_20171128_1142'),
        ('projects', '0052_merge_20171127_1329'),
    ]

    operations = [
    ]
