# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_auto_20171205_0847'),
        ('projects', '0055_merge_20171201_1608'),
    ]

    operations = [
    ]
