# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-20 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_merge_20171205_1236'),
        ('projects', '0055_project_campaign_edited'),
    ]

    operations = [
    ]
