# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 10:00
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


def clean_up_old_migration(apps, schema_editor):
    # Ugly hack to fix half migrated tenants
    from django.db import connection
    cursor = connection.cursor()
    cursor.execute("DROP TABLE IF EXISTS projects_projectcreatetemplate")


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20180118_1100'),
        ('projects', '0058_merge_20171220_1342'),
    ]

    operations = [
        migrations.RunPython(clean_up_old_migration),
        migrations.CreateModel(
            name='ProjectCreateTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[(b'EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('amount', bluebottle.utils.fields.MoneyField(currency_choices="[('EUR', u'Euro')]", decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('organization', models.ForeignKey(help_text='Default partner organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('project_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='projects.ProjectPlatformSettings')),
            ],
        ),
        migrations.AlterField(
            model_name='customprojectfield',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='projects.Project'),
        ),
    ]
