# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-22 09:37
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20171114_1035'),
        ('projects', '0058_auto_20171222_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcreatetemplate',
            name='organization',
            field=models.ForeignKey(help_text='Default partner organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='projectcreatetemplate',
            name='amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices="[('EUR', u'Euro')]", decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectcreatetemplate',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
    ]
