# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_merge_20171220_1342'),
        ('projects', '0059_auto_20171222_1037'),
    ]

    operations = [
    ]
