# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-19 15:25
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20180119_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcreatetemplate',
            name='default_organization',
        ),
        migrations.AlterField(
            model_name='projectcreatetemplate',
            name='default_amount_asked',
            field=bluebottle.utils.fields.MoneyField(currency_choices="[('EUR', u'Euro')]", decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
    ]
