# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-05 13:03
from __future__ import unicode_literals

import bluebottle.utils.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20180123_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geocoding',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='projectcreatetemplate',
            name='default_amount_asked',
            field=bluebottle.utils.fields.MoneyField(blank=True, currency_choices="[('EUR', u'Euro')]", decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
