# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-15 10:30
from __future__ import unicode_literals

from django.db import migrations


def move_position(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ProjectLocation = apps.get_model('projects', 'ProjectLocation')
    for project in Project.objects.filter(latitude__isnull=False).all():
        location = ProjectLocation.objects.create(
            project=project,
            latitude=project.latitude,
            longitude=project.longitude
        )
        location.save()


def restore_position(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ProjectLocation = apps.get_model('projects', 'ProjectLocation')
    for location in ProjectLocation.objects.all():
        project = Project.objects.filter(id=location.project_id).update(
            latitude=location.latitude,
            longitude=location.longitude
        )
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_auto_20180306_1614'),
    ]

    operations = [
        migrations.RunPython(move_position, restore_position)
    ]
