# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 13:56
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0074_auto_20180416_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlocation',
            options={'verbose_name': 'Map', 'verbose_name_plural': 'Map'},
        ),
        migrations.AlterModelOptions(
            name='projectphaselog',
            options={'verbose_name': 'project phase log', 'verbose_name_plural': 'project phase logs'},
        ),
        migrations.AddField(
            model_name='project',
            name='bank_details_reviewed',
            field=models.BooleanField(default=False, help_text='A staff memmber has reviewed the bank details for this project', verbose_name='Bank details reviewed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='payout_status',
            field=models.CharField(blank=True, choices=[(b'needs_approval', 'Needs approval'), (b'approved', 'Approved'), (b'scheduled', 'Scheduled'), (b're_scheduled', 'Re-scheduled'), (b'in_progress', 'In progress'), (b'partial', 'Partially paid'), (b'success', 'Success'), (b'failed', 'Failed')], max_length=50, null=True, verbose_name='payout_status'),
        ),
        migrations.AlterField(
            model_name='projectcreatetemplate',
            name='default_amount_asked',
            field=bluebottle.utils.fields.MoneyField(blank=True, currency_choices="[('EUR', u'Euro')]", decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='city',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='neighborhood',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='neighborhood'),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='place',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='postal_code'),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='street',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='street'),
        ),
    ]
