# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-10 12:05
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_auto_20180626_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='campaign_duration',
            field=models.IntegerField(null=True, verbose_name='running time'),
        ),
    ]
