# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-28 08:49
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_auto_20180626_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='popularity',
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Location'),
        ),
        migrations.AlterField(
            model_name='projectcreatetemplate',
            name='default_amount_asked',
            field=bluebottle.utils.fields.MoneyField(blank=True, currency_choices="[('EUR', u'Euro')]", decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='projectplatformsettings',
            name='allow_anonymous_rewards',
            field=models.BooleanField(default=True, verbose_name='Allow guests to donate rewards'),
        ),
    ]
