# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-21 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_auto_20180626_1225'),
        ('projects', '0080_auto_20180604_1322'),
    ]

    operations = [
    ]
