# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-19 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_auto_20180828_1049'),
        ('projects', '0080_auto_20180810_1405'),
    ]

    operations = [
    ]
