# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-18 11:35
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion
from multiselectfield import MultiSelectField


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_auto_20180810_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplatformsettings',
            name='match_options',
            field=MultiSelectField(blank=True, choices=[(b'theme', 'Theme'), (b'skill', 'Skill'), (b'location', 'Location')], max_length=100),
        ),
    ]
