# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_auto_20180904_1532'),
        ('projects', '0080_auto_20180810_1405'),
    ]

    operations = [
    ]
