# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_merge_20181012_1209'),
        ('projects', '0081_merge_20180919_1152'),
    ]

    operations = [
    ]
