# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-07 14:52
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_auto_20181207_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocument',
            name='author',
        ),
        migrations.RemoveField(
            model_name='projectdocument',
            name='project',
        ),
        migrations.AlterField(
            model_name='projectcreatetemplate',
            name='default_amount_asked',
            field=bluebottle.utils.fields.MoneyField(blank=True, currency_choices="[('EUR', u'Euro')]", decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectDocument',
        ),
    ]
