# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-07 14:52
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_auto_20181207_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDocument',
        ),
    ]
