# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-17 09:07
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0085_auto_20181207_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='account_bank_country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='account_details',
        ),
        migrations.RemoveField(
            model_name='project',
            name='account_holder_address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='account_holder_city',
        ),
        migrations.RemoveField(
            model_name='project',
            name='account_holder_country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='account_holder_postal_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='account_number',
        )
    ]
