# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-04 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_merge_20180911_1659'),
        ('projects', '0085_auto_20181207_1552'),
    ]

    operations = [
    ]
