# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-06 16:14


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0086_auto_20190117_1007'),
        ('projects', '0081_merge_20180911_1659'),
    ]

    operations = [
    ]
