# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-15 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_merge_20180911_1659'),
        ('projects', '0087_merge_20190130_1355'),
    ]

    operations = [
    ]
