# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-13 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0086_merge_20190204_1005'),
        ('projects', '0087_merge_20190130_1355'),
    ]

    operations = [
    ]
