# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-15 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_merge_20190208_1523'),
        ('projects', '0088_merge_20190215_1425'),
    ]

    operations = [
    ]
