# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-22 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_merge_20190213_1448'),
        ('projects', '0089_merge_20190215_1438'),
    ]

    operations = [
    ]
