# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-18 07:04
from __future__ import unicode_literals

from django.db import migrations, connection
from django.contrib.gis.geos import Point
from moneyed import Money

from bluebottle.clients import properties


def map_status(status):
    mapping = {
        'plan-new': 'draft',
        'plan-submitted': 'submitted',
        'plan-needs-work': 'needs_work',
        'voting': 'approved',
        'voting-done': 'approved',
        'campaign': 'approved',
        'to-be-continued': 'approved',
        'done-complete': 'approved',
        'done-incomplete': 'approved',
        'closed': 'closed',
        'refunded': 'approved',
    }
    return mapping[status.slug]


def map_funding_status(status):
    mapping = {
        'plan-new': 'draft',
        'plan-submitted': 'draft',
        'plan-needs-work': 'draft',
        'voting': 'draft',
        'voting-done': 'draft',
        'campaign': 'open',
        'to-be-continued': 'draft',
        'done-complete': 'succeeded',
        'done-incomplete': 'succeeded',
        'closed': 'closed',
        'refunded': 'refunded',
    }
    return mapping[status.slug]


def truncate(number, limit):
    return int(number * pow(10, limit)) / 10 ^ pow(10, limit)


def migrate_projects(apps, schema_editor):

    Project = apps.get_model('projects', 'Project')
    Initiative = apps.get_model('initiatives', 'Initiative')
    Funding = apps.get_model('funding', 'Funding')
    Geolocation = apps.get_model('geo', 'Geolocation')
    Country = apps.get_model('geo', 'Country')
    Image = apps.get_model('files', 'Image')
    Client = apps.get_model('clients', 'Client')
    OrganizationContact = apps.get_model('organizations', 'OrganizationContact')
    OldStripePayoutAccount = apps.get_model('payouts', 'StripePayoutAccount')
    PlainPayoutAccount = apps.get_model('payouts', 'PlainPayoutAccount')
    StripePayoutAccount = apps.get_model('funding_stripe', 'StripePayoutAccount')
    ExternalAccount = apps.get_model('funding_stripe', 'ExternalAccount')
    BankPayoutAccount = apps.get_model('funding', 'BankPayoutAccount')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Clean-up previous migrations of projects to initiatives
    Initiative.objects.all().delete()

    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    properties.set_tenant(tenant)

    for project in Project.objects.all():

        if hasattr(project, 'projectlocation') and project.projectlocation.country:
            if project.projectlocation.latitude and project.projectlocation.longitude:
                point = Point(
                    truncate(project.projectlocation.longitude, 12),
                    truncate(project.projectlocation.latitude, 12)
                )
            else:
                point = Point(0, 0)

            country = project.country

            if not country and project.projectlocation.country and Country.objects.filter(
                    translations__name=project.projectlocation.country
                ).count():
                country = Country.objects.filter(
                    translations__name__contains=project.projectlocation.country
                ).first()

            if not country:
                country = Country.objects.filter(alpha2_code=properties.DEFAULT_COUNTRY_CODE).first()

            if country:
                place = Geolocation.objects.create(
                    street=project.projectlocation.street,
                    postal_code=project.projectlocation.postal_code,
                    country=country,
                    locality=project.projectlocation.city,
                    position=point
                )
            else:
                place = None
        else:
            if project.country:
                place = Geolocation.objects.create(
                    country=project.country,
                    position=Point(0, 0)
                )
            else:
                place = None

        initiative = Initiative.objects.create(
            title=project.title,
            slug=project.slug,
            pitch=project.pitch or '',
            story=project.story or '',
            theme=project.theme,
            video_url=project.video_url,
            place=place,
            location=project.location,
            owner=project.owner,
            reviewer=project.reviewer,
            activity_manager=project.task_manager,
            promoter=project.promoter,
            status=map_status(project.status)

        )
        if project.image:
            try:
                image = Image.objects.create(owner=project.owner)
                image.file.save(project.image.name, project.image.file, save=True)
                initiative.image = image
            except IOError:
                pass

        if project.organization:
            initiative.organization = project.organization

        contact = OrganizationContact.objects.filter(organization=project.organization).first()
        if contact:
            initiative.organization_contact = contact

        initiative.created = project.created
        initiative.categories = project.categories.all()
        initiative.save()

        # Create Funding event if we target amount is set
        if project.project_type in ['both', 'funding'] or project.donation_set.count():
            account = None
            if isinstance(project.payout_account, OldStripePayoutAccount):
                content_type = ContentType.objects.get_for_model(StripePayoutAccount)
                account = StripePayoutAccount.objects.create(
                    polymorphic_ctype=content_type,  # This does not get set automatically in migrations
                    owner=project.payout.account.user,
                    account_id=project.payout_account.account_id,
                    country=project.payout_account.country
                )
                ExternalAccount.objects.create(
                    account=account,
                    account_id=project.payout_account.bank_details.account
                )
            elif isinstance(project.payout_account, PlainPayoutAccount):
                content_type = ContentType.objects.get_for_model(BankPayoutAccount)
                account = BankPayoutAccount.objects.create(
                    polymorphic_ctype=content_type,  # This does not get set automatically in migrations
                    owner=project.payout_account.user,
                    account_number=project.payout_account.account_number,
                    account_details=project.payout_account.account_details,

                    account_holder_name=project.payout_account.account_holder_name,
                    account_holder_address=project.payout_account.account_holder_address,
                    account_bank_country=project.payout_account.account_bank_country,
                )

            content_type = ContentType.objects.get_for_model(Funding)
            funding = Funding.objects.create(
                # Common activity fields
                polymorphic_ctype=content_type,  # This does not get set automatically in migrations
                initiative=initiative,
                owner=project.owner,
                highlight=project.is_campaign,
                created=project.created,
                updated=project.updated,
                status=map_funding_status(project.status),
                title=project.title,
                slug=project.slug,
                description=project.pitch or '',

                # Funding specific fields
                deadline=project.deadline,
                # ??? duration
                target=project.amount_asked,
                amount_matching=project.amount_extra,
                country=project.country,
                account=account
            )

            # TODO: Add budget lines
            # TODO: Add fundraisers
            # TODO: Add rewards


def wipe_initiatives(apps, schema_editor):

    Initiative = apps.get_model('initiatives', 'Initiative')
    Funding = apps.get_model('funding', 'Funding')

    Initiative.objects.all().delete()
    Funding.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_merge_20190222_1101'),
        ('funding', '0026_auto_20190904_1200'),
        ('initiatives', '0015_auto_20190708_1417'),
    ]

    operations = [
        migrations.RunPython(migrate_projects, wipe_initiatives)
    ]
