# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-18 07:04
from __future__ import unicode_literals
from __future__ import division

from builtins import str
from past.utils import old_div
from django.db import migrations, connection, models
from django.contrib.gis.geos import Point

from bluebottle.clients import properties

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_merge_20190222_1101'),
        ('funding', '0042_auto_20191104_1154'),
        ('funding_lipisha', '0006_auto_20191001_2251'),
        ('funding_vitepay', '0007_auto_20191002_0903'),
        ('funding_flutterwave', '0005_auto_20191002_0903'),
        ('funding_pledge', '0004_pledgebankaccount'),
        ('initiatives', '0014_auto_20190628_1656'),
        ('wallposts', '0019_auto_20191017_2204'),
        ('funding_stripe', '0001_initial'),
        ('funding_pledge', '0002_pledgepaymentprovider'),
        ('rewards', '0009_auto_20191104_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_id',
            field=models.IntegerField(null=True),
        ),
    ]
