# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-31 08:01
from __future__ import unicode_literals

from django.db import migrations


def remove_project_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    permission = Permission.objects.get(codename='change_project')

    for group in Group.objects.all():
        group.permissions.remove(permission)
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0091_project_to_initiatives'),
    ]

    operations = [
        migrations.RunPython(remove_project_permissions)
    ]
