# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-06 08:28
from __future__ import unicode_literals

from django.db import migrations


def migrate_settings(apps, schema_editor):
    ProjectSettings = apps.get_model('projects', 'ProjectPlatformSettings')
    NotificationSettings = apps.get_model('notifications', 'NotificationPlatformSettings')
    InitiativeSettings = apps.get_model('initiatives', 'InitiativePlatformSettings')
    FundingSettings = apps.get_model('funding', 'FundingPlatformSettings')

    project_settings, _c = ProjectSettings.objects.get_or_create()
    notification_settings, _c = NotificationSettings.objects.get_or_create()
    initiative_settings, _c = InitiativeSettings.objects.get_or_create()
    funding_settings, _c = FundingSettings.objects.get_or_create()

    notification_settings.share_options = project_settings.share_options
    notification_settings.facebook_at_work_url = project_settings.facebook_at_work_url
    notification_settings.match_options = project_settings.match_options
    notification_settings.save()

    initiative_settings.contact_method = project_settings.contact_method
    initiative_settings.save()

    funding_settings.allow_anonymous_rewards = project_settings.allow_anonymous_rewards
    funding_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0092_auto_20191031_0901'),
    ]

    operations = [
        migrations.RunPython(migrate_settings, migrations.RunPython.noop)
    ]
