# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-07 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_auto_20191106_0928'),
        ('projects', '0093_auto_20191106_1206'),
    ]

    operations = [
    ]
