# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-04 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripepayment',
            old_name='intent_secret',
            new_name='client_secret',
        ),
    ]
