# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0002_auto_20190604_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='client_secret',
            field=models.CharField(max_length=100),
        ),
    ]
