# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-15 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0011_auto_20190615_0926'),
        ('funding_stripe', '0003_auto_20190607_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentProvider',
            fields=[
                ('paymentprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funding.PaymentProvider')),
            ],
            options={
                'abstract': False,
            },
            bases=('funding.paymentprovider',),
        ),
    ]
