# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-28 08:26
from __future__ import unicode_literals

import bluebottle.fsm
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funding_stripe', '0004_stripepaymentprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', bluebottle.fsm.FSMField(default=b'new', max_length=20)),
                ('account_id', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=2)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_stripe_payout_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=40)),
                ('connect_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_accounts', to='funding_stripe.ConnectAccount')),
            ],
        ),
    ]
