# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-10 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0012_auto_20190708_0731'),
        ('funding_stripe', '0004_stripepaymentprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_id', models.CharField(max_length=30)),
                ('client_secret', models.CharField(max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.Funding')),
            ],
        ),
        migrations.RemoveField(
            model_name='stripepayment',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='stripepayment',
            name='intent_id',
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='payment_intent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='funding_stripe.PaymentIntent'),
            preserve_default=False,
        ),
    ]
