# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-19 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0012_auto_20190619_1047'),
        ('funding_stripe', '0004_stripepaymentprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeKYCCheck',
            fields=[
                ('kyccheck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funding.KYCCheck')),
                ('account_id', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=100)),
            ],
            bases=('funding.kyccheck',),
        ),
    ]
