# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0012_auto_20190708_0731'),
        ('funding_stripe', '0005_auto_20190710_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentintent',
            name='activity',
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='donation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='funding.Donation'),
            preserve_default=False,
        ),
    ]
