# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-09 15:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0005_auto_20201118_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayoutaccount',
            name='eventually_due',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
    ]
