# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-10 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0013_auto_20190710_1455'),
        ('funding_stripe', '0006_auto_20190710_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSourcePayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funding.Payment')),
                ('source_token', models.CharField(max_length=30)),
                ('charge_token', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('funding.payment',),
        ),
    ]
