# Generated by Django 3.2.20 on 2023-12-23 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0006_auto_20210409_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripepayment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='stripesourcepayment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripepayoutaccount',
            name='eventually_due',
            field=models.JSONField(default=list, null=True),
        ),
    ]
