# Generated by Django 3.2.20 on 2024-05-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0006_auto_20210409_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripepayment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='stripesourcepayment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='stripepayoutaccount',
            name='eventually_due',
            field=models.JSONField(default=list, null=True),
        ),
    ]
