# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0007_stripesourcepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesourcepayment',
            name='charge_token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
