# Generated by Django 3.2.20 on 2024-06-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0007_auto_20240618_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepaymentprovider',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, help_text='This is only needed if you want to use a specific Stripe account.', max_length=200, null=True, verbose_name='Stripe publishable key'),
        ),
        migrations.AlterField(
            model_name='stripepaymentprovider',
            name='stripe_secret',
            field=models.CharField(blank=True, help_text='This is only needed if you want to use a specific Stripe account.', max_length=200, null=True, verbose_name='Stripe secret key'),
        ),
    ]
