# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-16 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0008_auto_20190710_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='payment_intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='funding_stripe.PaymentIntent'),
        ),
    ]
