# Generated by Django 3.2.20 on 2024-06-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0008_auto_20240618_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepaymentprovider',
            name='webhook_secret_connect',
            field=models.CharField(blank=True, help_text='The secret for connect webhook.', max_length=200, null=True, verbose_name='Stripe connect webhook secret'),
        ),
        migrations.AddField(
            model_name='stripepaymentprovider',
            name='webhook_secret_intents',
            field=models.CharField(blank=True, help_text='The secret for payment intents webhook.', max_length=200, null=True, verbose_name='Stripe payment intents webhook secret'),
        ),
        migrations.AddField(
            model_name='stripepaymentprovider',
            name='webhook_secret_sources',
            field=models.CharField(blank=True, help_text='The secret for payment sources webhook.', max_length=200, null=True, verbose_name='Stripe payment sources webhook secret'),
        ),
    ]
