# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-29 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0009_auto_20190716_1602'),
        ('funding_stripe', '0005_connectaccount_externalaccount'),
    ]

    operations = [
    ]
