# Generated by Django 3.2.20 on 2024-07-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0009_auto_20240625_1058'),
        ('funding_stripe', '0009_merge_20240707_1008'),
    ]

    operations = [
    ]
