# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-29 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0010_merge_20190729_1128'),
        ('funding_stripe', '0007_auto_20190729_0837'),
    ]

    operations = [
    ]
