# Generated by Django 3.2.20 on 2024-08-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0010_merge_20240707_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayoutaccount',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
