# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0011_merge_20190729_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayoutaccount',
            name='document_type',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
