# Generated by Django 3.2.20 on 2024-08-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funding_stripe", "0011_auto_20240817_1234"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="externalaccount",
            options={
                "verbose_name": "Stripe external account",
                "verbose_name_plural": "Stripe external account",
            },
        ),
        migrations.RemoveField(
            model_name="stripepayoutaccount",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="stripepayoutaccount",
            name="eventually_due",
        ),
        migrations.AddField(
            model_name="stripepayoutaccount",
            name="payments_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stripepayoutaccount",
            name="payouts_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stripepayoutaccount",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="stripepayoutaccount",
            name="account_id",
            field=models.CharField(
                blank=True, help_text="Starts with 'acct_...'", max_length=40, null=True
            ),
        ),
    ]
