# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-13 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0029_auto_20190913_1458'),
        ('funding_stripe', '0012_stripepayoutaccount_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalaccount',
            name='id',
        ),
        migrations.AddField(
            model_name='externalaccount',
            name='bankaccount_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funding.BankAccount'),
            preserve_default=False,
        ),
    ]
