# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-16 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0013_auto_20190913_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayoutaccount',
            name='document_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
