# Generated by Django 3.2.20 on 2024-09-24 09:11

from django.db import migrations

from bluebottle.funding_stripe.utils import get_stripe
from bluebottle.funding_stripe.models import StripePayoutAccount


def update_payout_accounts(apps, schema_editor):
    StripePayoutAccount = apps.get_model("funding_stripe", "StripePayoutAccount")

    for account in StripePayoutAccount.objects.filter(
        external_accounts__funding__status="open"
    ):
        stripe = get_stripe()
        stripe_account = stripe.Account.retrieve(account.account_id)

        account.requirements = stripe_account.requirements.eventually_due

        try:
            account.verified = (
                stripe_account.individual.verification.status == "verified"
            )
        except AttributeError:
            pass

        account.payments_enabled = stripe_account.charges_enabled
        account.payouts_enabled = stripe_account.payouts_enabled

        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ("funding_stripe", "0014_auto_20240913_1128"),
    ]

    operations = [
        migrations.RunPython(update_payout_accounts, migrations.RunPython.noop)
    ]
