# Generated by Django 3.2.20 on 2024-10-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funding_stripe", "0015_auto_20240923_1143"),
        ("funding_stripe", "0016_auto_20240925_1317"),
    ]

    operations = []
