# Generated by Django 3.2.20 on 2024-11-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0017_merge_0015_auto_20240923_1143_0016_auto_20240925_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepaymentprovider',
            name='currency',
            field=models.CharField(default='EUR', help_text='The currency for the global account.', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='stripepayoutaccount',
            name='business_type',
            field=models.CharField(blank=True, choices=[('company', 'Commercial company'), ('individual', 'Individual person'), ('non_profit', 'Non-profit organization')], default='individual', max_length=100),
        ),
        migrations.AlterField(
            model_name='stripepayoutaccount',
            name='tos_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
