# Generated by Django 3.2.20 on 2025-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0019_paymentintent_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalaccount',
            options={'verbose_name': 'Bank account', 'verbose_name_plural': 'Bank accounts'},
        ),
        migrations.AddField(
            model_name='stripepaymentprovider',
            name='country',
            field=models.CharField(default='NL', help_text='Normally this is NL, but by overriding the stripe key, another primary stripe account can be select. ', max_length=2, verbose_name='Country of primary stripe account'),
        ),
    ]
