# Generated by Django 4.2.20 on 2025-05-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0020_auto_20250207_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccount',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency code', max_length=10, null=True),
        ),
    ]
