# Generated by Django 4.2.20 on 2025-07-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0022_alter_externalaccount_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripepaymentprovider',
            name='webhook_secret_sources',
        ),
        migrations.AddField(
            model_name='stripepaymentprovider',
            name='webhook_secret_checkout',
            field=models.CharField(blank=True, help_text='The secret for payment checkout session webhook.', max_length=200, null=True, verbose_name='Stripe payment checkout session webhook secret'),
        ),
    ]
