# Generated by Django 4.2.20 on 2025-07-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0022_alter_externalaccount_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayoutaccount',
            name='verificationMethod',
            field=models.CharField(blank=True, null=True, choices=[('personal', 'Personal'), ('link', 'Link')], max_length=100),
        ),
        migrations.AlterField(
            model_name='stripepayoutaccount',
            name='business_type',
            field=models.CharField(blank=True, choices=[('company', 'Commercial company'), ('individual', 'Individual person'), ('non_profit', 'Non-profit organization')], max_length=100),
        ),
    ]
