# Generated by Django 4.2.20 on 2025-07-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0024_rename_verificationmethod_stripepayoutaccount_verification_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayoutaccount',
            name='business_type',
            field=models.CharField(choices=[('company', 'Commercial company'), ('individual', 'Individual person'), ('non_profit', 'Non-profit organization')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stripepayoutaccount',
            name='verification_method',
            field=models.CharField(choices=[('personal', 'Personal'), ('link', 'Link')], max_length=100, null=True),
        ),
    ]
