# Generated by Django 4.2.20 on 2025-07-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0023_remove_stripepaymentprovider_webhook_secret_sources_and_more'),
        ('funding_stripe', '0025_alter_stripepayoutaccount_business_type_and_more'),
    ]

    operations = [
    ]
