# Generated by Django 4.2.20 on 2025-08-20 08:58

from django.db import migrations, models


def set_verification_method(apps, schema_editor):
    StripePayoutAccount = apps.get_model('funding_stripe', 'StripePayoutAccount')

    StripePayoutAccount.objects.update(verification_method='personal')


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0026_merge_20250722_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayoutaccount',
            name='business_type',
            field=models.CharField(choices=[('individual', 'Individual person'), ('non_profit', 'Non-profit organization'), ('company', 'Commercial company')], max_length=100, null=True, verbose_name='Verification type'),
        ),
        migrations.AlterField(
            model_name='stripepayoutaccount',
            name='verification_method',
            field=models.CharField(choices=[('personal', 'Personal')], default='personal', max_length=100, null=True),
        ),
        migrations.RunPython(set_verification_method, migrations.RunPython.noop)
    ]
