# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 13:25
from __future__ import unicode_literals

import bluebottle.utils.fields
import bluebottle.utils.utils
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', bluebottle.utils.fields.ImageField(blank=True, help_text='Minimal of 800px wide', max_length=255, null=True, upload_to=b'fundraiser_images/', verbose_name='picture')),
                ('video_url', models.URLField(blank=True, default=b'', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default=b'EUR', max_length=10)),
                ('deadline', models.DateTimeField(null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, help_text='When this fundraiser was created.', verbose_name='created')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='updated')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='deleted')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Location')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, ),
        ),
    ]
