# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_auto_20201103_1028'),
        ('fundraisers', '0007_auto_20170803_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='fundraiser',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='fundraiser',
            name='project',
        ),
        migrations.DeleteModel(
            name='Fundraiser',
        ),
    ]
