# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-23 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookerEmbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('type', models.CharField(choices=[(b'dashboard', 'Dashboard'), (b'look', 'Look'), (b'space', 'Space')], max_length=10, verbose_name='type')),
                ('looker_id', models.IntegerField(verbose_name='Looker Id')),
            ],
        ),
    ]
