# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-28 08:54


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('looker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookerembed',
            options={'permissions': (('access_looker_embeds', 'Can access looker embeds'),)},
        ),
    ]
