# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-01 12:19
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def generate_looker_embeds(apps, schema_editor):
    LookerEmbed = apps.get_model('looker', 'LookerEmbed')
    LookerEmbed.objects.filter(looker_id=67).update(looker_id=79)


def dummy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('looker', '0003_init_looker_embeds'),
    ]

    operations = [
        migrations.RunPython(generate_looker_embeds, dummy)
    ]
