# Generated by Django 4.2.20 on 2025-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looker', '0004_auto_20201001_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookerembed',
            name='type',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('look', 'Look'), ('space', 'Space')], max_length=10, verbose_name='type'),
        ),
    ]
