from decimal import Decimal

from django.db import models
from django.utils.translation import ugettext as _

from bluebottle.payments.models import Payment


class InterswitchPayment(Payment):
    product_id = models.CharField(help_text=_('Product Identifier for PAYDirect.'), max_length=200, null=True, blank=True)
    amount = models.CharField(help_text=_('Transaction amount in small (kobo or cents) denomination. E.g., 200000 for 2,000.00'), max_length=200, null=True, blank=True)
    currency = models.CharField(help_text=_('566 (For Naira)'), max_length=200, default='566')
    site_redirect_url = models.CharField(help_text=_('URL of the page on your web site/portal user is to be redirected to after payment. You may want to add encrypted authentication information to allow a user renter the web site/portal transparently without being challenged'), max_length=200, null=True, blank=True)
    txn_ref = models.CharField(help_text=_('Transaction Reference Number. This Reference Number must be generated by your web site/portal and a unique value must be sent for each transaction'), max_length=200, null=True, blank=True)
    hash = models.CharField(help_text=_('A Hashed value of selected combined parameters. See How to compute the request hash.'), max_length=200, null=True, blank=True)
    pay_item_id = models.CharField(help_text=_('PAYDirect Payment Item ID'), max_length=200, null=True, blank=True)
    site_name = models.CharField(help_text=_('Internet site name of the web site/ portal from which http post is coming from. E.g. www.abc.com. This internet site name will be authenticated.'), max_length=200, null=True, blank=True)
    cust_id = models.CharField(help_text=_('Unique Customer Identification Number'), max_length=200, null=True, blank=True)
    cust_id_desc = models.CharField(help_text=_('Customer Identification Number description. A descriptive name/label for Customer Identification Number above.'), max_length=200, null=True, blank=True)
    cust_name = models.CharField(help_text=_('Customer Name'), max_length=200, null=True, blank=True)
    cust_name_desc = models.CharField(help_text=_('Customer Name Description. A descriptive name/label for Customer Name above.'), max_length=200, null=True, blank=True)
    pay_item_name = models.CharField(help_text=_('PAYDirect Payment Item Name'), max_length=200, null=True, blank=True)
    local_date_time = models.CharField(help_text=_('Local Transaction Date Time: DD-MMM-YY HH:MM:SS'), max_length=200, null=True, blank=True)
    response = models.CharField(help_text=_('Response from Interswitch'), max_length=1000, null=True, blank=True)
    update_response = models.CharField(help_text=_('Result from Interswitch (status update)'), max_length=1000, null=True, blank=True)

    class Meta:
        ordering = ('-created', '-updated')
        verbose_name = "Interswitch Payment"
        verbose_name_plural = "Interswitch Payments"

    def get_fee(self):
        """
        a fee of 1.5% of the value of the transaction subject to a cap
        of N2,000 is charged. (i.e. for transactions below N133,333, a
        fee of 1.5% applies), and N2,000 flat fee (for transactions above N133,333).
        """
        fee = round(self.order_payment.amount * Decimal(0.015), 2)
        if fee > 2000:
            return 2000
        return fee
