# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-13 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('disabled', models.BooleanField(default=False, verbose_name='disabled')),
            ],
            options={
                'ordering': ['translations__name'],
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ThemeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='initiatives.Theme')),
            ],
            options={
                'managed': True,
                'db_table': 'initiatives_theme_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'Theme Translation',
            },
        ),
        migrations.AlterField(
            model_name='initiative',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='initiatives.Theme'),
        ),
        migrations.AlterUniqueTogether(
            name='themetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
