# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-13 12:17
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    group_perms = {
        'Staff': {
            'perms': [
                permission.codename.replace('_project', '_initiative') for permission
                in Group.objects.get(name='Staff').permissions.all() if permission.codename.endswith('_project')
            ]
        },
        'Anonymous': {
            'perms': [
                permission.codename.replace('_project', '_initiative') for permission
                in Group.objects.get(name='Anonymous').permissions.all() if permission.codename.endswith('_project')
            ],
        },
        'Authenticated': {
            'perms': [
                permission.codename.replace('_project', '_initiative') for permission
                in Group.objects.get(name='Authenticated').permissions.all() if permission.codename.endswith('_project')
            ],
        }
    }

    update_group_permissions('initiatives', group_perms, apps)


class Migration(migrations.Migration):
    dependencies = [
        ('initiatives', '0002_auto_20190213_1216'),
    ]

    operations = [
            migrations.RunPython(add_group_permissions)
    ]
