# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_copy_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.File'),
        ),
    ]
