# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_copy_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initiative',
            options={'permissions': (('api_read_initiative', 'Can view initiative through the API'), ('api_add_initiative', 'Can add initiative through the API'), ('api_change_initiative', 'Can change initiative through the API'), ('api_delete_initiative', 'Can delete initiative through the API'), ('api_read_own_initiative', 'Can view own initiative through the API'), ('api_add_own_initiative', 'Can add own initiative through the API'), ('api_change_own_initiative', 'Can change own initiative through the API'), ('api_change_own_running_initiative', 'Can change own initiative through the API'), ('api_delete_own_initiative', 'Can delete own initiative through the API')), 'verbose_name': 'Initiative', 'verbose_name_plural': 'Initiatives'},
        ),
        migrations.AlterField(
            model_name='initiative',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
