# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 08:56
from __future__ import unicode_literals

import os

from django.contrib.gis.geos import Point
from django.core.files import File
from django.db import migrations

from bluebottle.clients import properties


def map_status(status):

    mapping = {
        'plan-new': 'created',
        'plan-submitted': 'submitted',
        'plan-needs-work': 'needs_work',
        'voting': 'approved',
        'voting-done': 'approved',
        'campaign': 'approved',
        'to-be-continued': 'approved',
        'done-complete': 'approved',
        'done-incomplete': 'approved',
        'closed': 'rejected',
        'refunded': 'approved',
    }

    return mapping[status.slug]


def truncate(number, limit):
    return int(number * pow(10, limit)) / 10 ^ pow(10, limit)


def migrate_projects(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Initiative = apps.get_model('initiatives', 'Initiative')
    InitiativePlace = apps.get_model('geo', 'InitiativePlace')
    Country = apps.get_model('geo', 'Country')
    Image = apps.get_model('files', 'Image')

    for project in Project.objects.all():

        if hasattr(project, 'projectlocation') and project.projectlocation.country:
            if project.projectlocation.latitude and project.projectlocation.longitude:
                point = Point(
                    truncate(project.projectlocation.longitude, 12),
                    truncate(project.projectlocation.latitude, 12)
                )
            else:
                point = None

            country = project.country

            if not country and project.projectlocation.country and Country.objects.filter(
                    translations__name=project.projectlocation.country
                ).count():
                country = Country.objects.filter(
                    translations__name__contains=project.projectlocation.country
                ).first()

            if not country:
                country = Country.objects.filter(alpha2_code=properties.DEFAULT_COUNTRY_CODE).first()

            if country:
                place = InitiativePlace.objects.create(
                    street=project.projectlocation.street,
                    postal_code=project.projectlocation.postal_code,
                    country=country,
                    locality=project.projectlocation.city,
                    position=point
                )
            else:
                place = None
        else:
            if project.country:
                place = InitiativePlace.objects.create(
                    country=project.country,
                )
            else:
                place = None

        initiative = Initiative.objects.create(
            title=project.title,
            slug=project.slug,
            pitch=project.pitch or '',
            story=project.story or '',
            theme=project.theme,
            video_url=project.video_url,
            place=place,
            location=project.location,
            owner=project.owner,
            reviewer=project.reviewer,
            review_status=map_status(project.status)

        )
        if project.image:
            try:
                image = Image.objects.create(owner=project.owner)
                image.file.save(project.image.name, project.image.file, save=True)
                initiative.image = image
            except IOError:
                pass
        initiative.created = project.created
        initiative.categories = project.categories.all()
        initiative.save()


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_auto_20190418_0936'),
    ]

    operations = [
        migrations.RunPython(migrate_projects, migrations.RunPython.noop)
    ]
