# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 08:56
from __future__ import unicode_literals

from django.contrib.gis.geos import Point
from django.db import migrations


def map_status(status):

    mapping = {
        'plan-new': 'created',
        'plan-submitted': 'submitted',
        'plan-needs-work': 'needs_work',
        'voting': 'approved',
        'voting-done': 'approved',
        'campaign': 'approved',
        'to-be-continued': 'approved',
        'done-complete': 'approved',
        'done-incomplete': 'approved',
        'closed': 'rejected',
        'refunded': 'approved',
    }

    return mapping[status.slug]


def migrate_projects(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Initiative = apps.get_model('initiatives', 'Initiative')
    InitiativePlace = apps.get_model('geo', 'InitiativePlace')
    Country = apps.get_model('geo', 'Country')

    for project in Project.objects.all():

        if hasattr(project, 'projectlocation') and project.projectlocation.country:
            if project.projectlocation.latitude and project.projectlocation.longitude:
                point = Point(
                    round(project.projectlocation.longitude, 12),
                    round(project.projectlocation.latitude, 12)
                )
            else:
                point = None

            if not project.country and project.projectlocation.country:
                project.country = Country.objects.get()

            place = InitiativePlace.objects.create(
                street=project.projectlocation.street,
                postal_code=project.projectlocation.postal_code,
                country=project.country,
                locality=project.projectlocation.city,
                position=point
            )
        else:
            if project.country:
                place = InitiativePlace.objects.create(
                    country=project.country,
                )
            else:
                place = None

        initiative = Initiative.objects.create(
            title=project.title,
            slug=project.slug,
            pitch=project.pitch,
            story=project.story,
            theme=project.theme,
            video_url=project.video_url,
            place=place,
            location=project.location,
            owner=project.owner,
            reviewer=project.reviewer,
            review_status=map_status(project.status)

        )
        initiative.categories = project.categories.all()
        initiative.save()


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_auto_20190418_0936'),
    ]

    operations = [
        migrations.RunPython(migrate_projects, migrations.RunPython.noop)
    ]
