# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-16 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_initiative_hasorganization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiative',
            old_name='hasOrganization',
            new_name='has_organization',
        ),
    ]
