# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-03 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_auto_20190416_1553'),
        ('initiatives', '0005_auto_20190418_0937'),
    ]

    operations = [
    ]
