# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-21 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0009_auto_20190520_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='slug',
            field=models.SlugField(default=b'new', max_length=100, verbose_name='slug'),
        ),
    ]
