# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-22 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0010_auto_20190521_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiativeplatformsettings',
            name='facebook_at_work_url',
        ),
        migrations.RemoveField(
            model_name='initiativeplatformsettings',
            name='share_options',
        ),
    ]
