# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0009_auto_20190524_1144'),
        ('initiatives', '0011_auto_20190522_0931'),
    ]

    operations = [
    ]
