# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-26 07:15


from django.db import migrations, connection

from bluebottle.clients import properties


def migrate_activity_types(apps, schema_editor):
    InitiativePlatformSettings = apps.get_model('initiatives', 'InitiativePlatformSettings')
    Client = apps.get_model('clients', 'Client')

    initiative_settings, _ = InitiativePlatformSettings.objects.get_or_create()

    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    properties.set_tenant(tenant)

    initiative_settings.activity_types = ['event', 'assignment']

    if 'funding' in properties.PROJECT_CREATE_TYPES:
        initiative_settings.activity_types += ['funding']

    initiative_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0015_auto_20190708_1417'),
    ]

    operations = [
        migrations.RunPython(migrate_activity_types)
    ]
