# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-29 10:31
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0019_merge_20191108_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='activity_search_filters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'location', 'Location'), (b'date', 'Date'), (b'skill', 'Skill'), (b'type', 'Type'), (b'theme', 'Theme'), (b'category', 'Category'), (b'status', 'Status')], default=[], max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='initiative_search_filters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'location', 'Location'), (b'theme', 'Theme'), (b'category', 'Category')], default=[], max_length=1000),
            preserve_default=False,
        ),
    ]
