# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-29 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0021_auto_20191129_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiativeplatformsettings',
            name='search_filters',
        ),
    ]
