# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-28 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0023_auto_20200624_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiativeplatformsettings',
            name='enable_impact',
        ),
    ]
