# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-16 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0024_merge_20200806_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='slug',
            field=models.SlugField(default='new', max_length=100, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text="Do you have a video pitch or a short movie that explains your initiative? Cool! We can't wait to see it! You can paste the link to YouTube or Vimeo video here", max_length=100, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='activity_search_filters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('location', 'Office location'), ('country', 'Country'), ('date', 'Date'), ('skill', 'Skill'), ('type', 'Type'), ('theme', 'Theme'), ('category', 'Category'), ('status', 'Status'), ('segments', 'Segments')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='activity_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('funding', 'Funding'), ('event', 'Events'), ('assignment', 'Assignment'), ('withadeadlineactivity', 'Activity with a deadline'), ('onadateactivity', 'Activity on a specific date'), ('ongoingactivity', 'Ongoing activity')], max_length=100),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='contact_method',
            field=models.CharField(choices=[('mail', 'E-mail'), ('phone', 'Phone')], default='mail', max_length=100),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='initiative_search_filters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('location', 'Office location'), ('country', 'Country'), ('theme', 'Theme'), ('category', 'Category')], max_length=1000),
        ),
    ]
