# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-29 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0026_auto_20201112_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='enable_office_regions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='activity_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('funding', 'Funding'), ('periodactivity', 'Activity during a period'), ('dateactivity', 'Activity on a specific date')], max_length=100),
        ),
    ]
