# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-16 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0028_auto_20210209_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='enable_participant_exports',
            field=models.BooleanField(default=False),
        ),
    ]
