# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-24 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0033_auto_20210303_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='enable_matching_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='activity_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('funding', 'Funding'), ('periodactivity', 'Activity during a period'), ('dateactivity', 'Activity on a specific date'), ('deed', 'Deed')], max_length=100),
        ),
    ]
