# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-05 13:21
from __future__ import unicode_literals

from django.db import migrations

def move_activity_manager(apps, schema_editor):
    Initiative = apps.get_model('initiatives', 'Initiative')

    for initiative in Initiative.objects.all():
        initiative.activity_managers.add(initiative.activity_manager)


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0035_auto_20210505_1425'),
    ]

    operations = [
        migrations.RunPython(move_activity_manager)
    ]
