# Generated by Django 2.2.20 on 2021-07-16 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0037_merge_20210525_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='is_global',
            field=models.BooleanField(
                default=False,
                help_text='Global initiatives do not have a location. '
                          'Instead the location is stored on the respective activities.',
                verbose_name='is global'),
        ),
    ]
