# Generated by Django 2.2.24 on 2022-09-05 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0039_auto_20220316_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='show_all_activities',
            field=models.BooleanField(default=False, help_text='In initial search show all activities, not only upcoming.'),
        ),
    ]
