# Generated by Django 2.2.24 on 2022-09-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0040_auto_20220905_1417'),
        ('initiatives', '0040_auto_20220901_0932'),
    ]

    operations = [
    ]
