# Generated by Django 2.2.24 on 2022-09-28 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0041_merge_20220906_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='enable_office_restrictions',
            field=models.BooleanField(default=False, help_text='Allow activity managers to specify office restrictions on activities.'),
        ),
    ]
