# Generated by Django 2.2.24 on 2022-12-05 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0043_auto_20221109_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='has_deleted_data',
            field=models.BooleanField(default=False),
        ),
    ]
