# Generated by Django 2.2.24 on 2023-03-29 15:00

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0044_auto_20221205_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='activity_highlighted_filters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('location', 'Office location'), ('country', 'Country'), ('date', 'Date'), ('skill', 'Skill'), ('type', 'Type'), ('team_activity', 'Team activities'), ('theme', 'Theme'), ('category', 'Category'), ('segments', 'Segments'), ('status', 'Status')], default=[], max_length=1000),
        ),
    ]
