# Generated by Django 2.2.24 on 2023-03-31 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0044_auto_20221205_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeSearchFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('location', 'Office location'), ('country', 'Country'), ('date', 'Date'), ('skill', 'Skill'), ('type', 'Type'), ('team_activity', 'Team activities'), ('theme', 'Theme'), ('category', 'Category'), ('segments', 'Segments'), ('status', 'Status')], max_length=100)),
                ('highlight', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.InitiativePlatformSettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySearchFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('location', 'Office location'), ('country', 'Country'), ('date', 'Date'), ('skill', 'Skill'), ('type', 'Type'), ('team_activity', 'Team activities'), ('theme', 'Theme'), ('category', 'Category'), ('segments', 'Segments'), ('status', 'Status')], max_length=100)),
                ('highlight', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.InitiativePlatformSettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
