# Generated by Django 2.2.24 on 2023-03-31 13:24

from django.db import migrations


def migrate_search_filters(apps, schema_editor):
    InitiativePlatformSettings = apps.get_model('initiatives', 'InitiativePlatformSettings')
    ActivitySearchFilter = apps.get_model('initiatives', 'ActivitySearchFilter')
    InitiativeSearchFilter = apps.get_model('initiatives', 'InitiativeSearchFilter')
    SegmentType = apps.get_model('segments', 'SegmentType')
    settings = InitiativePlatformSettings.objects.first()

    for filter in settings.activity_search_filters:
        if filter == 'type':
            filter = 'activity-type'
        if filter == 'segments':
            for segment in SegmentType.objects.filter(enable_search=True).all():
                ActivitySearchFilter.objects.create(settings=settings, type=f'segment.{segment.slug}')
        else:
            ActivitySearchFilter.objects.create(settings=settings, type=filter)

    for filter in settings.initiative_search_filters:
        if filter == 'type':
            filter = 'activity-type'
        if filter == 'segments':
            for segment in SegmentType.objects.filter(enable_search=True).all():
                InitiativeSearchFilter.objects.create(settings=settings, type=f'segment.{segment.slug}')
        else:
            InitiativeSearchFilter.objects.create(settings=settings, type=filter)


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0045_auto_20230331_1410'),
    ]

    operations = [
        migrations.RunPython(
            migrate_search_filters,
            migrations.RunPython.noop
        )
    ]
