# Generated by Django 2.2.24 on 2023-06-29 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0047_auto_20230526_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='enable_matching_emails',
            field=models.BooleanField(default=False, help_text='When enabled: show matching wizard, show my matching preferences, show matching labels, send monthly matching emails', verbose_name='Matching'),
        ),
    ]
