# Generated by Django 3.2.20 on 2023-11-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiatives', '0049_auto_20230710_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiativeplatformsettings',
            name='show_all_activities',
        ),
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='include_full_activities',
            field=models.BooleanField(default=True, help_text='Include full activities in upcoming activities list'),
        ),
    ]
