# Generated by Django 3.2.20 on 2024-10-18 06:53

from django.db import migrations



def set_no_org(apps, schema_editor):
    Initiative = apps.get_model('initiatives', 'Initiative')
    Initiative.objects.filter(has_organization=None).update(has_organization=False)


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0053_auto_20241018_0851'),
    ]

    operations = [
        migrations.RunPython(
            set_no_org,
            migrations.RunPython.noop,
        )
    ]
