# Generated by Django 3.2.20 on 2025-02-25 13:33

import json
from django.db import migrations

def convert_to_quill(apps, schema_editor):
    Initiative = apps.get_model('initiatives', 'Initiative')

    for initiative in Initiative.objects.all(): 
        initiative.story = json.dumps({"html": initiative.story, "delta": ""})
        initiative.save()


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0054_auto_20241018_0853'),
    ]

    operations = [
        migrations.RunPython(convert_to_quill, migrations.RunPython.noop)
    ]
