# Generated by Django 4.2.20 on 2025-03-18 07:45

from django.db import migrations


def remove_managing_status_filters(apps, schema_editor):
    ActivitySearchFilter = apps.get_model("initiatives", "ActivitySearchFilter")
    ActivitySearchFilter.objects.filter(type__in=["managing", "status"]).delete()


def reverse_migration(apps, schema_editor):
    # No reverse migration provided since we're deleting data
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0055_auto_20250225_1433"),
    ]

    operations = [
        migrations.RunPython(remove_managing_status_filters, reverse_migration),
    ]
