# Generated by Django 4.2.17 on 2025-03-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0055_auto_20250122_1142'),
        ('initiatives', '0055_auto_20250225_1433'),
    ]

    operations = [
    ]
