# Generated by Django 4.2.17 on 2025-03-10 14:02

import bluebottle.files.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('initiatives', '0057_initiativeplatformsettings_enable_reviewing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='published',
            field=models.DateTimeField(blank=True, help_text='Date that the initiative went online.', null=True, verbose_name='Published date'),
        ),
    ]
