# Generated by Django 4.2.20 on 2025-03-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0056_remove_managing_status_filters'),
        ('initiatives', '0058_initiative_published'),
    ]

    operations = [
    ]
