# Generated by Django 4.2.20 on 2025-08-06 09:51

import bluebottle.files.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0060_activityquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='terms_of_service',
            field=models.TextField(blank=True, help_text='Terms of service that is shown to users when they create an activity.', verbose_name='Terms of Service'),
        ),
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='terms_of_service_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives_terms_of_service_page', to='pages.page', verbose_name='Terms of Service page'),
        ),
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='terms_of_service_required',
            field=models.BooleanField(default=False, help_text='Require users to agree to the terms of service when creating an activity.'),
        ),
    ]
