# Generated by Django 4.2.20 on 2025-08-13 13:11

import bluebottle.files.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiatives', '0062_alter_activityquestiontranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiativeplatformsettings',
            name='terms_of_service_page',
        ),
    ]
