# Generated by Django 4.2.20 on 2025-08-20 08:32

import bluebottle.files.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('initiatives', '0063_alter_remove_tos_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='bcc_terms_of_service',
            field=models.EmailField(blank=True,
                                    help_text='Email address to send a BCC of the terms of service email to.',
                                    max_length=254, verbose_name='BCC email with terms of service'),
        ),
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='mail_terms_of_service',
            field=models.BooleanField(default=False,
                                      help_text='Send an email with the terms of service when their application is accepted.',
                                      verbose_name='Send email with terms of service'),
        ),
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='terms_of_service_mail_text',
            field=models.TextField(
                blank=True,
                help_text='Leave emtpy to use the Terms of Service as above. You can use placeholders like in custom email templates.',
                verbose_name='Terms of Service - Email'),
        ),

    ]
