# Generated by Django 4.2.20 on 2025-08-28 14:20

import bluebottle.files.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0064_mail_tos'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='hour_registration',
            field=models.CharField(choices=[('disabled', 'Disable'), ('per_activity', 'Unique per activity'), ('generic', 'Same for all activities')], default='disabled', help_text='Hour registration only applies to time-based activity types.', max_length=100, verbose_name='Hour registration'),
        ),
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='hour_registration_data',
            field=models.CharField(blank=True, help_text='What data to collect when registering hours.', max_length=400, null=True, verbose_name='Hour registration code/url'),
        ),
    ]
