# Generated by Django 4.2.20 on 2026-02-09 11:52

import bluebottle.files.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0065_hour_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='vet_organizations',
            field=models.BooleanField(default=False, help_text='Require reviewers to vet the organization before reviewing grant applications'),
        ),
    ]
