# Generated by Django 4.2.20 on 2025-12-11 15:29

import bluebottle.files.fields
from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion
import django_quill.fields
import multiselectfield.db.fields
import parler.fields


def check_themetranslation_table_exists(schema_editor):
    """Check if initiatives_themetranslation table exists"""
    table_name = 'initiatives_themetranslation'
    db_connection = schema_editor.connection if hasattr(schema_editor, 'connection') else connection
    
    with db_connection.cursor() as c:
        if 'postgresql' in db_connection.vendor:
            # Check current schema (could be tenant schema)
            c.execute("SELECT current_schema()")
            schema = c.fetchone()[0]
            c.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = %s 
                    AND table_name = %s
                );
            """, [schema, table_name])
            return c.fetchone()[0]
        else:
            # For other databases, try a simpler check
            try:
                c.execute(f"SELECT 1 FROM {table_name} LIMIT 1")
                return True
            except Exception:
                return False


def apply_themetranslation_changes(apps, schema_editor):
    """Apply themetranslation changes only if table exists"""
    if not check_themetranslation_table_exists(schema_editor):
        # Table doesn't exist, skip the database operations
        return
    
    # Apply the database operations conditionally
    # AlterModelTable: ensure table name is correct
    db_connection = schema_editor.connection if hasattr(schema_editor, 'connection') else connection
    
    # Check current table name and rename if needed
    with db_connection.cursor() as c:
        if 'postgresql' in db_connection.vendor:
            c.execute("SELECT current_schema()")
            schema = c.fetchone()[0]
            # Check if table exists with different name
            c.execute("""
                SELECT table_name FROM information_schema.tables 
                WHERE table_schema = %s 
                AND table_name LIKE '%%themetranslation%%'
            """, [schema])
            existing_tables = [row[0] for row in c.fetchall()]
            target_table = 'initiatives_themetranslation'
            
            if existing_tables and target_table not in existing_tables:
                # Table exists with different name, rename it
                old_table = existing_tables[0]
                if old_table != target_table:
                    c.execute(f'ALTER TABLE "{schema}"."{old_table}" RENAME TO "{target_table}"')
            
            # Alter unique constraint if needed
            # This is handled by the state operation, but we ensure the constraint exists
            try:
                c.execute("""
                    SELECT constraint_name FROM information_schema.table_constraints 
                    WHERE table_schema = %s 
                    AND table_name = %s 
                    AND constraint_type = 'UNIQUE'
                    AND constraint_name LIKE '%%language_code%%'
                """, [schema, target_table])
                if not c.fetchone():
                    # Add unique constraint if it doesn't exist
                    c.execute(f"""
                        ALTER TABLE "{schema}"."{target_table}" 
                        ADD CONSTRAINT {target_table}_language_code_master_unique 
                        UNIQUE (language_code, master_id)
                    """)
            except Exception:
                # Constraint might already exist or table structure is different
                pass


def reverse_themetranslation_changes(apps, schema_editor):
    """Reverse operation - no-op since we're conditionally applying"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiatives', '0065_hour_registration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityquestiontranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='activityquestiontranslation',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='initiativeplatformsettings',
            options={'verbose_name': 'Activity & initiative settings', 'verbose_name_plural': 'Activity & initiative settings'},
        ),
        migrations.AlterField(
            model_name='activitysearchfilter',
            name='type',
            field=models.CharField(choices=[('country', 'Country'), ('date', 'Date'), ('distance', 'Distance'), ('is_online', 'Online / In-person'), ('skill', 'Skill'), ('team_activity', 'Individual / Team'), ('theme', 'Theme'), ('category', 'Category'), ('office', 'Office'), ('office_subregion', 'Office group'), ('office_region', 'Office region')], max_length=100),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='activity_manager',
            field=models.ForeignKey(blank=True, help_text='The co-initiator can create and edit activities for this initiative, but cannot edit the initiative itself.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_manager_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='co-initiator'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='activity_managers',
            field=models.ManyToManyField(blank=True, help_text='Co-initiators can create and edit activities for this initiative, but cannot edit the initiative itself.', related_name='activity_managers_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='co-initiators'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='image',
            field=bluebottle.files.fields.ImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoter_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='promoter'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='reviewer'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='story',
            field=django_quill.fields.QuillField(blank=True, verbose_name='story'),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='activity_search_filters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('country', 'Country'), ('date', 'Date'), ('distance', 'Distance'), ('is_online', 'Online / In-person'), ('skill', 'Skill'), ('team_activity', 'Individual / Team'), ('theme', 'Theme'), ('category', 'Category'), ('office', 'Office'), ('office_subregion', 'Office group'), ('office_region', 'Office region')], default=[], max_length=1000, verbose_name='Activity search: more filters'),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='activity_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('funding', 'Funding'), ('grantapplication', 'Grant Application'), ('periodactivity', 'Activity during a period'), ('dateactivity', 'Activity on a specific date'), ('deadlineactivity', 'Activity within a deadline'), ('scheduleactivity', 'Scheduled activity'), ('periodicactivity', 'Periodic Activity'), ('registereddateactivity', 'Past date activity'), ('deed', 'Deed'), ('collect', 'Collect activity')], max_length=300),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='bcc_terms_of_service',
            field=models.EmailField(blank=True, help_text='Enter the email address that should receive a Bcc (blind carbon copy) of the terms of service.', max_length=254, verbose_name='Bcc email with terms of service'),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='enable_participant_exports',
            field=models.BooleanField(default=False, help_text='Add a link to activities so managers can download a contributor list.'),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='enable_reviewing',
            field=models.BooleanField(default=True, help_text='Review initiatives and activities. Activities created within an initiative will not need to be reviewed. Crowdfunding activities will always need to be reviewed', verbose_name='Enable reviewing'),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='hour_registration_data',
            field=models.CharField(blank=True, help_text='Leave empty if ‘unique per activity’ was selected. If you selected ‘same for all activities’, this code or link will be used for every activity and can’t be changed.', max_length=400, null=True, verbose_name='Code / URL'),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='initiative_search_filters',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('office', 'Office'), ('country', 'Country'), ('theme', 'Theme'), ('category', 'Category'), ('open', 'Open initiatives'), ('office', 'Office'), ('office_subregion', 'Office group'), ('office_region', 'Office region')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='mail_terms_of_service',
            field=models.BooleanField(default=False, help_text='Send an email with the terms of service when an application is accepted.', verbose_name='Email terms of service'),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='terms_of_service',
            field=models.TextField(blank=True, help_text='Terms of service that is shown to users when they are on the create form.', verbose_name='Terms of Service'),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='terms_of_service_mail_text',
            field=models.TextField(blank=True, help_text='Leave emtpy if the Terms of Service sent by email is the same as the one above.', verbose_name='Custom terms of Service for email'),
        ),
        migrations.AlterField(
            model_name='initiativesearchfilter',
            name='type',
            field=models.CharField(choices=[('office', 'Office'), ('country', 'Country'), ('theme', 'Theme'), ('category', 'Category'), ('open', 'Open initiatives'), ('office', 'Office'), ('office_subregion', 'Office group'), ('office_region', 'Office region')], max_length=100),
        ),
        # Conditionally apply themetranslation changes only if table exists
        migrations.RunPython(
            apply_themetranslation_changes,
            reverse_themetranslation_changes,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='themetranslation',
                    name='master',
                    field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='initiatives.theme'),
                ),
                migrations.AlterUniqueTogether(
                    name='themetranslation',
                    unique_together={('language_code', 'master')},
                ),
                migrations.AlterModelTable(
                    name='themetranslation',
                    table='initiatives_theme_translation',
                ),
            ],
            database_operations=[],
        ),
        migrations.DeleteModel(
            name='ActivityQuestion',
        ),
        migrations.DeleteModel(
            name='ActivityQuestionTranslation',
        ),
    ]
