# Generated by Django 4.2.20 on 2026-04-23 09:03

import bluebottle.files.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_alter_document_owner_alter_image_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0039_merge_20260116_1155'),
        ('initiatives', '0066_alter_activityquestiontranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initiativeplatformsettings',
            options={'verbose_name': 'Activity & initiative settings', 'verbose_name_plural': 'Activity & initiative settings'},
        ),
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='restrict_updates',
            field=models.BooleanField(default=False, help_text='Restrict posting of updates on the activity wall to only activity managers and staff users', verbose_name='Restrict posting updates'),
        ),
    ]
