# Generated by Django 4.2.30 on 2026-05-21 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiatives', '0067_alter_activityquestiontranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='contact_activity_manager',
            field=models.BooleanField(default=True, help_text='Allow users to send messages to activity managers.',
                                      verbose_name='Contact activity manager'),
        ),
    ]
