# Generated by Django 4.2.30 on 2026-05-21 11:11

import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0016_alter_document_owner_alter_image_owner_and_more'),
        ('geo', '0049_alter_geofeature_options_and_more'),
        ('initiatives', '0068_alter_activityquestiontranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='location_features',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[('address', 'Address'), ('neighborhood', 'Neighbourhood'), ('place', 'City'),
                         ('region', 'Region/State'), ('country', 'Country')], default=['place', 'country'],
                help_text='Select the information of the location that is displayed on the activity cards.',
                max_length=1000, verbose_name='Location display format'),
        ),
    ]
