# Generated by Django 5.2.13 on 2026-07-06 12:39

import bluebottle.files.fields
import bluebottle.initiatives.models
import django.contrib.postgres.fields
import django.db.models.deletion
import django_quill.fields
import multiselectfield.db.fields
import parler.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_alter_document_owner_alter_image_owner_and_more'),
        ('geo', '0039_merge_20260116_1155'),
        ('initiatives', '0068_alter_activityquestiontranslation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='available_office_restrictions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('office', 'Open to people from the same work location'), ('office_subregion', 'Open to people from work locations within the same group'), ('office_region', 'Open to people from work locations within the same region'), ('all', 'Open to people from any work location')], max_length=200), default=bluebottle.initiatives.models.get_office_restriction_values, size=None),
        ),
    ]
