# Generated by Django 5.2.13 on 2026-07-07 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_alter_document_owner_alter_image_owner_and_more'),
        ('geo', '0039_merge_20260116_1155'),
        ('initiatives', '0069_remove_activityquestiontranslation_master_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeplatformsettings',
            name='allow_disable_office_filter',
            field=models.BooleanField(default=True, help_text='Members can choose to view activities outside their work location', verbose_name='Allow members to see all activities'),
        ),
    ]
