# Generated by Django 5.2.15 on 2026-07-23 13:49

from django.db import migrations, models
from django.db.models.functions import Left, Length


def truncate_pitches(apps, schema_editor):
    Initiative = apps.get_model('initiatives', 'Initiative')
    Initiative.objects.annotate(
        pitch_length=Length('pitch')
    ).filter(pitch_length__gt=350).update(pitch=Left('pitch', 350))


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0070_remove_activityquestiontranslation_master_and_more'),
    ]

    operations = [
        migrations.RunPython(truncate_pitches, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='initiative',
            name='pitch',
            field=models.TextField(
                blank=True,
                help_text='Pitch your smart idea in one sentence. Max: 350 characters.',
                max_length=350,
                verbose_name='pitch',
            ),
        ),
    ]
