# Generated by Django 5.2.15 on 2026-07-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0069_location_card_display'),
        ('initiatives', '0070_remove_activityquestiontranslation_master_and_more'),
    ]

    operations = [
    ]
