# Generated by Django 5.2.15 on 2026-07-28 07:33

from django.db import migrations, models
from django.db.models import Q


def migrate_generic_hour_registration(apps, schema_editor):
    InitiativePlatformSettings = apps.get_model(
        'initiatives', 'InitiativePlatformSettings'
    )
    TimeBasedActivity = apps.get_model('time_based', 'TimeBasedActivity')

    settings = InitiativePlatformSettings.objects.filter(
        hour_registration='generic'
    ).first()
    if not settings:
        return

    if settings.hour_registration_data:
        TimeBasedActivity.objects.filter(
            Q(hour_registration_data__isnull=True) | Q(hour_registration_data='')
        ).update(hour_registration_data=settings.hour_registration_data)

    InitiativePlatformSettings.objects.filter(hour_registration='generic').update(
        hour_registration='per_activity'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0071_alter_initiative_pitch_max_length'),
        ('time_based', '0149_alter_dateregistration_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_generic_hour_registration,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='hour_registration',
            field=models.CharField(
                choices=[('disabled', 'Disable'), ('per_activity', 'Enable')],
                default='disabled',
                help_text='Hour registration only applies to time-based activity types.',
                max_length=100,
                verbose_name='Hour registration',
            ),
        ),
        migrations.AlterField(
            model_name='initiativeplatformsettings',
            name='hour_registration_data',
            field=models.CharField(
                blank=True,
                help_text=(
                    'Enter a default code or URL for hour registration. '
                    'This will be used as the default for all activities, '
                    'but can be changed per activity.'
                ),
                max_length=400,
                null=True,
                verbose_name='Code / URL',
            ),
        ),
    ]
