# Generated by Django 5.2.15 on 2026-08-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0072_alter_hour_registration'),
        ('initiatives', '0073_activity_card_location_neighbourhood_city'),
    ]

    operations = [
    ]
