# Generated by Django 4.2.20 on 2025-10-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organization_options'),
        ('activity_links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedactivity',
            name='host_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_activities', to='organizations.organization'),
        ),
    ]
