# Generated by Django 4.2.20 on 2025-10-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0045_remove_event_linked_activity_and_more'),
        ('activity_links', '0002_linkedactivity_host_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkeddateactivity',
            name='end',
        ),
        migrations.RemoveField(
            model_name='linkeddateactivity',
            name='start',
        ),
        migrations.AddField(
            model_name='linkedactivity',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_activities', to='activity_pub.event'),
        ),
        migrations.AddField(
            model_name='linkeddeed',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkeddeed',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedfunding',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedfunding',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LinkedDateSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='activity_links.linkedactivity')),
            ],
        ),
    ]
