# Generated by Django 4.2.20 on 2025-10-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0003_remove_linkeddateactivity_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedDeadlineActivity',
            fields=[
                ('linkedactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_links.linkedactivity')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_links.linkedactivity',),
        ),
    ]
