# Generated by Django 4.2.20 on 2025-12-22 07:50

import bluebottle.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0004_linkeddeadlineactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedactivity',
            name='image',
            field=bluebottle.utils.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
