# Generated by Django 4.2.20 on 2026-01-04 10:08

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0005_linkedactivity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedfunding',
            name='amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default=Decimal('0.00'), default_currency='EUR', max_digits=12),
        ),
        migrations.AddField(
            model_name='linkedfunding',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='linkedfunding',
            name='donated',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default=Decimal('0.00'), default_currency='EUR', max_digits=12),
        ),
    ]
