# Generated by Django 4.2.20 on 2026-01-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0006_linkedfunding_amount_linkedfunding_amount_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedfunding',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='linkedfunding',
            name='amount_currency',
        ),
    ]
