# Generated by Django 4.2.20 on 2026-01-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0038_alter_geolocation_country'),
        ('activity_links', '0010_linkedcollectcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkeddeadlineactivity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.geolocation'),
        ),
    ]
