# Generated by Django 4.2.20 on 2026-01-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0038_alter_geolocation_country'),
        ('activity_links', '0011_linkeddeadlineactivity_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedPeriodicActivity',
            fields=[
                ('linkedactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_links.linkedactivity')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('repetition_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.geolocation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_links.linkedactivity',),
        ),
    ]
