# Generated by Django 4.2.20 on 2026-01-23 10:44

import bluebottle.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0013_linkedscheduleactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedactivity',
            name='image',
            field=bluebottle.utils.fields.ImageField(blank=True, null=True, upload_to='activity_links'),
        ),
    ]
