# Generated by Django 4.2.20 on 2026-01-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0013_linkedscheduleactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedperiodicactivity',
            old_name='repetition_mode',
            new_name='period',
        ),
    ]
