# Generated by Django 4.2.20 on 2026-01-23 13:29

import bluebottle.files.fields
import bluebottle.utils.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_alter_document_owner_alter_image_owner_and_more'),
        ('activity_links', '0014_alter_linkedactivity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedactivity',
            name='file_image',
            field=bluebottle.files.fields.ImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
        migrations.AlterField(
            model_name='linkedactivity',
            name='image',
            field=bluebottle.utils.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
