# Generated by Django 4.2.20 on 2026-01-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0014_alter_linkedactivity_image'),
        ('activity_links', '0014_rename_repetition_mode_linkedperiodicactivity_period'),
    ]

    operations = [
    ]
