# Generated by Django 4.2.20 on 2026-01-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0015_linkedactivity_file_image_alter_linkedactivity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedactivity',
            name='image',
        ),
    ]
