# Generated by Django 4.2.20 on 2026-01-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0016_remove_linkedactivity_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedactivity',
            old_name='file_image',
            new_name='image',
        ),
    ]
