# Generated by Django 4.2.20 on 2026-01-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0015_merge_20260123_1234'),
        ('activity_links', '0017_rename_file_image_linkedactivity_image'),
    ]

    operations = [
    ]
