# Generated by Django 4.2.20 on 2026-02-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0019_merge_20260202_1139'),
        ('activity_links', '0019_merge_20260202_1254'),
    ]

    operations = [
    ]
