# Generated by Django 4.2.20 on 2026-02-03 10:25

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0038_alter_geolocation_country'),
        ('activity_links', '0020_merge_20260202_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedGrantApplication',
            fields=[
                (
                    'linkedactivity_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='activity_links.linkedactivity',
                    ),
                ),
                ('target_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('target', bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default=None, default_currency='EUR', max_digits=12)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.geolocation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_links.linkedactivity',),
        ),
    ]
