# Generated by Django 4.2.20 on 2026-02-12 14:26

import bluebottle.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0021_linkedgrantapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedactivity',
            options={'verbose_name': 'linked activity', 'verbose_name_plural': 'Linked activities'},
        ),
        migrations.AddField(
            model_name='linkedactivity',
            name='show',
            field=models.BooleanField(default=True, help_text='If you uncheck this the activity will no longer show up in search results.', verbose_name='Show in search'),
        ),
        migrations.AlterField(
            model_name='linkedgrantapplication',
            name='target',
            field=bluebottle.utils.fields.MoneyField(blank=True, currency_choices=[('EUR', 'Euro')], decimal_places=2, default=None, default_currency='EUR', max_digits=12, null=True),
        ),
    ]
