# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-23 08:38


from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.FloatField(null=True, verbose_name='target')),
                ('realized', models.FloatField(null=True, verbose_name='realized')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'ordering': ['translations__name'],
                'verbose_name': 'impact type',
                'verbose_name_plural': 'impact types',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ImpactTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('unit', models.TextField(blank=True, verbose_name='unit')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='impact.ImpactType')),
            ],
            options={
                'managed': True,
                'db_table': 'impact_impacttype_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'impact type Translation',
            },
        ),
        migrations.AddField(
            model_name='impactgoal',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impact.ImpactType', verbose_name='type'),
        ),
        migrations.AlterUniqueTogether(
            name='impacttypetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
