# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-24 08:25


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_activity_video_url'),
        ('impact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactgoal',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='activities.Activity', verbose_name='activity'),
            preserve_default=False,
        ),
    ]
