# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-18 09:17


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0012_auto_20200817_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impacttypetranslation',
            name='name',
        ),
    ]
