# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-19 07:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0013_auto_20200818_1105'),
        ('impact', '0013_remove_impacttypetranslation_name'),
    ]

    operations = [
    ]
