# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-20 15:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0014_merge_20200819_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='impacttypetranslation',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='name'),
        ),
    ]
