# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-18 07:56


from django.db import migrations, models
from bluebottle.clients import properties
from parler.models import TranslatableModelMixin


def create_default_impact_types(apps, schema_editor):
    ImpactType = apps.get_model('impact', 'ImpactType')
    ImpactType.__bases__ = (models.Model, TranslatableModelMixin)

    ImpactTypeTranslation = apps.get_model('impact', 'ImpactTypeTranslation')
    Language = apps.get_model('utils', 'language')

    languages = [lang.code for lang in Language.objects.all()]

    definitions = [
        {
            'slug': 'co2',
            'icon': 'co2',
            'en': {
                'name': 'Reduce CO₂ emissions',
                'unit': 'kg',
                'text': 'reduce CO₂ emissions',
                'text_with_target': 'CO₂ emissions reduced',
                'text_passed': 'reduce CO₂ emissions by {} kg',
            },
            'nl': {
                'name': 'CO₂ uitstoot verminderen',
                'unit': 'kg',
                'text': 'CO₂ uitstoot te verminderen',
                'text_with_target': 'CO₂ uitstoot met {} kg te verminderen',
                'text_passed': 'CO₂ uitstoot verminderd'
            }
        },
        {
            'slug': 'people',
            'icon': 'people',
            'en': {
                'name': 'Reach people',
                'unit': '',
                'text': 'reach people',
                'text_with_target': 'reach {} people',
                'text_passed': 'people reached',
            },
            'nl': {
                'name': 'Mensen bereiken',
                'unit': '',
                'text': 'mensen te bereiken',
                'text_with_target': '{} mensen te bereiken',
                'text_passed': 'mensen bereikt'
            }
        },
        {
            'slug': 'food',
            'icon': '',
            'en': {
                'name': 'Reduce food waste',
                'unit': 'kg',
                'text': 'reduce food waste',
                'text_with_target': 'reduce food waste by {} kg',
                'text_passed': 'food waste reduced',
            },
            'nl': {
                'name': 'Voedselverspilling verminderen',
                'unit': 'kg',
                'text': 'voedselverspilling te verminderen',
                'text_with_target': 'voedselverspilling met {} kg te verminderen',
                'text_passed': 'voedselverspilling verminderd'
            }
        },
        {
            'slug': 'water',
            'icon': 'water',
            'en': {
                'name': 'Save water',
                'unit': 'l',
                'text': 'save water',
                'text_with_target': 'save {} l water',
                'text_passed': 'water saved',
            },
            'nl': {
                'name': 'Water besparen',
                'unit': 'l',
                'text': 'water te besparen',
                'text_with_target': '{} l water te besparen',
                'text_passed': 'water bespaard'
            }
        },
        {
            'slug': 'plastic',
            'icon': 'plastic',
            'en': {
                'name': 'Save plastic',
                'unit': 'kg',
                'text': 'save plastic',
                'text_with_target': 'save {} kg plastic',
                'text_passed': 'plastic saved',
            },
            'nl': {
                'name': 'Plastic besparen',
                'unit': 'kg',
                'text': 'plastic te besparen',
                'text_with_target': '{} kg plastic te besparen',
                'text_passed': 'plastic bespaard'
            }
        },
        {
            'slug': 'trees',
            'icon': 'trees',
            'en': {
                'name': 'Plant trees',
                'unit': '',
                'text': 'plant trees',
                'text_with_target': 'plant {} trees',
                'text_passed': 'trees planted',
            },
            'nl': {
                'name': 'Bomen planten',
                'unit': '',
                'text': 'bomen te planten',
                'text_with_target': '{} bomen te planten',
                'text_passed': 'bomen geplant'
            }
        },
        {
            'slug': 'jobs',
            'icon': 'jobs',
            'en': {
                'name': 'Create jobs',
                'unit': '',
                'text': 'create jobs',
                'text_with_target': 'create {} jobs',
                'text_passed': 'jobs created',
            },
            'nl': {
                'name': 'Banen creëren',
                'unit': '',
                'text': 'banen te creëren',
                'text_with_target': '{} banen te creëren',
                'text_passed': 'banen gecreëerd'
            }
        },
    ]

    for definition in definitions:
        impact_type, created = ImpactType.objects.update_or_create(
            slug=definition['slug'],
            defaults={
                'icon': definition['icon']
            }
        )
        for language in languages:
            if language in definition:
                ImpactTypeTranslation.objects.update_or_create(
                    language_code=language,
                    master=impact_type,
                    defaults=definition[language]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0015_impacttypetranslation_name'),
    ]

    operations = [
        migrations.RunPython(create_default_impact_types, migrations.RunPython.noop)
    ]
