# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-18 07:56
from __future__ import unicode_literals

from django.db import migrations, models
from bluebottle.clients import properties
from parler.models import TranslatableModelMixin


def create_default_impact_types(apps, schema_editor):
    ImpactType = apps.get_model('impact', 'ImpactType')
    ImpactType.__bases__ = (models.Model, TranslatableModelMixin)

    ImpactTypeTranslation = apps.get_model('impact', 'ImpactTypeTranslation')
    Language = apps.get_model('utils', 'language')

    languages = [lang.code for lang in Language.objects.all()]

    definitions = [
        {
            'slug': 'co2',
            'icon': 'co2',
            'en': {
                'name': u'Reduce CO₂ emissions',
                'unit': u'kg',
                'text': u'reduce CO₂ emissions',
                'text_passed': 'CO₂ emissions reduced',
                'text_with_target': u'reduce CO₂ emissions by {} kg',
            },
            'nl': {
                'name': u'CO₂ uitstoot verminderen',
                'unit': u'kg',
                'text': u'CO₂ uitstoot te verminderen',
                'text_passed': u'CO₂ uitstoot met {} kg te verminderen',
                'text_with_target': u'CO₂ uitstoot verminderd'
            }
        },
        {
            'slug': 'people',
            'icon': 'people',
            'en': {
                'name': u'Reach people',
                'unit': u'',
                'text': u'reach people',
                'text_passed': 'reach {} people',
                'text_with_target': u'people reached',
            },
            'nl': {
                'name': u'Mensen bereiken',
                'unit': u'',
                'text': u'mensen te bereiken',
                'text_passed': '{} mensen te bereiken',
                'text_with_target': u'mensen bereikt'
            }
        },
        {
            'slug': 'food',
            'icon': '',
            'en': {
                'name': u'Reduce food waste',
                'unit': u'kg',
                'text': u'reduce food waste',
                'text_passed': 'reduce food waste by {} kg',
                'text_with_target': u'food waste reduced',
            },
            'nl': {
                'name': u'Voedselverspilling verminderen',
                'unit': u'kg',
                'text': u'voedselverspilling te verminderen',
                'text_passed': 'voedselverspilling met {} kg te verminderen',
                'text_with_target': u'voedselverspilling verminderd'
            }
        },
        {
            'slug': 'water',
            'icon': 'water',
            'en': {
                'name': u'Save water',
                'unit': u'l',
                'text': u'save water',
                'text_passed': 'save {} l water',
                'text_with_target': u'water saved',
            },
            'nl': {
                'name': u'Water besparen',
                'unit': u'l',
                'text': u'water te besparen',
                'text_passed': '{} l water te besparen',
                'text_with_target': u'water bespaard'
            }
        },
        {
            'slug': 'plastic',
            'icon': 'plastic',
            'en': {
                'name': u'Save plastic',
                'unit': u'kg',
                'text': u'save plastic',
                'text_passed': 'save {} kg plastic',
                'text_with_target': u'plastic saved',
            },
            'nl': {
                'name': u'Plastic besparen',
                'unit': u'kg',
                'text': u'plastic te besparen',
                'text_passed': '{} kg plastic te besparen',
                'text_with_target': u'plastic bespaard'
            }
        },
        {
            'slug': 'trees',
            'icon': 'trees',
            'en': {
                'name': u'Plant trees',
                'unit': u'',
                'text': u'plant trees',
                'text_passed': 'plant {} trees',
                'text_with_target': u'trees planted',
            },
            'nl': {
                'name': u'Bomen planten',
                'unit': u'',
                'text': u'bomen te planten',
                'text_passed': '{} bomen te planten',
                'text_with_target': u'bomen geplant'
            }
        },
        {
            'slug': 'jobs',
            'icon': 'jobs',
            'en': {
                'name': u'Create jobs',
                'unit': u'',
                'text': u'create jobs',
                'text_passed': 'create {} jobs',
                'text_with_target': u'jobs created',
            },
            'nl': {
                'name': u'Banen creëren',
                'unit': u'',
                'text': u'banen te creëren',
                'text_passed': '{} banen te creëren',
                'text_with_target': u'banen gecreëerd'
            }
        },
    ]

    for definition in definitions:
        impact_type, created = ImpactType.objects.update_or_create(
            slug=definition['slug'],
            defaults={
                'active': False,
                'icon': definition['icon']
            }
        )
        for language in languages:
            if language in definition:
                ImpactTypeTranslation.objects.update_or_create(
                    language_code=language,
                    master=impact_type,
                    defaults=definition[language]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0015_impacttypetranslation_name'),
    ]

    operations = [
        migrations.RunPython(create_default_impact_types, migrations.RunPython.noop)
    ]
