# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0016_auto_20200820_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impacttype',
            options={'ordering': ('id',), 'verbose_name': 'impact type', 'verbose_name_plural': 'impact types'},
        ),
    ]
