# Generated by Django 2.2.20 on 2021-09-20 11:07

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0017_auto_20201110_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactgoal',
            name='coupled_with_contributions',
            field=models.BooleanField(default=False, help_text='Update realized impact automatically when a contribution is added', verbose_name='coupled with contributions'),
        ),
    ]
