# Generated by Django 2.2.20 on 2021-10-01 09:34

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0019_auto_20210924_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactgoal',
            name='realized_from_contributions',
            field=models.FloatField(blank=True, null=True, verbose_name='realized from contributions'),
        ),
        migrations.AlterField(
            model_name='impactgoal',
            name='target',
            field=models.FloatField(blank=True, help_text='Set a target for the impact you expect to make', null=True, verbose_name='target'),
        ),
        migrations.AlterField(
            model_name='impacttypetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='impact.ImpactType'),
        ),
    ]
