# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-29 10:12
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'add_activity', 'change_activity', 'delete_activity',
            )
        },
        'Anonymous': {
            'perms': ('api_read_activity',)
        },
        'Authenticated': {
            'perms': ('api_read_activity', )
        }
    }

    update_group_permissions('activities', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
