# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 09:57
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'add_activity', 'change_activity', 'delete_activity',
            )
        },
        'Anonymous': {
            'perms': ('api_read_activity',)
        },
        'Authenticated': {
            'perms': ('api_read_activity', )
        }
    }

    update_group_permissions('activities', group_perms, apps)

class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20190524_1041'),
    ]

    operations = [
        migrations.RunPython(
            add_group_permissions,
            migrations.RunPython.noop
        )
    ]
