# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-16 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('activities', '0003_auto_20190516_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_activities.contribution_set+', to='contenttypes.ContentType'),
        ),
    ]
