# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-17 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_contribution_polymorphic_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
