# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-28 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20190524_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[(b'draft', 'draft'), (b'open', 'open'), (b'full', 'full'), (b'running', 'running'), (b'done', 'done'), (b'closed', 'closed')], default=b'draft', max_length=50),
        ),
    ]
