# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-05 12:53
from __future__ import unicode_literals

import bluebottle.fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20190528_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(default=b'new', max_length=100, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=bluebottle.fsm.FSMField(choices=[(b'draft', 'draft'), (b'open', 'open'), (b'full', 'full'), (b'running', 'running'), (b'done', 'done'), (b'closed', 'closed')], default=b'draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=bluebottle.fsm.FSMField(default=b'new', max_length=20),
        ),
    ]
