# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-22 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20190517_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='initiatives.Initiative'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
