# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-07 13:06
from __future__ import unicode_literals

import bluebottle.fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20190814_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='contribution',
            name='transition_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=bluebottle.fsm.FSMField(default=b'in_review', max_length=20),
        ),
    ]
