# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-07 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20191007_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='transition_date',
            field=models.DateTimeField(null=True),
        ),
    ]
