# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-08 12:17
from __future__ import unicode_literals

from django.db import migrations


def correct_activity_status(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')

    Activity.objects.filter(
        review_status__in=('draft', 'submitted', 'needs_work')
    ).update(status='in_review')

    Activity.objects.filter(
        review_status='closed'
    ).update(status='closed')


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_auto_20191028_1156'),
    ]

    operations = [
        migrations.RunPython(correct_activity_status)
    ]
