# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-05 10:39


from django.db import migrations, connection


def create_contribution_view(apps, schema_editor):
    sql = """
    DROP VIEW IF EXISTS contributions;
    CREATE VIEW contributions AS 
        SELECT REPLACE(REPLACE(REPLACE(ct.model::text, 'participant'::text, 'event'::text), 'donation'::text, 'fundraiser'::text), 'applicant'::text, 'task'::text) AS activity_type,
        COALESCE(p.time_spent, 0::double precision) + COALESCE(a.time_spent, 0::double precision) AS time_spent,
        d.amount,
        d.amount_currency,
        d.name,
        c.user_id,
        c.activity_id,
        c.id,
        c.status,
        c.created,
        c.updated,
        c.contribution_date,
        c.transition_date
    FROM {0}.activities_contribution c
        JOIN {0}.django_content_type ct ON c.polymorphic_ctype_id = ct.id
        LEFT JOIN {0}.events_participant p ON p.contribution_ptr_id = c.id
        LEFT JOIN {0}.assignments_applicant a ON a.contribution_ptr_id = c.id
        LEFT JOIN {0}.funding_donation d ON d.contribution_ptr_id = c.id;    
    """.format(connection.tenant.schema_name)

    if connection.tenant.schema_name != 'public':
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_update_contribution_date'),
        ('funding', '0052_auto_20200205_1710'),
        ('assignments', '0013_assignment_update_contribution_date'),
        ('activities', '0015_auto_20200128_1045'),
    ]

    operations = [
        migrations.RunPython(create_contribution_view, migrations.RunPython.noop),
    ]
