# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-05 09:54

from django.db import migrations


def create_organizers(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')
    Organizer = apps.get_model('activities', 'Organizer')

    ContentType = apps.get_model('contenttypes', 'ContentType')
    organizer_ctype = ContentType.objects.get_for_model(Organizer)

    for activity in Activity.objects.all():
        if activity.review_status == 'approved':
            status = 'succeeded'
        elif activity.review_status == 'closed':
            status = 'closed'
        else:
            status = 'new'

        Organizer.objects.update_or_create(
            polymorphic_ctype=organizer_ctype,
            activity=activity,
            defaults={
                'user': activity.owner,
                'status': status,
                'contribution_date': activity.created
            }
        )


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0016_organizer'),
    ]

    operations = [
        migrations.RunPython(create_organizers, migrations.RunPython.noop),
    ]
