# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-11 12:19


from django.db import migrations
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'change_organizer', 'add_organizer',
                'delete_organizer',
            )
        },
    }

    update_group_permissions('activities', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_merge_20200213_1038'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
