# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-15 13:01


import bluebottle.activities.models
import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20200401_1223'),
        ('activities', '0020_auto_20200224_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name': 'Organizer', 'verbose_name_plural': 'Organizers'},
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=bluebottle.files.fields.ImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Image'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='activity',
            field=models.ForeignKey(on_delete=bluebottle.activities.models.NON_POLYMORPHIC_CASCADE, related_name='contributions', to='activities.Activity'),
        ),
    ]
