# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-07 07:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0003_auto_20200706_1630'),
        ('activities', '0022_activity_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='segments',
            field=models.ManyToManyField(related_name='activities', to='segments.Segment', verbose_name='Segment'),
        ),
    ]
