# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-30 06:45


from django.db import migrations


def fix_statuses(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')
    Activity.objects.filter(status='closed').update(status='cancelled')

    Contribution = apps.get_model('activities', 'Contribution')
    Contribution.objects.filter(status='closed').update(status='failed')

    Event = apps.get_model('events', 'Event')
    Participant = apps.get_model('events', 'Participant')
    Assignment = apps.get_model('assignments', 'Assignment')
    Applicant = apps.get_model('assignments', 'Applicant')
    Organizer = apps.get_model('activities', 'Organizer')

    # Organizer
    Organizer.objects.filter(
        activity__status__in=['cancelled', 'rejected']
    ).update(status='failed')

    Organizer.objects.filter(
        activity__status__in=['draft', 'submitted', 'needs_work']
    ).update(status='new')

    Organizer.objects.filter(
        activity__status__in=['failed', 'rejected', 'cancelled', 'deleted']
    ).update(status='failed')

    # Event
    Event.objects.filter(
        status__in=['cancelled', 'closed'],
        contributions__status__in=['succeeded'],
        contributions__polymorphic_ctype__model='participant'
    ).distinct().update(status='succeeded')

    # Participant
    Participant.objects.filter(
        status__in=['new'],
        activity__status__in=['cancelled', 'rejected', 'deleted']
    ).update(status='failed')

    Participant.objects.filter(
        status__in=['new'],
        activity__status__in=['succeeded']
    ).update(status='succeeded')

    # Assignment
    Assignment.objects.filter(
        status__in=['cancelled', 'closed'],
        contributions__status__in=['succeeded'],
        contributions__polymorphic_ctype__model='applicant'
    ).distinct().update(status='succeeded')

    # Applicant
    Applicant.objects.filter(
        status__in=['accepted', 'new', 'attending'],
        activity__status__in=['succeeded']
    ).update(status='succeeded')

    Applicant.objects.filter(
        status__in=['accepted', 'new'],
        activity__status__in=['cancelled', 'rejected', 'deleted']
    ).update(status='failed')

    Applicant.objects.filter(
        status__in=['accepted', 'new'],
        activity__status__in=['running']
    ).update(status='active')

    # More Organizers
    Organizer.objects.filter(
        activity__status__in=['succeeded', 'full', 'open', 'running', 'partially_funded']
    ).update(status='succeeded')


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_merge_20200527_0830'),
    ]

    operations = [
        migrations.RunPython(fix_statuses, migrations.RunPython.noop)
    ]
