# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-19 14:54


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_activity_segments'),
        ('activities', '0024_fix_statuses_20200630_0845'),
    ]

    operations = [
    ]
