# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-31 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0025_merge_20200819_1654'),
        ('activities', '0023_auto_20200706_1106'),
    ]

    operations = [
    ]
