# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0025_merge_20200819_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name': 'Activity owner', 'verbose_name_plural': 'Activity owners'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='review_status',
            field=models.CharField(default=b'draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='activity',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='activities', to='segments.Segment', verbose_name='Segment'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(default=b'new', max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
