# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models

from bluebottle.utils.operations import AlterBaseOperation
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_contributionvalue'),
    ]

    operations = [
        migrations.RenameModel('Contribution', 'Intention'),
    ]
