# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models

from bluebottle.utils.operations import AlterBaseOperation
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_contributionvalue'),
    ]

    operations = [
        migrations.RenameModel('Contribution', 'Intention'),
        migrations.AlterField(
            model_name='organizer',
            name='contribution_ptr',
            field=models.OneToOneField(
                auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                primary_key=True, serialize=False, to='activities.Intention')
        ),
        AlterBaseOperation(
            model_name='organizer',
            bases=('activities.intention',),
            prev_bases=('activities.contribution',)
        )

    ]
