# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-12 14:19
from __future__ import unicode_literals

import bluebottle.activities.models
from django.db import migrations, models
import django.db.models.deletion

from bluebottle.utils.operations import AlterBaseOperation


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0028_auto_20201112_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='contribution_ptr',
            field=models.OneToOneField(
                auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                primary_key=True, serialize=False, to='activities.Intention')
        ),
        migrations.RenameField(
            model_name='contributionvalue',
            old_name='contribution',
            new_name='intention',
        ),
        migrations.RenameField(
            model_name='intention',
            old_name='contribution_date',
            new_name='intention_date',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='contribution_ptr',
            new_name='intention_ptr',
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='activity',
            name='transition_date',
            field=models.DateTimeField(blank=True, help_text='Date the intention took place.', null=True, verbose_name='intention date'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='activity',
            field=models.ForeignKey(on_delete=bluebottle.activities.models.NON_POLYMORPHIC_CASCADE, related_name='intentions', to='activities.Activity'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_activities.intention_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='status',
            field=models.CharField(max_length=40),
        ),
    ]
