# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-20 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0031_auto_20201120_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_activities.contribution_set+', to='contenttypes.ContentType'),
        ),
    ]
