# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-23 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0032_auto_20201120_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerContribution',
            fields=[
                ('contribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Contribution')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
            },
            bases=('activities.contribution',),
        ),
        migrations.AlterField(
            model_name='activity',
            name='transition_date',
            field=models.DateTimeField(blank=True, help_text='Date of the last transition.', null=True, verbose_name='transition date'),
        ),
    ]
