# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0033_auto_20201123_1418'),
        ('time_based', '0039_auto_20201130_1313')
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start'),
        ),
    ]
