# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-30 12:37
from __future__ import unicode_literals

from django.db import migrations, connection


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0034_auto_20201130_1316'),
    ]

    operations = [
    ]
