# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-30 12:55
from __future__ import unicode_literals

from django.db import migrations, connection


def update_contribution_dates(apps, schema_editor):
    sql = """
        DROP VIEW IF EXISTS contributions;
        CREATE VIEW contributions AS
            SELECT ct.model::text AS activity_type,
            tc.value AS time_spent,
            mc.value AS amount,
            mc.value_currency AS amount_currency,
            don.name,
            cr.user_id,
            cr.activity_id,
            cr.id,
            cn.status,
            cr.created,
            cr.updated,
            cn.start as contribution_date,
            cn.end as transition_date,
            cn.start,
            cn.end
        FROM {0}.activities_contribution cn
            LEFT JOIN {0}.activities_contributor cr ON cn.contributor_id = cr.id
            LEFT JOIN {0}.time_based_timecontribution tc ON tc.contribution_ptr_id = cn.id
            LEFT JOIN {0}.funding_moneycontribution mc ON mc.contribution_ptr_id = cn.id
            LEFT JOIN {0}.funding_donor don ON don.contributor_ptr_id = cr.id
            JOIN {0}.django_content_type ct ON cr.polymorphic_ctype_id = ct.id;
    """.format(connection.tenant.schema_name)

    if connection.tenant.schema_name != 'public':
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0035_auto_20201130_1337'),
    ]

    operations = [
        migrations.RunPython(update_contribution_dates, migrations.RunPython.noop)
    ]
