# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-02 10:24
from __future__ import unicode_literals

from django.db import migrations, connection


def insert(table, fields, values):

    with connection.cursor() as cursor:
        query = 'INSERT into {} ({})  VALUES ({})'.format(
            table,
            ", ".join('"{}"'.format(field) for field in fields),
            ','.join('%s' for field in fields)
        )
        actual_values = []

        for value in values:
            actual_values.append(
                [value[field] for field in fields ]
            )

        cursor.executemany(query, actual_values)


def create_organizer_contributions(apps, schema_editor):
    Organizer = apps.get_model('activities', 'Organizer')
    Contribution = apps.get_model('activities', 'Contribution')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    OrganizerContribution = apps.get_model('activities', 'OrganizerContribution')

    organizer_contribution_ctype = ContentType.objects.get_for_model(OrganizerContribution).pk
    contributions = []
    organizer_contributions = []

    contribution_fields = [
        'status',
        'start',
        'contributor_id',
        'created',
        'polymorphic_ctype_id'
    ]
    organizer_contribution_fields = [
        'contribution_ptr_id',
    ]

    for organizer in Organizer.objects.values(
            'id',
            'status',
            'created',
            'contributor_ptr_id',
            'contributor_date'):

        contributions.append({
            'polymorphic_ctype_id': organizer_contribution_ctype,
            'status': organizer['status'],
            'start': organizer['contributor_date'],
            'contributor_id': organizer['id'],
            'created': organizer['created']
        })
        organizer_contributions.append({
            'contributor_id': organizer['id'],
        })

    insert('activities_contribution', contribution_fields, contributions)

    contributions = dict(Contribution.objects.values_list('contributor_id', 'id'))
    for organizer_contribution in organizer_contributions:
        organizer_contribution['contribution_ptr_id'] = contributions[organizer_contribution['contributor_id']]

    insert('activities_organizercontribution', organizer_contribution_fields, organizer_contributions)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0036_auto_20201130_1355'),
    ]

    operations = [
        migrations.RunPython(create_organizer_contributions, migrations.RunPython.noop),
    ]
