# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-02 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0036_auto_20201130_1355'),
    ]

    operations = [
    ]
