# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-27 12:58
from __future__ import unicode_literals

from django.db import migrations, connection

from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        activities_perms = {
            'Staff': {
                'perms': (
                    'add_effortcontribution', 'change_effortcontribution',
                    'delete_effortcontribution',

                )
            },
        }
    update_group_permissions('activities', activities_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0040_auto_20210224_1508'),
    ]

    operations = [
        migrations.RunPython(
            add_group_permissions,
            migrations.RunPython.noop
        )
    ]
