# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-08 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0041_auto_20210226_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='effortcontribution',
            name='contribution_type',
            field=models.CharField(choices=[('organizer', 'Activity Organizer'), ('deed', 'Deed particpant')], default='organizer', max_length=20, verbose_name='Contribution type'),
            preserve_default=False,
        ),
    ]
