# Generated by Django 2.2.20 on 2021-07-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0043_auto_20210420_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Location', verbose_name='office'),
        ),
    ]
