# Generated by Django 2.2.24 on 2022-03-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0045_auto_20211102_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='team_activity',
            field=models.BooleanField(default=False, help_text='Only teams can sign-up for this activity.', verbose_name='Team acticity'),
        ),
    ]
