# Generated by Django 2.2.24 on 2022-03-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0047_auto_20220321_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='activities.Team'),
        ),
    ]
