# Generated by Django 2.2.24 on 2021-09-22 13:02

from django.db import migrations, connection

from bluebottle.clients import properties
from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        group_perms = {
            'Staff': {
                'perms': (
                    'add_team', 'change_team', 'delete_team',
                    'api_change_team',
                )
            },
            'Anonymous': {
                'perms': (
                    'api_read_team',
                ) if not properties.CLOSED_SITE else ()
            },
            'Authenticated': {
                'perms': (
                    'api_read_team',
                    'api_change_own_team',
                )
            }
    }

    update_group_permissions('activities', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0049_auto_20220324_1120'),
    ]

    operations = [
        migrations.RunPython(
            add_group_permissions,
            migrations.RunPython.noop
        )
    ]
