# Generated by Django 2.2.24 on 2022-04-05 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0053_merge_20220405_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='invite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Invite'),
        ),
    ]
