# Generated by Django 2.2.24 on 2022-04-05 13:14

import django
from django.db import migrations, models
import uuid

def set_uuid(apps, schema_editor):
    Team = apps.get_model('activities', 'Team')

    for team in Team.objects.all():
        team.uuid = uuid.uuid4()
        team.save()

class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0053_merge_20220405_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.RunPython(set_uuid),

        migrations.AlterField(
            model_name='contributor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='activities.Team', to_field='uuid', verbose_name='team'),
        ),

        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),

        migrations.RenameField(
            model_name='team',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='contributor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='activities.Team', to_field='id', verbose_name='team'),
        ),
    ]
