# Generated by Django 2.2.24 on 2022-04-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0055_auto_20220406_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='invite',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor', to='activities.Invite'),
        ),
    ]
