# Generated by Django 2.2.24 on 2022-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0057_auto_20220608_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='team_activity',
            field=models.CharField(blank=True, choices=[('teams', 'Teams'), ('individuals', 'Individuals')], default='individuals', help_text='Is this activity open for individuals or can only teams sign up?', max_length=100, verbose_name='participation'),
        ),
    ]
