# Generated by Django 2.2.24 on 2022-08-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0058_auto_20220622_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='activities.Team', verbose_name='team'),
        ),
    ]
