# Generated by Django 2.2.24 on 2022-09-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0059_auto_20220804_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='office_restriction',
            field=models.CharField(choices=[('office', 'Only people from the same office are allowed to participate'), ('office_subregion', 'Only people within the same group are allowed to participate'), ('office_region', 'Only people within the same region are allowed to participate'), ('all', 'Everybody is allowed to participate')], default='all', max_length=100, verbose_name='Office restriction'),
        ),
    ]
