# Generated by Django 2.2.24 on 2022-08-31 13:07

from django.db import migrations


def migrate_office_to_activities(apps, schema_editor):
    Initiative = apps.get_model('initiatives', 'Initiative')
    for initiative in Initiative.objects.filter(location__isnull=False).all():
        initiative.activities.update(office_location=initiative.location)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0059_auto_20220804_1214'),
        ('collect', '0016_auto_20211119_1143'),
    ]

    operations = [
        migrations.RunPython(
            migrate_office_to_activities,
            migrations.RunPython.noop
        )
    ]

