# Generated by Django 2.2.24 on 2022-09-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0060_auto_20220831_1507'),
        ('activities', '0060_activity_office_restriction'),
    ]

    operations = [
    ]
