# Generated by Django 2.2.24 on 2022-12-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0062_auto_20221205_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deleted_successful_contributors',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of deleted successful contributors'),
        ),
    ]
