# Generated by Django 2.2.24 on 2022-12-09 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0063_auto_20221209_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='activities.Contributor'),
        ),
    ]
