# Generated by Django 2.2.24 on 2022-12-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0064_auto_20221209_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='deleted_successful_contributors',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of deleted successful contributors'),
        ),
    ]
