# Generated by Django 3.2.19 on 2023-07-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0031_auto_20230503_1524'),
        ('activities', '0067_auto_20230405_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='has_deleted_data',
            field=models.BooleanField(default=False, help_text='Due to company policies and local laws, user data maybe deleted in this activity.', verbose_name='Has anonymised and/or deleted data'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.location', verbose_name='Host office'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='office_restriction',
            field=models.CharField(blank=True, choices=[('office', 'Open to people from the same office'), ('office_subregion', 'Open to people from offices within the same group'), ('office_region', 'Open to people from offices within the same region'), ('all', 'Open to people from any office')], default='all', max_length=100, null=True, verbose_name='Restrictions'),
        ),
    ]
