# Generated by Django 3.2.20 on 2024-05-30 07:00

import bluebottle.activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0072_auto_20240207_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='activity',
            field=models.ForeignKey(on_delete=bluebottle.activities.models.NON_POLYMORPHIC_CASCADE, related_name='old_teams', to='activities.activity'),
        ),
    ]
