# Generated by Django 3.2.20 on 2024-07-18 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0073_alter_team_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='activities.team', verbose_name='Old team'),
        ),
    ]
