# Generated by Django 3.2.20 on 2024-07-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0074_alter_contributor_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="accepted_invite",
        ),
        migrations.RemoveField(
            model_name="contributor",
            name="invite",
        ),
    ]
