# Generated by Django 3.2.20 on 2024-10-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0075_auto_20240723_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='next_step_link',
            field=models.URLField(blank=True, default='', help_text='This link is shown after a user joined as the next step for the activity', max_length=2048, null=True, verbose_name='Redirect step link'),
        ),
    ]
