# Generated by Django 3.2.20 on 2025-02-24 15:30

import json
from django.db import migrations


def convert_to_quill(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')

    for activity in Activity.objects.all(): 
        activity.description = json.dumps({"html": activity.description, "delta": ""})
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0076_auto_20241018_1354'),
    ]

    operations = [
        migrations.RunPython(convert_to_quill, migrations.RunPython.noop)
    ]
