# Generated by Django 3.2.20 on 2024-12-22 13:19

import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_relatedimage_image'),
        ('activities', '0076_auto_20241018_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='source_platform',
            field=models.CharField(blank=True, help_text='If this activity was created on another platform, this field wil be set. This platform is managed by that platform and editing here is limited.', max_length=100, null=True, verbose_name='Source platform'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=bluebottle.files.fields.ImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Make your activity come alive with a video. You can paste the link to YouTube or Vimeo here.', max_length=100, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='effortcontribution',
            name='contribution_type',
            field=models.CharField(choices=[('organizer', 'Activity Organizer'), ('deed', 'Deed participant')], max_length=20, verbose_name='Contribution type'),
        ),
    ]
