# Generated by Django 3.2.20 on 2025-01-17 12:57

import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0054_auto_20241018_0853'),
        ('files', '0012_auto_20250113_1704'),
        ('organizations', '0017_auto_20241106_1009'),
        ('activities', '0077_auto_20250117_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='activity',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='initiatives.theme'),
        ),
    ]
