# Generated by Django 4.2.20 on 2025-03-20 08:50

import bluebottle.bluebottle_dashboard.quill
import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('activities', '0077_auto_20250224_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=bluebottle.bluebottle_dashboard.quill.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=bluebottle.files.fields.ImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Make your activity come alive with a video. You can paste the link to YouTube or Vimeo here.', max_length=100, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='effortcontribution',
            name='contribution_type',
            field=models.CharField(choices=[('organizer', 'Activity Organizer'), ('deed', 'Deed participant')], max_length=20, verbose_name='Contribution type'),
        ),
    ]
