# Generated by Django 4.2.17 on 2025-03-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0077_auto_20250224_1630'),
        ('activities', '0078_auto_20250117_1357'),
    ]

    operations = [
    ]
