# Generated by Django 3.2.20 on 2024-12-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0078_activity_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='remote_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='remote_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='source_platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
