# Generated by Django 4.2.17 on 2025-03-10 14:02

import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('initiatives', '0057_initiativeplatformsettings_enable_reviewing_and_more'),
        ('activities', '0079_merge_0077_auto_20250224_1630_0078_auto_20250117_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='published',
            field=models.DateTimeField(blank=True, help_text='Date that the activity went online.', null=True, verbose_name='Published date'),
        ),
    ]
