# Generated by Django 4.2.20 on 2025-03-21 10:21

from django.db import migrations
from django.db.models import Subquery, OuterRef



def migrate_themes_and_organizations(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')

    Activity.objects.update(
        theme_id=Subquery(
            Activity.objects.filter(pk=OuterRef('pk')).values('initiative__theme_id')[:1]
        ),
        organization_id=Subquery(
            Activity.objects.filter(pk=OuterRef('pk')).values('initiative__organization_id')[:1]
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0080_activity_published'),
    ]

    operations = [
        migrations.RunPython(migrate_themes_and_organizations, migrations.RunPython.noop),
    ]
