# Generated by Django 4.2.20 on 2025-05-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_auto_20241106_1009'),
        ('activities', '0083_auto_20250321_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='organizations.organization', verbose_name='Partner organization'),
        ),
    ]
