# Generated by Django 4.2.20 on 2025-06-04 08:14

import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('activities', '0085_activityanswer_activityquestion_textanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadAnswer',
            fields=[
                ('activityanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activityanswer')),
                ('answer', bluebottle.files.fields.DocumentField(on_delete=django.db.models.deletion.CASCADE, to='files.document')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activities.activityanswer',),
        ),
        migrations.AlterModelOptions(
            name='fileuploadquestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='segmentquestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='textquestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='fileuploadquestion',
            name='answer',
        ),
        migrations.AddField(
            model_name='activityquestion',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.DeleteModel(
            name='ActivityQuestionTranslation',
        ),
    ]
