# Generated by Django 4.2.20 on 2025-06-06 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0087_activityquestiontranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuploadanswer',
            old_name='answer',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='segmentanswer',
            old_name='answer',
            new_name='segment',
        ),
        migrations.AlterField(
            model_name='activityanswer',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='activities.activity'),
        ),
    ]
