# Generated by Django 4.2.20 on 2025-06-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0088_rename_answer_fileuploadanswer_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityquestiontranslation',
            name='name',
            field=models.CharField(default='Short name', max_length=255),
            preserve_default=False,
        ),
    ]
