# Generated by Django 4.2.20 on 2025-08-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0090_alter_activityquestion_activity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tos_accepted',
            field=models.BooleanField(default=False, help_text='Has the user accepted the terms of service for this activity?', verbose_name='Terms of Service accepted'),
        ),
    ]
