# Generated by Django 4.2.20 on 2025-09-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0091_alter_activityquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='activityquestion',
            options={'verbose_name': 'Form question', 'verbose_name_plural': 'Form questions'},
        ),
        migrations.AlterModelOptions(
            name='activityquestiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Form question Translation'},
        ),
        migrations.AlterField(
            model_name='activityquestiontranslation',
            name='name',
            field=models.CharField(help_text='The label for this question. This is used for validation messages e.g. "[label] is required".', max_length=255, verbose_name='Label'),
        ),
        migrations.AlterUniqueTogether(
            name='activityanswer',
            unique_together={('activity', 'question')},
        ),
    ]
