# Generated by Django 4.2.20 on 2025-09-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0093_confirmationanswer_confirmationquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationanswer',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confirmationquestion',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
