# Generated by Django 4.2.20 on 2025-09-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0094_confirmationanswer_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Make your activity come alive with a video. You can paste the link to YouTube or Vimeo here.', max_length=2048, null=True, verbose_name='video'),
        ),
    ]
