# Generated by Django 4.2.20 on 2025-09-29 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0029_image_url'),
        ('activities', '0095_alter_activity_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='activity_pub.event'),
        ),
    ]
