# Generated by Django 4.2.20 on 2025-11-17 00:00

from django.db import migrations, connection

from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)

    with LocalTenant(tenant):
        activities_permissions = {
            'Staff': {
                'perms': (
                    'add_activityquestion', 'change_activityquestion', 'delete_activityquestion',
                    'add_textquestion', 'change_textquestion', 'delete_textquestion',
                    'add_confirmationquestion', 'change_confirmationquestion', 'delete_confirmationquestion',
                    'add_segmentquestion', 'change_segmentquestion', 'delete_segmentquestion',
                    'add_fileuploadquestion', 'change_fileuploadquestion', 'delete_fileuploadquestion',
                    'add_activityanswer', 'change_activityanswer', 'delete_activityanswer',
                    'add_textanswer', 'change_textanswer', 'delete_textanswer',
                    'add_confirmationanswer', 'change_confirmationanswer', 'delete_confirmationanswer',
                    'add_segmentanswer', 'change_segmentanswer', 'delete_segmentanswer',
                    'add_fileuploadanswer', 'change_fileuploadanswer', 'delete_fileuploadanswer',
                )
            },
        }

        update_group_permissions('activities', activities_permissions, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0096_activityquestion_visibility'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions,  migrations.RunPython.noop)
    ]

