# Generated by Django 4.2.20 on 2025-12-01 11:54

import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('activities', '0097_add_staff_question_answer_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityquestion',
            name='visibility',
            field=models.CharField(choices=[('all', 'Everyone'), ('managers', 'Managers')], default='all', max_length=255, verbose_name='Who can see the answers?'),
        ),
        migrations.AlterField(
            model_name='fileuploadanswer',
            name='file',
            field=bluebottle.files.fields.PrivateDocumentField(on_delete=django.db.models.deletion.CASCADE, to='files.privatedocument'),
        ),
    ]
