# Generated by Django 4.2.20 on 2025-11-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0096_activityquestion_visibility'),
        ('activities', '0098_activity_host_organization_and_more'),
    ]

    operations = [
    ]
