# Generated by Django 4.2.20 on 2025-12-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0098_alter_activityquestion_visibility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'permissions': (('api_read_activity', 'Can view activity through the API'), ('api_read_own_activity', 'Can view own activity through the API'), ('api_review_activity', 'Can review activities through the API')), 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
