# Generated by Django 4.2.20 on 2025-12-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0098_alter_activityquestion_visibility_and_more'),
        ('activities', '0099_merge_20251103_1151'),
    ]

    operations = [
    ]
