# Generated by Django 4.2.20 on 2026-01-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0100_auto_20251210_1351'),
        ('activities', '0100_merge_20251204_1647'),
    ]

    operations = [
    ]
