# Generated by Django 4.2.20 on 2026-03-10 16:00

import bluebottle.activities.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0039_merge_20260116_1155'),
        ('activity_pub', '0071_event_contributor_count_alter_follow_adoption_type_and_more'),
        ('activities', '0101_merge_20260120_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.location', verbose_name='Host work location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='office_restriction',
            field=models.CharField(blank=True, choices=[('office', 'Open to people from the same work location'), ('office_subregion', 'Open to people from work locations within the same group'), ('office_region', 'Open to people from work locations within the same region'), ('all', 'Open to people from any work location')], default='all', max_length=100, null=True, verbose_name='Restrictions'),
        ),
        migrations.AlterField(
            model_name='activityanswer',
            name='activity',
            field=models.ForeignKey(on_delete=bluebottle.activities.models.POLYMORPHIC_CASCADE, related_name='answers', to='activities.activity'),
        ),
        migrations.CreateModel(
            name='RemoteContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', help_text='Name when no user is linked (e.g. synced participants).', max_length=255, verbose_name='Display name')),
                ('email', models.EmailField(blank=True, help_text='Email when no user is linked (e.g. synced participants).', max_length=254, null=True, verbose_name='Email')),
                ('sync_id', models.CharField(blank=True, help_text='Remote participant id for matching Join/Leave in synced activities.', max_length=255, null=True, unique=True, verbose_name='Sync identifier')),
                ('sync_actor', models.ForeignKey(blank=True, help_text='The ActivityPub Actor (platform) that sent the Join this participant came from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_remote_contributors', to='activity_pub.actor', verbose_name='Sync source (Actor)')),
                ('sync_follow', models.ForeignKey(blank=True, help_text='The Follow (connection) through which this participant joined.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_remote_contributors', to='activity_pub.follow', verbose_name='Sync source (Follow)')),
            ],
            options={
                'verbose_name': 'Remote contributor',
                'verbose_name_plural': 'Remote contributors',
            },
        ),
        migrations.AddField(
            model_name='contributor',
            name='remote_contributor',
            field=models.ForeignKey(blank=True, help_text='When set, this contributor is a synced participant without a local user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributors', to='activities.remotecontributor', verbose_name='Remote contributor'),
        ),
    ]
