# Generated by Django 4.2.20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0075_join_leave_participant_fields'),
        ('activities', '0102_contributor_display_name_email_sync_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='sync_actor',
            field=models.ForeignKey(
                blank=True,
                help_text='The ActivityPub Actor (platform) that sent the Join this participant came from.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='synced_contributors',
                to='activity_pub.actor',
                verbose_name='Sync source (Actor)',
            ),
        ),
        migrations.AddField(
            model_name='contributor',
            name='sync_follow',
            field=models.ForeignKey(
                blank=True,
                help_text='The Follow (connection) through which this participant joined.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='synced_contributors',
                to='activity_pub.follow',
                verbose_name='Sync source (Follow)',
            ),
        ),
    ]
