# Generated by Django 5.2.13 on 2026-06-11 13:02

import bluebottle.activities.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0102_activity_message'),
        ('geo', '0039_merge_20260116_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmationanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='confirmationquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fileuploadanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fileuploadquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='segmentanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='segmentquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textquestion',
            options={},
        ),
        migrations.AlterField(
            model_name='activity',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.location', verbose_name='Host work location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='office_restriction',
            field=models.CharField(blank=True, choices=[('office', 'Open to people from the same work location'), ('office_subregion', 'Open to people from work locations within the same group'), ('office_region', 'Open to people from work locations within the same region'), ('all', 'Open to people from any work location')], default='all', max_length=100, null=True, verbose_name='Restrictions'),
        ),
        migrations.AlterField(
            model_name='activityanswer',
            name='activity',
            field=models.ForeignKey(on_delete=bluebottle.activities.models.POLYMORPHIC_CASCADE, related_name='answers', to='activities.activity'),
        ),
    ]
