# Generated by Django 4.2.20

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


def create_remote_users_and_assign(apps, schema_editor):
    """Create RemoteUser from Contributor display_name/email/sync_id and set Contributor.remote_user."""
    Contributor = apps.get_model('activities', 'Contributor')
    RemoteUser = apps.get_model('activities', 'RemoteUser')

    to_migrate = Contributor.objects.filter(
        Q(display_name__isnull=False) & ~Q(display_name='') |
        Q(email__isnull=False) & ~Q(email='') |
        Q(sync_id__isnull=False) & ~Q(sync_id='')
    )

    seen_sync_ids = set()
    for contrib in to_migrate.iterator():
        sync_id = contrib.sync_id or None
        display_name = contrib.display_name or ''
        email = contrib.email or None

        if sync_id and sync_id in seen_sync_ids:
            remote_user = RemoteUser.objects.get(sync_id=sync_id)
        elif sync_id:
            remote_user, _ = RemoteUser.objects.get_or_create(
                sync_id=sync_id,
                defaults={'display_name': display_name, 'email': email},
            )
            seen_sync_ids.add(sync_id)
        else:
            remote_user = RemoteUser.objects.create(
                display_name=display_name,
                email=email,
                sync_id=None,
            )
        contrib.remote_user = remote_user
        contrib.save(update_fields=['remote_user_id'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0103_contributor_sync_actor_sync_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', help_text='Name when no user is linked (e.g. synced participants).', max_length=255, verbose_name='Display name')),
                ('email', models.EmailField(blank=True, help_text='Email when no user is linked (e.g. synced participants).', max_length=254, null=True, verbose_name='Email')),
                ('sync_id', models.CharField(blank=True, help_text='Remote participant id for matching Join/Leave in synced activities.', max_length=255, null=True, unique=True, verbose_name='Sync identifier')),
            ],
            options={
                'verbose_name': 'Remote user',
                'verbose_name_plural': 'Remote users',
            },
        ),
        migrations.AddField(
            model_name='contributor',
            name='remote_user',
            field=models.ForeignKey(
                blank=True,
                help_text='When set, this contributor is a synced participant without a local user.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='contributors',
                to='activities.remoteuser',
                verbose_name='Remote user',
            ),
        ),
        migrations.RunPython(create_remote_users_and_assign, noop),
        migrations.RemoveField(
            model_name='contributor',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='sync_id',
        ),
    ]
