# Generated by Django 4.2.20

from django.db import migrations, models
import django.db.models.deletion


def copy_sync_actor_follow_to_remote_contributor(apps, schema_editor):
    """Copy Contributor.sync_actor and sync_follow to Contributor.remote_contributor."""
    Contributor = apps.get_model('activities', 'Contributor')
    RemoteContributor = apps.get_model('activities', 'RemoteContributor')

    for contrib in Contributor.objects.filter(remote_contributor_id__isnull=False).iterator():
        if not contrib.sync_actor_id and not contrib.sync_follow_id:
            continue
        rc = RemoteContributor.objects.get(pk=contrib.remote_contributor_id)
        if contrib.sync_actor_id:
            rc.sync_actor_id = contrib.sync_actor_id
        if contrib.sync_follow_id:
            rc.sync_follow_id = contrib.sync_follow_id
        rc.save(update_fields=['sync_actor_id', 'sync_follow_id'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0075_join_leave_participant_fields'),
        ('activities', '0104_remoteuser_and_contributor_remote_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RemoteUser',
            new_name='RemoteContributor',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='remote_user',
            new_name='remote_contributor',
        ),
        migrations.AddField(
            model_name='remotecontributor',
            name='sync_actor',
            field=models.ForeignKey(
                blank=True,
                help_text='The ActivityPub Actor (platform) that sent the Join this participant came from.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='synced_remote_contributors',
                to='activity_pub.actor',
                verbose_name='Sync source (Actor)',
            ),
        ),
        migrations.AddField(
            model_name='remotecontributor',
            name='sync_follow',
            field=models.ForeignKey(
                blank=True,
                help_text='The Follow (connection) through which this participant joined.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='synced_remote_contributors',
                to='activity_pub.follow',
                verbose_name='Sync source (Follow)',
            ),
        ),
        migrations.RunPython(copy_sync_actor_follow_to_remote_contributor, noop),
        migrations.RemoveField(
            model_name='contributor',
            name='sync_actor',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='sync_follow',
        ),
    ]
