# Generated by Django 4.2.20 on 2026-05-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0102_remove_activity_origin_and_more'),
        ('activities', '0105_activity_synced_contributor_count'),
    ]

    operations = [
    ]
