# Generated by Django 4.2.20 on 2026-05-18 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0106_merge_20260511_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='First name')),
                ('email', models.EmailField(blank=True, help_text='Email when no user is linked (e.g. synced participants).', max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Remote contributor',
                'verbose_name_plural': 'Remote contributors',
            },
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='remote_contributor',
        ),
        migrations.DeleteModel(
            name='RemoteContributor',
        ),
        migrations.AddField(
            model_name='contributor',
            name='remote_user',
            field=models.ForeignKey(blank=True, help_text='When set, this contributor is a synced participant without a local user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributors', to='activities.remotemember', verbose_name='Remote member'),
        ),
    ]
