# Generated by Django 5.2.13 on 2026-05-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0107_remotemember_remove_contributor_remote_contributor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmationanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='confirmationquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fileuploadanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fileuploadquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='segmentanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='segmentquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textquestion',
            options={},
        ),
    ]
