# Generated by Django 5.2.13 on 2026-06-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0108_alter_confirmationanswer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='origin',
            new_name='old_origin',
        ),
    ]
