# Generated by Django 5.2.13 on 2026-06-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0102_activity_message'),
        ('activities', '0109_rename_origin_activity_old_origin'),
    ]

    operations = [
    ]
