# Generated by Django 5.2.13 on 2026-07-15 13:35

import bluebottle.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0110_merge_20260619_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=bluebottle.utils.fields.QuillField(blank=True, verbose_name='Description'),
        ),
    ]
