# Generated by Django 5.2.15 on 2026-07-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0103_alter_confirmationanswer_options_and_more'),
        ('activities', '0111_alter_activity_description'),
    ]

    operations = [
    ]
