# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payouts', '0001_initial'),
        ('accounting', '0002_auto_20160523_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payouts.ProjectPayout', verbose_name='Campaign payout'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='remote_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.RemoteDocdataPayment', verbose_name='Docdata payment'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='remote_payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.RemoteDocdataPayout', verbose_name='Docdata payout'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.BankTransactionTenant', verbose_name='Tenant'),
        ),
    ]
