import os
import re

from django.db import connection

from tenant_extras.management.commands.makepo import Command as BaseCommand
from django.core.management.base import CommandError

from tenant_schemas.utils import get_tenant_model

from bluebottle.bb_projects.models import ProjectTheme, ProjectPhase
from bluebottle.tasks.models import Skill
from bluebottle.geo.models import Country, Region


class Command(BaseCommand):
    help = "Make PO file with additional messages from models."

    def _additional_msgs(self):
        msgs = ()

        try:
            tenant = get_tenant_model().objects.get(client_name=self.tenant)
            connection.set_tenant(tenant)
        except get_tenant_model().DoesNotExist:
            self.stdout.write("Tenant does not exist: {}".format(self.tenant))
            return (), ""

        # If any of the following tables are empty then we haven't run loaddata
        # for the tenant. The translations should then fail.
        classes = [ProjectTheme, Skill, ProjectPhase, Country, Region]
        for cls in classes:
            if not cls.objects.count():
                raise CommandError("Missing {0} records. Has loaddata been run for {1}".format(cls.__name__, self.tenant))

        for cls in classes:
            for item in cls.objects.all():
                msgs = msgs + (item.name,)

        return msgs, "Additional messages generated by makepo_ext management command."
