# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-19 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0003_auto_20161025_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='LipishaPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.Payment')),
                ('reference', models.CharField(blank=True, help_text=b'Transaction reference', max_length=200, null=True)),
                ('transaction_status', models.CharField(blank=True, help_text=b'Lipisha transaction status', max_length=200, null=True)),
                ('transaction_type', models.CharField(blank=True, help_text=b'Lipisha transaction type', max_length=200, null=True)),
                ('transaction_amount', models.CharField(blank=True, help_text=b'Lipisha transaction reference', max_length=200, null=True)),
                ('transaction_currency', models.CharField(blank=True, help_text=b'Lipisha transaction currency', max_length=200, null=True)),
                ('transaction_reference', models.CharField(blank=True, help_text=b'Lipisha Transaction reference', max_length=200, null=True)),
                ('transaction_reversal_status', models.CharField(blank=True, help_text=b'Lipisha transaction reversal status', max_length=200, null=True)),
                ('transaction_account_name', models.CharField(blank=True, help_text=b'Lipisha transaction account name', max_length=200, null=True)),
                ('transaction_account_number', models.CharField(blank=True, help_text=b'Lipisha transaction account number', max_length=200, null=True)),
                ('transaction_date', models.CharField(blank=True, help_text=b'Lipisha transaction date', max_length=200, null=True)),
                ('transaction_email', models.CharField(blank=True, help_text=b'Lipisha transaction email', max_length=200, null=True)),
                ('transaction_method', models.CharField(blank=True, help_text=b'Lipisha transaction method', max_length=200, null=True)),
                ('transaction_mobile_number', models.CharField(blank=True, help_text=b'Lipisha transaction mobile number', max_length=200, null=True)),
                ('transaction_name', models.CharField(blank=True, help_text=b'Lipisha transaction name', max_length=200, null=True)),
                ('transaction_fee', models.TextField(blank=True, help_text=b'Lipisha transaction fee object', null=True)),
                ('response', models.TextField(blank=True, help_text='Response from Lipisha', null=True)),
                ('update_response', models.TextField(blank=True, help_text='Result from Lipisha (status update)', null=True)),
            ],
            options={
                'ordering': ('-created', '-updated'),
                'verbose_name': 'Lipisha Payment',
                'verbose_name_plural': 'Lipisha Payments',
            },
            bases=('payments.payment',),
        ),
    ]
