# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20171025_1253'),
        ('payments_lipisha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LipishaProject',
            fields=[
                ('projectaddon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.ProjectAddOn')),
                ('account_number', models.CharField(blank=True, help_text=b'Lipisha account number', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('projects.projectaddon',),
        ),
    ]
