# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 14:14
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'add_donation', 'change_donation', 'delete_donation',
            )
        }
    }

    update_group_permissions('donations', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20160718_1811'),
    ]

    operations = [
            migrations.RunPython(add_group_permissions)
    ]
