# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20170803_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of donor'),
        ),
    ]
