# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 08:00
from __future__ import unicode_literals

from django.db import migrations, connection
from bluebottle.clients import properties



def migrate_donation_settings(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    properties.set_tenant(tenant)
    DonationDefaultAmounts = apps.get_model("donations", "DonationDefaultAmounts")
    DonationPlatformSettings = apps.get_model("donations", "DonationPlatformSettings")
    settings, created = DonationPlatformSettings.objects.get_or_create()
    settings.show_donation_amount = properties.SHOW_DONATION_AMOUNTS
    settings.recurring_donations = properties.RECURRING_DONATIONS_ENABLED
    amounts = properties.DONATION_AMOUNTS
    for currency in amounts:
        values = amounts[currency]
        DonationDefaultAmounts.objects.create(
            settings=settings,
            currency=currency,
            value1=values[0],
            value2=values[1],
            value3=values[2],
            value4=values[3]
        )
    settings.save()


def dummy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20180206_0857'),
    ]

    operations = [
        migrations.RunPython(migrate_donation_settings, dummy)
    ]
