# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-01 09:46
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_auto_20190130_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'donation', 'verbose_name_plural': 'donations'},
        ),
        migrations.AddField(
            model_name='donation',
            name='new_donation_id',
            field=models.IntegerField(null=True),
        ),
    ]
