# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20191101_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='fundraiser',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='reward',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
