# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fluent_contents.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0001_initial'),
        ('pages', '0006_auto_20171114_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTextItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('text', fluent_contents.extensions.PluginHtmlField(blank=True, verbose_name='text')),
                ('text_final', models.TextField(blank=True, editable=False, null=True)),
                ('image', fluent_contents.extensions.PluginImageField(verbose_name='Image')),
                ('align', models.CharField(blank=True, choices=[(b'left', 'Left'), (b'right', 'Right')], max_length=10, verbose_name='Picture placement')),
                ('ratio', models.IntegerField(blank=True, choices=[(8, '2:1 (Text twice as wide)'), (6, '1:1 (Equal width)'), (4, '1:2 (Image twice as wide)')], default=6, max_length=10, verbose_name='Picture / Text ratio')),
            ],
            options={
                'db_table': 'contentitem_pages_imagetextitem',
                'verbose_name': 'Picture + Text',
                'verbose_name_plural': 'Picture + Text',
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
