# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 06:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0001_initial'),
        ('pages', '0007_imagetextitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('text', models.CharField(max_length=100, verbose_name='Link title')),
                ('document', models.FileField(upload_to=b'pages', verbose_name='Document')),
            ],
            options={
                'abstract': False,
                'db_table': 'contentitem_pages_documentitem',
            },
            bases=('fluent_contents.contentitem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='imagetextitem',
            name='ratio',
            field=models.IntegerField(blank=True, choices=[(8, '2:1 (Text twice as wide)'), (6, '1:1 (Equal width)'), (4, '1:2 (Image twice as wide)')], default=6, verbose_name='Picture / Text ratio'),
        ),
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
