# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-11 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20180711_0946'),
        ('pages', '0009_auto_20180709_1706'),
    ]

    operations = [
    ]
