# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-16 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20180709_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[(b'nl', b'Dutch'), (b'en', b'English')], max_length=5, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='page',
            name='publication_date',
            field=models.DateTimeField(db_index=True, help_text="To go live, status must be 'Published'.", null=True, verbose_name='publication date'),
        ),
    ]
