# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-13 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20180717_1017'),
        ('pages', '0010_merge_20180711_1057'),
    ]

    operations = [
    ]
