# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-06 15:29


from django.db import migrations, models
import django.db.models.deletion
import fluent_contents.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0001_initial'),
        ('pages', '0011_auto_20200106_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnsItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('text1', fluent_contents.extensions.PluginHtmlField(blank=True, verbose_name='text left')),
                ('text1_final', models.TextField(blank=True, editable=False, null=True)),
                ('text2', fluent_contents.extensions.PluginHtmlField(blank=True, verbose_name='text right')),
                ('text2_final', models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                'db_table': 'contentitem_pages_columnsitem',
                'verbose_name': 'Text in columns',
                'verbose_name_plural': 'Text in columns',
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
