# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-20 10:28


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_columnsitem'),
        ('pages', '0011_auto_20200106_1647'),
    ]

    operations = [
    ]
