# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-28 12:08


from django.db import migrations, models
import django.db.models.deletion
import fluent_contents.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0001_initial'),
        ('pages', '0013_merge_20200120_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTextRoundItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('text', fluent_contents.extensions.PluginHtmlField(blank=True, verbose_name='text')),
                ('text_final', models.TextField(blank=True, editable=False, null=True)),
                ('image', fluent_contents.extensions.PluginImageField(verbose_name='Image')),
            ],
            options={
                'db_table': 'contentitem_pages_imagetextrounditem',
                'verbose_name': 'Text + Round Image',
                'verbose_name_plural': 'Text + Round Image',
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
