# Generated by Django 3.2.20 on 2023-09-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_imagetextrounditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_title',
            field=models.BooleanField(default=True, help_text='Show the title of this page in the header'),
        ),
    ]
