# Generated by Django 4.2.20 on 2025-03-20 08:50

import bluebottle.utils.validators
from django.db import migrations, models
import fluent_contents.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20230921_1242'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actionitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='documentitem',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='document',
            field=models.FileField(upload_to='pages', validators=[bluebottle.utils.validators.FileMimetypeValidator(['application/pdf', 'application/zip', 'image/jpeg', 'image/png', 'image/gif', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='imagetextitem',
            name='align',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=10, verbose_name='Picture placement'),
        ),
        migrations.AlterField(
            model_name='imagetextitem',
            name='image',
            field=fluent_contents.extensions.PluginImageField(validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imagetextrounditem',
            name='image',
            field=fluent_contents.extensions.PluginImageField(validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('en', 'English')], max_length=7, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='page',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], db_index=True, default='draft', max_length=20, verbose_name='status'),
        ),
    ]
