# Generated by Django 4.2.20 on 2025-05-08 09:01

import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import fluent_contents.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0002_alter_contentitem_polymorphic_ctype'),
        ('pages', '0015_auto_20230921_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaledImageTextItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.contentitem')),
                ('text', fluent_contents.extensions.PluginHtmlField(blank=True, verbose_name='text')),
                ('image', fluent_contents.extensions.PluginImageField(validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Text + Scaled Image',
                'verbose_name_plural': 'Text + Scaled Image',
                'db_table': 'contentitem_pages_scaledimagetextitem',
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
