# Generated by Django 4.2.20 on 2025-05-08 09:16

import bluebottle.utils.validators
from django.db import migrations, models
import fluent_contents.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_scaledimagetextitem_alter_actionitem_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaledimagetextitem',
            name='align',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10, verbose_name='Picture placement'),
        ),
    ]
