# Generated by Django 4.2.20 on 2025-11-17 00:00

from django.db import migrations, connection

from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)

    with LocalTenant(tenant):
        pages_permissions = {
            'Staff': {
                'perms': (
                    'add_page', 'change_page', 'delete_page',
                    'add_documentitem', 'change_documentitem', 'delete_documentitem',
                    'add_actionitem', 'change_actionitem', 'delete_actionitem',
                    'add_columnsitem', 'change_columnsitem', 'delete_columnsitem',
                    'add_imagetextitem', 'change_imagetextitem', 'delete_imagetextitem',
                    'add_imagetextrounditem', 'change_imagetextrounditem', 'delete_imagetextrounditem',
                    'add_scaledimagetextitem', 'change_scaledimagetextitem', 'delete_scaledimagetextitem',
                )
            },
        }

        update_group_permissions('pages', pages_permissions, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_actionitem_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions, migrations.RunPython.noop)
    ]

