# Generated by Django 4.2.20 on 2025-10-27 13:45

import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import fluent_contents.extensions
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_actionitem_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('Start', 'Start initiative/activity'), ('terms', 'Terms of service'), ('privacy', 'Privacy policy')], default='Start', unique=True, verbose_name='Page type')),
            ],
            options={
                'permissions': (('api_read_platformpage', 'Can view platform pages through the API'), ('api_add_platformpage', 'Can add platform pages through the API'), ('api_change_platformpage', 'Can change platform pages through the API'), ('api_delete_platformpage', 'Can delete platform pages through the API')),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PlatformPageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.platformpage')),
            ],
            options={
                'verbose_name': 'platform page Translation',
                'db_table': 'pages_platformpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
