# Generated by Django 4.2.20 on 2025-09-05 09:08
from django.db import migrations
import json
from django.db.utils import IntegrityError


def migrate_text_items(apps, schema_editor):
    TextItem = apps.get_model('text', 'TextItem')
    TextOnlyItem = apps.get_model('pages', 'TextOnlyItem')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentItem = apps.get_model('fluent_contents', 'ContentItem')
    content_type = ContentType.objects.get_for_model(TextOnlyItem)

    for text_item in TextItem.objects.all():
        text = text_item.text
        contentitem_ptr_id = text_item.contentitem_ptr_id
        content_item = text_item.contentitem_ptr
        parent_id = text_item.parent_id
        text_item.delete()
        TextOnlyItem.objects.create(
            contentitem_ptr_id=contentitem_ptr_id,
            polymorphic_ctype_id=content_type.id,
            parent_type_id=text_item.parent_type_id,
            parent_id=parent_id,
            text=json.dumps({"html": text, "delta": ""}),
        )
        content_item.polymorphic_ctype_id = content_type.id
        content_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_textonlyitem_alter_imagetextitem_options_and_more'),
        ('cms', '0104_alter_imageplaintextitem_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_text_items, migrations.RunPython.noop),
    ]
