# Generated by Django 4.2.20 on 2025-10-27 13:25
from bluebottle.pages.models import PageTypeChoices
from django.db import migrations, connection

from bluebottle.clients import properties
from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant


def migrate_start_page(apps, schema_editor):
    Page = apps.get_model('pages', 'Page')
    PlatformPage = apps.get_model('pages', 'PlatformPage')
    Language = apps.get_model('utils', 'Language')
    SitePlatformSettings = apps.get_model('cms', 'SitePlatformSettings')
    SitePlatformSettingsTrans = apps.get_model('cms', 'SitePlatformSettingsTranslation')

    from fluent_contents.models import Placeholder, ContentItem

    slot = 'blog_contents'

    slugs = ['start', 'privacy', 'terms']

    mapping = {
        ('start', 'start'),
        ('terms', 'terms'),
        ('privacy', 'privacy'),
        ('terms-and-conditions', 'terms'),
        ('privacy-policy', 'privacy'),
        ('algemene-voorwaarden', 'terms'),
        ('impact-fonds', 'start'),
    }

    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)

    with LocalTenant(tenant):
        for old_slug, new_slug in mapping:
            new_page, created = PlatformPage.objects.get_or_create(slug=new_slug)
            title = PageTypeChoices.get_choice(new_slug).label
            if created:
                new_page.set_current_language(properties.LANGUAGE_CODE, initialize=True)
                new_page.title = title
                new_page.save()

            for lang in Language.objects.all():
                lang_code = lang.code
                if new_slug == 'start':
                    settings, _ = SitePlatformSettings.objects.get_or_create()
                    settings_trans = SitePlatformSettingsTrans.objects.filter(master_id=settings.id,
                                                                              language_code=lang_code).first()
                    settings_fallback = SitePlatformSettingsTrans.objects.filter(master_id=settings.id,
                                                                                 start_page__gt='').first()
                    if settings_fallback and settings_fallback.start_page:
                        old_slug = settings_fallback.start_page
                    if settings_trans and settings_trans.start_page:
                        old_slug = settings_trans.start_page

                print(f"Language {lang_code}, using page '{old_slug}'")
                src_page = Page.objects.filter(language=lang_code, slug=old_slug).first()
                if not src_page:
                    continue

                try:
                    src_ph = Placeholder.objects.get_by_slot(src_page, slot)
                except Placeholder.DoesNotExist:
                    continue

                new_page.set_current_language(lang_code)

                if not new_page.has_translation(lang_code):
                    new_page.create_translation(lang_code)


                title = getattr(src_page, 'title', '') or new_page.safe_translation_getter('title', default='')
                if title == 'Terms and conditions':
                    title = 'Terms of service'
                new_page.title = title
                new_page.save()

                try:
                    dst_ph = Placeholder.objects.get_by_slot(new_page, slot)
                except Placeholder.DoesNotExist:
                    dst_ph = Placeholder.objects.create_for_object(new_page, slot)

                items = (
                    ContentItem.objects
                    .filter(placeholder=src_ph)
                    .order_by('sort_order', 'pk')
                )
                for item in items:
                    new_item = item.copy_to_placeholder(dst_ph)
                    new_item.language_code = lang_code
                    new_item.save()



class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0018_platformpage'),
    ]

    operations = [
        migrations.RunPython(
            migrate_start_page,
            migrations.RunPython.noop
        ),
    ]
