# Generated by Django 4.2.20 on 2025-11-17 00:00

from django.db import migrations


def remove_reserved_slug_pages(apps, schema_editor):
    """Remove pages with reserved slugs that should be platform pages"""
    Page = apps.get_model('pages', 'Page')
    
    reserved_slugs = ['terms', 'terms-and-conditions', 'privacy', 'start']
    
    # Delete pages with reserved slugs
    deleted_count = Page.objects.filter(slug__in=reserved_slugs).delete()
    
    if deleted_count[0] > 0:
        print(f"Deleted {deleted_count[0]} page(s) with reserved slugs: {', '.join(reserved_slugs)}")


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20251027_1425'),
    ]

    operations = [
        migrations.RunPython(remove_reserved_slug_pages, migrations.RunPython.noop)
    ]

