# Generated by Django 4.2.20 on 2025-09-08 13:00

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20250908_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnsitem',
            name='text1',
            field=django_quill.fields.QuillField(blank=True, verbose_name='text left'),
        ),
        migrations.AlterField(
            model_name='columnsitem',
            name='text2',
            field=django_quill.fields.QuillField(blank=True, verbose_name='text right'),
        ),
        migrations.AlterField(
            model_name='imagetextitem',
            name='text',
            field=django_quill.fields.QuillField(blank=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='imagetextrounditem',
            name='text',
            field=django_quill.fields.QuillField(blank=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='scaledimagetextitem',
            name='text',
            field=django_quill.fields.QuillField(blank=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='textonlyitem',
            name='text',
            field=django_quill.fields.QuillField(blank=True, verbose_name='text'),
        ),
    ]
