# Generated by Django 4.2.20 on 2025-11-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_add_staff_page_content_permissions'),
        ('pages', '0020_remove_reserved_slug_pages'),
    ]

    operations = [
    ]
