# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 13:54
from __future__ import unicode_literals

import django.core.files.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='registration',
            field=models.FileField(blank=True, null=True,
                                   storage=django.core.files.storage.FileSystemStorage(
                                       location=settings.PRIVATE_MEDIA_ROOT),
                                   upload_to=b'organizations/registrations'),
        ),
    ]
