# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 09:57
from __future__ import unicode_literals

from django.db import migrations


def remove_duplicates(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    OrganizationMember = apps.get_model('organizations', 'OrganizationMember')
    Project = apps.get_model('projects', 'Project')

    def merge(master, organizations):
        """ Merge `organizations` into  `organization`.
        Makes sure that all foreign keys point to `organization`.

        Deletes all organization models in `organization` after merging.

        This duplicate `Organization.merge` since django migration do not give access to
        model methods.
        """
        for organization in organizations:
            for member in OrganizationMember.objects.filter(organization=organization):
                member.organization = master
                member.save()

            for project in Project.objects.filter(organization=organization):
                project.organization = master
                project.save()

            organization.delete()

    for organization in Organization.objects.all():
        try:
            Organization.objects.get(pk=organization.pk)
        except Organization.DoesNotExist:
            continue

        matches = Organization.objects.filter(
            name=organization.name,
            email=organization.email,
            website=organization.website,
            phone_number=organization.phone_number
        ).exclude(pk=organization.pk)

        if matches:
            merge(organization, matches)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20160610_1554'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates)
    ]
