# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationcontact'),
        ('organizations', '0003_auto_20170303_1057'),
    ]

    operations = [
    ]
