# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_merge_20170321_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontact',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
