# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20171114_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationcontact',
            options={'verbose_name': 'Partner Organization Contact', 'verbose_name_plural': 'Partner Organization Contacts'},
        ),
    ]
