# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_remove_organizationcontact_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='organizationcontact',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='organizationcontact',
            name='phone',
            field=models.TextField(blank=True, max_length=40, null=True, verbose_name='phone'),
        ),
    ]
