# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-09 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_auto_20190708_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcontact',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
