# Generated by Django 4.2.20 on 2025-07-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_auto_20241106_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
