# Generated by Django 4.2.20 on 2025-09-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_organization_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
    ]
