# Generated by Django 4.2.20 on 2025-10-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'organisation', 'verbose_name_plural': 'organisations'},
        ),
    ]
