# Generated by Django 4.2.20 on 2025-10-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0040_alter_follow_default_owner'),
        ('organizations', '0019_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'organisation', 'verbose_name_plural': 'organisations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='activity_pub.organization'),
        ),
    ]
