# Generated by Django 4.2.20 on 2025-12-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organization_options'),
        ('organizations', '0020_alter_organization_options_organization_origin'),
    ]

    operations = [
    ]
