# Generated by Django 4.2.20 on 2025-12-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_merge_20251219_1056'),
        ('organizations', '0021_merge_20251223_1051'),
    ]

    operations = [
    ]
