# Generated by Django 4.2.20 on 2026-04-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_merge_20251223_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='origin',
            new_name='origin_old',
        ),
    ]
