# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskfile',
            options={'verbose_name': 'task file', 'verbose_name_plural': 'task files'},
        ),
        migrations.AlterModelOptions(
            name='taskmember',
            options={'verbose_name': 'task member', 'verbose_name_plural': 'task members'},
        ),
    ]
