# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20160621_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='name_nl',
        ),
        migrations.AddField(
            model_name='skill',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='disabled'),
        ),
    ]
