# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20160720_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
