# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 21:37
from __future__ import unicode_literals

from django.utils import timezone
from django.db import migrations


def reschedule_tasks(apps, schema_editor):
    # Reschedule tasks to make sure deadlines are at the right date/time
    Task = apps.get_model("tasks", "Task")
    for task in Task.objects.all():
        task.deadline = task.deadline - timezone.timedelta(hours=2)
        task.save()

def restore_schedule_tasks(apps, schema_editor):
    # Reschedule tasks to make sure deadlines are at the right date/time
    Task = apps.get_model("tasks", "Task")
    for task in Task.objects.all():
        task.deadline = task.deadline + timezone.timedelta(hours=2)
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_fix_deadline_timestamp'),
    ]

    operations = [
        migrations.RunPython(reschedule_tasks, restore_schedule_tasks)
    ]


