# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_fix_deadline_timestamp'),
        ('tasks', '0006_auto_20160718_1811'),
        ('tasks', '0008_auto_20160802_1441'),
    ]

    operations = [
    ]
