# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 21:37
from __future__ import unicode_literals

from pytz import timezone
from django.db import migrations


def reschedule_tasks(apps, schema_editor):
    # Change task deadline to server timezone
    Task = apps.get_model("tasks", "Task")
    for task in Task.objects.all():
        deadline = timezone('Europe/Amsterdam').localize(task.deadline.replace(tzinfo=None))
        task.deadline = deadline
        task.save()


def restore_schedule_tasks(apps, schema_editor):
    # Change task deadline back to UTC.
    Task = apps.get_model("tasks", "Task")
    for task in Task.objects.all():
        deadline = timezone('UTC').localize(task.deadline.replace(tzinfo=None))
        task.deadline = deadline
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_fix_deadline_timestamp'),
    ]

    operations = [
        migrations.RunPython(reschedule_tasks, restore_schedule_tasks)
    ]


