# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20160919_1508'),
        ('tasks', '0011_auto_20160920_1019'),
    ]

    operations = [
    ]
