# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_merge'),
        ('tasks', '0012_merge'),
    ]

    operations = [
    ]
