# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[(b'ongoing', 'Ongoing (with deadline)'), (b'event', 'Event (on set date)')], default=b'ongoing', max_length=20, verbose_name='type'),
        ),
    ]
