# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20161006_1813'),
        ('tasks', '0013_merge'),
    ]

    operations = [
    ]
