# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(help_text='Deadline or event date', verbose_name='deadline'),
        ),
    ]
