# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_deadline_to_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(b'open', 'Open'), (b'full', 'Full'), (b'in progress', 'Running'), (b'realized', 'Realised'), (b'closed', 'Closed')], default=b'open', max_length=20, verbose_name='status'),
        ),
    ]
