# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_remove_task_deadline_to_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_to_apply',
            field=models.DateTimeField(help_text='Deadline to apply', null=True, verbose_name='deadline_to_apply'),
        ),
    ]
