# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_skill_expertise'),
        ('tasks', '0022_task_accepting'),
    ]

    operations = [
    ]
