# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-15 13:33
from __future__ import unicode_literals

from django.db import migrations, models


def set_no_skill_no_expertise(apps, schema_editor):
    # Currently Skill=1 is the only non-expertise based skill
    skill = apps.get_model('tasks', 'Skill')
    skill.objects.filter(id=1).update(expertise=False)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_task_accepting'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='expertise',
            field=models.BooleanField(default=True, help_text='Is this skill expertise based, or could anyone do it?', verbose_name='expertise'),
        ),
        migrations.RunPython(set_no_skill_no_expertise),
    ]
