# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-29 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_taskmember_resume'),
        ('tasks', '0023_merge_20170519_1012'),
    ]

    operations = [
    ]
