# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-01 13:40
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_merge_20170529_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='needs_motivation',
            field=models.BooleanField(default=False, help_text='Indicates if a task candidate needs to submit a motivation', verbose_name='Needs motivation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_to_apply',
            field=models.DateTimeField(help_text='Deadline to apply', verbose_name='Deadline to apply'),
        ),
        migrations.AlterField(
            model_name='taskmember',
            name='resume',
            field=bluebottle.utils.fields.PrivateFileField(blank=True, upload_to=b'private/private/private/task-members/resume'),
        ),
    ]
