# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-28 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_auto_20170602_2304'),
        ('tasks', '0025_auto_20170601_1540'),
    ]

    operations = [
    ]
