# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_merge_20170628_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_status_change',
        ),
    ]
