# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-04 09:55
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_delete_tasks_date_status_changed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created'], 'permissions': (('api_read_task', 'Can view tasks through the API'), ('api_add_task', 'Can add tasks through the API'), ('api_change_task', 'Can change tasks through the API'), ('api_delete_task', 'Can delete tasks through the API')), 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskmember',
            options={'permissions': (('api_read_taskmember', 'Can view taskmembers through the API'), ('api_add_taskmember', 'Can add taskmembers through the API'), ('api_change_taskmember', 'Can change taskmembers through the API'), ('api_delete_taskmember', 'Can delete taskmembers through the API')), 'verbose_name': 'task member', 'verbose_name_plural': 'task members'},
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, help_text='Task location (leave empty for anywhere/online)', max_length=200, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='taskmember',
            name='resume',
            field=bluebottle.utils.fields.PrivateFileField(blank=True, upload_to=b'private/private/private/task-members/resume'),
        ),
    ]
