# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 14:14
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'add_task', 'change_task', 'delete_task',
                'add_taskmember', 'change_taskmember', 'delete_taskmember',
                'add_taskfile', 'change_taskfile', 'delete_taskfile',
                'add_skill', 'change_skill', 'delete_skill',
            )
        },
        'Anonymous': {
            'perms': ('api_read_task',)
        },
        'Authenticated': {
            'perms': (
                'api_read_task', 'api_add_task', 'api_change_task',
                'api_read_taskmember', 'api_add_taskmember',
                'api_change_taskmember', 'api_delete_taskmember',
            )
        }
    }
    update_group_permissions('tasks', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_add_api_permissions'),
    ]

    operations = [
            migrations.RunPython(add_group_permissions)
    ]
