# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_add_skill_permission'),
        ('tasks', '0028_auto_20170817_1546'),
    ]

    operations = [
    ]
