# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_more_owner_permissions'),
        ('tasks', '0029_fix_migration_statuslog_creation_20170721_1329'),
    ]

    operations = [
    ]
