# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 09:56
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_merge_20170831_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmember',
            name='resume',
            field=bluebottle.utils.fields.PrivateFileField(blank=True, upload_to=b'private/task-members/resume'),
        ),
    ]
