# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 13:54
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_auto_20171005_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmember',
            name='resume',
            field=bluebottle.utils.fields.PrivateFileField(blank=True, upload_to=b'private/private/private/task-members/resume'),
        ),
    ]
