# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_auto_20171010_1554'),
        ('tasks', '0036_auto_20171114_1056'),
    ]

    operations = [
    ]
