# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_migrate_skill_translations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skilltranslation',
            old_name='_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        )
    ]
