# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-23 10:36
from __future__ import unicode_literals

from datetime import timedelta

from django.db import migrations, connection, models
from django.utils.text import slugify
from django.contrib.gis.geos import Point


from bluebottle.clients import properties


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_remove_untranslated_fields'),
        ('assignments', '0011_applicant_document'),
        ('events', '0015_auto_20200226_0838'),
        ('wallposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='activity_id',
            field=models.IntegerField(null=True),
        ),
    ]
