# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-02 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_auto_20210302_0827'),
    ]

    operations = [
    ]
