# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-02 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0044_auto_20210302_0936'),
        ('members', '0040_auto_20210302_0836'),
        ('time_based', '0060_auto_20210302_0905'),
        ('surveys', '0035_auto_20210302_1020'),
    ]

    state_operations = [
        migrations.DeleteModel('Task'),
        migrations.DeleteModel('TaskStatusLog'),
        migrations.DeleteModel('TaskFile'),
        migrations.DeleteModel('TaskMember'),
        migrations.DeleteModel('TaskMemberStatusLog'),
        migrations.DeleteModel('Skill'),
        migrations.DeleteModel('SkillTranslation')
    ]

    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=state_operations
      )
    ]
