# Generated by Django 4.2.20 on 2025-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0003_auto_20180907_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='termsagreement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
