# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-06 13:07


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funding', '0054_auto_20200610_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelesomBankAccount',
            fields=[
                ('bankaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funding.BankAccount')),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Telesom bank account',
                'verbose_name_plural': 'Telesom bank accounts',
            },
            bases=('funding.bankaccount',),
        ),
        migrations.CreateModel(
            name='TelesomPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funding.Payment')),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_name', models.CharField(blank=True, max_length=30, null=True)),
                ('unique_id', models.CharField(max_length=30)),
                ('reference_id', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_amount', models.CharField(max_length=100)),
                ('issuer_transaction_id', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('funding.payment',),
        ),
        migrations.CreateModel(
            name='TelesomPaymentProvider',
            fields=[
                ('paymentprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='funding.PaymentProvider')),
                ('merchant_uid', models.CharField(max_length=100)),
                ('api_user_id', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
                ('api_url', models.CharField(default=b'https://sandbox.safarifoneict.com/asm/', max_length=100)),
                ('prefix', models.CharField(default=b'goodup', max_length=10)),
            ],
            options={
                'verbose_name': 'Telesom payment provider',
            },
            bases=('funding.paymentprovider',),
        ),
    ]
