# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-07 07:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_telesom', '0003_telesompayment_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telesompayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=12),
        ),
    ]
