# Generated by Django 4.2.20 on 2025-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_telesom', '0005_auto_20201207_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telesompayment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='telesompayment',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
