from bluebottle.fsm.effects import RelatedTransitionEffect, TransitionEffect
from bluebottle.fsm.triggers import (
    register,
    TransitionTrigger,
    TriggerManager,
    ModelDeletedTrigger
)
from bluebottle.notifications.effects import NotificationEffect
from bluebottle.time_based.effects.teams import (
    CreateTeamRegistrationEffect,
    CreateCaptainTeamMemberEffect,
    CreateTeamSlotEffect,
    CreateTeamMemberSlotParticipantsEffect,
    DeleteTeamMemberSlotParticipantsEffect,
)
from bluebottle.time_based.models import Team, TeamMember
from bluebottle.time_based.states.participants import (
    TeamScheduleParticipantStateMachine,
)
from bluebottle.time_based.states.slots import TeamScheduleSlotStateMachine
from bluebottle.time_based.states.teams import TeamStateMachine, TeamMemberStateMachine
from bluebottle.time_based.notifications.teams import (
    ManagerTeamRemovedNotification,
    UserTeamRemovedNotification,
    UserTeamWithdrewNotification,
    ManagerTeamWithdrewNotification,
    UserTeamScheduledNotification,
    CaptainTeamMemberWithdrewNotification,
    UserTeamMemberWithdrewNotification,
    CaptainTeamMemberRemovedNotification,
    UserTeamMemberRemovedNotification,
)


@register(Team)
class TeamTriggers(TriggerManager):
    def should_auto_accept(effect):
        """ Check if the team should be auto accepted """
        return not effect.instance.activity.review

    triggers = [
        TransitionTrigger(
            TeamStateMachine.initiate,
            effects=[
                CreateTeamSlotEffect,
                CreateCaptainTeamMemberEffect,
                CreateTeamRegistrationEffect,
                TransitionEffect(
                    TeamStateMachine.accept, conditions=[should_auto_accept]
                ),
            ],
        ),
        TransitionTrigger(
            TeamStateMachine.reject,
            effects=[
                RelatedTransitionEffect(
                    "team_members",
                    TeamMemberStateMachine.reject,
                ),
            ],
        ),
        TransitionTrigger(
            TeamStateMachine.accept,
            effects=[
                RelatedTransitionEffect(
                    "team_members",
                    TeamMemberStateMachine.accept,
                ),
            ],
        ),
        TransitionTrigger(
            TeamStateMachine.withdraw,
            effects=[
                RelatedTransitionEffect(
                    "team_members",
                    TeamMemberStateMachine.withdraw,
                ),
                NotificationEffect(UserTeamWithdrewNotification),
                NotificationEffect(ManagerTeamWithdrewNotification),
            ],
        ),
        TransitionTrigger(
            TeamStateMachine.rejoin,
            effects=[
                RelatedTransitionEffect(
                    "team_members",
                    TeamMemberStateMachine.reapply,
                ),
            ],
        ),
        TransitionTrigger(
            TeamStateMachine.remove,
            effects=[
                RelatedTransitionEffect(
                    "team_members",
                    TeamMemberStateMachine.remove,
                ),
                NotificationEffect(UserTeamRemovedNotification),
                NotificationEffect(ManagerTeamRemovedNotification),
            ],
        ),
        TransitionTrigger(
            TeamStateMachine.schedule,
            effects=[
                NotificationEffect(UserTeamScheduledNotification),
            ],
        ),
        TransitionTrigger(
            TeamStateMachine.readd,
            effects=[
                RelatedTransitionEffect(
                    "team_members",
                    TeamMemberStateMachine.readd,
                ),
            ],
        ),
        TransitionTrigger(
            TeamStateMachine.cancel,
            effects=[
                RelatedTransitionEffect(
                    "slots",
                    TeamScheduleSlotStateMachine.cancel,
                ),
                RelatedTransitionEffect(
                    "team_members",
                    TeamMemberStateMachine.cancel,
                ),
            ],
        ),
        TransitionTrigger(
            TeamStateMachine.restore,
            effects=[
                RelatedTransitionEffect(
                    "slots",
                    TeamScheduleSlotStateMachine.restore,
                ),
                RelatedTransitionEffect(
                    "team_members",
                    TeamMemberStateMachine.restore,
                ),
            ],
        ),
        TransitionTrigger(
            TeamStateMachine.withdraw,
            effects=[
                RelatedTransitionEffect(
                    "slots",
                    TeamScheduleSlotStateMachine.cancel,
                ),
                RelatedTransitionEffect(
                    "team_members",
                    TeamMemberStateMachine.cancel,
                ),
            ],
        ),
        TransitionTrigger(
            TeamStateMachine.rejoin,
            effects=[
                RelatedTransitionEffect(
                    "slots",
                    TeamScheduleSlotStateMachine.restore,
                ),
                RelatedTransitionEffect(
                    "team_members",
                    TeamMemberStateMachine.restore,
                ),
            ],
        ),
        TransitionTrigger(
            TeamStateMachine.cancel,
            effects=[
                RelatedTransitionEffect(
                    'slots',
                    TeamScheduleSlotStateMachine.cancel,
                ),
                RelatedTransitionEffect(
                    'team_members',
                    TeamMemberStateMachine.cancel,
                )
            ]
        ),
        TransitionTrigger(
            TeamStateMachine.restore,
            effects=[
                RelatedTransitionEffect(
                    'slots',
                    TeamScheduleSlotStateMachine.restore,
                ),
                RelatedTransitionEffect(
                    'team_members',
                    TeamMemberStateMachine.restore,
                )
            ]
        ),
        TransitionTrigger(
            TeamStateMachine.withdraw,
            effects=[
                RelatedTransitionEffect(
                    'slots',
                    TeamScheduleSlotStateMachine.cancel,
                ),
                RelatedTransitionEffect(
                    'team_members',
                    TeamMemberStateMachine.cancel,
                )
            ]
        ),
        TransitionTrigger(
            TeamStateMachine.rejoin,
            effects=[
                RelatedTransitionEffect(
                    'slots',
                    TeamScheduleSlotStateMachine.restore,
                ),
                RelatedTransitionEffect(
                    'team_members',
                    TeamMemberStateMachine.restore,
                )
            ]
        ),
    ]


@register(TeamMember)
class TeamMemberTriggers(TriggerManager):
    triggers = [
        TransitionTrigger(
            TeamMemberStateMachine.initiate,
            effects=[
                CreateTeamMemberSlotParticipantsEffect,
            ]
        ),
        TransitionTrigger(
            TeamMemberStateMachine.withdraw,
            effects=[
                RelatedTransitionEffect(
                    'participants',
                    TeamScheduleParticipantStateMachine.withdraw,
                ),
                NotificationEffect(CaptainTeamMemberWithdrewNotification),
                NotificationEffect(UserTeamMemberWithdrewNotification),
            ],
        ),
        TransitionTrigger(
            TeamMemberStateMachine.reapply,
            effects=[
                RelatedTransitionEffect(
                    'participants',
                    TeamScheduleParticipantStateMachine.restore,
                )
            ]
        ),
        TransitionTrigger(
            TeamMemberStateMachine.cancel,
            effects=[
                RelatedTransitionEffect(
                    'participants',
                    TeamScheduleParticipantStateMachine.cancel,
                )
            ]
        ),
        TransitionTrigger(
            TeamMemberStateMachine.restore,
            effects=[
                RelatedTransitionEffect(
                    'participants',
                    TeamScheduleParticipantStateMachine.restore,
                )
            ]
        ),
        ModelDeletedTrigger(
            effects=[
                DeleteTeamMemberSlotParticipantsEffect,
            ]
        ),
        TransitionTrigger(
            TeamMemberStateMachine.withdraw,
            effects=[
                RelatedTransitionEffect(
                    "participants",
                    TeamScheduleParticipantStateMachine.withdraw,
                ),
            ],
        ),
        TransitionTrigger(
            TeamMemberStateMachine.reapply,
            effects=[
                RelatedTransitionEffect(
                    "participants",
                    TeamScheduleParticipantStateMachine.reapply,
                ),
            ],
        ),
        TransitionTrigger(
            TeamMemberStateMachine.remove,
            effects=[
                RelatedTransitionEffect(
                    "participants",
                    TeamScheduleParticipantStateMachine.remove,
                ),
                NotificationEffect(CaptainTeamMemberRemovedNotification),
                NotificationEffect(UserTeamMemberRemovedNotification),
            ],
        ),
        TransitionTrigger(
            TeamMemberStateMachine.readd,
            effects=[
                RelatedTransitionEffect(
                    "participants",
                    TeamScheduleParticipantStateMachine.readd,
                ),
            ],
        ),
    ]
