# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-09 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170803_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'permissions': (('api_read_news_item', 'Can view news items through the API'), ('api_add_news_item', 'Can add news items through the API'), ('api_change_news_item', 'Can change news items through the API'), ('api_delete_news_item', 'Can delete news items through the API')), 'verbose_name': 'news item', 'verbose_name_plural': 'news items'},
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
