# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180709_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='publication_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text="To go live, status must be 'Published'.", null=True, verbose_name='publication date'),
        ),
    ]
