# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-14 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onadateactivity',
            options={'permissions': (('api_read_onadateactivity', 'Can view on a date activities through the API'), ('api_add_onadateactivity', 'Can add on a date activities through the API'), ('api_change_onadateactivity', 'Can change on a date activities through the API'), ('api_delete_onadateactivity', 'Can delete on a date activities through the API'), ('api_read_own_onadateactivity', 'Can view own on a date activities through the API'), ('api_add_own_onadateactivity', 'Can add own on a date activities through the API'), ('api_change_own_onadateactivity', 'Can change own on a date activities through the API'), ('api_delete_own_onadateactivity', 'Can delete own on a date activities through the API')), 'verbose_name': 'On a date activity', 'verbose_name_plural': 'On A Date Activities'},
        ),
        migrations.AlterModelOptions(
            name='ongoingactivity',
            options={'permissions': (('api_read_ongoingactivity', 'Can view ongoing activities through the API'), ('api_add_ongoingactivity', 'Can add ongoing activities through the API'), ('api_change_ongoingactivity', 'Can change ongoing activities through the API'), ('api_delete_ongoingactivity', 'Can delete ongoing activities through the API'), ('api_read_own_ongoingactivity', 'Can view own ongoing activities through the API'), ('api_add_own_ongoingactivity', 'Can add own ongoing activities through the API'), ('api_change_own_ongoingactivity', 'Can change own ongoing activities through the API'), ('api_delete_own_ongoingactivity', 'Can delete own ongoing activities through the API')), 'verbose_name': 'Ongoing activity', 'verbose_name_plural': 'Ongoing activities'},
        ),
        migrations.AlterModelOptions(
            name='withadeadlineactivity',
            options={'permissions': (('api_read_withadeadlineactivity', 'Can view activities with a deadline through the API'), ('api_add_withadeadlineactivity', 'Can add activities with a deadline through the API'), ('api_change_withadeadlineactivity', 'Can change activities with a deadline through the API'), ('api_delete_withadeadlineactivity', 'Can delete activities with a deadline through the API'), ('api_read_own_withadeadlineactivity', 'Can view own activities with a deadline through the API'), ('api_add_own_withadeadlineactivity', 'Can add own activities with a deadline through the API'), ('api_change_own_withadeadlineactivity', 'Can change own activities with a deadline through the API'), ('api_delete_own_withadeadlineactivity', 'Can delete own activities with a deadline through the API')), 'verbose_name': 'Activity with a deadline', 'verbose_name_plural': 'Activities with a deadline'},
        ),
    ]
