# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0003_auto_20201014_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingactivity',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='ongoingactivity',
            name='duration_period',
            field=models.CharField(blank=True, choices=[('overall', 'overall'), ('week', 'per week'), ('month', 'per month')], max_length=20, null=True, verbose_name='duration period'),
        ),
        migrations.AddField(
            model_name='withadeadlineactivity',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='withadeadlineactivity',
            name='duration_period',
            field=models.CharField(blank=True, choices=[('overall', 'overall'), ('week', 'per week'), ('month', 'per month')], max_length=20, null=True, verbose_name='duration period'),
        ),
    ]
