# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-21 11:15
from __future__ import unicode_literals

import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20201021_1315'),
        ('time_based', '0004_auto_20201014_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('contribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Contribution')),
                ('motivation', models.TextField(blank=True)),
                ('document', bluebottle.files.fields.PrivateDocumentField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.PrivateDocument')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Application',
                'permissions': (('api_read_application', 'Can view application through the API'), ('api_add_application', 'Can add application through the API'), ('api_change_application', 'Can change application through the API'), ('api_delete_application', 'Can delete application through the API'), ('api_read_own_application', 'Can view own application through the API'), ('api_add_own_application', 'Can add own application through the API'), ('api_change_own_application', 'Can change own application through the API'), ('api_delete_own_application', 'Can delete own application through the API')),
            },
            bases=('activities.contribution',),
        ),
    ]
