# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 09:59
from __future__ import unicode_literals

from django.db import migrations, connection

from bluebottle.utils.utils import update_group_permissions

from bluebottle.clients import properties
from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        group_perms = {
            'Staff': {
                'perms': (
                    'add_application', 'change_application', 'delete_application',
                )
            },
            'Anonymous': {
                'perms': (
                    'api_read_application',
                ) if not properties.CLOSED_SITE else ()
            },
            'Authenticated': {
                'perms': (
                    'api_read_application', 'api_add_application', 'api_change_own_application', 'api_delete_own_application',
                )
            }
    }

    update_group_permissions('time_based', group_perms, apps)

class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0005_application'),
    ]

    operations = [
        migrations.RunPython(
            add_group_permissions,
            migrations.RunPython.noop
        )
    ]
