# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-23 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0006_auto_20201021_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingactivity',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start of activity'),
        ),
        migrations.AddField(
            model_name='withadeadlineactivity',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start of activity'),
        ),
        migrations.AlterField(
            model_name='onadateactivity',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='activity date'),
        ),
        migrations.AlterField(
            model_name='ongoingactivity',
            name='duration_period',
            field=models.CharField(blank=True, choices=[('overall', 'overall'), ('day', 'per day'), ('week', 'per week'), ('month', 'per month')], max_length=20, null=True, verbose_name='duration period'),
        ),
        migrations.AlterField(
            model_name='withadeadlineactivity',
            name='duration_period',
            field=models.CharField(blank=True, choices=[('overall', 'overall'), ('day', 'per day'), ('week', 'per week'), ('month', 'per month')], max_length=20, null=True, verbose_name='duration period'),
        ),
    ]
