# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0007_auto_20201023_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingactivity',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Start of activity'),
        ),
        migrations.AlterField(
            model_name='withadeadlineactivity',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Start of activity'),
        ),
    ]
