# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-26 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_contributionvalue'),
        ('time_based', '0008_auto_20201023_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionDuration',
            fields=[
                ('contributionvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.ContributionValue')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='duration')),
                ('duration_period', models.CharField(blank=True, choices=[('overall', 'overall'), ('day', 'per day'), ('week', 'per week'), ('month', 'per month')], max_length=20, null=True, verbose_name='duration period')),
            ],
            options={
                'abstract': False,
            },
            bases=('activities.contributionvalue',),
        ),
        migrations.AlterField(
            model_name='withadeadlineactivity',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='start'),
        ),
    ]
