# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-28 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0011_auto_20201028_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongoingactivity',
            name='duration',
        ),
        migrations.AddField(
            model_name='ongoingactivity',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.RemoveField(
            model_name='withadeadlineactivity',
            name='duration',
        ),

        migrations.AddField(
            model_name='withadeadlineactivity',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='duration'),
        ),
    ]
