# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-28 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0012_auto_20201028_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withadeadlineactivity',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='deadline'),
        ),
    ]
