# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-30 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0017_auto_20201029_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duration',
            name='period_duration',
        ),
        migrations.AddField(
            model_name='duration',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='end'),
        ),
    ]
