# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-30 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0018_auto_20201030_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='start',
            field=models.DateField(verbose_name='start'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duration',
            name='value',
            field=models.DurationField(verbose_name='value'),
            preserve_default=False,
        ),
    ]
