# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 09:59
from __future__ import unicode_literals

from django.db import migrations, connection

from bluebottle.utils.utils import update_group_permissions

from bluebottle.clients import properties
from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        group_perms = {
            'Staff': {
                'perms': (
                    'add_dateactivity', 'change_dateactivity', 'delete_dateactivity',
                    'add_periodactivity', 'change_periodactivity', 'delete_periodactivity',
                )
            },
            'Anonymous': {
                'perms': (
                    'api_read_dateactivity',
                    'api_read_periodactivity',
                ) if not properties.CLOSED_SITE else ()
            },
            'Authenticated': {
                'perms': (
                    'api_read_dateactivity', 'api_add_own_dateactivity', 'api_change_own_dateactivity', 'api_delete_own_dateactivity',
                    'api_read_periodactivity', 'api_add_own_periodactivity', 'api_change_own_periodactivity', 'api_delete_own_periodactivity',
                )
            }
    }

    update_group_permissions('time_based', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0026_auto_20201110_1558'),
    ]

    operations = [
        migrations.RunPython(
            add_group_permissions,
            migrations.RunPython.noop
        )
    ]
