# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-11 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0027_auto_20201110_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateactivity',
            name='online_meeting_url',
            field=models.TextField(blank=True, default='', verbose_name='Online Meeting URL'),
        ),
    ]
