# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-13 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0029_auto_20201112_1519'),
        ('time_based', '0028_dateactivity_online_meeting_url'),
    ]

    operations = [
    ]
