# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-17 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0031_auto_20201117_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateparticipant',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodparticipant',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
