# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-20 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0032_auto_20201120_1304'),
        ('time_based', '0033_auto_20201117_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duration',
            old_name='contributionvalue_ptr',
            new_name='contribution_ptr'
        ),
    ]
