# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-20 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0034_auto_20201120_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duration',
            new_name='TimeContribution',
        ),
        migrations.AlterModelOptions(
            name='dateparticipant',
            options={'permissions': (('api_read_dateparticipant', 'Can view participant through the API'), ('api_add_dateparticipant', 'Can add participant through the API'), ('api_change_dateparticipant', 'Can change participant through the API'), ('api_delete_dateparticipant', 'Can delete participant through the API'), ('api_read_own_dateparticipant', 'Can view own participant through the API'), ('api_add_own_dateparticipant', 'Can add own participant through the API'), ('api_change_own_dateparticipant', 'Can change own participant through the API'), ('api_delete_own_dateparticipant', 'Can delete own participant through the API')), 'verbose_name': 'Participant on a date', 'verbose_name_plural': 'Participants on a date'},
        ),
        migrations.AlterModelOptions(
            name='timecontribution',
            options={'verbose_name': 'Contribution', 'verbose_name_plural': 'Contributions'},
        ),
    ]
