# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-25 11:58
from __future__ import unicode_literals

from datetime import timedelta

from django.db import transaction
from django.db import migrations, transaction, connection


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0035_auto_20201120_1318'),
        ('assignments', '0024_auto_20201112_1519'),
        ('events', '0020_auto_20201112_1519')
    ]

    operations = [
    ]
