# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-26 09:42
from __future__ import unicode_literals

from django.db import migrations


def update_settings(apps, schema_editor):
    InitiativePlatformSettings = apps.get_model('initiatives', 'InitiativePlatformSettings')

    settings = InitiativePlatformSettings.objects.get()

    if 'event' in settings.activity_types or 'assignment' in settings.activity_types:
        settings.activity_types.append('dateactivity')
        settings.activity_types.append('periodactivity')

    try:
        settings.activity_types.remove('event')
    except ValueError:
        pass

    try:
        settings.activity_types.remove('assignment')
    except ValueError:
        pass

    settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0036_auto_20201125_1258'),
    ]

    operations = [
        migrations.RunPython(update_settings)
    ]
