# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-30 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0038_timebasedactivity_preparation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timecontribution',
            old_name='end',
            new_name='old_end',
        ),
        migrations.RenameField(
            model_name='timecontribution',
            old_name='start',
            new_name='old_start',
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='preparation',
            field=models.DurationField(blank=True, null=True, verbose_name='Preparation time'),
        ),
    ]
