# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-30 12:30
from __future__ import unicode_literals

from django.db import migrations, connection


def create_contribution_view(apps, schema_editor):
    sql = """
    UPDATE {0}.activities_contribution
        SET "start" = tc.old_start, "end" = tc.old_end 
        FROM {0}.time_based_timecontribution tc 
        WHERE tc.contribution_ptr_id = id;
    """.format(connection.tenant.schema_name)

    if connection.tenant.schema_name != 'public':
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0039_auto_20201130_1313'),
        ('activities', '0034_auto_20201130_1316')
    ]

    operations = [
        migrations.RunPython(create_contribution_view, migrations.RunPython.noop)
    ]
