# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-30 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0040_auto_20201130_1330'),
        ('activities', '0035_auto_20201130_1337')
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecontribution',
            name='old_end',
        ),
        migrations.RemoveField(
            model_name='timecontribution',
            name='old_start',
        ),
    ]
