# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-01 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0041_auto_20201130_1400'),
        ('time_based', '0035_auto_20201120_1318'),
    ]

    operations = [
    ]
