# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-24 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0044_auto_20201224_1120'),
        ('time_based', '0044_auto_20201223_1240'),
    ]

    operations = [
    ]
