# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-11 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0047_migrate_to_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_based.DateParticipant')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_based.DateActivitySlot')),
            ],
        ),
        migrations.AddField(
            model_name='timecontribution',
            name='slot_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_based.SlotParticipant'),
        ),
        migrations.AddField(
            model_name='dateactivity',
            name='slot_selection',
            field=models.CharField(blank=True,
                                   choices=[('all', 'All'), ('free', 'Free')],
                                   default='all',
                                   help_text='All: Participant will join all time slots. '
                                             'Free: Participant can pick any number of slots to join.',
                                   max_length=20, null=True, verbose_name='Slot selection'),
        ),

    ]
