# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-12 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0049_auto_20210112_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_participants', to='time_based.DateParticipant'),
        ),
        migrations.AlterField(
            model_name='timecontribution',
            name='slot_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='time_based.SlotParticipant'),
        ),
        migrations.AlterUniqueTogether(
            name='slotparticipant',
            unique_together=set([('slot', 'participant')]),
        ),
    ]
