# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-20 16:16
from __future__ import unicode_literals

from django.db import migrations, connection


def migrate_to_slot_participants(apps, schema_editor):
    slot_participant_sql = """
    INSERT INTO {0}.time_based_slotparticipant
        (participant_id, slot_id, status) 
        SELECT c.id, s.id, 'registered' as status FROM 
        {0}.time_based_dateparticipant as p 
        JOIN {0}.activities_contributor c ON p.contributor_ptr_id = c.id 
        JOIN {0}.time_based_dateactivityslot s ON s.activity_id = c.activity_id
    """.format(connection.tenant.schema_name)

    contribution_sql = """
    UPDATE {0}.time_based_timecontribution as tc
        SET slot_participant_id=sub.id
        FROM (
            SELECT sp.id as id, cbn.id as contribution_id FROM {0}.activities_contributor cbr
            JOIN {0}.time_based_slotparticipant as sp ON sp.participant_id = cbr.id
            JOIN {0}.activities_contribution as cbn ON cbn.contributor_id = cbr.id
        ) AS sub WHERE sub.contribution_id = tc.contribution_ptr_id
    """.format(connection.tenant.schema_name)

    if connection.tenant.schema_name != 'public':
        schema_editor.execute(slot_participant_sql)
        schema_editor.execute(contribution_sql)


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0052_slot_permissions_20210114_1056'),
    ]

    operations = [
        migrations.RunPython(
            migrate_to_slot_participants,
            migrations.RunPython.noop
        )
    ]
