# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-29 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0053_auto_20210120_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timebasedactivity',
            old_name='is_online',
            new_name='old_is_online',
        ),
        migrations.RenameField(
            model_name='timebasedactivity',
            old_name='location',
            new_name='old_location',
        ),
        migrations.RenameField(
            model_name='timebasedactivity',
            old_name='location_hint',
            new_name='old_location_hint',
        ),
    ]
