# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-29 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0053_auto_20210120_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timebasedactivity',
            old_name='is_online',
            new_name='old_is_online',
        ),
        migrations.RenameField(
            model_name='timebasedactivity',
            old_name='location',
            new_name='old_location',
        ),
        migrations.RenameField(
            model_name='timebasedactivity',
            old_name='location_hint',
            new_name='old_location_hint',
        ),
        migrations.RenameField(
            model_name='dateactivity',
            old_name='online_meeting_url',
            new_name='old_online_meeting_url',
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='old_is_online',
            field=models.NullBooleanField(
                choices=[(None, 'Not set yet'), (True, 'Yes, anywhere/online'), (False, 'No, enter a location')],
                db_column='is_online', default=None, verbose_name='is online'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='old_location',
            field=models.ForeignKey(
                blank=True, db_column='location_id', null=True,
                on_delete=django.db.models.deletion.SET_NULL, to='geo.Geolocation',
                verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='old_location_hint',
            field=models.TextField(blank=True, db_column='location_hint', null=True, verbose_name='location hint'),
        ),
    ]
