# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-29 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0056_auto_20210129_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timebasedactivity',
            name='old_is_online',
        ),
        migrations.RemoveField(
            model_name='timebasedactivity',
            name='old_location',
        ),
        migrations.RemoveField(
            model_name='timebasedactivity',
            name='old_location_hint',
        ),
    ]
