# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-02 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0056_auto_20210129_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecontribution',
            name='contribution_type',
            field=models.CharField(blank=True, choices=[('date', 'activity on a date'), ('period', 'activity over a period'), ('preparation', 'preparation')], max_length=20, null=True, verbose_name='Contribution type'),
        ),
    ]
