# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-14 09:56
from __future__ import unicode_literals

from django.db import migrations, connection

from bluebottle.utils.utils import update_group_permissions

from bluebottle.clients import properties
from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        group_perms = {
            'Staff': {
                'perms': (
                    'add_slotparticipant', 'change_slotparticipant', 'delete_slotparticipant',
                )
            },
        }

    update_group_permissions('time_based', group_perms, apps)

class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0057_add_contribution_type_20210202_1131'),
    ]

    operations = [
        migrations.RunPython(
            add_group_permissions,
            migrations.RunPython.noop
        )
    ]
