# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-03 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0061_auto_20210302_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateactivityslot',
            options={'ordering': ['start', 'id'], 'permissions': (('api_read_dateactivityslot', 'Can view on date activity slots through the API'), ('api_add_dateactivityslot', 'Can add on a date activity slots through the API'), ('api_change_dateactivityslot', 'Can change on a date activity slots through the API'), ('api_delete_dateactivityslot', 'Can delete on a date activity slots through the API'), ('api_read_own_dateactivityslot', 'Can view own on a date activity slots through the API'), ('api_add_own_dateactivityslot', 'Can add own on a date activity slots through the API'), ('api_change_own_dateactivityslot', 'Can change own on a date activity slots through the API'), ('api_delete_own_dateactivityslot', 'Can delete own on a date activity slots through the API')), 'verbose_name': 'slot', 'verbose_name_plural': 'slots'},
        ),
        migrations.RemoveField(
            model_name='dateactivity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='dateactivity',
            name='start',
        ),
        migrations.AlterField(
            model_name='dateactivity',
            name='old_online_meeting_url',
            field=models.TextField(blank=True, db_column='online_meeting_url', default='', verbose_name='online meeting link'),
        ),
        migrations.AlterField(
            model_name='dateactivityslot',
            name='is_online',
            field=models.NullBooleanField(choices=[(None, 'Not set yet'), (True, 'Yes, anywhere/online'), (False, 'No, enter a location')], default=None, verbose_name='is online'),
        ),
        migrations.AlterUniqueTogether(
            name='skilltranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterModelTable(
            name='skill',
            table=None,
        ),
    ]
