# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-31 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0064_merge_20210303_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebasedactivity',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_based.Skill', verbose_name='skill'),
        ),
    ]
