# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-31 10:07
from __future__ import unicode_literals

from django.db import migrations
from django.db import migrations, models
from parler.models import TranslatableModelMixin


def delete_no_skills_needed(apps, schema_editor):
    Skill = apps.get_model('time_based', 'Skill')

    Skill.__bases__ = (models.Model, TranslatableModelMixin)

    skill = Skill.objects.filter(translations__name__icontains='No specific skill').first()
    if not skill:
        skill = Skill.objects.filter(translations__name__icontains='geen specifieke').first()

    if not skill:
        skill = Skill.objects.filter(translations__name__icontains='no special skills').first()

    if not skill:
        skill = Skill.objects.filter(translations__name__icontains='- hands on -').first()

    if not skill:
        skill = Skill.objects.filter(translations__name__icontains='any skill').first()

    if not skill:
        skill = Skill.objects.filter(translations__name='Other').first()

    if skill:
        print('deleting: {}'.format(skill.translations.first().name))
        skill.delete()




class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0065_auto_20210331_1206'),
    ]

    operations = [
        migrations.RunPython(delete_no_skills_needed, migrations.RunPython.noop)
    ]
