# Generated by Django 2.2.24 on 2022-06-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0066_auto_20210331_1207'),
        ('time_based', '0067_auto_20220608_1147'),
    ]

    operations = [
    ]
