# Generated by Django 2.2.24 on 2022-06-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0070_auto_20220622_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamslot',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='activities.Team'),
        ),
    ]
