# Generated by Django 2.2.24 on 2022-06-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0071_auto_20220622_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamslot',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='duration'),
        ),
    ]
