# Generated by Django 2.2.24 on 2023-01-27 14:52
import datetime

from bluebottle.clients.utils import LocalTenant

from bluebottle.clients.models import Client
from django.db import migrations, connection
from django.db.models import F


def migrate_back_dated_contributions(apps, schema_editor):

    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        TimeContribution = apps.get_model('time_based', 'TimeContribution')

        # contribution_type = 'period'
        # c.start < c.created
        contributions = TimeContribution.objects.filter(contribution_type='period', start__date__lt=F('created__date'))

        for c in contributions:
            try: 
                a = c.contributor.activity.timebasedactivity.periodactivity
                if a.deadline:
                    deadline = datetime.datetime.combine(a.deadline, datetime.time(0, 0, 0), c.created.tzinfo)
                else:
                    deadline = None
                if a.start:
                    start = datetime.datetime.combine(a.start, datetime.time(0, 0, 0), c.created.tzinfo)
                else:
                    start = None

                if deadline and c.created > deadline:
                    c.start = deadline
                elif (not deadline or c.created < deadline) and start:
                    if c.created < start:
                        c.start = start
                    else:
                        c.start = c.created
                elif not start:
                    c.start = c.created
                c.save()
            except AttributeError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0074_auto_20220720_1349'),
    ]

    operations = [
        migrations.RunPython(
            migrate_back_dated_contributions,
            migrations.RunPython.noop
        )
    ]
