# Generated by Django 2.2.24 on 2022-07-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0075_periodslotparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodslotparticipant',
            name='status',
            field=models.CharField(default='registered', max_length=40),
            preserve_default=False,
        ),
    ]
