# Generated by Django 2.2.24 on 2022-07-13 08:24

import bluebottle.fsm.triggers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('time_based', '0076_periodslotparticipant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSlotParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_time_based.baseslotparticipant_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Slot participant',
                'verbose_name_plural': 'Slot participants',
            },
            bases=(bluebottle.fsm.triggers.TriggerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DateSlotParticipant',
            fields=[
                ('baseslotparticipant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='time_based.BaseSlotParticipant')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_slot_participants', to='time_based.DateParticipant')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_slot_participants', to='time_based.DateActivitySlot')),
            ],
            options={
                'permissions': (('api_read_slotparticipant', 'Can view slot participant through the API'), ('api_add_slotparticipant', 'Can add slot participant through the API'), ('api_change_slotparticipant', 'Can change slot participant through the API'), ('api_delete_slotparticipant', 'Can delete slot participant through the API'), ('api_read_own_slotparticipant', 'Can view own slot participant through the API'), ('api_add_own_slotparticipant', 'Can add own slot participant through the API'), ('api_change_own_slotparticipant', 'Can change own slot participant through the API'), ('api_delete_own_slotparticipant', 'Can delete own slot participant through the API')),
                'abstract': False,
                'base_manager_name': 'objects',
                'unique_together': {('slot', 'participant')},
            },
            bases=('time_based.baseslotparticipant',),
        ),
    ]
