# Generated by Django 3.2.20 on 2023-09-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0077_auto_20230913_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timebasedactivity',
            name='old_is_online',
        ),
        migrations.RemoveField(
            model_name='timebasedactivity',
            name='old_location',
        ),
        migrations.RemoveField(
            model_name='timebasedactivity',
            name='old_location_hint',
        ),
        migrations.AlterField(
            model_name='dateactivityslot',
            name='is_online',
            field=models.BooleanField(choices=[(None, 'Not set yet'), (True, 'Yes, anywhere/online'), (False, 'No, enter a location')], default=None, null=True, verbose_name='is online'),
        ),
        migrations.AlterField(
            model_name='periodactivity',
            name='is_online',
            field=models.BooleanField(choices=[(None, 'Not set yet'), (True, 'Yes, participants can join from anywhere or online'), (False, 'No, enter a location')], default=None, null=True, verbose_name='is online'),
        ),
        migrations.AlterField(
            model_name='periodactivityslot',
            name='is_online',
            field=models.BooleanField(choices=[(None, 'Not set yet'), (True, 'Yes, anywhere/online'), (False, 'No, enter a location')], default=None, null=True, verbose_name='is online'),
        ),
        migrations.AlterField(
            model_name='slotparticipant',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_participants', to='time_based.dateparticipant'),
        ),
        migrations.AlterField(
            model_name='teamslot',
            name='is_online',
            field=models.BooleanField(choices=[(None, 'Not set yet'), (True, 'Yes, anywhere/online'), (False, 'No, enter a location')], default=None, null=True, verbose_name='is online'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of participants or teams that can join', null=True, verbose_name='attendee limit'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='review',
            field=models.BooleanField(default=None, help_text='Activity manager accepts or rejects participants or teams', null=True, verbose_name='review participants'),
        ),
        migrations.AlterField(
            model_name='timecontribution',
            name='slot_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='time_based.slotparticipant'),
        ),
    ]
