# Generated by Django 2.2.24 on 2022-07-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0078_auto_20220713_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timecontribution',
            old_name='slot_participant',
            new_name='old_slot_participant',
        ),
    ]
