# Generated by Django 3.2.20 on 2023-10-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0079_auto_20231012_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebasedactivity',
            name='review_description',
            field=models.TextField(blank=True, help_text='Description of the application step', null=True, verbose_name='Application description'),
        ),
        migrations.AddField(
            model_name='timebasedactivity',
            name='review_document_enabled',
            field=models.BooleanField(default=False, help_text='Can participants upload a document in the application step', null=True, verbose_name='Application document enabled'),
        ),
        migrations.AddField(
            model_name='timebasedactivity',
            name='review_title',
            field=models.CharField(blank=True, help_text='Title of the application step', max_length=255, null=True, verbose_name='Application step title'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='review',
            field=models.BooleanField(default=None, help_text='Activity manager accepts or rejects participants or teams', null=True, verbose_name='Review participants'),
        ),
    ]
