# Generated by Django 2.2.24 on 2022-07-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0079_auto_20220713_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecontribution',
            name='new_slot_participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='time_based.BaseSlotParticipant'),
        ),
    ]
