# Generated by Django 2.2.24 on 2022-07-13 08:42

from django.db import migrations


def set_slot_participants(apps, schema_editor):
    DateSlotParticipant = apps.get_model('time_based', 'DateSlotParticipant')
    TimeContribution = apps.get_model('time_based', 'TimeContribution')

    for contribution in TimeContribution.objects.filter(
        old_slot_participant__isnull=False
    ).select_related(
        'old_slot_participant'
    ):
        contribution.new_slot_participant = DateSlotParticipant.objects.get(
            slot_id=contribution.old_slot_participant.slot_id,
            participant_id=contribution.old_slot_participant.participant_id
        )
        contribution.save()


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0080_timecontribution_slot_participant'),
    ]

    operations = [
        migrations.RunPython(set_slot_participants)
    ]
