# Generated by Django 3.2.20 on 2023-12-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0080_auto_20231025_1324'),
        ('time_based', '0081_auto_20231206_1119'),
    ]

    operations = [
    ]
