# Generated by Django 3.2.20 on 2023-12-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0082_auto_20231215_1155'),
        ('time_based', '0082_merge_0080_auto_20231025_1324_0081_auto_20231206_1119'),
    ]

    operations = [
    ]
