# Generated by Django 2.2.24 on 2022-07-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0082_auto_20220713_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodslotparticipant',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='periodslotparticipant',
            name='id',
        ),
        migrations.AddField(
            model_name='periodslotparticipant',
            name='baseslotparticipant_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='time_based.BaseSlotParticipant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='periodslotparticipant',
            unique_together={('slot', 'participant')},
        ),
        migrations.RemoveField(
            model_name='periodslotparticipant',
            name='status',
        ),
    ]
