# Generated by Django 3.2.20 on 2024-01-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0083_merge_20231218_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodactivity',
            name='slot_type',
            field=models.CharField(choices=[(None, 'Not set yet'), ('free', 'Anytime. Participants will execute the task on their own time'), ('tailored', 'Tailored. After signing up, participants will be assigned a date and time by the activity manager.'), ('recurring', 'Recurring. Participants are expected to contribute every week or month.'), (False, 'No, enter a location')], default=None, help_text='How and when will participants contribute to this activity?', max_length=100, null=True, verbose_name='Time slot type'),
        ),
        migrations.AlterField(
            model_name='dateactivity',
            name='slot_selection',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('free', 'Free')], default='free', help_text='All: Participant will join all time slots. Free: Participant can pick any number of slots to join.', max_length=20, null=True, verbose_name='Slot selection'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='review_description',
            field=models.TextField(blank=True, help_text='Description of the registration step', null=True, verbose_name='Registration description'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='review_document_enabled',
            field=models.BooleanField(default=False, help_text='Can participants upload a document in the registration step', null=True, verbose_name='Registration document enabled'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='review_title',
            field=models.CharField(blank=True, help_text='Title of the registration step', max_length=255, null=True, verbose_name='Registration step title'),
        ),
    ]
