# Generated by Django 2.2.24 on 2022-07-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0083_auto_20220713_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateslotparticipant',
            options={'base_manager_name': 'objects', 'permissions': (('api_read_dateslotparticipant', 'Can view slot participant through the API'), ('api_add_dateslotparticipant', 'Can add slot participant through the API'), ('api_change_dateslotparticipant', 'Can change slot participant through the API'), ('api_delete_dateslotparticipant', 'Can delete slot participant through the API'), ('api_read_own_dateslotparticipant', 'Can view own slot participant through the API'), ('api_add_own_dateslotparticipant', 'Can add own slot participant through the API'), ('api_change_own_dateslotparticipant', 'Can change own slot participant through the API'), ('api_delete_own_dateslotparticipant', 'Can delete own slot participant through the API'))},
        ),
        migrations.AlterField(
            model_name='dateslotparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_participants', to='time_based.DateParticipant'),
        ),
        migrations.AlterField(
            model_name='dateslotparticipant',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_participants', to='time_based.DateActivitySlot'),
        ),
        migrations.DeleteModel(
            name='SlotParticipant',
        ),
    ]
