# Generated by Django 3.2.20 on 2024-01-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0084_auto_20240122_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebasedactivity',
            name='review_link',
            field=models.URLField(blank=True, help_text='External link where the participant should complete their registration', max_length=255, null=True, verbose_name='Registration link'),
        ),
        migrations.AlterField(
            model_name='dateactivity',
            name='old_online_meeting_url',
            field=models.TextField(blank=True, db_column='online_meeting_url', default='', verbose_name='online meeting link'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='review_document_enabled',
            field=models.BooleanField(default=False, help_text='Can participants upload a document in the review step', null=True, verbose_name='Review document enabled'),
        ),
    ]
