# Generated by Django 3.2.20 on 2024-01-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0085_auto_20240126_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebasedactivity',
            name='registration_flow',
            field=models.CharField(choices=[('none', 'No question'), ('question', 'Ask the participant a question on the platform.'), ('link', 'Direct the participant to an external website e.g. a Google form.')], default='none', help_text='Do you want to ask any questions to your partipants when they join your activity?', max_length=100, verbose_name='Registration flow'),
        ),
    ]
