# Generated by Django 3.2.20 on 2024-01-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0085_auto_20240105_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodactivity',
            name='deadline',
            field=models.DateField(blank=True, help_text='Participants can contribute until this date.', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='periodactivity',
            name='duration',
            field=models.DurationField(blank=True, help_text='How much time will a participant contribute?', null=True, verbose_name='Activity duration'),
        ),
        migrations.AlterField(
            model_name='periodactivity',
            name='duration_period',
            field=models.CharField(blank=True, choices=[('overall', 'in total'), ('days', 'per day'), ('weeks', 'per week'), ('months', 'per month')], max_length=20, null=True, verbose_name='Recurring period'),
        ),
        migrations.AlterField(
            model_name='periodactivity',
            name='max_iterations',
            field=models.PositiveIntegerField(blank=True, help_text='How many weeks/months will a participant contribute to this activity?', null=True, verbose_name='Max iterations'),
        ),
        migrations.AlterField(
            model_name='periodactivity',
            name='start',
            field=models.DateField(blank=True, help_text='The first moment participants can start.', null=True, verbose_name='Start date'),
        ),
    ]
