# Generated by Django 3.2.20 on 2024-01-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0085_auto_20240126_1335"),
        ("time_based", "0086_auto_20240107_1347"),
    ]

    operations = []
