# Generated by Django 3.2.20 on 2024-02-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0090_deadlineparticipant_deadlineregistration_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateparticipant',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_based.registration'),
        ),
        migrations.AddField(
            model_name='deadlineparticipant',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_based.registration'),
        ),
        migrations.AddField(
            model_name='periodparticipant',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_based.registration'),
        ),
    ]
