# Generated by Django 3.2.20 on 2024-02-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0091_auto_20240207_1503"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodactivity",
            name="slot_type",
        ),
    ]
