# Generated by Django 3.2.20 on 2024-02-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0092_remove_periodactivity_slot_type'),
        ('time_based', '0093_auto_20240208_1050'),
    ]

    operations = [
    ]
