# Generated by Django 3.2.20 on 2024-02-14 13:04

from django.db import migrations


def enable_deadline_activity(apps, schema_editor):
    InitiativePlatformSettings = apps.get_model('initiatives', 'InitiativePlatformSettings')
    settings, _create = InitiativePlatformSettings.objects.get_or_create()
    settings.activity_types.append('deadlineactivity')
    settings.save()



class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0094_merge_20240208_1501'),
    ]

    operations = [
        migrations.RunPython(enable_deadline_activity, migrations.RunPython.noop)
    ]
