# Generated by Django 3.2.20 on 2024-02-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0095_auto_20240214_1404"),
        ("time_based", "0097_periodicactivity_period"),
    ]

    operations = []
