# Generated by Django 3.2.20 on 2024-03-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0099_auto_20240304_1341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodicactivity",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hours", "per hour"),
                    ("days", "per day"),
                    ("weeks", "per week"),
                    ("months", "per month"),
                ],
                help_text="When should the activity be repeated?",
                max_length=100,
                null=True,
                verbose_name="Period",
            ),
        ),
        migrations.AlterField(
            model_name="periodicparticipant",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="time_based.periodicslot",
            ),
        ),
        migrations.AlterField(
            model_name="periodicslot",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="time_based.periodicactivity",
            ),
        ),
    ]
