# Generated by Django 3.2.20 on 2024-03-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0033_auto_20231211_1541'),
        ('time_based', '0101_auto_20240304_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebasedactivity',
            name='registration_flow',
            field=models.CharField(choices=[('none', 'No'), ('question', 'Ask a single question on the platform.'), ('link', 'Direct the participants to a questionnaire on an external website like Microsoft forms.')], default='none', help_text='Do you want to ask any questions to your participants when they join your activity?', max_length=100, verbose_name='Ask a question'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='review',
            field=models.BooleanField(default=None, help_text='Activity manager accepts or rejects participants or teams.', null=True, verbose_name='Review participants'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='review_description',
            field=models.TextField(blank=True, help_text='Give some more context to help the participant answer the question.', null=True, verbose_name='Question description'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='review_document_enabled',
            field=models.BooleanField(default=False, help_text='Allow participants to upload documents that support their application.', null=True, verbose_name='Upload documents'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='review_link',
            field=models.URLField(blank=True, help_text='Direct participants to a questionnaire created from an external website like Microsoft forms.', max_length=255, null=True, verbose_name='External website link'),
        ),
        migrations.AlterField(
            model_name='timebasedactivity',
            name='review_title',
            field=models.CharField(blank=True, help_text='This is the question that participants will answer.', max_length=255, null=True, verbose_name='Question label'),
        ),
        migrations.CreateModel(
            name='ScheduleActivity',
            fields=[
                ('timebasedactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='time_based.timebasedactivity')),
                ('is_online', models.BooleanField(choices=[(None, 'Not set yet'), (True, 'Yes, participants can join from anywhere or online'), (False, 'No, enter a location')], default=None, null=True, verbose_name='is online')),
                ('location_hint', models.TextField(blank=True, null=True, verbose_name='location hint')),
                ('start', models.DateField(blank=True, help_text='The first moment participants can start.', null=True, verbose_name='Start date')),
                ('deadline', models.DateField(blank=True, help_text='Participants can contribute until this date.', null=True, verbose_name='End date')),
                ('duration', models.DurationField(blank=True, help_text='How much time will a participant contribute?', null=True, verbose_name='Activity duration')),
                ('online_meeting_url', models.TextField(blank=True, default='', verbose_name='Online Meeting URL')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.geolocation', verbose_name='location')),
            ],
            options={
                'verbose_name': 'Schedule activity',
                'verbose_name_plural': 'Schedule activities',
                'permissions': (('api_read_scheduleactivity', 'Can view on a schedule activities through the API'), ('api_add_scheduleactivity', 'Can add on a schedule activities through the API'), ('api_change_scheduleactivity', 'Can change on a schedule activities through the API'), ('api_delete_scheduleactivity', 'Can delete on a schedule activities through the API'), ('api_read_own_scheduleactivity', 'Can view own on a schedule activities through the API'), ('api_add_own_scheduleactivity', 'Can add own on a schedule activities through the API'), ('api_change_own_scheduleactivity', 'Can change own on a schedule activities through the API'), ('api_delete_own_scheduleactivity', 'Can delete own on a schedule activities through the API')),
            },
            bases=('time_based.timebasedactivity',),
        ),
    ]
