# Generated by Django 3.2.20 on 2024-03-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0072_auto_20240207_1140'),
        ('time_based', '0102_auto_20240311_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRegistration',
            fields=[
                ('registration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='time_based.registration')),
            ],
            options={
                'verbose_name': 'Deadline registration',
                'verbose_name_plural': 'Deadline registrations',
                'permissions': (('api_read_scheduleregistration', 'Can view registation through the API'), ('api_add_scheduleregistration', 'Can add registation through the API'), ('api_change_scheduleregistration', 'Can change registation through the API'), ('api_delete_scheduleregistration', 'Can delete registation through the API'), ('api_read_own_scheduleregistration', 'Can view own registation through the API'), ('api_add_own_scheduleregistration', 'Can add own registation through the API'), ('api_change_own_scheduleregistration', 'Can change own registation through the API'), ('api_delete_own_scheduleregistration', 'Can delete own registation through the API')),
            },
            bases=('time_based.registration',),
        ),
        migrations.CreateModel(
            name='ScheduleParticipant',
            fields=[
                ('contributor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.contributor')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_based.registration')),
            ],
            options={
                'verbose_name': 'Schedule participant',
                'verbose_name_plural': 'Schedule participants',
                'permissions': (('api_read_scheduleparticipant', 'Can view participant through the API'), ('api_add_scheduleparticipant', 'Can add participant through the API'), ('api_change_scheduleparticipant', 'Can change participant through the API'), ('api_delete_scheduleparticipant', 'Can delete participant through the API'), ('api_read_own_scheduleparticipant', 'Can view own participant through the API'), ('api_add_own_scheduleparticipant', 'Can add own participant through the API'), ('api_change_own_scheduleparticipant', 'Can change own participant through the API'), ('api_delete_own_scheduleparticipant', 'Can delete own participant through the API')),
            },
            bases=('activities.contributor',),
        ),
    ]
