# Generated by Django 3.2.20 on 2024-03-11 15:26
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import unicode_literals

from django.db import migrations, connection

from bluebottle.clients import properties
from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        group_perms = {
            "Staff": {
                "perms": (
                    "add_scheduleactivity",
                    "change_scheduleactivity",
                    "delete_scheduleactivity",
                    "add_scheduleregistration",
                    "change_scheduleregistration",
                    "delete_scheduleregistration",
                    "add_scheduleparticipant",
                    "change_scheduleparticipant",
                    "delete_scheduleparticipant",
                )
            },
            "Anonymous": {
                "perms": (
                    (
                        "api_read_scheduleactivity",
                        "api_read_scheduleregistration",
                        "api_read_scheduleparticipant",
                    )
                    if not properties.CLOSED_SITE
                    else ()
                )
            },
            "Authenticated": {
                "perms": (
                    "api_add_own_scheduleactivity",
                    "api_add_scheduleregistration",
                    "api_add_scheduleparticipant",
                    "api_read_scheduleactivity",
                    "api_read_scheduleregistration",
                    "api_read_scheduleparticipant",
                    "api_change_own_scheduleactivity",
                    "api_change_own_scheduleregistration",
                    "api_change_own_scheduleparticipant",
                )
            },
        }

    update_group_permissions("time_based", group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0103_scheduleparticipant_scheduleregistration"),
    ]

    operations = [
        migrations.RunPython(add_group_permissions, migrations.RunPython.noop)
    ]
