# Generated by Django 3.2.20 on 2024-03-11 15:29
from django.db import migrations


def enable_activity_types(apps, schema_editor):
    InitiativePlatformSettings = apps.get_model(
        "initiatives", "InitiativePlatformSettings"
    )
    settings, _create = InitiativePlatformSettings.objects.get_or_create()
    if "periodactivity" in settings.activity_types:
        settings.activity_types.append("periodicactivity")
        settings.activity_types.append("scheduleactivity")
    settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0104_schedule_permissions"),
    ]

    operations = [
        migrations.RunPython(enable_activity_types, migrations.RunPython.noop)
    ]
