# Generated by Django 3.2.20 on 2024-03-12 16:44

import bluebottle.fsm.triggers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0105_activity_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduleactivity",
            name="duration",
        ),
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=40)),
                (
                    "start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="start date and time"
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end date and time"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="time_based.scheduleactivity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(bluebottle.fsm.triggers.TriggerMixin, models.Model),
        ),
        migrations.AddField(
            model_name="scheduleparticipant",
            name="slot",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="time_based.scheduleslot",
            ),
            preserve_default=False,
        ),
    ]
