# Generated by Django 3.2.20 on 2024-03-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0106_auto_20240312_1744"),
        ("time_based", "0106_auto_20240314_1444"),
    ]

    operations = []
