# Generated by Django 3.2.20 on 2024-03-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0110_merge_20240321_1437"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleactivity",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="How much time will a participant contribute?",
                null=True,
                verbose_name="Activity duration",
            ),
        ),
    ]
