# Generated by Django 3.2.20 on 2024-04-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0111_auto_20240321_1504"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dateparticipant",
            options={
                "permissions": (
                    (
                        "api_read_dateparticipant",
                        "Can view participant through the API",
                    ),
                    ("api_add_dateparticipant", "Can add participant through the API"),
                    (
                        "api_change_dateparticipant",
                        "Can change participant through the API",
                    ),
                    (
                        "api_delete_dateparticipant",
                        "Can delete participant through the API",
                    ),
                    (
                        "api_read_own_dateparticipant",
                        "Can view own participant through the API",
                    ),
                    (
                        "api_add_own_dateparticipant",
                        "Can add own participant through the API",
                    ),
                    (
                        "api_change_own_dateparticipant",
                        "Can change own participant through the API",
                    ),
                    (
                        "api_delete_own_dateparticipant",
                        "Can delete own participant through the API",
                    ),
                ),
                "verbose_name": "Participant to date activities",
                "verbose_name_plural": "Participants to date activities",
            },
        ),
        migrations.AlterModelOptions(
            name="deadlineactivity",
            options={
                "permissions": (
                    (
                        "api_read_deadlineactivity",
                        "Can view on a felxible activities through the API",
                    ),
                    (
                        "api_add_deadlineactivity",
                        "Can add on a felxible activities through the API",
                    ),
                    (
                        "api_change_deadlineactivity",
                        "Can change on a felxible activities through the API",
                    ),
                    (
                        "api_delete_deadlineactivity",
                        "Can delete on a felxible activities through the API",
                    ),
                    (
                        "api_read_own_deadlineactivity",
                        "Can view own on a felxible activities through the API",
                    ),
                    (
                        "api_add_own_deadlineactivity",
                        "Can add own on a felxible activities through the API",
                    ),
                    (
                        "api_change_own_deadlineactivity",
                        "Can change own on a felxible activities through the API",
                    ),
                    (
                        "api_delete_own_deadlineactivity",
                        "Can delete own on a felxible activities through the API",
                    ),
                ),
                "verbose_name": "Flexible activity",
                "verbose_name_plural": "Flexible activities",
            },
        ),
        migrations.AlterModelOptions(
            name="deadlineparticipant",
            options={
                "permissions": (
                    (
                        "api_read_deadlineparticipant",
                        "Can view participant through the API",
                    ),
                    (
                        "api_add_deadlineparticipant",
                        "Can add participant through the API",
                    ),
                    (
                        "api_change_deadlineparticipant",
                        "Can change participant through the API",
                    ),
                    (
                        "api_delete_deadlineparticipant",
                        "Can delete participant through the API",
                    ),
                    (
                        "api_read_own_deadlineparticipant",
                        "Can view own participant through the API",
                    ),
                    (
                        "api_add_own_deadlineparticipant",
                        "Can add own participant through the API",
                    ),
                    (
                        "api_change_own_deadlineparticipant",
                        "Can change own participant through the API",
                    ),
                    (
                        "api_delete_own_deadlineparticipant",
                        "Can delete own participant through the API",
                    ),
                ),
                "verbose_name": "Participant to flexible activities",
                "verbose_name_plural": "Participants to flexible activities",
            },
        ),
        migrations.AlterModelOptions(
            name="deadlineregistration",
            options={
                "permissions": (
                    (
                        "api_read_deadlineregistration",
                        "Can view registration through the API",
                    ),
                    (
                        "api_add_deadlineregistration",
                        "Can add registration through the API",
                    ),
                    (
                        "api_change_deadlineregistration",
                        "Can change candidates through the API",
                    ),
                    (
                        "api_delete_deadlineregistration",
                        "Can delete candidates through the API",
                    ),
                    (
                        "api_read_own_deadlineregistration",
                        "Can view own candidates through the API",
                    ),
                    (
                        "api_add_own_deadlineregistration",
                        "Can add own candidates through the API",
                    ),
                    (
                        "api_change_own_deadlineregistration",
                        "Can change own candidates through the API",
                    ),
                    (
                        "api_delete_own_deadlineregistration",
                        "Can delete own candidates through the API",
                    ),
                ),
                "verbose_name": "Candidate for flexible activities",
                "verbose_name_plural": "Candidates for flexible activities",
            },
        ),
        migrations.AlterModelOptions(
            name="periodicactivity",
            options={
                "permissions": (
                    (
                        "api_read_periodicactivity",
                        "Can view on a periodic activities through the API",
                    ),
                    (
                        "api_add_periodicactivity",
                        "Can add on a periodic activities through the API",
                    ),
                    (
                        "api_change_periodicactivity",
                        "Can change on a periodic activities through the API",
                    ),
                    (
                        "api_delete_periodicactivity",
                        "Can delete on a periodic activities through the API",
                    ),
                    (
                        "api_read_own_periodicactivity",
                        "Can view own on a periodic activities through the API",
                    ),
                    (
                        "api_add_own_periodicactivity",
                        "Can add own on a periodic activities through the API",
                    ),
                    (
                        "api_change_own_periodicactivity",
                        "Can change own on a periodic activities through the API",
                    ),
                    (
                        "api_delete_own_periodicactivity",
                        "Can delete own on a periodic activities through the API",
                    ),
                ),
                "verbose_name": "Recurring activity",
                "verbose_name_plural": "Recurring activities",
            },
        ),
        migrations.AlterModelOptions(
            name="periodicparticipant",
            options={
                "permissions": (
                    (
                        "api_read_periodicparticipant",
                        "Can view recurring participant through the API",
                    ),
                    (
                        "api_add_periodicparticipant",
                        "Can add recurring participant through the API",
                    ),
                    (
                        "api_change_periodicparticipant",
                        "Can change recurring participant through the API",
                    ),
                    (
                        "api_delete_periodicparticipant",
                        "Can delete recurring participant through the API",
                    ),
                    (
                        "api_read_own_periodicparticipant",
                        "Can view own recurring participant through the API",
                    ),
                    (
                        "api_add_own_periodicparticipant",
                        "Can add own recurring participant through the API",
                    ),
                    (
                        "api_change_own_periodicparticipant",
                        "Can change own recurring participant through the API",
                    ),
                    (
                        "api_delete_own_periodicparticipant",
                        "Can delete own recurring participant through the API",
                    ),
                ),
                "verbose_name": "Participant to ecurring activities",
                "verbose_name_plural": "Participants to recurring activities",
            },
        ),
        migrations.AlterModelOptions(
            name="periodicregistration",
            options={
                "permissions": (
                    (
                        "api_read_periodicregistration",
                        "Can view periodic candidates through the API",
                    ),
                    (
                        "api_add_periodicregistration",
                        "Can add periodic candidates through the API",
                    ),
                    (
                        "api_change_periodicregistration",
                        "Can change periodic candidates through the API",
                    ),
                    (
                        "api_delete_periodicregistration",
                        "Can delete periodic candidates through the API",
                    ),
                    (
                        "api_read_own_periodicregistration",
                        "Can view own periodic candidates through the API",
                    ),
                    (
                        "api_add_own_periodicregistration",
                        "Can add own periodic candidates through the API",
                    ),
                    (
                        "api_change_own_periodicregistration",
                        "Can change own periodic candidates through the API",
                    ),
                    (
                        "api_delete_own_periodicregistration",
                        "Can delete own periodic candidates through the API",
                    ),
                ),
                "verbose_name": "Candidate for recurring activities",
                "verbose_name_plural": "Candidates for recurring activities",
            },
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={"verbose_name": "Candidate", "verbose_name_plural": "Candidates"},
        ),
        migrations.AlterModelOptions(
            name="scheduleparticipant",
            options={
                "permissions": (
                    (
                        "api_read_scheduleparticipant",
                        "Can view participant through the API",
                    ),
                    (
                        "api_add_scheduleparticipant",
                        "Can add participant through the API",
                    ),
                    (
                        "api_change_scheduleparticipant",
                        "Can change participant through the API",
                    ),
                    (
                        "api_delete_scheduleparticipant",
                        "Can delete participant through the API",
                    ),
                    (
                        "api_read_own_scheduleparticipant",
                        "Can view own participant through the API",
                    ),
                    (
                        "api_add_own_scheduleparticipant",
                        "Can add own participant through the API",
                    ),
                    (
                        "api_change_own_scheduleparticipant",
                        "Can change own participant through the API",
                    ),
                    (
                        "api_delete_own_scheduleparticipant",
                        "Can delete own participant through the API",
                    ),
                ),
                "verbose_name": "Participant to schedule activities",
                "verbose_name_plural": "Participants to schedule activities",
            },
        ),
        migrations.AlterModelOptions(
            name="scheduleregistration",
            options={
                "permissions": (
                    (
                        "api_read_scheduleregistration",
                        "Can view candidates through the API",
                    ),
                    (
                        "api_add_scheduleregistration",
                        "Can add candidates through the API",
                    ),
                    (
                        "api_change_scheduleregistration",
                        "Can change candidates through the API",
                    ),
                    (
                        "api_delete_scheduleregistration",
                        "Can delete candidates through the API",
                    ),
                    (
                        "api_read_own_scheduleregistration",
                        "Can view own candidates through the API",
                    ),
                    (
                        "api_add_own_scheduleregistration",
                        "Can add own candidates through the API",
                    ),
                    (
                        "api_change_own_scheduleregistration",
                        "Can change own candidates through the API",
                    ),
                    (
                        "api_delete_own_scheduleregistration",
                        "Can delete own candidates through the API",
                    ),
                ),
                "verbose_name": "Candidate for schedule activities",
                "verbose_name_plural": "Candidates for schedule activities",
            },
        ),
        migrations.RemoveField(
            model_name="dateactivity",
            name="slot_selection",
        ),
        migrations.AlterField(
            model_name="scheduleparticipant",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="time_based.scheduleslot",
            ),
        ),
    ]
