# Generated by Django 3.2.20 on 2024-04-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0113_auto_20240425_1206'),
        ('time_based', '0113_teamscheduleparticipant_teamscheduleregistration_teamscheduleslot'),
    ]

    operations = [
    ]
