# Generated by Django 3.2.20 on 2024-04-28 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0116_teamscheduleregistration_invite_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleteammember',
            options={'verbose_name': 'Team member  for schedule activities', 'verbose_name_plural': 'Team members for schedule activities'},
        ),
        migrations.RemoveField(
            model_name='teamscheduleregistration',
            name='invite_code',
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date and time'),
        ),
        migrations.AlterField(
            model_name='scheduleteammember',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_based.teamscheduleregistration'),
        ),
        migrations.AlterField(
            model_name='teamscheduleslot',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date and time'),
        ),
    ]
