# Generated by Django 3.2.20 on 2024-04-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0117_auto_20240428_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleteammember',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='time_based.teamscheduleregistration'),
        ),
        migrations.AlterField(
            model_name='teamscheduleparticipant',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='time_based.registration'),
        ),
    ]
