# Generated by Django 3.2.20 on 2024-05-01 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0118_auto_20240429_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamscheduleregistration",
            name="invite_code",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
