# Generated by Django 3.2.20 on 2024-05-21 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_based', '0120_auto_20240517_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='time_based.timebasedactivity'),
        ),
        migrations.AlterField(
            model_name='team',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='time_based.registration'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_captains', to=settings.AUTH_USER_MODEL, verbose_name='Team captain'),
        ),
    ]
