# Generated by Django 3.2.20 on 2024-05-30 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0073_alter_team_activity'),
        ('time_based', '0121_auto_20240521_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleparticipant',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='time_based.scheduleregistration'),
        ),
        migrations.AlterField(
            model_name='team',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='teamscheduleparticipant',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='time_based.teamscheduleregistration'),
        ),
    ]
