# Generated by Django 3.2.20 on 2024-05-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0122_auto_20240530_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='invite_code',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
