# Generated by Django 3.2.20 on 2024-06-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0123_teammember_invite_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "permissions": (
                    ("api_read_team", "Can view on a team through the API"),
                    ("api_add_team", "Can add on a team through the API"),
                    ("api_change_team", "Can change on a team through the API"),
                    ("api_delete_team", "Can delete on a team through the API"),
                    ("api_read_own_team", "Can view own on a team through the API"),
                    ("api_add_own_team", "Can add own on a team through the API"),
                    ("api_change_own_team", "Can change own on a team through the API"),
                    ("api_delete_own_team", "Can delete own on a team through the API"),
                ),
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "permissions": (
                    (
                        "api_read_teammember",
                        "Can view on a team member through the API",
                    ),
                    ("api_add_teammember", "Can add on a team member through the API"),
                    (
                        "api_change_teammember",
                        "Can change on a team member through the API",
                    ),
                    (
                        "api_delete_teammember",
                        "Can delete on a team member through the API",
                    ),
                    (
                        "api_read_own_teammember",
                        "Can view own on a team member through the API",
                    ),
                    (
                        "api_add_own_teammember",
                        "Can add own on a team member through the API",
                    ),
                    (
                        "api_change_own_teammember",
                        "Can change own on a team member through the API",
                    ),
                    (
                        "api_delete_own_teammember",
                        "Can delete own on a team member through the API",
                    ),
                ),
                "verbose_name": "Team member",
                "verbose_name_plural": "Team members",
            },
        ),
        migrations.AlterField(
            model_name="scheduleactivity",
            name="deadline",
            field=models.DateField(
                blank=True,
                help_text="The end of the period in which the teams/participants can take part in your activity.",
                null=True,
                verbose_name="End date",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleactivity",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="How much time a participant is expected to contribute. This will be an estimate since the exact hours will be based on the start/end time set for each participant or team.",
                null=True,
                verbose_name="Activity duration",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleactivity",
            name="start",
            field=models.DateField(
                blank=True,
                help_text="The start of the period in which the teams/participants can take part in your activity.",
                null=True,
                verbose_name="Start date",
            ),
        ),
        migrations.AlterField(
            model_name="teamscheduleparticipant",
            name="team_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="time_based.teammember",
            ),
        ),
        migrations.AlterField(
            model_name="teamscheduleslot",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="How much time the team is expected to contribute.",
                null=True,
                verbose_name="Team duration",
            ),
        ),
    ]
