# Generated by Django 3.2.20 on 2024-08-01 11:20
from django.db import migrations, connection

from bluebottle.clients import properties
from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


permissions = [
    "api_read_own_deadlineactivity",
    "api_add_own_deadlineactivity",
    "api_change_own_deadlineactivity",
    "api_delete_own_deadlineactivity",
    "view_deadlineparticipant",
    "api_read_deadlineparticipant",
    "api_change_deadlineparticipant",
    "view_registration",
    "view_deadlineregistration",
    "api_read_deadlineregistration",
    "api_change_deadlineregistration",
    "api_read_own_periodicactivity",
    "api_add_own_periodicactivity",
    "api_change_own_periodicactivity",
    "api_delete_own_periodicactivity",
    "view_periodicregistration",
    "api_read_periodicregistration",
    "api_change_periodicregistration",
    "view_periodicslot",
    "view_periodicparticipant",
    "api_read_periodicparticipant",
    "api_change_periodicparticipant",
    "api_read_own_scheduleactivity",
    "api_add_own_scheduleactivity",
    "api_change_own_scheduleactivity",
    "api_delete_own_scheduleactivity",
    "view_scheduleregistration",
    "api_read_scheduleregistration",
    "api_change_scheduleregistration",
    "view_scheduleparticipant",
    "api_read_scheduleparticipant",
    "api_change_scheduleparticipant",
    "view_scheduleslot",
    "view_teamscheduleregistration",
    "api_read_teamscheduleregistration",
    "view_teamscheduleslot",
    "view_teamscheduleparticipant",
    "api_read_teamscheduleparticipant",
    "view_team",
    "api_read_team",
    "api_change_team",
    "view_teammember",
    "api_read_teammember",
]


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        group_perms = {
            "Partner": {"perms": permissions},
        }

    update_group_permissions("time_based", group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0128_auto_20240716_1452"),
    ]

    operations = [
        migrations.RunPython(add_group_permissions, migrations.RunPython.noop)
    ]
