# Generated by Django 3.2.20 on 2024-08-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0129_auto_20240801_1320'),
        ('time_based', '0130_merge_0128_auto_20240716_1452_0129_auto_20240718_1638'),
    ]

    operations = [
    ]
