# Generated by Django 3.2.20 on 2024-08-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0130_auto_20240807_1536'),
        ('time_based', '0131_merge_20240806_1129'),
    ]

    operations = [
    ]
