# Generated by Django 3.2.20 on 2025-01-28 08:49

from django.db import migrations
from sphinx.addnodes import document

from bluebottle.time_based.models import DateRegistration


def migrate_date_participants(apps, schema_editor):

    DateParticipant = apps.get_model('time_based', 'DateParticipant')
    DateRegistration = apps.get_model('time_based', 'DateRegistration')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    date_registration_ctype = ContentType.objects.get_for_model(DateRegistration)
    date_participant_ctype = ContentType.objects.get_for_model(DateParticipant)

    for participant in DateParticipant.objects.all():
        registration = DateRegistration.objects.create(
            user=participant.user,
            activity=participant.activity,
            status=participant.status,
            created=participant.created,
            answer=participant.motivation,
            document=participant.document,
            polymorphic_ctype=date_registration_ctype
        )
        slot_participants = participant.slot_participants.all()
        for slot_participant in slot_participants:
            participant_status = slot_participant.status
            if participant_status == 'registered':
                participant_status = 'accepted'
            new_participant = DateParticipant.objects.create(
                user=participant.user,
                registration=registration,
                activity=participant.activity,
                slot=slot_participant.slot,
                status=slot_participant.status,
                created=slot_participant.created,
                polymorphic_ctype=date_participant_ctype
            )
            slot_participant.contributions.update(contributor=new_participant)
            slot_participant.delete()
        participant.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0135_auto_20250128_0948'),
    ]

    operations = [
        migrations.RunPython(migrate_date_participants, reverse_code=migrations.RunPython.noop),
    ]
