# Generated by Django 3.2.20 on 2025-02-04 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0136_auto_20250128_0949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlotParticipant',
            new_name='OldSlotParticipant',
        ),
        migrations.AlterField(
            model_name='deadlineparticipant',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_based.registration'),
        ),
        migrations.AlterField(
            model_name='periodicparticipant',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_based.registration'),
        ),
        migrations.AlterField(
            model_name='periodparticipant',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_based.registration'),
        ),
        migrations.AlterField(
            model_name='scheduleparticipant',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='time_based.scheduleregistration'),
        ),
        migrations.AlterField(
            model_name='teamscheduleparticipant',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='time_based.teamscheduleregistration'),
        ),
    ]
