# Generated by Django 3.2.20 on 2025-02-05 10:12

from django.db import migrations


def migrate_date_participant_status(apps, schema_editor):

    DateParticipant = apps.get_model('time_based', 'DateParticipant')

    DateParticipant.objects.filter(status='registered', registration__status='accepted').update(status='accepted')
    DateParticipant.objects.filter(status='registered', registration__status='new').update(status='new')

class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0137_auto_20250204_1109'),
    ]

    operations = [
        migrations.RunPython(migrate_date_participant_status, reverse_code=migrations.RunPython.noop),
    ]
