# Generated by Django 4.2.20 on 2025-04-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('time_based', '0139_auto_20250214_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDateActivity',
            fields=[
                ('timebasedactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='time_based.timebasedactivity')),
                ('duration', models.DurationField(blank=True, help_text='How much time did/will a participant contribute?', null=True, verbose_name='Activity duration')),
                ('start', models.DateField(blank=True, help_text='Start of the period during which participants/teams can take part in your activity.', null=True, verbose_name='Start date')),
            ],
            options={
                'verbose_name': 'Registered date activity',
                'verbose_name_plural': 'Registered date activities',
                'permissions': (('api_read_registereddate', 'Can view on a registered date activities through the API'), ('api_add_registereddate', 'Can add on a registered date activities through the API'), ('api_change_registereddate', 'Can change on a registered date activities through the API'), ('api_delete_registereddate', 'Can delete on a registered date activities through the API'), ('api_read_own_registereddate', 'Can view own on a registered date activities through the API'), ('api_add_own_registereddate', 'Can add own on a registered date activities through the API'), ('api_change_own_registereddate', 'Can change own on a registered date activities through the API'), ('api_delete_own_registereddate', 'Can delete own on a registered date activities through the API')),
            },
            bases=('time_based.timebasedactivity',),
        ),
        migrations.RemoveField(
            model_name='periodactivityslot',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='periodactivityslot',
            name='location',
        ),
        migrations.RemoveField(
            model_name='teamslot',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='teamslot',
            name='location',
        ),
        migrations.RemoveField(
            model_name='teamslot',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='deadlineactivity',
            options={'permissions': (('api_read_deadlineactivity', 'Can view on a flexible activities through the API'), ('api_add_deadlineactivity', 'Can add on a flexible activities through the API'), ('api_change_deadlineactivity', 'Can change on a flexible activities through the API'), ('api_delete_deadlineactivity', 'Can delete on a flexible activities through the API'), ('api_read_own_deadlineactivity', 'Can view own on a flexible activities through the API'), ('api_add_own_deadlineactivity', 'Can add own on a flexible activities through the API'), ('api_change_own_deadlineactivity', 'Can change own on a flexible activities through the API'), ('api_delete_own_deadlineactivity', 'Can delete own on a flexible activities through the API')), 'verbose_name': 'Flexible activity', 'verbose_name_plural': 'Flexible activities'},
        ),
        migrations.AlterField(
            model_name='registration',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.DeleteModel(
            name='PeriodActivity',
        ),
        migrations.DeleteModel(
            name='PeriodActivitySlot',
        ),
        migrations.DeleteModel(
            name='TeamSlot',
        ),
    ]
