# Generated by Django 4.2.20 on 2025-04-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0083_auto_20250321_1130'),
        ('geo', '0035_set_alternate_names'),
        ('time_based', '0140_registereddateactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDateParticipant',
            fields=[
                ('contributor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.contributor')),
            ],
            options={
                'verbose_name': 'Participant to registered date activity',
                'verbose_name_plural': 'Participants to registered date activity',
                'permissions': (('api_read_registereddateparticipant', 'Can view participant through the API'), ('api_add_registereddateparticipant', 'Can add participant through the API'), ('api_change_registereddateparticipant', 'Can change participant through the API'), ('api_delete_registereddateparticipant', 'Can delete participant through the API'), ('api_read_own_registereddateparticipant', 'Can view own participant through the API'), ('api_add_own_registereddateparticipant', 'Can add own participant through the API'), ('api_change_own_registereddateparticipant', 'Can change own participant through the API'), ('api_delete_own_registereddateparticipant', 'Can delete own participant through the API')),
            },
            bases=('activities.contributor',),
        ),
        migrations.AddField(
            model_name='registereddateactivity',
            name='location',
            field=models.ForeignKey(blank=True, help_text='If the activity takes place in multiple locations then add the region. You will be able to add specific locations to individual participants when they are scheduled.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.geolocation', verbose_name='location'),
        ),
    ]
