# Generated by Django 4.2.20 on 2025-04-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0141_registereddateparticipant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereddateactivity',
            name='start',
            field=models.DateTimeField(blank=True, help_text='Start of the activity.', null=True, verbose_name='Start date'),
        ),
    ]
