# Generated by Django 3.2.20 on 2024-08-01 12:00
from django.db import connection, migrations

from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions

anonymous_permissions = [
    "api_read_registereddateactivity",
    "view_registereddateparticipant",
]
permissions = [
    # RegisteredDateActivity permissions
    "api_read_own_registereddateactivity",
    "api_add_own_registereddateactivity",
    "api_change_own_registereddateactivity",
    "api_delete_own_registereddateactivity",
    # RegisteredDateParticipant permissions
    "api_read_registereddateparticipant",
    "api_change_registereddateparticipant",
]


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        group_perms = {
            "Anonymous": {"perms": anonymous_permissions},
            "Authenticated": {"perms": anonymous_permissions + permissions},
            "Partner": {"perms": anonymous_permissions + permissions},
        }

        update_group_permissions("time_based", group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ("time_based", "0142_alter_registereddateactivity_start"),
    ]

    operations = [
        migrations.RunPython(add_group_permissions, migrations.RunPython.noop)
    ]
