# Generated by Django 4.2.20 on 2025-08-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0144_alter_registereddateactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebasedactivity',
            name='hour_registration',
            field=models.CharField(blank=True, help_text='Give a link or code for participants to register their hours.', max_length=300, null=True, verbose_name='Hour registration'),
        ),
    ]
