# Generated by Django 4.2.20 on 2025-08-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0145_timebasedactivity_hour_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timebasedactivity',
            name='hour_registration',
        ),
        migrations.AddField(
            model_name='timebasedactivity',
            name='hour_registration_data',
            field=models.CharField(blank=True, help_text='A link or code for participants to register their hours.', max_length=300, null=True, verbose_name='Hour registration'),
        ),
    ]
