# Generated by Django 4.2.20 on 2025-10-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0036_alter_subevent_parent'),
        ('time_based', '0146_remove_timebasedactivity_hour_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateactivityslot',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_slots', to='activity_pub.subevent'),
        ),
    ]
