# Generated by Django 4.2.20 on 2025-11-17 00:00

from django.db import migrations, connection

from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)

    with LocalTenant(tenant):
        time_based_permissions = {
            'Staff': {
                'perms': (
                    # RegisteredDateActivity permissions
                    'add_registereddateactivity', 'change_registereddateactivity', 'delete_registereddateactivity',
                    # RegisteredDateParticipant permissions
                    'add_registereddateparticipant', 'change_registereddateparticipant', 'delete_registereddateparticipant',
                    # Registration base permissions
                    'add_registration', 'change_registration', 'delete_registration',
                    # DateRegistration permissions
                    'add_dateregistration', 'change_dateregistration', 'delete_dateregistration',
                    # DeadlineRegistration permissions
                    'add_deadlineregistration', 'change_deadlineregistration', 'delete_deadlineregistration',
                    # ScheduleRegistration permissions
                    'add_scheduleregistration', 'change_scheduleregistration', 'delete_scheduleregistration',
                    # PeriodicRegistration permissions
                    'add_periodicregistration', 'change_periodicregistration', 'delete_periodicregistration',
                    # TeamScheduleRegistration permissions
                    'add_teamscheduleregistration', 'change_teamscheduleregistration', 'delete_teamscheduleregistration',
                    # DateParticipant permissions
                    'add_dateparticipant', 'change_dateparticipant', 'delete_dateparticipant',
                    # PeriodParticipant permissions
                    'add_periodparticipant', 'change_periodparticipant', 'delete_periodparticipant',
                    # DeadlineParticipant permissions
                    'add_deadlineparticipant', 'change_deadlineparticipant', 'delete_deadlineparticipant',
                    # ScheduleParticipant permissions
                    'add_scheduleparticipant', 'change_scheduleparticipant', 'delete_scheduleparticipant',
                    # TeamScheduleParticipant permissions
                    'add_teamscheduleparticipant', 'change_teamscheduleparticipant', 'delete_teamscheduleparticipant',
                    # PeriodicParticipant permissions
                    'add_periodicparticipant', 'change_periodicparticipant', 'delete_periodicparticipant',
                )
            },
        }

        update_group_permissions('time_based', time_based_permissions, apps)


def remove_group_permissions(apps, schema_editor):
    # Reverse migration - remove permissions from Staff group
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    
    with LocalTenant(tenant):
        from django.contrib.auth.models import Group, Permission
        from django.contrib.contenttypes.models import ContentType
        
        try:
            staff_group = Group.objects.get(name='Staff')
            permission_codenames = [
                'add_registereddateactivity', 'change_registereddateactivity', 'delete_registereddateactivity',
                'add_registereddateparticipant', 'change_registereddateparticipant', 'delete_registereddateparticipant',
                'add_registration', 'change_registration', 'delete_registration',
                'add_dateregistration', 'change_dateregistration', 'delete_dateregistration',
                'add_deadlineregistration', 'change_deadlineregistration', 'delete_deadlineregistration',
                'add_scheduleregistration', 'change_scheduleregistration', 'delete_scheduleregistration',
                'add_periodicregistration', 'change_periodicregistration', 'delete_periodicregistration',
                'add_teamscheduleregistration', 'change_teamscheduleregistration', 'delete_teamscheduleregistration',
                'add_dateparticipant', 'change_dateparticipant', 'delete_dateparticipant',
                'add_periodparticipant', 'change_periodparticipant', 'delete_periodparticipant',
                'add_deadlineparticipant', 'change_deadlineparticipant', 'delete_deadlineparticipant',
                'add_scheduleparticipant', 'change_scheduleparticipant', 'delete_scheduleparticipant',
                'add_teamscheduleparticipant', 'change_teamscheduleparticipant', 'delete_teamscheduleparticipant',
                'add_periodicparticipant', 'change_periodicparticipant', 'delete_periodicparticipant',
            ]
            
            permissions = Permission.objects.filter(
                codename__in=permission_codenames,
                content_type__app_label='time_based'
            )
            
            staff_group.permissions.remove(*permissions)
        except Group.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0146_remove_timebasedactivity_hour_registration_and_more'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions, remove_group_permissions)
    ]

