# Generated by Django 4.2.20 on 2025-12-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0147_add_staff_registration_participant_permissions'),
        ('time_based', '0147_dateactivityslot_origin'),
    ]

    operations = [
    ]
