# Generated by Django 4.2.20 on 2026-03-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0148_merge_20251204_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateregistration',
            options={'base_manager_name': 'objects', 'permissions': (('api_read_dateregistration', 'Can view registration through the API'), ('api_add_dateregistration', 'Can add registration through the API'), ('api_change_dateregistration', 'Can change candidates through the API'), ('api_delete_dateregistration', 'Can delete candidates through the API'), ('api_read_own_dateregistration', 'Can view own candidates through the API'), ('api_add_own_dateregistration', 'Can add own candidates through the API'), ('api_change_own_dateregistration', 'Can change own candidates through the API'), ('api_delete_own_dateregistration', 'Can delete own candidates through the API')), 'verbose_name': 'Candidate for date activities', 'verbose_name_plural': 'Candidates for date activities'},
        ),
        migrations.AlterField(
            model_name='team',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='time_based.registration'),
        ),
    ]
