# Generated by Django 5.2.15 on 2026-08-10 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models, connection

from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        group_perms = {
            'Authenticated': {
                'perms': (
                    'api_add_own_interest',
                    'api_read_own_interest',
                    'api_delete_own_interest',
                    'api_add_interest',
                    'api_read_interest',
                    'api_delete_interest',
                )
            },
            'Staff': {
                'perms': (
                    'add_interest',
                    'change_interest',
                    'delete_interest',
                )
            },
        }
        update_group_permissions('time_based', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0103_alter_confirmationanswer_options_and_more'),
        ('time_based', '0149_alter_dateregistration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='activities.activity')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='time_based.dateactivityslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
                'permissions': (
                    ('api_read_interest', 'Can view interest through the API'),
                    ('api_add_interest', 'Can add interest through the API'),
                    ('api_change_interest', 'Can change interest through the API'),
                    ('api_delete_interest', 'Can delete interest through the API'),
                    ('api_read_own_interest', 'Can view own interest through the API'),
                    ('api_add_own_interest', 'Can add own interest through the API'),
                    ('api_change_own_interest', 'Can change own interest through the API'),
                    ('api_delete_own_interest', 'Can delete own interest through the API'),
                ),
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('slot__isnull', False)),
                        fields=('user', 'slot'),
                        name='unique_interest_user_slot',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(('slot__isnull', True)),
                        fields=('user', 'activity'),
                        name='unique_interest_user_activity',
                    ),
                ],
            },
        ),
        migrations.RunPython(add_group_permissions, migrations.RunPython.noop),
    ]
