# Generated by Django 4.2.20 on 2026-04-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0149_alter_dateregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateparticipant',
            options={'ordering': ('-created',), 'permissions': (('api_read_dateparticipant', 'Can view participant through the API'), ('api_add_dateparticipant', 'Can add participant through the API'), ('api_change_dateparticipant', 'Can change participant through the API'), ('api_delete_dateparticipant', 'Can delete participant through the API'), ('api_read_own_dateparticipant', 'Can view own participant through the API'), ('api_add_own_dateparticipant', 'Can add own participant through the API'), ('api_change_own_dateparticipant', 'Can change own participant through the API'), ('api_delete_own_dateparticipant', 'Can delete own participant through the API')), 'verbose_name': 'Participant to date activity slot', 'verbose_name_plural': 'Participants to date activity slot'},
        ),
        migrations.AlterModelOptions(
            name='deadlineparticipant',
            options={'ordering': ('-created',), 'permissions': (('api_read_deadlineparticipant', 'Can view participant through the API'), ('api_add_deadlineparticipant', 'Can add participant through the API'), ('api_change_deadlineparticipant', 'Can change participant through the API'), ('api_delete_deadlineparticipant', 'Can delete participant through the API'), ('api_read_own_deadlineparticipant', 'Can view own participant through the API'), ('api_add_own_deadlineparticipant', 'Can add own participant through the API'), ('api_change_own_deadlineparticipant', 'Can change own participant through the API'), ('api_delete_own_deadlineparticipant', 'Can delete own participant through the API')), 'verbose_name': 'Participant to flexible activities', 'verbose_name_plural': 'Participants to flexible activities'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ('-created',), 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='scheduleparticipant',
            options={'base_manager_name': 'objects', 'permissions': (('api_read_scheduleparticipant', 'Can view participant through the API'), ('api_add_scheduleparticipant', 'Can add participant through the API'), ('api_change_scheduleparticipant', 'Can change participant through the API'), ('api_delete_scheduleparticipant', 'Can delete participant through the API'), ('api_read_own_scheduleparticipant', 'Can view own participant through the API'), ('api_add_own_scheduleparticipant', 'Can add own participant through the API'), ('api_change_own_scheduleparticipant', 'Can change own participant through the API'), ('api_delete_own_scheduleparticipant', 'Can delete own participant through the API')), 'verbose_name': 'Participant to schedule activities', 'verbose_name_plural': 'Participants to schedule activities'},
        ),
        migrations.AddField(
            model_name='dateactivityslot',
            name='remote_contributor_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='time_based.registration'),
        ),
    ]
