# Generated by Django 5.2.13 on 2026-05-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0150_alter_dateparticipant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateregistration',
            options={'permissions': (('api_read_dateregistration', 'Can view registration through the API'), ('api_add_dateregistration', 'Can add registration through the API'), ('api_change_dateregistration', 'Can change candidates through the API'), ('api_delete_dateregistration', 'Can delete candidates through the API'), ('api_read_own_dateregistration', 'Can view own candidates through the API'), ('api_add_own_dateregistration', 'Can add own candidates through the API'), ('api_change_own_dateregistration', 'Can change own candidates through the API'), ('api_delete_own_dateregistration', 'Can delete own candidates through the API')), 'verbose_name': 'Candidate for date activities', 'verbose_name_plural': 'Candidates for date activities'},
        ),
        migrations.AlterModelOptions(
            name='scheduleparticipant',
            options={'permissions': (('api_read_scheduleparticipant', 'Can view participant through the API'), ('api_add_scheduleparticipant', 'Can add participant through the API'), ('api_change_scheduleparticipant', 'Can change participant through the API'), ('api_delete_scheduleparticipant', 'Can delete participant through the API'), ('api_read_own_scheduleparticipant', 'Can view own participant through the API'), ('api_add_own_scheduleparticipant', 'Can add own participant through the API'), ('api_change_own_scheduleparticipant', 'Can change own participant through the API'), ('api_delete_own_scheduleparticipant', 'Can delete own participant through the API')), 'verbose_name': 'Participant to schedule activities', 'verbose_name_plural': 'Participants to schedule activities'},
        ),
        migrations.AlterModelOptions(
            name='timebasedactivity',
            options={},
        ),
        migrations.RemoveField(
            model_name='dateactivityslot',
            name='origin',
        ),
    ]
