# Generated by Django 5.2.13 on 2026-06-10 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0108_alter_confirmationanswer_options_and_more'),
        ('time_based', '0151_alter_dateregistration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='remote_user',
            field=models.ForeignKey(blank=True, help_text='When set, this registration is a synced participant without a local user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='activities.remotemember', verbose_name='Remote member'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
