# Generated by Django 5.2.15 on 2026-07-29 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0112_merge_20260717_1346'),
        ('time_based', '0152_registration_remote_user_alter_registration_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-created', 'pk'), 'permissions': (('api_read_team', 'Can view a team through the API'), ('api_add_team', 'Can add a team through the API'), ('api_change_team', 'Can change a team through the API'), ('api_delete_team', 'Can delete a team through the API'), ('api_read_own_team', 'Can view own team through the API'), ('api_add_own_team', 'Can add own team through the API'), ('api_change_own_team', 'Can change own team through the API'), ('api_delete_own_team', 'Can delete own team through the API')), 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='team',
            name='remote_user',
            field=models.ForeignKey(blank=True, help_text='When set, this team was synced from another platform without a local captain user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='activities.remotemember', verbose_name='Remote captain'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='remote_user',
            field=models.ForeignKey(blank=True, help_text='When set, this team member was synced from another platform without a local user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='activities.remotemember', verbose_name='Remote member'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_captains', to=settings.AUTH_USER_MODEL, verbose_name='Team captain'),
        ),
    ]
