# Generated by Django 5.2.13 on 2026-09-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0151_merge_0150_interest_0150_registration_closed_status'),
        ('time_based', '0153_team_schedule_activitypub'),
    ]

    operations = [
    ]
