# Generated by Django 4.2.20 on 2025-06-17 12:43

import bluebottle.fsm.triggers
import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_quill.fields
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funding', '0073_alter_payout_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('activities', '0084_alter_activity_organization'),
        ('geo', '0035_set_alternate_names'),
        ('organizations', '0017_auto_20241106_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('target_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('target', bluebottle.utils.fields.MoneyField(blank=True, currency_choices=[('EUR', 'Euro')], decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=12, null=True)),
                ('started', models.DateTimeField(blank=True, null=True, verbose_name='started')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funding.bankaccount')),
                ('impact_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_applications', to='geo.geolocation')),
            ],
            options={
                'verbose_name': 'Grant application',
                'verbose_name_plural': 'Grant applications',
                'permissions': (('api_read_grantapplication', 'Can view grant application through the API'), ('api_add_grantapplication', 'Can add funding through the API'), ('api_change_grantapplication', 'Can change funding through the API'), ('api_delete_grantapplication', 'Can delete funding through the API'), ('api_read_own_grantapplication', 'Can view own funding through the API'), ('api_add_own_grantapplication', 'Can add own funding through the API'), ('api_change_own_grantapplication', 'Can change own funding through the API'), ('api_delete_own_grantapplication', 'Can delete own funding through the API')),
            },
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='GrantFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('currency', bluebottle.utils.fields.CurrencyField(default="<class 'django.db.models.fields.NOT_PROVIDED'>", max_length=3)),
                ('description', django_quill.fields.QuillField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Grant fund',
                'verbose_name_plural': 'Grant funds',
            },
        ),
        migrations.CreateModel(
            name='GrantPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('total', bluebottle.utils.fields.MoneyField(blank=True, currency_choices=[('EUR', 'Euro')], decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=12, null=True)),
                ('status', models.CharField(max_length=40)),
                ('checkout_id', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grant payment',
                'verbose_name_plural': 'Grant payments',
            },
            bases=(bluebottle.fsm.triggers.TriggerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GrantProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='weekly', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grant provider',
                'verbose_name_plural': 'Grant providers',
            },
        ),
        migrations.CreateModel(
            name='LedgerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('amount', bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default=None, default_currency='EUR', max_digits=12)),
                ('type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'credit')])),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_items', to='grant_management.grantfund')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_item', to='contenttypes.contenttype')),
            ],
            bases=(bluebottle.fsm.triggers.TriggerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GrantPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=40)),
                ('date_approved', models.DateTimeField(blank=True, null=True, verbose_name='approved')),
                ('date_started', models.DateTimeField(blank=True, null=True, verbose_name='started')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='completed')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='grant_management.grantapplication', verbose_name='Grant application')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='grant_management.grantpayment')),
            ],
            options={
                'verbose_name': 'Grant payout',
                'verbose_name_plural': 'Grant payouts',
            },
            bases=(bluebottle.fsm.triggers.TriggerMixin, models.Model),
        ),
        migrations.AddField(
            model_name='grantpayment',
            name='grant_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grant_management.grantprovider'),
        ),
        migrations.AddField(
            model_name='grantfund',
            name='grant_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='grant_management.grantprovider'),
        ),
        migrations.AddField(
            model_name='grantfund',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization'),
        ),
        migrations.CreateModel(
            name='GrantDonor',
            fields=[
                ('contributor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.contributor')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('amount', bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default=None, default_currency='EUR', max_digits=12)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='grant_management.grantfund')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='grant_management.grantpayout')),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grants',
            },
            bases=('activities.contributor',),
        ),
        migrations.CreateModel(
            name='GrantDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('amount', bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default=None, default_currency='EUR', max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grant_management.grantfund')),
            ],
            bases=(bluebottle.fsm.triggers.TriggerMixin, models.Model),
        ),
    ]
