# Generated by Django 4.2.20 on 2025-07-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0002_alter_grantfund_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantpayment',
            name='payment_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
