# Generated by Django 4.2.20 on 2025-07-04 12:26

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0003_grantpayment_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantprovider',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
