# Generated by Django 4.2.20 on 2025-07-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0003_grantpayment_payment_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantdonor',
            options={'permissions': (('api_read_grantdonor', 'Can view grant application through the API'), ('api_add_grantdonor', 'Can add funding through the API'), ('api_change_grantdonor', 'Can change funding through the API'), ('api_delete_grantdonor', 'Can delete funding through the API'), ('api_read_own_grantdonor', 'Can view own funding through the API'), ('api_add_own_grantdonor', 'Can add own funding through the API'), ('api_change_own_grantdonor', 'Can change own funding through the API'), ('api_delete_own_grantdonor', 'Can delete own funding through the API')), 'verbose_name': 'Grant', 'verbose_name_plural': 'Grants'},
        ),
        migrations.AlterModelOptions(
            name='grantfund',
            options={'permissions': (('api_read_grantfund', 'Can view grant application through the API'), ('api_add_grantfund', 'Can add funding through the API'), ('api_change_grantfund', 'Can change funding through the API'), ('api_delete_grantfund', 'Can delete funding through the API'), ('api_read_own_grantfund', 'Can view own funding through the API'), ('api_add_own_grantfund', 'Can add own funding through the API'), ('api_change_own_grantfund', 'Can change own funding through the API'), ('api_delete_own_grantfund', 'Can delete own funding through the API'))},
        ),
    ]
