# Generated by Django 4.2.20 on 2025-07-09 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grant_management', '0006_merge_0005_auto_20250704_0855_0005_auto_20250704_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grantfund',
            options={'permissions': (('api_read_grantfund', 'Can view grant application through the API'), ('api_add_grantfund', 'Can add funding through the API'), ('api_change_grantfund', 'Can change funding through the API'), ('api_delete_grantfund', 'Can delete funding through the API'), ('api_read_own_grantfund', 'Can view own funding through the API'), ('api_add_own_grantfund', 'Can add own funding through the API'), ('api_change_own_grantfund', 'Can change own funding through the API'), ('api_delete_own_grantfund', 'Can delete own funding through the API')), 'verbose_name': 'Grant fund', 'verbose_name_plural': 'Grant funds'},
        ),
        migrations.AddField(
            model_name='grantprovider',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_providers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grantpayment',
            name='grant_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='grant_management.grantprovider'),
        ),
        migrations.AlterField(
            model_name='grantprovider',
            name='payment_frequency',
            field=models.CharField(choices=[('1', 'Every week'), ('2', 'Every two weeks'), ('4', 'Every four weeks')], default='weekly', max_length=100),
        ),
    ]
