# Generated by Django 4.2.20 on 2025-07-11 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grant_management', '0007_alter_grantfund_options_grantprovider_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantpayout',
            name='provider',
            field=models.CharField(default='stripe', max_length=100),
        ),
        migrations.AlterField(
            model_name='grantprovider',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='This person will receive the payment requests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_providers', to=settings.AUTH_USER_MODEL, verbose_name='Finance manager'),
        ),
    ]
