# Generated by Django 4.2.20 on 2025-10-17 10:48

from django.db import migrations, connection


def create_contribution_view(apps, schema_editor):
    sql = """
        DROP VIEW IF EXISTS grants;
        CREATE VIEW grants AS
            SELECT
                d.amount,
                d.amount_currency,
                c.status,
                c.created,
                p.date_completed,
                p.date_approved,
                p.date_started
            FROM {0}.grant_management_grantdonor AS d
            JOIN {0}.activities_contributor AS c ON d.contributor_ptr_id = c.id
            LEFT JOIN {0}.grant_management_grantapplication AS a ON a.activity_ptr_id = c.activity_id
            LEFT JOIN {0}.grant_management_grantpayout AS p ON p.activity_id = c.activity_id;
    """.format(connection.tenant.schema_name)

    if connection.tenant.schema_name != 'public':
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0009_auto_20250820_0905'),
    ]

    operations = [
        migrations.RunPython(create_contribution_view, migrations.RunPython.noop),
    ]
