# Generated by Django 4.2.20 on 2025-10-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0010_auto_20251017_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantpayment',
            name='intent_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
