# Generated by Django 4.2.20 on 2025-12-09 13:26

import bluebottle.fsm.triggers
import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grant_management', '0012_add_staff_grant_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantWithdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('amount', bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default=None, default_currency='EUR', max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grant_management.grantfund')),
            ],
            options={
                'abstract': False,
            },
            bases=(bluebottle.fsm.triggers.TriggerMixin, models.Model),
        ),
    ]
