# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-11 12:19
from __future__ import unicode_literals

from django.db import migrations
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'add_image',
                'change_image',
                'delete_image',
                'add_document',
                'change_document',
                'delete_document',
            )
        },
    }

    update_group_permissions('files', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_relatedimage'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
