# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-11 12:19


from django.db import migrations
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'add_relatedimage',
                'change_relatedimage',
                'delete_relatedimage',
            )
        },
    }

    update_group_permissions('files', group_perms, apps)

class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20191111_1533'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
