# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

import bluebottle.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20200401_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=b'files', validators=[bluebottle.utils.validators.FileMimetypeValidator([b'image/png', b'image/jpeg', b'image/gif', b'image/tiff', b'application/msword', b'application/vnd.openxmlformats-officedocument.wordprocessingml.document', b'application/pdf', b'application/vnd.oasis.opendocument.text', b'text/rtf'], None, b'invalid_mimetype')], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=b'files', validators=[bluebottle.utils.validators.FileMimetypeValidator([b'image/png', b'image/jpeg', b'image/gif', b'image/tiff', b'application/msword', b'application/vnd.openxmlformats-officedocument.wordprocessingml.document', b'application/pdf', b'application/vnd.oasis.opendocument.text', b'text/rtf'], None, b'invalid_mimetype')], verbose_name='file'),
        ),
    ]
