# Generated by Django 3.2.20 on 2023-11-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20201117_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
