# Generated by Django 4.2.20 on 2025-09-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0029_image_url'),
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activity_pub.image'),
        ),
    ]
