# Generated by Django 4.2.20 on 2026-04-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_alter_document_owner_alter_image_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='origin',
        ),
    ]
