# Generated by Django 5.2.13 on 2026-06-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_remove_image_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='origin',
            new_name='old_origin',
        ),
    ]
