# Generated by Django 5.2.13 on 2026-06-09 16:30

import bluebottle.utils.fields
import bluebottle.utils.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('publication_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text="To go live, status must be 'Published'.", null=True, verbose_name='publication date')),
                ('publication_end_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='publication end date')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='last modification')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('language', models.CharField(choices="[('en', 'English')]", max_length=7, verbose_name='language')),
                ('full_page', models.BooleanField(default=False, verbose_name='Page without sub-navigation')),
                ('show_title', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'Content page',
                'verbose_name_plural': 'Content pages',
                'ordering': ('language', 'slug'),
                'unique_together': {('language', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('image', 'Image'), ('text_image', 'Text + image'), ('video', 'Video'), ('button', 'Button'), ('spacer', 'Spacer')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('title_text', models.CharField(blank=True, default='', max_length=500)),
                ('title_level', models.PositiveSmallIntegerField(default=1)),
                ('text', models.TextField(blank=True, default='')),
                ('image', bluebottle.utils.fields.ImageField(blank=True, null=True, upload_to='content', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='Image')),
                ('align', models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('ratio', models.PositiveSmallIntegerField(blank=True, default=6, null=True)),
                ('video_url', models.URLField(blank=True, default='')),
                ('video_provider', models.CharField(blank=True, default='', max_length=20)),
                ('button_label', models.CharField(blank=True, default='', max_length=200)),
                ('button_url', models.URLField(blank=True, default='')),
                ('spacer_size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.contentpage')),
            ],
            options={
                'verbose_name': 'Content block',
                'verbose_name_plural': 'Content blocks',
                'ordering': ('sort_order', 'pk'),
            },
        ),
    ]
