# Generated by Django 4.2.20 on 2025-09-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('activitypubmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activitypubmodel')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.activitypubmodel',),
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('activitypubmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activitypubmodel')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.activitypubmodel',),
        ),
        migrations.RemoveField(
            model_name='actor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='actor',
            name='activitypubmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activitypubmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='outbox',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.outbox'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='inbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.inbox'),
        ),
    ]
