# Generated by Django 4.2.20 on 2025-09-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0002_inbox_outbox_remove_actor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='public_key_pem',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
