# Generated by Django 4.2.20 on 2025-09-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0003_publickey_public_key_pem'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypubmodel',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
