# Generated by Django 4.2.20 on 2025-09-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0004_activitypubmodel_is_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypubmodel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
