# Generated by Django 4.2.20 on 2025-09-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0006_remove_activitypubmodel_is_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='to',
        ),
    ]
