# Generated by Django 4.2.20 on 2025-09-09 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_pub', '0007_remove_activity_summary_remove_activity_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
