# Generated by Django 4.2.20 on 2025-09-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0009_alter_person_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activity')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.follow')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.activity',),
        ),
    ]
