# Generated by Django 4.2.20 on 2025-09-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0014_alter_deedparticipant_options'),
        ('activity_pub', '0010_accept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('activitypubmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activitypubmodel')),
                ('name', models.CharField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('activity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='deeds.deed')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.person')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.activitypubmodel',),
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activity')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.event')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.activity',),
        ),
    ]
