# Generated by Django 4.2.20 on 2025-09-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0012_event_description_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypubmodel',
            name='url',
            field=models.URLField(null=True, unique=True),
        ),
    ]
