# Generated by Django 4.2.20 on 2025-09-11 11:10

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0012_event_description_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
