# Generated by Django 4.2.20 on 2025-09-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0013_alter_activitypubmodel_url'),
        ('activity_pub', '0013_alter_event_description'),
    ]

    operations = [
    ]
