# Generated by Django 4.2.20 on 2025-09-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0015_alter_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key_pem', models.CharField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Shared activity', 'verbose_name_plural': 'Shared activities'},
        ),
        migrations.AddField(
            model_name='publickey',
            name='private_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.privatekey'),
        ),
    ]
