# Generated by Django 4.2.20 on 2025-09-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0017_alter_privatekey_private_key_pem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatekey',
            name='private_key_pem',
            field=models.TextField(),
        ),
    ]
