# Generated by Django 4.2.20 on 2025-09-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0094_confirmationanswer_confirmed_and_more'),
        ('activity_pub', '0017_alter_follow_object_puborganization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
    ]
