# Generated by Django 4.2.20 on 2025-09-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0017_alter_follow_object_puborganization_and_more'),
        ('activity_pub', '0018_alter_privatekey_private_key_pem'),
    ]

    operations = [
    ]
