# Generated by Django 4.2.20 on 2025-09-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_alter_organization_options'),
        ('activity_pub', '0019_merge_20250917_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PubOrganization',
            new_name='Organization',
        ),
    ]
