# Generated by Django 4.2.20 on 2025-09-17 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_alter_organization_options'),
        ('activity_pub', '0020_rename_puborganization_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='preferred_username',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_pub_organization', to='organizations.organization'),
        ),
    ]
