# Generated by Django 4.2.20 on 2025-09-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0020_event_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slot_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
