# Generated by Django 4.2.20 on 2025-09-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0094_confirmationanswer_confirmed_and_more'),
        ('activity_pub', '0021_event_slot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity'),
        ),
    ]
