# Generated by Django 4.2.20 on 2025-09-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0022_event_end_event_start_alter_event_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
