# Generated by Django 4.2.20 on 2025-09-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0021_actor_preferred_username_and_more'),
        ('activity_pub', '0023_remove_event_end_date_remove_event_start_date'),
    ]

    operations = [
    ]
