# Generated by Django 4.2.20 on 2025-09-23 13:39

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0025_place_follower_following_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('activitypubmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activitypubmodel')),
                ('street_address', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(max_length=1000)),
                ('address_locality', models.CharField(max_length=1000)),
                ('address_region', models.CharField(max_length=1000)),
                ('address_country', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.activitypubmodel',),
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='place',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='place',
            name='mapbox_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='place',
            name='region',
        ),
        migrations.RemoveField(
            model_name='place',
            name='street_address',
        ),
        migrations.CreateModel(
            name='CrowdFunding',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.event')),
                ('target_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('target', bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default=None, default_currency='EUR', max_digits=12)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.event',),
        ),
        migrations.CreateModel(
            name='GoodDeed',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.event')),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.event',),
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.address'),
        ),
        migrations.CreateModel(
            name='CollectionDrive',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.event')),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.place')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.event',),
        ),
    ]
