# Generated by Django 4.2.20 on 2025-09-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0026_address_alter_event_options_remove_event_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='content',
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
