# Generated by Django 4.2.20 on 2025-09-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0026_address_alter_event_options_remove_event_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='gooddeed',
            old_name='end',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='gooddeed',
            old_name='start',
            new_name='startTime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slot_id',
        ),
    ]
