# Generated by Django 4.2.20 on 2025-09-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0029_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdfunding',
            name='end',
        ),
        migrations.RemoveField(
            model_name='crowdfunding',
            name='start',
        ),
        migrations.RemoveField(
            model_name='gooddeed',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='gooddeed',
            name='startTime',
        ),
        migrations.AddField(
            model_name='crowdfunding',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='crowdfunding',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gooddeed',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gooddeed',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='collectiondrive',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
