# Generated by Django 4.2.20 on 2025-09-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0030_remove_crowdfunding_end_remove_crowdfunding_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfunding',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.place'),
        ),
        migrations.AlterField(
            model_name='crowdfunding',
            name='target',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='crowdfunding',
            name='target_currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='CollectionDrive',
        ),
    ]
