# Generated by Django 4.2.20 on 2025-10-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0032_alter_address_address_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crowdfunding',
            options={'verbose_name': 'Funding', 'verbose_name_plural': 'Funding'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Shared activity', 'verbose_name_plural': 'Shared activities'},
        ),
        migrations.AlterModelOptions(
            name='gooddeed',
            options={'verbose_name': 'Deed', 'verbose_name_plural': 'Deeds'},
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.organization'),
        ),
        migrations.AlterField(
            model_name='crowdfunding',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.place'),
        ),
    ]
