# Generated by Django 4.2.20 on 2025-10-07 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0032_alter_address_address_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crowdfunding',
            options={'verbose_name': 'Funding', 'verbose_name_plural': 'Funding'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Shared activity', 'verbose_name_plural': 'Shared activities'},
        ),
        migrations.AlterModelOptions(
            name='gooddeed',
            options={'verbose_name': 'Deed', 'verbose_name_plural': 'Deeds'},
        ),
        migrations.AlterField(
            model_name='crowdfunding',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.place'),
        ),
        migrations.CreateModel(
            name='DoGoodEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.event')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('event_attendance_mode', models.CharField(choices=[('OnlineEventAttendanceMode', 'online'), ('OfflineEventAttendanceMode', 'offline')], null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.place')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.dogoodevent')),
            ],
            options={
                'verbose_name': 'Do good event',
                'verbose_name_plural': 'Do good event',
            },
            bases=('activity_pub.event',),
        ),
    ]
