# Generated by Django 4.2.20 on 2025-10-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0146_remove_timebasedactivity_hour_registration_and_more'),
        ('activity_pub', '0033_alter_crowdfunding_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogoodevent',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_based.dateactivityslot'),
        ),
    ]
