# Generated by Django 4.2.20 on 2025-10-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0033_alter_crowdfunding_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
