# Generated by Django 4.2.20 on 2025-10-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0146_remove_timebasedactivity_hour_registration_and_more'),
        ('activity_pub', '0034_dogoodevent_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogoodevent',
            options={'verbose_name': 'Do good event', 'verbose_name_plural': 'Do good events'},
        ),
        migrations.RemoveField(
            model_name='dogoodevent',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='dogoodevent',
            name='slot',
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('activitypubmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activitypubmodel')),
                ('name', models.CharField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('event_attendance_mode', models.CharField(choices=[('OnlineEventAttendanceMode', 'online'), ('OfflineEventAttendanceMode', 'offline')], null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.place')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.dogoodevent')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_based.dateactivityslot')),
            ],
            options={
                'verbose_name': 'Sub event',
                'verbose_name_plural': 'Sub events',
            },
            bases=('activity_pub.activitypubmodel',),
        ),
    ]
