# Generated by Django 4.2.20 on 2025-10-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0034_activity_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='inbox',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.inbox'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='outbox',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.outbox'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='public_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.publickey'),
        ),
    ]
