# Generated by Django 4.2.20 on 2025-10-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0034_organization_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='image',
        ),
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.image'),
        ),
    ]
