# Generated by Django 4.2.20 on 2025-10-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0036_default_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('activitypubmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activitypubmodel')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.activitypubmodel',),
        ),
        migrations.AddField(
            model_name='actor',
            name='followers',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.followers'),
        ),
    ]
