# Generated by Django 4.2.20 on 2025-10-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0037_merge_20251009_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedActivity',
            fields=[
            ],
            options={
                'verbose_name': 'Published activity',
                'verbose_name_plural': 'Publihed activities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('activity_pub.event',),
        ),
        migrations.CreateModel(
            name='ReceivedActivity',
            fields=[
            ],
            options={
                'verbose_name': 'Received activity',
                'verbose_name_plural': 'Received activities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('activity_pub.event',),
        ),
        migrations.AlterModelOptions(
            name='dogoodevent',
            options={'base_manager_name': 'objects', 'verbose_name': 'Date activity', 'verbose_name_plural': 'Date activities'},
        ),
        migrations.AddField(
            model_name='event',
            name='partner_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.organization'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='inbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.inbox'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='outbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.outbox'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='public_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.publickey'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_event', to='activity_pub.dogoodevent'),
        ),
    ]
