# Generated by Django 4.2.20 on 2025-10-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0036_alter_subevent_parent'),
        ('activity_pub', '0037_followers_actor_followers'),
    ]

    operations = [
    ]
