# Generated by Django 4.2.20 on 2025-10-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0038_publishedactivity_receivedactivity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='partner_organization',
            new_name='organization',
        ),
    ]
