# Generated by Django 4.2.20 on 2025-10-08 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0038_merge_20251008_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitypubmodel',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='activitypubmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
