# Generated by Django 4.2.20 on 2025-10-17 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_pub', '0039_rename_partner_organization_event_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='default_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Default activity owner'),
        ),
    ]
