# Generated by Django 4.2.20 on 2025-10-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0040_alter_follow_default_owner'),
        ('activity_pub', '0041_dogoodevent_registration_deadline'),
    ]

    operations = [
    ]
