# Generated by Django 4.2.20 on 2025-10-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0001_initial'),
        ('activity_pub', '0041_dogoodevent_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='linked_activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_links.linkedactivity'),
        ),
    ]
