# Generated by Django 4.2.20 on 2025-10-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0043_event_activity_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='adoption_mode',
            field=models.CharField(choices=[('NothingAdoptionMode', 'nothing'), ('LinkAdoptionMode', 'link'), ('PublishAdoptionMode', 'publish'), ('CopyAdoptionMode', 'copy')], default='NothingAdoptionMode', help_text='Select what should happen when a new activity has been received.', verbose_name='Adoption mode'),
        ),
    ]
