# Generated by Django 4.2.20 on 2025-11-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0042_merge_20251022_1100'),
        ('activity_pub', '0043_organization_logo_alter_organization_image'),
    ]

    operations = [
    ]
