# Generated by Django 4.2.20 on 2025-10-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0044_follow_adoption_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='linked_activity',
        ),
        migrations.AlterField(
            model_name='follow',
            name='adoption_mode',
            field=models.CharField(choices=[('NothingAdoptionMode', 'Leave new activities. Adoption is managed manually.'), ('LinkAdoptionMode', 'Create a link to new activities.'), ('PublishAdoptionMode', 'Publish the new activities.'), ('CopyAdoptionMode', 'Create a local copy for new activities.')], default='NothingAdoptionMode', help_text='Select what should happen when a new activity has been received.', verbose_name='Adoption mode'),
        ),
    ]
