# Generated by Django 4.2.20 on 2025-10-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0044_alter_actor_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='publish_type',
            field=models.CharField(blank=True, choices=[('automatic', 'automatic'), ('manual', 'manual')], default='automatic', null=True, verbose_name='Publish settings'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='inbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.inbox'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='outbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.outbox'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='public_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.publickey'),
        ),
    ]
