# Generated by Django 4.2.20 on 2025-12-09 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_pub', '0045_publish_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='recipients',
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.BooleanField(default=False)),
                ('activity',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.activity')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients',
                                            to='activity_pub.actor')),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
                'unique_together': {('activity', 'actor')},
            },
        ),
    ]
