# Generated by Django 4.2.20 on 2026-02-03 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activity_pub', '0046_alter_follower_options_alter_following_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                (
                    'event_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='activity_pub.event',
                    ),
                ),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                (
                    'location',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='activity_pub.place',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Grant application',
                'verbose_name_plural': 'Grant applications',
            },
            bases=('activity_pub.event',),
        ),
    ]
