# Generated by Django 4.2.20 on 2025-10-22 11:46
from django.db import migrations, connection
from django.apps import apps

from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant

def set_default_to(migration_apps, schema_editor):
    Activity = migration_apps.get_model('activity_pub', 'Activity')
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)

    with LocalTenant(tenant):
        for activity in Activity.objects.all():
            content_type = activity.polymorphic_ctype

            model_class = apps.get_model(content_type.app_label, content_type.model)
            activity.to = model_class.objects.get(pk=activity.pk).default_audience

            activity.save()




class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0046_merge_20251022_1343'),
    ]

    operations = [
        migrations.RunPython(set_default_to, migrations.RunPython.noop)
    ]
