# Generated by Django 4.2.20 on 2025-12-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0048_alter_follower_options_alter_following_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='adoption_type',
            field=models.CharField(choices=[('template', 'Use received activities as template to create your own activities.'), ('link', 'Show adopted activities as links to the partner platform.'), ('hosted', 'Activities are managed by the partner platform, sign ups are synced.')], default='template', help_text='Select how a received activity should be adopted.', verbose_name='Adoption type'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='adoption_mode',
            field=models.CharField(choices=[('manual', 'Received activities are adopted manually.'), ('automatic', 'Received activities are always automatically adopted and published.')], default='manual', help_text='Select what should happen when a new activity has been received.', verbose_name='Adoption mode'),
        ),
    ]
