# Generated by Django 4.2.20 on 2025-12-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0047_merge_20251219_1056'),
        ('activity_pub', '0050_follow_publish_mode'),
    ]

    operations = [
    ]
