# Generated by Django 4.2.20 on 2025-12-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0051_merge_20251223_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitypubmodel',
            options={'verbose_name': 'GoodUp Connect object', 'verbose_name_plural': 'GoodUp Connect objects'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name': 'Consumer', 'verbose_name_plural': 'Consumers'},
        ),
        migrations.AlterModelOptions(
            name='following',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='publishedactivity',
            options={'verbose_name': 'Shared activity', 'verbose_name_plural': 'Shated activities'},
        ),
    ]
