# Generated by Django 4.2.20 on 2026-01-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activity_pub', '0052_alter_activitypubmodel_options_alter_follow_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='activity_link',
            new_name='url',
        ),
        migrations.AddField(
            model_name='crowdfunding',
            name='donated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='crowdfunding',
            name='donated_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='crowdfunding',
            name='target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='crowdfunding',
            name='target_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
