# Generated by Django 4.2.20 on 2026-01-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0053_rename_activity_link_event_url_crowdfunding_donated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activity')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('activity_pub.activity',),
        ),
        migrations.CreateModel(
            name='Delete',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activity')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('activity_pub.activity',),
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activity')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('activity_pub.activity',),
        ),
    ]
