# Generated by Django 4.2.20 on 2026-01-21 13:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0054_finish_delete_cancel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Shared/Received activity', 'verbose_name_plural': 'Shared/Received activities'},
        ),
        migrations.AlterModelOptions(
            name='publishedactivity',
            options={'verbose_name': 'Shared activity', 'verbose_name_plural': 'Shared activities'},
        ),
        migrations.AddField(
            model_name='follow',
            name='automatic_adoption_activity_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('funding', 'Funding'), ('grantapplication', 'Grant Application'), ('periodactivity', 'Activity during a period'), ('dateactivity', 'Activity on a specific date'), ('deadlineactivity', 'Activity within a deadline'), ('scheduleactivity', 'Scheduled activity'), ('periodicactivity', 'Periodic Activity'), ('registereddateactivity', 'Past date activity'), ('deed', 'Deed'), ('collect', 'Collect activity')], default='', max_length=300),
            preserve_default=False,
        ),
    ]
