# Generated by Django 4.2.20 on 2026-01-19 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_based', '0148_merge_20251204_1647'),
        ('activity_pub', '0054_finish_delete_cancel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Shared/Received activity', 'verbose_name_plural': 'Shared/Received activities'},
        ),
        migrations.AlterModelOptions(
            name='publishedactivity',
            options={'verbose_name': 'Shared activity', 'verbose_name_plural': 'Shared activities'},
        ),
        migrations.AlterField(
            model_name='crowdfunding',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.place'),
        ),
        migrations.AlterField(
            model_name='dogoodevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.place'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.place'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_based.dateactivityslot'),
        ),
        migrations.CreateModel(
            name='CollectCampaign',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.event')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('type', models.CharField(verbose_name='Type')),
                ('target', models.FloatField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.place')),
            ],
            options={
                'verbose_name': 'Collect campaign',
                'verbose_name_plural': 'Collect campaigns',
            },
            bases=('activity_pub.event',),
        ),
    ]
