# Generated by Django 4.2.20 on 2026-01-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0055_triple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triple',
            name='datatype',
        ),
        migrations.RemoveField(
            model_name='triple',
            name='value',
        ),
        migrations.AlterField(
            model_name='triple',
            name='object',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triple',
            name='predicate',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='triple',
            name='subject',
            field=models.JSONField(),
        ),
    ]
