# Generated by Django 4.2.20 on 2026-01-21 13:16

from django.db import migrations

from bluebottle.initiatives.models import InitiativePlatformSettings


def set_default_activity_types(apps, schema_editor):
    Follow = apps.get_model('activity_pub', 'Follow')
    for follow in Follow.objects.filter(iri__isnull=True):
        if follow.adoption_mode == 'automatic':
            follow.automatic_adoption_activity_types = [
                type for (type, _) in InitiativePlatformSettings.ACTIVITY_TYPES
            ]
            follow.save()


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0055_alter_event_options_alter_publishedactivity_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_activity_types)
    ]
