# Generated by Django 4.2.20 on 2026-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0055_collect_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectcampaign',
            name='type',
        ),
        migrations.AddField(
            model_name='collectcampaign',
            name='collect_type',
            field=models.CharField(max_length=200, null=True, verbose_name='Type'),
        ),
    ]
