# Generated by Django 4.2.20 on 2026-01-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0056_remove_collectcampaign_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectcampaign',
            name='location_hint',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
