# Generated by Django 4.2.20 on 2026-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0057_collectcampaign_location_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogoodevent',
            name='repetition_mode',
            field=models.CharField(choices=[('OnceRepetitionMode', 'once'), ('DailyRepetitionMode', 'daily'), ('WeeklyRepetitionMode', 'weekly'), ('MonthlyRepetitionMode', 'monthly')], default='OnceRepetitionMode', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collectcampaign',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectcampaign',
            name='location_hint',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='collectcampaign',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dogoodevent',
            name='join_mode',
            field=models.CharField(choices=[('OpenJoinMode', 'open'), ('ReviewJoinMode', 'review'), ('SelectedJoinMode', 'selected')], null=True),
        ),
    ]
