# Generated by Django 4.2.20 on 2026-01-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0058_dogoodevent_repetition_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogoodevent',
            name='slot_mode',
            field=models.CharField(choices=[('SetSlotMode', 'set'), ('ScheduledSlotMode', 'scheduled'), ('RepeatedSlotMode', 'periodic')], default='SetSlotMode', null=True),
        ),
        migrations.AlterField(
            model_name='dogoodevent',
            name='repetition_mode',
            field=models.CharField(choices=[('DailyRepetitionMode', 'daily'), ('WeeklyRepetitionMode', 'weekly'), ('MonthlyRepetitionMode', 'monthly')], null=True),
        ),
    ]
