# Generated by Django 4.2.20 on 2026-01-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0061_remove_follow_adoption_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_locality',
            new_name='locality',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='collectcampaign',
            old_name='amount',
            new_name='donated',
        ),
        migrations.RenameField(
            model_name='dogoodevent',
            old_name='registration_deadline',
            new_name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='collectcampaign',
            name='location_hint',
        ),
        migrations.AddField(
            model_name='address',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
