# Generated by Django 4.2.20 on 2026-02-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0061_remove_follow_adoption_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
