# Generated by Django 4.2.20 on 2026-01-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0062_rename_address_country_address_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='logo',
            new_name='icon',
        ),
    ]
