# Generated by Django 4.2.20 on 2026-01-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0063_rename_logo_organization_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publish',
            new_name='Create',
        ),
    ]
