# Generated by Django 4.2.20 on 2026-01-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0065_alter_accept_object_delete_announce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.activitypubmodel'),
        ),
    ]
