# Generated by Django 4.2.20 on 2026-02-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0062_alter_event_summary'),
        ('activity_pub', '0066_alter_accept_object'),
    ]

    operations = [
    ]
