# Generated by Django 4.2.20 on 2026-02-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0047_grantapplication_event'),
        ('activity_pub', '0067_merge_20260202_1139'),
    ]

    operations = [
    ]
