# Generated by Django 4.2.20 on 2026-02-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0067_merge_20260202_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('activitypubmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activitypubmodel')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.activitypubmodel',),
        ),
        migrations.AlterField(
            model_name='dogoodevent',
            name='event_attendance_mode',
            field=models.CharField(blank=True, choices=[('OnlineEventAttendanceMode', 'online'), ('OfflineEventAttendanceMode', 'offline')], null=True),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='event_attendance_mode',
            field=models.CharField(blank=True, choices=[('OnlineEventAttendanceMode', 'online'), ('OfflineEventAttendanceMode', 'offline')], null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('activitypubmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activitypubmodel')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('url', models.URLField(null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.image')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.activitypubmodel',),
        ),
    ]
