# Generated by Django 4.2.20 on 2026-02-18 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_pub', '0068_merge_20260204_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogoodevent',
            name='event_attendance_mode',
            field=models.CharField(blank=True, choices=[('OnlineEventAttendanceMode', 'online'), ('OfflineEventAttendanceMode', 'offline')], null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='default_owner',
            field=models.ForeignKey(blank=True, help_text='This user will be assigned as the activity manager for any activity adopted as a template. It can be left empty and no activity manager will be assigned by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Default activity owner'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='publish_mode',
            field=models.CharField(choices=[('manual', 'Choose which activities you want to share'), ('automatic', 'Activities will be shared when they go live.')], default='manual', verbose_name='Publish mode'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='event_attendance_mode',
            field=models.CharField(blank=True, choices=[('OnlineEventAttendanceMode', 'online'), ('OfflineEventAttendanceMode', 'offline')], null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.activitypubmodel'),
        ),
    ]
