# Generated by Django 4.2.20 on 2026-02-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0068_collection_alter_dogoodevent_event_attendance_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypubmodel',
            name='part_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.collection'),
        ),
    ]
