# Generated by Django 4.2.20 on 2026-02-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0069_activitypubmodel_part_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypubmodel',
            name='part_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='activity_pub.collection'),
        ),
    ]
