# Generated by Django 4.2.20 on 2026-02-24 16:06

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0069_alter_dogoodevent_event_attendance_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='adoption_type',
            field=models.CharField(choices=[('template', 'Use received activities as template to create your own activities.'), ('link', 'Show adopted activities as links to the partner platform.')], default='template', help_text='Select how a received activity should be adopted.', verbose_name='Adoption type'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='automatic_adoption_activity_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('funding', 'Funding'), ('grantapplication', 'Grant Application'), ('periodactivity', 'Activity during a period'), ('dateactivity', 'Activity on a specific date'), ('deadlineactivity', 'Activity within a deadline'), ('scheduleactivity', 'Scheduled activity'), ('periodicactivity', 'Periodic Activity'), ('registereddateactivity', 'Past date activity'), ('deed', 'Deed'), ('collect', 'Collect activity')], help_text='Selected activity types are automatically adopted when they are published.', max_length=300, null=True, verbose_name='Automatically adopted these activity types'),
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activity')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('activity_pub.activity',),
        ),
    ]
