# Generated by Django 4.2.20 on 2026-03-10 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_pub', '0070_alter_follow_adoption_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contributor_count',
            field=models.PositiveIntegerField(default=0, help_text='Total contributors from all platforms'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='adoption_type',
            field=models.CharField(choices=[('clone', 'Use received activities as template to create your own activities.'), ('link', 'Show adopted activities as links to the partner platform.'), ('sync', 'Fully synced copy; participant count syncs with source.')], default='clone', help_text='Select how a received activity should be adopted.', verbose_name='Adoption type'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='default_owner',
            field=models.ForeignKey(blank=True, help_text='This user will be assigned as the activity manager for any activity cloned from a template. It can be left empty and no activity manager will be assigned by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Default activity owner'),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activity')),
                ('participant_sync_id', models.CharField(blank=True, help_text='Stable id to match the participant to remove.', max_length=255, null=True, verbose_name='Participant sync id')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.event')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.activity',),
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activity')),
                ('participant_sync_id', models.CharField(blank=True, help_text='Stable id to match this participant on Leave.', max_length=255, null=True, verbose_name='Participant sync id')),
                ('participant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Participant name')),
                ('participant_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Participant email')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.event')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('activity_pub.activity',),
        ),
    ]
