# Generated by Django 4.2.20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0070_alter_follow_adoption_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='adoption_type',
            field=models.CharField(
                choices=[
                    ('template', 'Use received activities as template to create your own activities.'),
                    ('link', 'Show adopted activities as links to the partner platform.'),
                    ('sync', 'Fully synced copy; participant count syncs with source.'),
                ],
                default='template',
                help_text='Select how a received activity should be adopted.',
                verbose_name='Adoption type',
            ),
        ),
    ]
