# Generated by Django 4.2.20 on 2026-09-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0070_alter_follow_adoption_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='identifiers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
