# Generated by Django 4.2.20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0071_event_contributor_count_alter_follow_adoption_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='sub_event',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='activity_pub.subevent',
            ),
        ),
        migrations.AddField(
            model_name='leave',
            name='sub_event',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='activity_pub.subevent',
            ),
        ),
    ]
