# Generated by Django 4.2.20 on 2026-04-14 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0023_rename_origin_organization_origin_old'),
        ('activity_pub', '0071_remove_organization_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='member',
            new_name='federated_object',
        ),
        migrations.AddField(
            model_name='person',
            name='family_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='given_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='federated_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='organizations.organization'),
        ),
    ]
