# Generated by Django 4.2.20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0071_follow_adoption_type_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooddeed',
            name='synced_participant_count',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Aggregate participant count from Join/Leave across synced platforms.'
            ),
        ),
    ]
