# Generated by Django 4.2.20 on 2026-09-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0071_place_place_type_identifiers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='identifiers',
            new_name='identifier',
        ),
    ]
