# Generated by Django 4.2.20 on 2026-04-15 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0102_remove_activity_origin_and_more'),
        ('activity_pub', '0072_remove_person_member_person_family_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='activity',
            new_name='federated_object',
        ),
        migrations.AlterField(
            model_name='person',
            name='federated_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to=settings.AUTH_USER_MODEL),
        ),
    ]
