# Generated by Django 4.2.20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0072_gooddeed_synced_participant_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('activity_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='activity_pub.activity',
                )),
                ('object', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='activity_pub.event',
                )),
            ],
            options={
                'abstract': False,
            },
            bases=('activity_pub.activity',),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('activity_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='activity_pub.activity',
                )),
                ('object', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='activity_pub.event',
                )),
            ],
            options={
                'abstract': False,
            },
            bases=('activity_pub.activity',),
        ),
    ]
