# Generated by Django 4.2.20

from django.db import migrations, models


def template_to_clone(apps, schema_editor):
    Follow = apps.get_model('activity_pub', 'Follow')
    Follow.objects.filter(adoption_type='template').update(adoption_type='clone')


def clone_to_template(apps, schema_editor):
    Follow = apps.get_model('activity_pub', 'Follow')
    Follow.objects.filter(adoption_type='clone').update(adoption_type='template')


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0073_join_leave_activities'),
    ]

    operations = [
        migrations.RunPython(template_to_clone, clone_to_template),
        migrations.AlterField(
            model_name='follow',
            name='adoption_type',
            field=models.CharField(
                choices=[
                    ('clone', 'Use received activities as template to create your own activities.'),
                    ('link', 'Show adopted activities as links to the partner platform.'),
                    ('sync', 'Fully synced copy; participant count syncs with source.'),
                ],
                default='clone',
                help_text='Select how a received activity should be adopted.',
                verbose_name='Adoption type',
            ),
        ),
    ]
