# Generated by Django 4.2.20 on 2026-04-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_remove_image_origin'),
        ('activities', '0102_remove_activity_origin_and_more'),
        ('activity_pub', '0073_remove_event_activity_event_federated_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='federated_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='files.image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='federated_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to='activities.activity'),
        ),
    ]
