# Generated by Django 4.2.20 on 2026-03-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0073_subevent_contributor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogoodevent',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Overall attendee limit (schema.org maximumAttendeeCapacity). Mirrors time-based activity.', null=True, verbose_name='maximum attendee capacity'),
        ),
        migrations.AddField(
            model_name='subevent',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Per-slot attendee limit (schema.org maximumAttendeeCapacity). Mirrors activity slot.', null=True, verbose_name='maximum attendee capacity'),
        ),
    ]
