# Generated by Django 4.2.20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0074_follow_adoption_type_template_to_clone'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='participant_sync_id',
            field=models.CharField(
                blank=True,
                help_text='Stable id to match this participant on Leave.',
                max_length=255,
                null=True,
                verbose_name='Participant sync id',
            ),
        ),
        migrations.AddField(
            model_name='join',
            name='participant_name',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='Participant name',
            ),
        ),
        migrations.AddField(
            model_name='join',
            name='participant_email',
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name='Participant email',
            ),
        ),
        migrations.AddField(
            model_name='leave',
            name='participant_sync_id',
            field=models.CharField(
                blank=True,
                help_text='Stable id to match the participant to remove.',
                max_length=255,
                null=True,
                verbose_name='Participant sync id',
            ),
        ),
    ]
