# Generated by Django 4.2.20

from django.db import migrations
from django.db.models import Q


def backfill_contributor_count(apps, schema_editor):
    """Set contributor_count = current (synced) + local participants on source deed."""
    GoodDeed = apps.get_model('activity_pub', 'GoodDeed')
    DeedParticipant = apps.get_model('deeds', 'DeedParticipant')
    for good_deed in GoodDeed.objects.all():
        local = DeedParticipant.objects.filter(
            activity__origin_id=good_deed.pk,
            status__in=['accepted', 'succeeded', 'activity_refunded'],
        ).filter(Q(sync_id__isnull=True) | Q(sync_id='')).count()
        if local > 0:
            good_deed.contributor_count = (good_deed.contributor_count or 0) + local
            good_deed.save(update_fields=['contributor_count'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0075_join_leave_participant_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gooddeed',
            old_name='synced_participant_count',
            new_name='contributor_count',
        ),
        migrations.RunPython(backfill_contributor_count, noop),
    ]
