# Generated by Django 4.2.20 on 2026-05-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0074_image_federated_object_alter_event_federated_object'),
        ('activity_pub', '0075_subevent_slot_onetoone'),
    ]

    operations = [
    ]
