# Generated by Django 4.2.20 on 2026-05-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_links', '0023_remove_linkedactivity_show_linkedactivity_archived'),
        ('activity_pub', '0077_remove_join_participant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to='activity_links.linkedactivity'),
        ),
    ]
