# Generated by Django 5.2.13 on 2026-05-19 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0108_alter_confirmationanswer_options_and_more'),
        ('activity_pub', '0079_join_federated_object'),
        ('files', '0017_remove_image_origin'),
        ('organizations', '0023_rename_origin_organization_origin_old'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accept',
            options={},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterModelOptions(
            name='create',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dogoodevent',
            options={'verbose_name': 'Date activity', 'verbose_name_plural': 'Date activities'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inbox',
            options={},
        ),
        migrations.AlterModelOptions(
            name='join',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={},
        ),
        migrations.AlterModelOptions(
            name='outbox',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publickey',
            options={},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='federated_object',
            new_name='adopted',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='federated_object',
            new_name='adopted',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='federated_object',
            new_name='adopted',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='federated_object',
            new_name='adopted',
        ),
        migrations.RemoveField(
            model_name='person',
            name='federated_object',
        ),
        migrations.AddField(
            model_name='event',
            name='origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_pub_model', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='image',
            name='origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_pub_model', to='files.image'),
        ),
        migrations.AddField(
            model_name='join',
            name='origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_pub_model', to='activities.contributor'),
        ),
        migrations.AddField(
            model_name='organization',
            name='origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_pub_model', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='person',
            name='adopted',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='activities.remotemember'),
        ),
        migrations.AddField(
            model_name='person',
            name='origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_pub', to=settings.AUTH_USER_MODEL),
        ),
    ]
