# Generated by Django 5.2.13 on 2026-05-19 15:26

from django.db import migrations

def create_transition_parent(apps, schema_editor):
    Start = apps.get_model('activity_pub', 'Start')
    Finish = apps.get_model('activity_pub', 'Finish')
    Delete = apps.get_model('activity_pub', 'Delete')
    Cancel = apps.get_model('activity_pub', 'Cancel')

    for model in [Start, Finish, Delete, Cancel]:
        print(model.objects.all())
        for transition in model.objects.all():
            __import__('ipdb').set_trace()



class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0082_transition_cancel_transition_ptr_and_more'),
    ]

    operations = [
        migrations.RunPython(create_transition_parent)
    ]
