# Generated by Django 5.2.13 on 2026-05-19 15:26

from django.db import migrations

def create_transition_parent(apps, schema_editor):
    Start = apps.get_model('activity_pub', 'Start')
    Finish = apps.get_model('activity_pub', 'Finish')
    Delete = apps.get_model('activity_pub', 'Delete')
    Cancel = apps.get_model('activity_pub', 'Cancel')
    Transition = apps.get_model('activity_pub', 'Transition')

    for model in [Start, Finish, Delete, Cancel]:
        print(model.objects.all())
        for transition in model.objects.all():
            intermediate = Transition(
                object_id=transition.object_id,
                activity_ptr_id=transition.activity_ptr_id,
                transitioned=transition.transitioned,
                actor_id=transition.actor_id
            )
            intermediate.save()
            transition.transition_ptr_id = intermediate.pk
            transition.save()



class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0082_transition_cancel_transition_ptr_and_more'),
    ]

    operations = [
        migrations.RunPython(create_transition_parent, migrations.RunPython.noop)
    ]
