# Generated by Django 5.2.13 on 2026-05-19 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0083_auto_20260519_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancel',
            name='activity_ptr',
        ),
        migrations.RemoveField(
            model_name='cancel',
            name='object',
        ),
        migrations.RemoveField(
            model_name='cancel',
            name='transitioned',
        ),
        migrations.RemoveField(
            model_name='delete',
            name='activity_ptr',
        ),
        migrations.RemoveField(
            model_name='delete',
            name='object',
        ),
        migrations.RemoveField(
            model_name='delete',
            name='transitioned',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='activity_ptr',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='object',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='transitioned',
        ),
        migrations.RemoveField(
            model_name='start',
            name='activity_ptr',
        ),
        migrations.RemoveField(
            model_name='start',
            name='object',
        ),
        migrations.RemoveField(
            model_name='start',
            name='transitioned',
        ),
        migrations.AlterField(
            model_name='cancel',
            name='transition_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.transition'),
        ),
        migrations.AlterField(
            model_name='delete',
            name='transition_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.transition'),
        ),
        migrations.AlterField(
            model_name='finish',
            name='transition_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.transition'),
        ),
        migrations.AlterField(
            model_name='start',
            name='transition_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.transition'),
        ),
    ]
