# Generated by Django 5.2.13 on 2026-05-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0084_remove_cancel_activity_ptr_remove_cancel_object_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='object',
        ),
        migrations.AddField(
            model_name='join',
            name='object_content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='join',
            name='object_id',
            field=models.PositiveBigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
