# Generated by Django 5.2.13 on 2026-05-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0085_remove_join_object_join_object_content_type_and_more'),
        ('time_based', '0151_alter_dateregistration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subevent',
            name='slot',
        ),
        migrations.AddField(
            model_name='subevent',
            name='adopted',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='time_based.dateactivityslot'),
        ),
        migrations.AddField(
            model_name='subevent',
            name='origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_pub_model', to='time_based.dateactivityslot'),
        ),
    ]
