# Generated by Django 5.2.13 on 2026-06-04 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0087_remove_leave_participant_sync_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.activitypubmodel'),
        ),
    ]
