# Generated by Django 5.2.13 on 2026-06-11 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0088_alter_create_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='activity_ptr',
        ),
        migrations.AddField(
            model_name='join',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='create',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.event'),
        ),
    ]
