# Generated by Django 5.2.13 on 2026-06-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0089_remove_join_adopted_remove_join_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='adopted',
        ),
        migrations.RemoveField(
            model_name='join',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='object',
        ),
        migrations.AddField(
            model_name='leave',
            name='transition_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.transition'),
            preserve_default=False,
        ),
    ]
