# Generated by Django 5.2.13 on 2026-06-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0090_remove_join_adopted_remove_join_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='object_content_type',
        ),
        migrations.RemoveField(
            model_name='join',
            name='object_id',
        ),
        migrations.AddField(
            model_name='join',
            name='object',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='activity_pub.activitypubmodel'),
            preserve_default=False,
        ),
    ]
