# Generated by Django 5.2.13 on 2026-06-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0091_remove_join_object_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='sub_event',
        ),
        migrations.AddField(
            model_name='join',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.organization'),
        ),
    ]
