# Generated by Django 5.2.13 on 2026-06-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0092_remove_join_sub_event_join_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activity')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.activitypubmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('activity_pub.activity',),
        ),
    ]
