# Generated by Django 5.2.13 on 2026-06-25 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0093_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_pub.organization'),
        ),
    ]
