# Generated by Django 5.2.13 on 2026-06-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0096_auto_20260630_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subevent',
            name='adopted',
        ),
        migrations.RemoveField(
            model_name='subevent',
            name='origin',
        ),
    ]
