# Generated by Django 5.2.13 on 2026-07-01 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0099_alter_create_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_pub.activitypubmodel'),
        ),
    ]
