# Generated by Django 5.2.13 on 2026-07-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0111_alter_activity_description'),
        ('activity_pub', '0100_alter_transition_object'),
        ('files', '0018_rename_origin_image_old_origin'),
        ('organizations', '0023_rename_origin_organization_origin_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('transition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.transition')),
            ],
            options={
                'abstract': False,
            },
            bases=('activity_pub.transition',),
        ),
        migrations.AlterField(
            model_name='event',
            name='origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_pub_model', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='image',
            name='origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_pub_model', to='files.image'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_pub_model', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='activity_pub.actor'),
        ),
    ]
