# Generated by Django 5.2.15 on 2026-07-29 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0101_lock_alter_event_origin_alter_image_origin_and_more'),
        ('time_based', '0152_registration_remote_user_alter_registration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogoodevent',
            name='participation_mode',
            field=models.CharField(blank=True, choices=[('IndividualParticipationMode', 'individuals'), ('TeamParticipationMode', 'teams'), ('AnyParticipationMode', 'any')], default='IndividualParticipationMode', null=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('activitypubmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activitypubmodel')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('adopted', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='time_based.team')),
                ('attributed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='activity_pub.dogoodevent')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='activity_pub.person')),
                ('origin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_pub_model', to='time_based.team')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
            bases=('activity_pub.activitypubmodel',),
        ),
        migrations.CreateModel(
            name='Add',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.activity')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='activity_pub.person')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_pub.organization')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adds', to='activity_pub.team')),
            ],
            options={
                'abstract': False,
            },
            bases=('activity_pub.activity',),
        ),
        migrations.AddField(
            model_name='join',
            name='instrument',
            field=models.ForeignKey(blank=True, help_text='Team used when joining a team-schedule activity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joins', to='activity_pub.team'),
        ),
    ]
