# Generated by Django 5.2.15 on 2026-07-29 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0102_team_schedule_activitypub'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team this schedule slot belongs to (team-mode activities).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_events', to='activity_pub.team'),
        ),
    ]
