# Generated by Django 5.2.15 on 2026-08-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0103_subevent_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(
                blank=True,
                default='',
                help_text='Make your activity come alive with a video. You can paste the link to YouTube or Vimeo here.',
                max_length=2048,
                null=True,
                verbose_name='video',
            ),
        ),
    ]
