# Generated by Django 5.2.15 on 2026-08-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0104_event_video_url'),
        ('activity_pub', '0104_leave_forced'),
    ]

    operations = [
    ]
