# Generated by Django 5.2.15 on 2026-08-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0106_remove_leave_forced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='instrument',
            new_name='team',
        ),
    ]
