# Generated by Django 5.2.13 on 2026-09-08 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0106_remove_leave_forced'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remove',
            fields=[
                ('transition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity_pub.transition')),
            ],
            options={
                'abstract': False,
            },
            bases=('activity_pub.transition',),
        ),
    ]
