# Generated by Django 5.2.13 on 2026-09-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0108_basejoin_dateslotremove_registrationleave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
