# Generated by Django 5.2.13 on 2026-09-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0072_rename_place_identifiers'),
        ('activity_pub', '0109_team_name_team_summary'),
    ]

    operations = [
    ]
