# Generated by Django 5.2.13 on 2026-09-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_pub', '0110_merge_20260923_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamJoin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('activity_pub.basejoin',),
        ),
        migrations.CreateModel(
            name='TeamMemberJoin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('activity_pub.basejoin',),
        ),
        migrations.CreateModel(
            name='TeamRemove',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('activity_pub.remove',),
        ),
        migrations.CreateModel(
            name='TeamScheduleSlotJoin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('activity_pub.slotjoin',),
        ),
        migrations.RemoveField(
            model_name='join',
            name='instrument',
        ),
        migrations.DeleteModel(
            name='Add',
        ),
    ]
