# Generated by Django 3.2.19 on 2023-07-10 11:13

import re

from django.db import migrations


def migrate_redirects(apps, schema_editor):
    Redirect = apps.get_model('redirects', 'Redirect')
    Category = apps.get_model('categories', 'Category')

    for redirect in Redirect.objects.all():

        if 'projects' in redirect.new_path:
            redirect.delete()
            continue

        if 'category=' in redirect.new_path:
            print(redirect.new_path)
            pattern = r'.*category=(\d+).*'
            match = re.match(pattern, redirect.new_path)
            if match:
                category_id = match.group(1)
                redirect.new_path = f'/categories/{category_id}/slug/activities/list'
                redirect.save()
            else:
                redirect.delete()
            print(redirect.new_path)


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            migrate_redirects,
            migrations.RunPython.noop
        )
    ]
