from django.core.urlresolvers import reverse_lazy


SCHEMAS = [
    {
        u"attributes": [
            {
                u"caseExact": False,
                u"description": u"An HTTP-addressable URL pointing to the service provider's human-consumable help documentation.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"documentationUri",
                u"referenceTypes": [u"external"],
                u"required": False,
                u"returned": u"default",
                u"type": u"reference",
                u"uniqueness": u"none",
            },
            {
                u"description": u"A complex type that specifies PATCH configuration options.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"patch",
                u"required": True,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"description": u"A Boolean value specifying whether or not the operation is supported.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"supported",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"boolean",
                    }
                ],
                u"type": u"complex",
            },
            {
                u"description": u"A complex type that specifies bulk configuration options.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"bulk",
                u"required": True,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"description": u"A Boolean value specifying whether or not the operation is supported.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"supported",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                    {
                        u"description": u"An integer value specifying the maximum number of operations.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"maxOperations",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"integer",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"An integer value specifying the maximum payload size in bytes.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"maxPayloadSize",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"integer",
                        u"uniqueness": u"none",
                    },
                ],
                u"type": u"complex",
            },
            {
                u"description": u"A complex type that specifies FILTER options.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"filter",
                u"required": True,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"description": u"A Boolean value specifying whether or not the operation is supported.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"supported",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                    {
                        u"description": u"An integer value specifying the maximum number of resources returned in a response.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"maxResults",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"integer",
                        u"uniqueness": u"none",
                    },
                ],
                u"type": u"complex",
            },
            {
                u"description": u"A complex type that specifies configuration options related to changing a password.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"changePassword",
                u"required": True,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"description": u"A Boolean value specifying whether or not the operation is supported.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"supported",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"boolean",
                    }
                ],
                u"type": u"complex",
            },
            {
                u"description": u"A complex type that specifies sort result options.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"sort",
                u"required": True,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"description": u"A Boolean value specifying whether or not the operation is supported.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"supported",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"boolean",
                    }
                ],
                u"type": u"complex",
            },
            {
                u"description": u"A complex type that specifies supported authentication scheme properties.",
                u"multiValued": True,
                u"mutability": u"readOnly",
                u"name": u"authenticationSchemes",
                u"required": True,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"The common authentication scheme name, e.g., HTTP Basic.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"name",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"A description of the authentication scheme.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"description",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"An HTTP-addressable URL pointing to the authentication scheme's specification.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"specUri",
                        u"referenceTypes": [u"external"],
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"reference",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"An HTTP-addressable URL pointing to the authentication scheme's usage documentation.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"documentationUri",
                        u"referenceTypes": [u"external"],
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"reference",
                        u"uniqueness": u"none",
                    },
                ],
                u"type": u"complex",
            },
        ],
        u"description": u"Schema for representing the service provider's configuration",
        u"id": u"urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig",
        "meta": {
            u"location": reverse_lazy(
                "scim-schema-detail",
                args=("urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig",),
            ),
            u"resourceType": u"Schema",
        },
        u"name": u"Service Provider Configuration",
    },
    {
        u"attributes": [
            {
                u"caseExact": False,
                u"description": u"The unique URI of the schema. When applicable, service providers MUST specify the URI.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"id",
                u"required": True,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"The schema's human-readable name.  When applicable, service providers MUST specify the name, e.g., 'User'.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"name",
                u"required": True,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"The schema's human-readable name.  When applicable, service providers MUST specify the name, e.g., 'User'.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"description",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"description": u"A complex attribute that includes the attributes of a schema.",
                u"multiValued": True,
                u"mutability": u"readOnly",
                u"name": u"attributes",
                u"required": True,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": True,
                        u"description": u"The attribute's name.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"name",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"canonicalValues": [
                            u"string",
                            u"complex",
                            u"boolean",
                            u"decimal",
                            u"integer",
                            u"dateTime",
                            u"reference",
                        ],
                        u"caseExact": False,
                        u"description": u"The attribute's data type. Valid values include 'string', 'complex', 'boolean', 'decimal', 'integer', 'dateTime', 'reference'.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"type",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"A Boolean value indicating an attribute's plurality.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"multiValued",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                    {
                        u"caseExact": True,
                        u"description": u"A human-readable description of the attribute.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"description",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"A boolean value indicating whether or not the attribute is required.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"required",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                    {
                        u"caseExact": True,
                        u"description": u"A collection of canonical values.  When applicable, service providers MUST specify the canonical types, e.g., 'work', 'home'.",
                        u"multiValued": True,
                        u"mutability": u"readOnly",
                        u"name": u"canonicalValues",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"A Boolean value indicating whether or not a string attribute is case sensitive.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"caseExact",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                    {
                        u"canonicalValues": [
                            u"readOnly",
                            u"readWrite",
                            u"immutable",
                            u"writeOnly",
                        ],
                        u"caseExact": True,
                        u"description": u"Indicates whether or not an attribute is modifiable.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"mutability",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"canonicalValues": [
                            u"always",
                            u"never",
                            u"default",
                            u"request",
                        ],
                        u"caseExact": True,
                        u"description": u"Indicates when an attribute is returned in a response (e.g., to a query).",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"returned",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"canonicalValues": [u"none", u"server", u"global"],
                        u"caseExact": True,
                        u"description": u"Indicates how unique a value must be.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"uniqueness",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": True,
                        u"description": u"Used only with an attribute of type 'reference'.  Specifies a SCIM resourceType that a reference attribute MAY refer to, e.g., 'User'.",
                        u"multiValued": True,
                        u"mutability": u"readOnly",
                        u"name": u"referenceTypes",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"Used to define the sub-attributes of a complex attribute.",
                        u"multiValued": True,
                        u"mutability": u"readOnly",
                        u"name": u"subAttributes",
                        u"required": False,
                        u"returned": u"default",
                        u"subAttributes": [
                            {
                                u"caseExact": True,
                                u"description": u"The attribute's name.",
                                u"multiValued": False,
                                u"mutability": u"readOnly",
                                u"name": u"name",
                                u"required": True,
                                u"returned": u"default",
                                u"type": u"string",
                                u"uniqueness": u"none",
                            },
                            {
                                u"canonicalValues": [
                                    u"string",
                                    u"complex",
                                    u"boolean",
                                    u"decimal",
                                    u"integer",
                                    u"dateTime",
                                    u"reference",
                                ],
                                u"caseExact": False,
                                u"description": u"The attribute's data type. Valid values include 'string', 'complex', 'boolean', 'decimal', 'integer', 'dateTime', 'reference'.",
                                u"multiValued": False,
                                u"mutability": u"readOnly",
                                u"name": u"type",
                                u"required": True,
                                u"returned": u"default",
                                u"type": u"string",
                                u"uniqueness": u"none",
                            },
                            {
                                u"description": u"A Boolean value indicating an attribute's plurality.",
                                u"multiValued": False,
                                u"mutability": u"readOnly",
                                u"name": u"multiValued",
                                u"required": True,
                                u"returned": u"default",
                                u"type": u"boolean",
                            },
                            {
                                u"caseExact": True,
                                u"description": u"A human-readable description of the attribute.",
                                u"multiValued": False,
                                u"mutability": u"readOnly",
                                u"name": u"description",
                                u"required": False,
                                u"returned": u"default",
                                u"type": u"string",
                                u"uniqueness": u"none",
                            },
                            {
                                u"description": u"A boolean value indicating whether or not the attribute is required.",
                                u"multiValued": False,
                                u"mutability": u"readOnly",
                                u"name": u"required",
                                u"required": False,
                                u"returned": u"default",
                                u"type": u"boolean",
                            },
                            {
                                u"caseExact": True,
                                u"description": u"A collection of canonical values.  When applicable, service providers MUST specify the canonical types, e.g., 'work', 'home'.",
                                u"multiValued": True,
                                u"mutability": u"readOnly",
                                u"name": u"canonicalValues",
                                u"required": False,
                                u"returned": u"default",
                                u"type": u"string",
                                u"uniqueness": u"none",
                            },
                            {
                                u"description": u"A Boolean value indicating whether or not a string attribute is case sensitive.",
                                u"multiValued": False,
                                u"mutability": u"readOnly",
                                u"name": u"caseExact",
                                u"required": False,
                                u"returned": u"default",
                                u"type": u"boolean",
                            },
                            {
                                u"canonicalValues": [
                                    u"readOnly",
                                    u"readWrite",
                                    u"immutable",
                                    u"writeOnly",
                                ],
                                u"caseExact": True,
                                u"description": u"Indicates whether or not an attribute is modifiable.",
                                u"multiValued": False,
                                u"mutability": u"readOnly",
                                u"name": u"mutability",
                                u"required": False,
                                u"returned": u"default",
                                u"type": u"string",
                                u"uniqueness": u"none",
                            },
                            {
                                u"canonicalValues": [
                                    u"always",
                                    u"never",
                                    u"default",
                                    u"request",
                                ],
                                u"caseExact": True,
                                u"description": u"Indicates when an attribute is returned in a response (e.g., to a query).",
                                u"multiValued": False,
                                u"mutability": u"readOnly",
                                u"name": u"returned",
                                u"required": False,
                                u"returned": u"default",
                                u"type": u"string",
                                u"uniqueness": u"none",
                            },
                            {
                                u"canonicalValues": [u"none", u"server", u"global"],
                                u"caseExact": True,
                                u"description": u"Indicates how unique a value must be.",
                                u"multiValued": False,
                                u"mutability": u"readOnly",
                                u"name": u"uniqueness",
                                u"required": False,
                                u"returned": u"default",
                                u"type": u"string",
                                u"uniqueness": u"none",
                            },
                            {
                                u"caseExact": True,
                                u"description": u"Used only with an attribute of type 'reference'.  Specifies a SCIM resourceType that a reference attribute MAY refer to, e.g., 'User'.",
                                u"multiValued": False,
                                u"mutability": u"readOnly",
                                u"name": u"referenceTypes",
                                u"required": False,
                                u"returned": u"default",
                                u"type": u"string",
                                u"uniqueness": u"none",
                            },
                        ],
                        u"type": u"complex",
                    },
                ],
                u"type": u"complex",
            },
        ],
        u"description": u"Specifies the schema that describes a SCIM schema",
        u"id": u"urn:ietf:params:scim:schemas:core:2.0:Schema",
        "meta": {
            u"location": reverse_lazy(
                "scim-schema-detail",
                args=("urn:ietf:params:scim:schemas:core:2.0:Schema",),
            ),
            u"resourceType": u"Schema",
        },
        u"name": u"Schema",
    },
    {
        u"attributes": [
            {
                u"caseExact": False,
                u"description": u"Unique identifier for the User, typically used by the user to directly authenticate to the service provider. Each User MUST include a non-empty userName value.  This identifier MUST be unique across the service provider's entire set of Users. REQUIRED.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"userName",
                u"required": True,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"server",
            },
            {
                u"description": u"The components of the user's real name. Providers MAY return just the full name as a single string in the formatted sub-attribute, or they MAY return just the individual component attributes using the other sub-attributes, or they MAY return both.  If both variants are returned, they SHOULD be describing the same name, with the formatted name indicating how the component attributes should be combined.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"name",
                u"required": False,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"The full name, including all middle names, titles, and suffixes as appropriate, formatted for display (e.g., 'Ms. Barbara J Jensen, III').",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"formatted",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The family name of the User, or last name in most Western languages (e.g., 'Jensen' given the full name 'Ms. Barbara J Jensen, III').",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"familyName",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The given name of the User, or first name in most Western languages (e.g., 'Barbara' given the full name 'Ms. Barbara J Jensen, III').",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"givenName",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The middle name(s) of the User (e.g., 'Jane' given the full name 'Ms. Barbara J Jensen, III').",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"middleName",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The honorific prefix(es) of the User, or title in most Western languages (e.g., 'Ms.' given the full name 'Ms. Barbara J Jensen, III').",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"honorificPrefix",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The honorific suffix(es) of the User, or suffix in most Western languages (e.g., 'III' given the full name 'Ms. Barbara J Jensen, III').",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"honorificSuffix",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                ],
                u"type": u"complex",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"The name of the User, suitable for display to end-users.  The name SHOULD be the full name of the User being described, if known.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"displayName",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"The casual way to address the user in real life, e.g., 'Bob' or 'Bobby' instead of 'Robert'.  This attribute SHOULD NOT be used to represent a User's username (e.g., 'bjensen' or 'mpepperidge').",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"nickName",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"A fully qualified URL pointing to a page representing the User's online profile.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"profileUrl",
                u"referenceTypes": [u"external"],
                u"required": False,
                u"returned": u"default",
                u"type": u"reference",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u'The user\'s title, such as "Vice President."',
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"title",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"Used to identify the relationship between the organization and the user.  Typical values used might be 'Contractor', 'Employee', 'Intern', 'Temp', 'External', and 'Unknown', but any value may be used.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"userType",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"Indicates the User's preferred written or spoken language.  Generally used for selecting a localized user interface; e.g., 'en_US' specifies the language English and country US.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"preferredLanguage",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"Used to indicate the User's default location for purposes of localizing items such as currency, date time format, or numerical representations.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"locale",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"The User's time zone in the 'Olson' time zone database format, e.g., 'America/Los_Angeles'.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"timezone",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"description": u"A Boolean value indicating the User's administrative status.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"active",
                u"required": False,
                u"returned": u"default",
                u"type": u"boolean",
            },
            {
                u"caseExact": False,
                u"description": u"The User's cleartext password.  This attribute is intended to be used as a means to specify an initial password when creating a new User or to reset an existing User's password.",
                u"multiValued": False,
                u"mutability": u"writeOnly",
                u"name": u"password",
                u"required": False,
                u"returned": u"never",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"description": u"Email addresses for the user.  The value SHOULD be canonicalized by the service provider, e.g., 'bjensen@example.com' instead of 'bjensen@EXAMPLE.COM'. Canonical type values of 'work', 'home', and 'other'.",
                u"multiValued": True,
                u"mutability": u"readWrite",
                u"name": u"emails",
                u"required": False,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"Email addresses for the user.  The value SHOULD be canonicalized by the service provider, e.g., 'bjensen@example.com' instead of 'bjensen@EXAMPLE.COM'. Canonical type values of 'work', 'home', and 'other'.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"value",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"A human-readable name, primarily used for display purposes.  READ-ONLY.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"display",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"canonicalValues": [u"work", u"home", u"other"],
                        u"caseExact": False,
                        u"description": u"A label indicating the attribute's function, e.g., 'work' or 'home'.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"type",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"A Boolean value indicating the 'primary' or preferred attribute value for this attribute, e.g., the preferred mailing address or primary email address.  The primary attribute value 'true' MUST appear no more than once.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"primary",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                ],
                u"type": u"complex",
                u"uniqueness": u"none",
            },
            {
                u"description": u"Phone numbers for the User.  The value SHOULD be canonicalized by the service provider according to the format specified in RFC 3966, e.g., 'tel:+1-201-555-0123'. Canonical type values of 'work', 'home', 'mobile', 'fax', 'pager', and 'other'.",
                u"multiValued": True,
                u"mutability": u"readWrite",
                u"name": u"phoneNumbers",
                u"required": False,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"Phone number of the User.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"value",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"A human-readable name, primarily used for display purposes.  READ-ONLY.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"display",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"canonicalValues": [
                            u"work",
                            u"home",
                            u"mobile",
                            u"fax",
                            u"pager",
                            u"other",
                        ],
                        u"caseExact": False,
                        u"description": u"A label indicating the attribute's function, e.g., 'work', 'home', 'mobile'.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"type",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"A Boolean value indicating the 'primary' or preferred attribute value for this attribute, e.g., the preferred phone number or primary phone number.  The primary attribute value 'true' MUST appear no more than once.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"primary",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                ],
                u"type": u"complex",
            },
            {
                u"description": u"Instant messaging addresses for the User.",
                u"multiValued": True,
                u"mutability": u"readWrite",
                u"name": u"ims",
                u"required": False,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"Instant messaging address for the User.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"value",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"A human-readable name, primarily used for display purposes.  READ-ONLY.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"display",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"canonicalValues": [
                            u"aim",
                            u"gtalk",
                            u"icq",
                            u"xmpp",
                            u"msn",
                            u"skype",
                            u"qq",
                            u"yahoo",
                        ],
                        u"caseExact": False,
                        u"description": u"A label indicating the attribute's function, e.g., 'aim', 'gtalk', 'xmpp'.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"type",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"A Boolean value indicating the 'primary' or preferred attribute value for this attribute, e.g., the preferred messenger or primary messenger.  The primary attribute value 'true' MUST appear no more than once.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"primary",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                ],
                u"type": u"complex",
            },
            {
                u"description": u"URLs of photos of the User.",
                u"multiValued": True,
                u"mutability": u"readWrite",
                u"name": u"photos",
                u"required": False,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"URL of a photo of the User.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"value",
                        u"referenceTypes": [u"external"],
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"reference",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"A human-readable name, primarily used for display purposes.  READ-ONLY.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"display",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"canonicalValues": [u"photo", u"thumbnail"],
                        u"caseExact": False,
                        u"description": u"A label indicating the attribute's function, i.e., 'photo' or 'thumbnail'.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"type",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"A Boolean value indicating the 'primary' or preferred attribute value for this attribute, e.g., the preferred photo or thumbnail.  The primary attribute value 'true' MUST appear no more than once.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"primary",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                ],
                u"type": u"complex",
            },
            {
                u"description": u"A physical mailing address for this User. Canonical type values of 'work', 'home', and 'other'.  This attribute is a complex type with the following sub-attributes.",
                u"multiValued": True,
                u"mutability": u"readWrite",
                u"name": u"addresses",
                u"required": False,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"The full mailing address, formatted for display or use with a mailing label.  This attribute MAY contain newlines.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"formatted",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The full street address component, which may include house number, street name, P.O. box, and multi-line extended street address information.  This attribute MAY contain newlines.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"streetAddress",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The city or locality component.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"locality",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The state or region component.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"region",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The zip code or postal code component.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"postalCode",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The country name component.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"country",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"canonicalValues": [u"work", u"home", u"other"],
                        u"caseExact": False,
                        u"description": u"A label indicating the attribute's function, e.g., 'work' or 'home'.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"type",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                ],
                u"type": u"complex",
                u"uniqueness": u"none",
            },
            {
                u"description": u"A list of groups to which the user belongs, either through direct membership, through nested groups, or dynamically calculated.",
                u"multiValued": True,
                u"mutability": u"readOnly",
                u"name": u"groups",
                u"required": False,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"The identifier of the User's group.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"value",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The URI of the corresponding 'Group' resource to which the user belongs.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"$ref",
                        u"referenceTypes": [u"User", u"Group"],
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"reference",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"A human-readable name, primarily used for display purposes.  READ-ONLY.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"display",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"canonicalValues": [u"direct", u"indirect"],
                        u"caseExact": False,
                        u"description": u"A label indicating the attribute's function, e.g., 'direct' or 'indirect'.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"type",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                ],
                u"type": u"complex",
            },
            {
                u"description": u"A list of entitlements for the User that represent a thing the User has.",
                u"multiValued": True,
                u"mutability": u"readWrite",
                u"name": u"entitlements",
                u"required": False,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"The value of an entitlement.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"value",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"A human-readable name, primarily used for display purposes.  READ-ONLY.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"display",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"A label indicating the attribute's function.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"type",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"A Boolean value indicating the 'primary' or preferred attribute value for this attribute.  The primary attribute value 'true' MUST appear no more than once.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"primary",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                ],
                u"type": u"complex",
            },
            {
                u"description": u"A list of roles for the User that collectively represent who the User is, e.g., 'Student', 'Faculty'.",
                u"multiValued": True,
                u"mutability": u"readWrite",
                u"name": u"roles",
                u"required": False,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"The value of a role.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"value",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"A human-readable name, primarily used for display purposes.  READ-ONLY.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"display",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"canonicalValues": [],
                        u"caseExact": False,
                        u"description": u"A label indicating the attribute's function.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"type",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"A Boolean value indicating the 'primary' or preferred attribute value for this attribute.  The primary attribute value 'true' MUST appear no more than once.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"primary",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                ],
                u"type": u"complex",
            },
            {
                u"caseExact": False,
                u"description": u"A list of certificates issued to the User.",
                u"multiValued": True,
                u"mutability": u"readWrite",
                u"name": u"x509Certificates",
                u"required": False,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"The value of an X.509 certificate.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"value",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"binary",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"A human-readable name, primarily used for display purposes.  READ-ONLY.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"display",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"canonicalValues": [],
                        u"caseExact": False,
                        u"description": u"A label indicating the attribute's function.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"type",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"A Boolean value indicating the 'primary' or preferred attribute value for this attribute.  The primary attribute value 'true' MUST appear no more than once.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"primary",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                ],
                u"type": u"complex",
            },
        ],
        u"description": u"User Account",
        u"id": u"urn:ietf:params:scim:schemas:core:2.0:User",
        u"meta": {
            u"location": reverse_lazy(
                "scim-schema-detail",
                args=("urn:ietf:params:scim:schemas:core:2.0:User",),
            ),
            u"resourceType": u"Schema",
        },
        u"name": u"User",
    },
    {
        u"attributes": [
            {
                u"caseExact": False,
                u"description": u"The resource type's server unique id. May be the same as the 'name' attribute.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"id",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"The resource type name.  When applicable, service providers MUST specify the name, e.g., 'User'.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"name",
                u"required": True,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"The resource type's human-readable description.  When applicable, service providers MUST specify the description.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"description",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"The resource type's HTTP-addressable endpoint relative to the Base URL, e.g., '/Users'.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"endpoint",
                u"referenceTypes": [u"uri"],
                u"required": True,
                u"returned": u"default",
                u"type": u"reference",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": True,
                u"description": u"The resource type's primary/base schema URI.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"schema",
                u"referenceTypes": [u"uri"],
                u"required": True,
                u"returned": u"default",
                u"type": u"reference",
                u"uniqueness": u"none",
            },
            {
                u"description": u"A list of URIs of the resource type's schema extensions.",
                u"multiValued": False,
                u"mutability": u"readOnly",
                u"name": u"schemaExtensions",
                u"required": True,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": True,
                        u"description": u"The URI of a schema extension.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"schema",
                        u"referenceTypes": [u"uri"],
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"reference",
                        u"uniqueness": u"none",
                    },
                    {
                        u"description": u"A Boolean value that specifies whether or not the schema extension is required for the resource type.  If true, a resource of this type MUST include this schema extension and also include any attributes declared as required in this schema extension. If false, a resource of this type MAY omit this schema extension.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"required",
                        u"required": True,
                        u"returned": u"default",
                        u"type": u"boolean",
                    },
                ],
                u"type": u"complex",
            },
        ],
        u"description": u"Specifies the schema that describes a SCIM resource type",
        u"id": u"urn:ietf:params:scim:schemas:core:2.0:ResourceType",
        "meta": {
            u"location": reverse_lazy(
                "scim-schema-detail",
                args=("urn:ietf:params:scim:schemas:core:2.0:ResourceType",),
            ),
            u"resourceType": u"Schema",
        },
        u"name": u"ResourceType",
    },
    {
        u"attributes": [
            {
                u"caseExact": False,
                u"description": u"A human-readable name for the Group. REQUIRED.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"displayName",
                u"required": True,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"description": u"A list of members of the Group.",
                u"multiValued": True,
                u"mutability": u"readWrite",
                u"name": u"members",
                u"required": False,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"Identifier of the member of this Group.",
                        u"multiValued": False,
                        u"mutability": u"immutable",
                        u"name": u"value",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The URI corresponding to a SCIM resource that is a member of this Group.",
                        u"multiValued": False,
                        u"mutability": u"immutable",
                        u"name": u"$ref",
                        u"referenceTypes": [u"User", u"Group"],
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"reference",
                        u"uniqueness": u"none",
                    },
                    {
                        u"canonicalValues": [u"User", u"Group"],
                        u"caseExact": False,
                        u"description": u"A label indicating the type of resource, e.g., 'User' or 'Group'.",
                        u"multiValued": False,
                        u"mutability": u"immutable",
                        u"name": u"type",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                ],
                u"type": u"complex",
            },
        ],
        u"description": u"Group",
        u"id": u"urn:ietf:params:scim:schemas:core:2.0:Group",
        u"meta": {
            u"location": reverse_lazy(
                "scim-schema-detail",
                args=("urn:ietf:params:scim:schemas:core:2.0:Group",),
            ),
            u"resourceType": u"Schema",
        },
        u"name": u"Group",
    },
    {
        u"attributes": [
            {
                u"caseExact": False,
                u"description": u"Numeric or alphanumeric identifier assigned to a person, typically based on order of hire or association with anorganization.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"employeeNumber",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"Identifies the name of a cost center.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"costCenter",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"Identifies the name of an organization.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"organization",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"Identifies the name of a division.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"division",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"caseExact": False,
                u"description": u"Identifies the name of a department.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"department",
                u"required": False,
                u"returned": u"default",
                u"type": u"string",
                u"uniqueness": u"none",
            },
            {
                u"description": u"The User's manager. A complex type that optionally allows service providers to represent organizational hierarchy by referencing the 'id' attribute of another User.",
                u"multiValued": False,
                u"mutability": u"readWrite",
                u"name": u"manager",
                u"required": False,
                u"returned": u"default",
                u"subAttributes": [
                    {
                        u"caseExact": False,
                        u"description": u"The id of the SCIM resource representingthe User's manager.  REQUIRED.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"value",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The URI of the SCIM resource representing the User's manager.  REQUIRED.",
                        u"multiValued": False,
                        u"mutability": u"readWrite",
                        u"name": u"$ref",
                        u"referenceTypes": [u"User"],
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"reference",
                        u"uniqueness": u"none",
                    },
                    {
                        u"caseExact": False,
                        u"description": u"The displayName of the User's manager. OPTIONAL and READ-ONLY.",
                        u"multiValued": False,
                        u"mutability": u"readOnly",
                        u"name": u"displayName",
                        u"required": False,
                        u"returned": u"default",
                        u"type": u"string",
                        u"uniqueness": u"none",
                    },
                ],
                u"type": u"complex",
            },
        ],
        u"description": u"Enterprise User",
        u"id": u"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
        u"meta": {
            u"location": u"/v2/Schemas/urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
            u"resourceType": u"Schema",
        },
        u"name": u"EnterpriseUser",
    },
]
