# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-09 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20190529_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='registration deadline'),
        ),
    ]
