# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-03 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20190529_0858'),
        ('assignments', '0002_auto_20190529_1755'),
    ]

    operations = [
    ]
