# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-09 13:07
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'add_assignment', 'change_assignment', 'delete_assignment',
                'add_applicant', 'change_applicant', 'delete_applicant',
            )
        },
        'Anonymous': {
            'perms': (
                'api_read_assignment',
            )
        },
        'Authenticated': {
            'perms': (
                'api_read_assignment',
                'api_add_own_assignment',
                'api_change_own_assignment',
                'api_delete_own_assignment',

                'api_read_applicant',
                'api_add_applicant',
                'api_change_own_applicant',
            )
        }
    }

    update_group_permissions('assignments', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_auto_20190909_1514'),
    ]

    operations = [
        migrations.RunPython(
            add_group_permissions,
            migrations.RunPython.noop
        )
    ]
