# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-09 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20190909_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='registration deadline'),
        ),
    ]
