# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-13 10:04
from __future__ import unicode_literals

import bluebottle.files.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('assignments', '0010_auto_20190911_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='document',
            field=bluebottle.files.fields.DocumentField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Image'),
        ),
    ]
