# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-06 15:49


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_assignment_update_contribution_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('-created',), 'permissions': (('api_read_assignment', 'Can view task through the API'), ('api_add_assignment', 'Can add task through the API'), ('api_change_assignment', 'Can change task through the API'), ('api_delete_assignment', 'Can delete task through the API'), ('api_read_own_assignment', 'Can view own task through the API'), ('api_add_own_assignment', 'Can add own task through the API'), ('api_change_own_assignment', 'Can change own task through the API'), ('api_delete_own_assignment', 'Can delete own task through the API')), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='preparation',
            field=models.FloatField(blank=True, null=True, verbose_name='number of hours required for preparation'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_time',
            field=models.TimeField(blank=True, help_text='On the specific task date, the start time.', null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number of people needed'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='number of hours per person'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_date_type',
            field=models.CharField(blank=True, choices=[(b'deadline', 'Deadline'), (b'on_date', 'On specific date')], default=None, help_text='Does the task have a deadline or does it take place on a specific date.', max_length=50, null=True, verbose_name='date type'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Skill', verbose_name='skill'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Geolocation', verbose_name='task location'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='deadline to apply'),
        ),
    ]
