# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-01 10:21


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0018_auto_20200401_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='document',
        ),
    ]
