# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-12 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0021_auto_20201012_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='online_meeting_url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Online Meeting URL'),
        ),
    ]
