# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-12 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from bluebottle.utils.operations import AlterBaseOperation


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0022_auto_20201013_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contribution_ptr',
            field=models.OneToOneField(
                auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                primary_key=True, serialize=False, to='activities.Intention')
        ),
        AlterBaseOperation(
            model_name='applicant',
            bases=('activities.intention',),
            prev_bases=('activities.contribution',)
        )
    ]
