# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_logger', '0002_auto_20201103_1028'),
        ('payments', '0007_auto_20201103_1028'),
        ('payments_telesom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telesompayment',
            name='payment_ptr',
        ),
        migrations.DeleteModel(
            name='TelesomPayment',
        ),
    ]
