# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-18 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0039_auto_20210218_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deed',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('activities.activity',),
        ),
    ]
