# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-18 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deed',
            options={'permissions': (('api_read_deed', 'Can view deed through the API'), ('api_add_deed', 'Can add deed through the API'), ('api_change_deed', 'Can change deed through the API'), ('api_delete_deed', 'Can delete deed through the API'), ('api_read_own_deed', 'Can view own deed through the API'), ('api_add_own_deed', 'Can add own deed through the API'), ('api_change_own_deed', 'Can change own deed through the API'), ('api_delete_own_deed', 'Can delete own deed through the API')), 'verbose_name': 'Deed', 'verbose_name_plural': 'Deeds'},
        ),
    ]
