# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-22 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0005_auto_20210222_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deedparticipant',
            options={'permissions': (('api_read_deedparticipant', 'Can view deed through the API'), ('api_add_deedparticipant', 'Can add deed through the API'), ('api_change_deedparticipant', 'Can change deed through the API'), ('api_delete_deedparticipant', 'Can delete deed through the API'), ('api_read_own_deedparticipant', 'Can view own deed through the API'), ('api_add_own_deedparticipant', 'Can add own deed through the API'), ('api_change_own_deedparticipant', 'Can change own deed through the API'), ('api_delete_own_deedparticipant', 'Can delete own deed through the API')), 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
    ]
