# Generated by Django 2.2.24 on 2021-09-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0007_auto_20210222_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
