# Generated by Django 2.2.20 on 2021-10-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0008_deed_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='enable_impact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deed',
            name='target',
            field=models.IntegerField(blank=True, help_text='The number of users you want to participate.', null=True),
        ),
    ]
