# Generated by Django 2.2.24 on 2021-12-08 07:33

from django.db import migrations
from django.utils.timezone import now


def succeed_accepted_participants(apps, schema_editor):
    return
    DeedParticipants = apps.get_model('deeds', 'DeedParticipant')
    DeedParticipants.objects.filter(
        status__in=['accepted', 'new'],
        activity__deed__start__lte=now()
    ).update(status='succeeded')
    DeedParticipants.objects.filter(
        status='accepted',
        activity__deed__start__isnull=True
    ).update(status='succeeded')
    EffortContribution = apps.get_model('activities', 'EffortContribution')
    for eff in EffortContribution.objects.filter(
        contributor__status='succeeded',
        status__in=['succeeded', 'new']
    ).all():
        eff.status = 'succeeded'
        eff.start = eff.contributor.created
        eff.save()



class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0009_auto_20211004_1150'),
    ]

    operations = [
        migrations.RunPython(
            succeed_accepted_participants,
            migrations.RunPython.noop
        )
    ]
