# Generated by Django 4.2.20 on 2025-03-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0013_auto_20230626_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deedparticipant',
            options={'permissions': (('api_read_deedparticipant', 'Can view deed through the API'), ('api_add_deedparticipant', 'Can add deed through the API'), ('api_change_deedparticipant', 'Can change deed through the API'), ('api_delete_deedparticipant', 'Can delete deed through the API'), ('api_read_own_deedparticipant', 'Can view own deed through the API'), ('api_add_own_deedparticipant', 'Can add own deed through the API'), ('api_change_own_deedparticipant', 'Can change own deed through the API'), ('api_delete_own_deedparticipant', 'Can delete own deed through the API')), 'verbose_name': 'Deed participant', 'verbose_name_plural': 'Deed participants'},
        ),
    ]
