# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_vitepay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitepaypayment',
            name='payment_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
