# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_vitepay', '0002_vitepaypayment_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitepaypaymentprovider',
            name='prefix',
            field=models.CharField(default=b'goodup', max_length=10),
        ),
    ]
