# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-08 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_vitepay', '0007_auto_20191002_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitepaybankaccount',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vitepaybankaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
