# Generated by Django 4.2.20 on 2025-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_vitepay', '0009_auto_20191111_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitepaybankaccount',
            options={'verbose_name': 'Vitepay bank account', 'verbose_name_plural': 'Vitepay bank accounts'},
        ),
        migrations.AlterModelOptions(
            name='vitepaypayment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='vitepaypaymentprovider',
            name='api_url',
            field=models.CharField(default='https://api.vitepay.com/v1/prod/payments', max_length=100),
        ),
        migrations.AlterField(
            model_name='vitepaypaymentprovider',
            name='prefix',
            field=models.CharField(default='goodup', max_length=10),
        ),
    ]
