# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding_vitepay', '0009_auto_20191111_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitepaybankaccount',
            options={'verbose_name': 'Vitepay bank account', 'verbose_name_plural': 'Vitepay bank accounts'},
        ),
    ]
