# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 13:25
from __future__ import unicode_literals

from bluebottle.clients.utils import LocalTenant

from bluebottle.clients.models import Client

from bluebottle.clients import properties
from django.db import migrations, models, connection


def add_languages(apps, schema_editor):
    Language = apps.get_model('utils', 'Language')
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        for lang in properties.LANGUAGES:
            if lang[0] == 'nl':
                Language.objects.get_or_create(
                    code='nl',
                    language_name='Dutch',
                    native_name='Nederlands'
                )
            elif lang[0] == 'en':
                Language.objects.get_or_create(
                    code='en',
                    language_name='English',
                    native_name='English'
                )
            elif lang[0] == 'fr':
                Language.objects.get_or_create(
                    code='fr',
                    language_name='French',
                    native_name=u'Français'
                )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('language_name', models.CharField(max_length=100)),
                ('native_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['language_name'],
            },
        ),
        migrations.CreateModel(
            name='MetaDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(
            add_languages,
            migrations.RunPython.noop

        )
    ]
