# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_maillog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaDataModel',
        ),
    ]
