# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-26 08:47


from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_maillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationPlatformSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TranslationPlatformSettingsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('locations', models.CharField(blank=True, max_length=100, null=True)),
                ('location_group', models.CharField(blank=True, max_length=100, null=True)),
                ('location_groups', models.CharField(blank=True, max_length=100, null=True)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='utils.TranslationPlatformSettings')),
            ],
            options={
                'managed': True,
                'db_table': 'utils_translationplatformsettings_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'translation platform settings Translation',
            },
        ),
        migrations.DeleteModel(
            name='MetaDataModel',
        ),
        migrations.AlterUniqueTogether(
            name='translationplatformsettingstranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
