# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-06-26 08:53


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20200626_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationplatformsettings',
            options={'verbose_name': 'translation platform settings', 'verbose_name_plural': 'translation settings'},
        ),
    ]
