# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20200626_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationplatformsettingstranslation',
            name='whats_the_location_of_your_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='What\u2019s the location of your office?'),
        ),
    ]
