# Generated by Django 2.2.20 on 2021-08-25 08:18

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20200626_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='language',
            name='sub_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
