# Generated by Django 2.2.20 on 2021-08-25 08:18
from django.db import migrations
from bluebottle.clients import properties


def set_default(apps, schema_editor):
    Language = apps.get_model('utils', 'Language')

    language = Language.objects.get(code=properties.LANGUAGE_CODE)
    language.default = True
    language.save()


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20210825_1018'),
    ]

    operations = [
        migrations.RunPython(set_default, migrations.RunPython.noop)
    ]
