# Generated by Django 2.2.20 on 2021-08-25 08:18
from django.db import migrations, connection
from bluebottle.clients import properties
from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant


def set_default(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        try:
            Language = apps.get_model('utils', 'Language')
            language = Language.objects.get(code=properties.LANGUAGE_CODE)
        except Language.DoesNotExist:
            try:
                language = Language.objects.get()
            except Language.DoesNotExist:
                return

        language.default = True
        language.save()


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20210825_1018'),
    ]

    operations = [
        migrations.RunPython(set_default, migrations.RunPython.noop)
    ]
