# Generated by Django 4.2.20 on 2025-11-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20211012_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationplatformsettings',
            name='translate_user_content',
            field=models.BooleanField(default=False, help_text='Give users the option to translate user generated content.', verbose_name='translate user content'),
        ),
        migrations.DeleteModel(
            name='TranslationPlatformSettingsTranslation',
        ),
    ]
