# Generated by Django 4.2.20 on 2025-11-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_translationplatformsettings_translate_user_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslationPlatformSettings',
        ),
    ]
