from __future__ import absolute_import
from builtins import object
from django.db import models
from django.utils.translation import gettext_lazy as _

from bluebottle.funding.models import Payment, PaymentProvider, PaymentMethod, BankAccount


class LipishaPaymentProvider(PaymentProvider):

    title = 'Lipisha / M-Pesa'

    api_key = models.CharField(max_length=100)
    api_signature = models.CharField(max_length=500)
    prefix = models.CharField(
        max_length=100, default='goodup',
        help_text=_('Use the Lipisha account name e.g. "opc"')
    )
    paybill = models.CharField(
        _('Business Number'), max_length=10,
        help_text='Find this at https://app.lypa.io/payment under `Business Number`')

    @property
    def payment_methods(self):
        return [
            PaymentMethod(
                provider='lipisha',
                name='M-PESA',
                currencies=['KES'],
                code='mpesa'
            )
        ]

    @property
    def private_settings(self):
        return {
            'api_key': self.api_key,
            'api_signature': self.api_signature,
            'prefix': self.prefix
        }

    class Meta(object):
        verbose_name = 'Lipisha payment provider'


class LipishaPayment(Payment):
    mobile_number = models.CharField(max_length=30, blank=True, null=True)
    method = models.CharField(max_length=30, default='Paybill (M-Pesa)')
    transaction = models.CharField(max_length=200, blank=True, null=True)
    unique_id = models.CharField(max_length=30)
    provider = 'lipisha'

    def update(self):
        from bluebottle.funding_lipisha.utils import check_payment_status
        check_payment_status(self)

    def save(self, *args, **kwargs):
        if not self.unique_id:
            provider = LipishaPaymentProvider.objects.get()
            self.unique_id = "{}-{}".format(provider.prefix, self.donation.id)
        super(LipishaPayment, self).save(*args, **kwargs)


class LipishaBankAccount(BankAccount):
    provider_class = LipishaPaymentProvider

    account_number = models.CharField(max_length=50, blank=True, null=True)
    account_name = models.CharField(max_length=200, blank=True, null=True)
    bank_name = models.CharField(max_length=50, blank=True, null=True)
    bank_code = models.CharField(max_length=50, blank=True, null=True)
    branch_name = models.CharField(max_length=200, blank=True, null=True)
    branch_code = models.CharField(max_length=200, blank=True, null=True)
    address = models.CharField(max_length=500, blank=True, null=True)
    swift = models.CharField('SWIFT/Routing Code', max_length=50, blank=True, null=True)

    mpesa_code = models.CharField(
        'MPESA code',
        help_text='Generated by magic',
        unique=True, max_length=50, blank=True, null=True)

    payout_code = models.CharField(
        'Lipisha payout code',
        help_text='Generated by magic',
        unique=True, max_length=50, blank=True, null=True)

    def save(self, *args, **kwargs):
        super(LipishaBankAccount, self).save(*args, **kwargs)

    class Meta(object):
        verbose_name = _('Lipisha bank account')
        verbose_name_plural = _('Lipisha bank accounts')

    class JSONAPIMeta(object):
        resource_name = 'payout-accounts/lipisha-external-accounts'

    @property
    def public_data(self):
        if not self.mpesa_code:
            return {}
        provider = LipishaPaymentProvider.objects.first()

        return {
            'business': provider.paybill,
            'account': self.mpesa_code
        }


from .states import *  # noqa
