# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_resultscontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultpage',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='resultpage',
            old_name='start',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='statscontent',
            name='title',
        ),
        migrations.AddField(
            model_name='resultpage',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='resultpage',
            name='slug',
            field=models.SlugField(default='test', max_length=200, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='value',
            field=models.CharField(blank=True, help_text="Use this for 'manual' input or the override the calculated value.", max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='type',
            field=models.CharField(choices=[(b'manual', 'Manual input'), (b'people_involved', 'People involved'), (b'projects_realized', 'Projects realised'), (b'tasks_realized', 'Tasks realised'), (b'donated_total', 'Donated total'), (b'votes_cast', 'Votes casts')], max_length=40),
        ),
    ]
