# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20161207_0918'),
        ('cms', '0002_shareresultscontent'),
    ]

    operations = [
    ]
