# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_merge_20161207_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Header image'),
        ),
    ]
