# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 14:21
from __future__ import unicode_literals

import bluebottle.cms.models
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20160609_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='meta_image',
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'article', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'text', wagtail.wagtailcore.blocks.RichTextBlock(required=False))])), (b'block_items', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'intro', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'blocks', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'title', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'text', wagtail.wagtailcore.blocks.TextBlock(required=False))]), icon=b'image', template=b'pages/blocks/projects.html')), (b'button', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.TextBlock(required=True)), (b'url', wagtail.wagtailcore.blocks.TextBlock(required=True))], required=False))])), (b'projects', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'projects', wagtail.wagtailcore.blocks.ListBlock(bluebottle.cms.blocks.ProjectChooserBlock()))])), (b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title', icon=b'title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon=b'image')), (b'step_blocks', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'title', wagtail.wagtailcore.blocks.TextBlock(required=False)), (b'text', wagtail.wagtailcore.blocks.TextBlock(required=False))]), icon=b'image', template=b'pages/blocks/projects.html'))], null=True),
        ),
    ]
