# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_auto_20161115_1601'),
        ('cms', '0004_auto_20161201_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultscontent',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
    ]
