# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def forwards_func(apps, schema_editor):
        ResultPage = apps.get_model('cms', 'ResultPage')
        ResultPageTranslation = apps.get_model('cms', 'ResultPageTranslation')

        for object in ResultPage.objects.all():
            ResultPageTranslation.objects.create(
                master_id=object.pk,
                language_code=settings.LANGUAGE_CODE,
                title=object.title,
                slug=object.slug,
                description=object.description
            )


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_resultpage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'managed': True,
                'db_table': 'cms_resultpage_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'result page Translation',
            },
        ),
        migrations.AddField(
            model_name='resultpagetranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.ResultPage'),
        ),
        migrations.RunPython(forwards_func),
        migrations.RemoveField(
            model_name='resultpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resultpage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='resultpage',
            name='title',
        ),
        migrations.AlterUniqueTogether(
            name='resultpagetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
