# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_resultscontent_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='name',
        ),
        migrations.AddField(
            model_name='quotescontent',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotescontent',
            name='title',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='resultscontent',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resultscontent',
            name='title',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='statscontent',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statscontent',
            name='title',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
