# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_projectsmapcontent'),
        ('cms', '0006_auto_20161208_1159'),
    ]

    operations = [
    ]
