# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def forwards_func(apps, schema_editor):
        Quote = apps.get_model('cms', 'Quote')
        QuoteTranslation = apps.get_model('cms', 'QuoteTranslation')

        for object in Quote.objects.all():
            QuoteTranslation.objects.create(
                master_id=object.pk,
                language_code=settings.LANGUAGE_CODE,
                quote=object.quote,
                name=object.name
            )


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20161207_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=30)),
                ('quote', models.CharField(max_length=60)),
            ],
            options={
                'managed': True,
                'db_table': 'cms_quote_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'quote Translation',
            },
        ),
        migrations.AddField(
            model_name='quotetranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.Quote'),
        ),
        migrations.RunPython(forwards_func),
        migrations.RemoveField(
            model_name='quote',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote',
        ),
        migrations.AlterField(
            model_name='resultpagetranslation',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resultpagetranslation',
            name='slug',
            field=models.SlugField(max_length=40, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='resultpagetranslation',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
        migrations.AlterUniqueTogether(
            name='quotetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
