# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_merge_20161212_1501'),
        ('cms', '0008_merge_20161212_1459'),
    ]

    operations = [
    ]
