# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20161214_1524'),
        ('cms', '0012_auto_20161214_1618'),
    ]

    operations = [
    ]
