# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0013_merge_20161214_1637'),
    ]

    operations = [
    ]
