# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20161216_1359'),
        ('cms', '0014_auto_20161216_1424'),
    ]

    operations = [
    ]
