# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_merge_20161219_0946'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='projectimagescontent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='projectscontent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='projectsmapcontent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='quotescontent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='shareresultscontent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='statscontent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='supportertotalcontent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='surveycontent',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='shareresultscontent',
            name='share_title',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectimagescontent',
            name='action_link',
            field=models.CharField(blank=True, default=b'/projects?status=campaign%2Cvoting ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectscontent',
            name='action_text',
            field=models.CharField(blank=True, default='Start your own project', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shareresultscontent',
            name='share_text',
            field=models.CharField(default=b'', help_text=b'{amount}, {projects}, {tasks}, {hours}, {votes}, {people} will be replaced by live statistics', max_length=100),
        ),
        migrations.AlterField(
            model_name='stat',
            name='type',
            field=models.CharField(choices=[(b'manual', 'Manual input'), (b'people_involved', 'People involved'), (b'projects_realized', 'Projects realised'), (b'tasks_realized', 'Tasks realised'), (b'donated_total', 'Donated total'), (b'amount_matched', 'Amount matched'), (b'projects_online', 'Projects Online'), (b'votes_cast', 'Votes casts'), (b'time_spent', 'Time spent')], max_length=25),
        ),
    ]
