# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_add_group_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultpage',
            options={'permissions': (('api_read_resultpage', 'Can view result pages through the API'), ('api_add_resultpage', 'Can add result pages through the API'), ('api_change_resultpage', 'Can change result pages through the API'), ('api_delete_resultpage', 'Can delete result pages through the API'))},
        ),
    ]
