# Generated by Django 1.10.7 on 2017-08-29 07:48
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'add_resultpage', 'change_resultpage', 'delete_resultpage',
            )
        },
        'Anonymous': {
            'perms': ('api_read_resultpage', )
        },
        'Authenticated': {
            'perms': ('api_read_resultpage', )
        }
    }
    update_group_permissions('cms', group_perms, apps)




class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20170829_1005'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
