# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.HomePage')),
            ],
            options={
                'managed': True,
                'db_table': 'cms_homepage_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'home page Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='homepagetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
