# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_quotes(apps, schema_editor):
    Quote = apps.get_model('cms', 'Quote')
    for quote in Quote.objects.all():
        quote.block = quote.quotes.quote_list.get()
        quote.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20171005_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_quotes', to='cms.QuotesContent'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quotes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_quotes', to='cms.Quotes'),
        ),
        migrations.AlterField(
            model_name='quotescontent',
            name='quotes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_list', to='cms.Quotes'),
        ),
        migrations.RunPython(migrate_quotes),
        migrations.RemoveField(
            model_name='quote',
            name='quotes',
        ),
        migrations.RemoveField(
            model_name='quotescontent',
            name='quotes',
        ),
        migrations.AlterField(
            model_name='quote',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes',
                                    to='cms.QuotesContent'),
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
