# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-19 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20171019_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkgroup',
            options={'ordering': ['group_order']},
        ),
        migrations.AddField(
            model_name='linkgroup',
            name='group_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
