# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20171006_1208'),
        ('cms', '0027_migrate_stats_3'),
    ]

    operations = [
    ]
