# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_auto_20171010_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriescontent',
            name='categories',
            field=models.ManyToManyField(db_table=b'cms_taskscontent_categories', to='categories.Category'),
        ),
    ]
