# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_projects(apps, schema_editor):
    ProjectsContent = apps.get_model('cms', 'ProjectsContent')
    for project_block in ProjectsContent.objects.all():
        project_block.new_projects = project_block.projects.projects.all()
        project_block.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_migrate_projects_1'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ProjectsContent',
            managers=[
                ('objects', models.manager.Manager()),
            ],
        ),
        migrations.RunPython(migrate_projects),
    ]
