# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_migrate_projects_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='projectscontent',
            name='projects',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.RenameField(
            model_name='projectscontent',
            old_name='new_projects',
            new_name='projects',
        ),

    ]
