# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-17 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20171017_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='temp_title',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
    ]
