# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_auto_20171018_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='name_tmp',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_tmp',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
