# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 12:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0042_auto_20171018_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotetranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='quotetranslation',
            name='master',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='name_tmp',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_tmp',
            new_name='quote',
        ),
        migrations.DeleteModel(
            name='QuoteTranslation',
        ),
    ]
