# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 12:57
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_auto_20171018_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='image',
            field=bluebottle.utils.fields.ImageField(blank=True, max_length=255, null=True, upload_to=b'quote_images/', verbose_name='Image'),
        ),
    ]
