# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_auto_20171018_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='logoscontent',
            name='action_link',
            field=models.CharField(blank=True, default=b'/start-project', max_length=100, null=True),
        ),
    ]
