# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 13:54
from __future__ import unicode_literals

import bluebottle.utils.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0001_initial'),
        ('cms', '0047_auto_20171018_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', bluebottle.utils.fields.ImageField(blank=True, max_length=255, null=True, upload_to=b'link_images/', verbose_name='Image')),
                ('action_text', models.CharField(max_length=40)),
                ('action_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinksContent',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'contentitem_cms_linkscontent',
                'verbose_name': 'Links',
            },
            bases=('fluent_contents.contentitem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='projectscontent',
            name='action_text',
            field=models.CharField(blank=True, default='Start your own project', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contentlink',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cms.LinksContent'),
        ),
    ]
