# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-30 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_auto_20171027_1419'),
    ]

    operations = [
    ]
