# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-12 13:32
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.db.models.manager
from bluebottle.utils.utils import update_group_permissions


def migrate_site_platform_settings(apps, schema_editor):
    SitePlatformSettings = apps.get_model('cms', 'SitePlatformSettings')
    site_setttings, _ = SitePlatformSettings.objects.get_or_create()
    site_setttings.save()


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Anonymous': {
            'perms': (
                'api_read_page',
            )
        },
        'Authenticated': {
            'perms': (
                'api_read_page',
            )
        },
    }

    update_group_permissions('pages', group_perms, apps)

    group_perms = {
        'Anonymous': {
            'perms': (
                'api_read_newsitem',
            )
        },
        'Authenticated': {
            'perms': (
                'api_read_newsitem',
            )
        },
    }

    update_group_permissions('news', group_perms, apps)


def migrate_start_project(apps, schema_editor):
    Link = apps.get_model('cms', 'Link')
    Language = apps.get_model('utils', 'language')
    english = Language.objects.filter(language_name='English').first()
    dutch = Language.objects.filter(language_name='Dutch').first()
    french = Language.objects.filter(language_name='French').first()

    if english:
        Link.objects.filter(
            component='page',
            component_id='start-project',
            link_group__site_links__language=english.id
        ).update(
            component='initiatives.start',
            component_id='',
            title='Start an initiative'
        )
        Link.objects.filter(
            component='project',
            link_group__site_links__language=english.id
        ).update(
            component='initiatives.activities.list',
            component_id='',
            title='Search activities'
        )

    if dutch:
        Link.objects.filter(
            component='page',
            component_id='start-project',
            link_group__site_links__language=dutch.id
        ).update(
            component='initiatives.start',
            component_id='',
            title='Start een initiatief'
        )
        Link.objects.filter(
            component='project',
            link_group__site_links__language=dutch.id
        ).update(
            component='initiatives.activities.list',
            component_id='',
            title='Zoek activiteiten'
        )

    if french:
        Link.objects.filter(
            component='page',
            component_id='start-project',
            link_group__site_links__language=french.id
        ).update(
            component='initiatives.start',
            component_id='',
            title='Lancez votre participatif'
        )
        Link.objects.filter(
            component='project',
            link_group__site_links__language=french.id
        ).update(
            component='initiatives.activities.list',
            component_id='',
            title='Rechercher des activités'
        )


class Migration(migrations.Migration):

    replaces = [(b'cms', '0054_auto_20171031_1428'), (b'cms', '0021_auto_20171017_2015'), (b'cms', '0022_auto_20171019_1725'), (b'cms', '0023_auto_20171019_2042'), (b'cms', '0024_siteplatformsettings'), (b'cms', '0025_auto_20171024_1600'), (b'cms', '0055_merge_20171031_1713'), (b'cms', '0056_auto_20171102_1527'), (b'cms', '0057_auto_20171103_1438'), (b'cms', '0058_auto_20171110_1230'), (b'cms', '0059_auto_20171121_1022'), (b'cms', '0059_auto_20171121_0959'), (b'cms', '0060_merge_20171121_1334'), (b'cms', '0061_auto_20171128_1135'), (b'cms', '0062_auto_20171128_1355'), (b'cms', '0063_auto_20171204_1049'), (b'cms', '0064_auto_20171220_1145'), (b'cms', '0065_auto_20180313_1401'), (b'cms', '0066_auto_20180709_1657'), (b'cms', '0067_auto_20190710_0938'), (b'cms', '0068_migrate_start_project')]

    dependencies = [
        ('news', '0007_auto_20180709_1706'),
        ('cms', '0053_auto_20171030_1645'),
        ('utils', '0002_maillog'),
        ('fluent_contents', '0001_initial'),
        ('pages', '0009_auto_20180709_1706'),
        ('funding', '0027_merge_20190912_1324'),
    ]

    operations = [
    ]
