# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-31 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0053_auto_20171030_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectscontent',
            name='projects',
            field=models.ManyToManyField(blank=True, db_table=b'cms_projectscontent_projects', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(),
        ),
    ]
