# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-31 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_auto_20171024_1600'),
        ('cms', '0054_auto_20171031_1428'),
    ]

    operations = [
    ]
