# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-29 08:06


import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0056_auto_20191106_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePlatformSettingsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('metadata_title', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata_description', models.TextField(blank=True, null=True)),
                ('metadata_keywords', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'cms_siteplatformsettings_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'site platform settings Translation',
            },
        ),
        migrations.AlterField(
            model_name='link',
            name='component',
            field=models.CharField(blank=True, choices=[(b'page', 'Page'), (b'initiatives.list', 'Initiative Search'), (b'initiatives.start', 'Initiative Start'), (b'initiatives.create', 'Initiative Create'), (b'initiatives.detail', 'Initiative Detail'), (b'initiatives.activities.list', 'Activities Search'), (b'project', 'Project'), (b'task', 'Task'), (b'fundraiser', 'Fundraiser'), (b'results-page', 'Results Page'), (b'news', 'News')], max_length=50, null=True, verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='shareresultscontent',
            name='share_text',
            field=models.CharField(default=b'', help_text=b'{amount}, {fundraisers}, {events}, {tasks}, {hours}, {people} will be replaced by live statistics', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteplatformsettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=b'site_content/', validators=[bluebottle.utils.validators.FileExtensionValidator([b'svg'], None, b'invalid_extension')]),
        ),
        migrations.AlterField(
            model_name='stat',
            name='type',
            field=models.CharField(choices=[(b'manual', 'Manual input'), (b'people_involved', 'People involved'), (b'participants', 'Participants'), (b'activities_succeeded', 'Activities succeeded'), (b'assignments_succeeded', 'Tasks succeeded'), (b'events_succeeded', 'Events succeeded'), (b'fundings_succeeded', 'Funding activities succeeded'), (b'assignment_members', 'Task applicants'), (b'event_members', 'Event participants'), (b'assignments_online', 'Tasks online'), (b'events_online', 'Events online'), (b'fundings_online', 'Funding activities online'), (b'donations', 'Donations'), (b'donated_total', 'Donated total'), (b'pledged_total', 'Pledged total'), (b'amount_matched', 'Amount matched'), (b'activities_online', 'Activities Online'), (b'votes_cast', 'Votes casts'), (b'time_spent', 'Time spent'), (b'members', 'Number of members')], max_length=25),
        ),
        migrations.AddField(
            model_name='siteplatformsettingstranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.SitePlatformSettings'),
        ),
        migrations.AlterUniqueTogether(
            name='siteplatformsettingstranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
