# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-01 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0057_auto_20200129_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteplatformsettingstranslation',
            name='start_page',
            field=models.CharField(blank=True, help_text='Slug of the start initiative page', max_length=100, null=True),
        ),
    ]
