# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0064_auto_20171220_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteplatformsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b'site_content/'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='type',
            field=models.CharField(choices=[(b'manual', 'Manual input'), (b'people_involved', 'People involved'), (b'participants', 'Participants'), (b'projects_realized', 'Projects realised'), (b'projects_complete', 'Projects complete'), (b'tasks_realized', 'Tasks realised'), (b'task_members', 'Taskmembers'), (b'donated_total', 'Donated total'), (b'pledged_total', 'Pledged total'), (b'amount_matched', 'Amount matched'), (b'projects_online', 'Projects Online'), (b'votes_cast', 'Votes casts'), (b'time_spent', 'Time spent'), (b'members', 'Number of members')], max_length=25),
        ),
    ]
