# Generated by Django 2.2.24 on 2022-01-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0065_auto_20220121_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='external_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link_behaviour',
            new_name='open_in_new_tab',
        ),
    ]
