# Generated by Django 2.2.24 on 2022-01-21 13:02

from django.db import migrations


def migrate_old_links(apps, schema_editor):
    Link = apps.get_model('cms', 'Link')

    for link in Link.objects.all():
        if not link.link and link.component:
            if link.component == 'page':
                link.link = f'/pages/{link.component_id}'
        if link.component == 'initiatives.list':
            link.link = f'/initiatives/list'
        if link.component == 'initiatives.start':
            link.link = f'/initiatives/start'
        if link.component == 'initiatives.create':
            link.link = f'/initiatives/start'
        if link.component == 'initiatives.activities.list':
            link.link = f'/initiatives/activities/list'
        if link.component == 'news':
            link.link = f'/news'
        link.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0066_auto_20220121_1401'),
    ]

    operations = [
        migrations.RunPython(
            migrate_old_links,
            migrations.RunPython.noop
        )
    ]
