# Generated by Django 2.2.24 on 2022-01-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0067_auto_20220121_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='component',
        ),
        migrations.RemoveField(
            model_name='link',
            name='component_id',
        ),
    ]
