# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-24 16:16
from __future__ import unicode_literals

from django.db import migrations


def migrate_start_project(apps, schema_editor):
    Link = apps.get_model('cms', 'Link')
    Language = apps.get_model('utils', 'language')
    english = Language.objects.filter(language_name='English').first()
    dutch = Language.objects.filter(language_name='Dutch').first()
    french = Language.objects.filter(language_name='French').first()

    if english:
        Link.objects.filter(
            component='page',
            component_id='start-project',
            link_group__site_links__language=english.id
        ).update(
            component='initiatives.start',
            component_id='',
            title='Start an initiative'
        )
        Link.objects.filter(
            component='project',
            link_group__site_links__language=english.id
        ).update(
            component='initiatives.activities.list',
            component_id='',
            title='Search activities'
        )

    if dutch:
        Link.objects.filter(
            component='page',
            component_id='start-project',
            link_group__site_links__language=dutch.id
        ).update(
            component='initiatives.start',
            component_id='',
            title='Start een initiatief'
        )
        Link.objects.filter(
            component='project',
            link_group__site_links__language=dutch.id
        ).update(
            component='initiatives.activities.list',
            component_id='',
            title='Zoek activiteiten'
        )

    if french:
        Link.objects.filter(
            component='page',
            component_id='start-project',
            link_group__site_links__language=french.id
        ).update(
            component='initiatives.start',
            component_id='',
            title='Lancez votre participatif'
        )
        Link.objects.filter(
            component='project',
            link_group__site_links__language=french.id
        ).update(
            component='initiatives.activities.list',
            component_id='',
            title='Rechercher des activités'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0067_auto_20190710_0938'),
    ]

    operations = [
        migrations.RunPython(migrate_start_project, migrations.RunPython.noop)
    ]
