# Generated by Django 2.2.24 on 2022-08-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0068_auto_20220121_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='statscontent',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
