# Generated by Django 2.2.24 on 2022-08-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0068_auto_20220121_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
