# Generated by Django 2.2.24 on 2022-09-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0070_homepagestatisticscontent_year'),
        ('cms', '0070_auto_20220829_1600'),
    ]

    operations = [
    ]
