# Generated by Django 2.2.24 on 2022-09-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0071_merge_20220906_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitiescontent',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='activitiescontent',
            name='highlighted',
        ),
    ]
