# Generated by Django 2.2.24 on 2023-01-06 11:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0072_auto_20220922_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteplatformsettings',
            name='action_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Colour for action buttons and links', max_length=18, null=True, samples=None, verbose_name='Action colour'),
        ),
        migrations.AddField(
            model_name='siteplatformsettings',
            name='action_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', help_text='If the action colour is quite light, you could set this to a darker colour for better contrast', max_length=18, null=True, samples=None, verbose_name='Action text colour'),
        ),
        migrations.AddField(
            model_name='siteplatformsettings',
            name='description_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Colour for descriptive texts', max_length=18, null=True, samples=None, verbose_name='Description colour'),
        ),
    ]
