# Generated by Django 2.2.24 on 2023-01-10 07:42

import bluebottle.cms.models
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0074_siteplatformsettings_title_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteplatformsettings',
            name='alternative_link_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='If the action colour is quite light, you can set this colour to use for text links', max_length=18, null=True, samples=None, verbose_name='Alternative link colour'),
        ),
        migrations.AddField(
            model_name='siteplatformsettings',
            name='description_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', help_text='If the description colour is quite light, you could set this to a darker colour for better contrast', max_length=18, null=True, samples=None, verbose_name='Description text colour'),
        ),
        migrations.AddField(
            model_name='siteplatformsettings',
            name='footer_color',
            field=colorfield.fields.ColorField(blank=True, default='#3b3b3b', help_text='Colour for platform footer', max_length=18, null=True, samples=None, verbose_name='Footer colour'),
        ),
        migrations.AddField(
            model_name='siteplatformsettings',
            name='footer_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', help_text='If the footer colour is quite light, you could set this to a darker colour for better contrast', max_length=18, null=True, samples=None, verbose_name='Footer text colour'),
        ),
        migrations.AlterField(
            model_name='siteplatformsettings',
            name='description_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Colour for descriptive and secondary buttons', max_length=18, null=True, samples=None, verbose_name='Description colour'),
        ),
        migrations.AlterField(
            model_name='siteplatformsettings',
            name='title_font',
            field=models.FileField(blank=True, help_text='Font to use for titles. Should be .woff2 type', null=True, upload_to='', validators=[bluebottle.cms.models.SitePlatformSettings.validate_file_extension], verbose_name='Title font'),
        ),
    ]
