# Generated by Django 2.2.24 on 2023-01-10 08:33
import os

from bluebottle.clients.models import Client
from django.db import migrations, connection
import json
from os import path
from django.core.files import File
from io import BytesIO

import base64


def migrate_tenant_colors(apps, schema_editor):
    SitePlatformSettings = apps.get_model('cms', 'SitePlatformSettings')
    settings, _ = SitePlatformSettings.objects.get_or_create()
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)

    basepath = path.dirname(__file__)
    with open(f'{basepath}/colors.json') as colors_file:
        data = json.load(colors_file)[tenant.client_name]

    for key, value in data.items():
        if key.endswith('font'):
            file_name, content = value
            content = File(BytesIO(base64.b64decode(content)))
            getattr(settings, key).save(f'{file_name}.woff2', content, save=True)
        else:
            setattr(settings, key, value)
        
    settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0076_siteplatformsettings_body_font'),
    ]

    operations = [
        migrations.RunPython(
            migrate_tenant_colors,
            migrations.RunPython.noop
        )
    ]
