# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-07 10:37
from __future__ import unicode_literals

from django.db import migrations

def set_logo_title(apps, schema_editor):
    LogosContent = apps.get_model('cms', 'LogosContent')

    for content in LogosContent.objects.all():
        content.title = content.action_text
        content.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0077_migrate_tenant_colors_20230110_0933'),
    ]

    operations = [
        migrations.RunPython(set_logo_title, migrations.RunPython.noop)
    ]
