# Generated by Django 2.2.24 on 2023-01-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0078_auto_20230126_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoscontent',
            name='action_link',
        ),
        migrations.RemoveField(
            model_name='logoscontent',
            name='action_text',
        ),
    ]
