# Generated by Django 2.2.24 on 2023-02-14 09:31

import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import fluent_contents.extensions


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0001_initial'),
        ('cms', '0079_auto_20230126_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePlainTextItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('text', models.TextField()),
                ('image', fluent_contents.extensions.PluginImageField(validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='Image')),
                ('align', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=10, verbose_name='Picture placement')),
                ('ratio', models.IntegerField(blank=True, choices=[(8, '2:1 (Text twice as wide)'), (6, '1:1 (Equal width)'), (4, '1:2 (Image twice as wide)')], default=6, verbose_name='Picture / Text ratio')),
            ],
            options={
                'verbose_name': 'Plain Text + Image',
                'verbose_name_plural': 'Plain Text + Image',
                'db_table': 'contentitem_cms_imageplaintextitem',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.CreateModel(
            name='PlainTextItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Plain Text',
                'verbose_name_plural': 'Plain Text',
                'db_table': 'contentitem_cms_plaintextitem',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
