# Generated by Django 2.2.24 on 2023-02-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0080_auto_20230214_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageplaintextitem',
            name='align',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10, verbose_name='Picture placement'),
        ),
        migrations.AlterField(
            model_name='imageplaintextitem',
            name='ratio',
            field=models.CharField(choices=[('0.5', '2:1 (Text twice as wide)'), ('1', '1:1 (Equal width)'), ('2', '1:2 (Image twice as wide)')], default='0.5', max_length=10, verbose_name='Picture / Text ratio'),
        ),
    ]
