# Generated by Django 2.2.24 on 2023-02-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0081_auto_20230214_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentlink',
            name='open_in_new_tab',
            field=models.BooleanField(default=False),
        ),
    ]
