# Generated by Django 2.2.24 on 2023-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0084_auto_20230220_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiescontent',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('highlighted', 'Highlighted'), ('matching', 'Matching preferences'), ('time_based', 'Time based'), ('deed', 'Deeds'), ('funding', 'Crowdfunding'), ('collect', 'Collecting')], default='highlighted', max_length=30, null=True),
        ),
    ]
