# Generated by Django 2.2.24 on 2023-03-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0085_activitiescontent_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsmapcontent',
            options={'verbose_name': 'Activities Map'},
        ),
        migrations.AddField(
            model_name='quote',
            name='role',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='imageplaintextitem',
            name='ratio',
            field=models.CharField(choices=[('0.5', '1:2 (Text twice as wide)'), ('1', '1:1 (Equal width)'), ('2', '2:1 (Image twice as wide)')], default='0.5', max_length=10, verbose_name='Picture / Text ratio'),
        ),
    ]
