# Generated by Django 2.2.24 on 2023-03-08 13:42

import bluebottle.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0086_auto_20230301_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteplatformsettings',
            name='footer_banner',
            field=models.ImageField(blank=True, help_text='Banner shown just above the footer', null=True, upload_to='site_content/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='Footer banner'),
        ),
    ]
