# Generated by Django 2.2.24 on 2023-03-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0087_imageitem'),
        ('cms', '0087_siteplatformsettings_footer_banner'),
    ]

    operations = [
    ]
