# Generated by Django 2.2.24 on 2023-04-13 07:41

import bluebottle.cms.models
import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0088_merge_20230310_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(),
        ),
    ]
