# Generated by Django 3.2.20 on 2024-03-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0090_auto_20230921_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='link_text',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
