# Generated by Django 3.2.20 on 2024-03-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0091_step_link_text"),
        ("cms", "0092_auto_20240301_1346"),
    ]

    operations = []
