# Generated by Django 3.2.20 on 2024-08-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0093_merge_0091_step_link_text_0092_auto_20240301_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmapcontent',
            name='map_type',
            field=models.CharField(choices=[('all', 'Global'), ('office_subregion', 'Office group (based on user office)')], default='all', help_text="The map will show all projects or only projects from the user's office group", max_length=100, verbose_name='Map type'),
        ),
    ]
