# Generated by Django 3.2.20 on 2024-09-05 12:13

import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0065_auto_20221223_1058'),
        ('fluent_contents', '0001_initial'),
        ('cms', '0095_auto_20240815_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageplaintextitem',
            options={'verbose_name': 'Plain Text + Media', 'verbose_name_plural': 'Plain Text + Media'},
        ),
        migrations.AlterField(
            model_name='imageplaintextitem',
            name='ratio',
            field=models.CharField(choices=[('0.5', '1:2 (Text twice as wide)'), ('1', '1:1 (Equal width)'), ('2', '2:1 (Media twice as wide)')], default='0.5', max_length=10, verbose_name='Picture / Text ratio'),
        ),
        migrations.AlterField(
            model_name='projectsmapcontent',
            name='map_type',
            field=models.CharField(choices=[('all', 'Global'), ('office_subregion', 'Office group (based on user office)')], default='all', help_text="The map will show all activities or only from the user's office group", max_length=100, verbose_name='Map type'),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=bluebottle.utils.fields.ImageField(blank=True, help_text='You can upload an image with a 16:9 aspect ratio for best results or an illustration/icon as a square.', max_length=255, null=True, upload_to='step_images/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='DonateButtonContent',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.contentitem')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=400, null=True)),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.funding')),
            ],
            options={
                'verbose_name': 'Donate button',
                'db_table': 'contentitem_cms_donatebuttoncontent',
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
