# Generated by Django 3.2.20 on 2025-03-05 10:33

import bluebottle.utils.fields
import bluebottle.utils.validators
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0002_alter_contentitem_polymorphic_ctype'),
        ('funding', '0070_auto_20250305_1106'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cms', '0098_auto_20250121_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleContent',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.contentitem')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Persons',
                'db_table': 'contentitem_cms_peoplecontent',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.AlterField(
            model_name='donatebuttoncontent',
            name='funding',
            field=models.ForeignKey(limit_choices_to={'status': 'open'}, on_delete=django.db.models.deletion.CASCADE, to='funding.funding', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='link',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that can see this link. Leave empty if it should be visible to everyone.', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='siteplatformsettings',
            name='action_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='If the action colour is quite light, you could set this to a darker colour for better contrast', max_length=18, null=True, samples=None, verbose_name='Action text colour'),
        ),
        migrations.AlterField(
            model_name='siteplatformsettings',
            name='description_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='If the description colour is quite light, you could set this to a darker colour for better contrast', max_length=18, null=True, samples=None, verbose_name='Description text colour'),
        ),
        migrations.AlterField(
            model_name='siteplatformsettings',
            name='footer_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='If the footer colour is quite light, you could set this to a darker colour for better contrast', max_length=18, null=True, samples=None, verbose_name='Footer text colour'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('avatar', bluebottle.utils.fields.ImageField(blank=True, max_length=255, null=True, upload_to='people_images/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='Image')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='cms.peoplecontent')),
            ],
        ),
    ]
