# Generated by Django 3.2.20 on 2025-02-25 14:04

import json
from django.db import migrations

def convert_to_quill(apps, schema_editor):
    ImagePlainTextItem = apps.get_model('cms', 'ImagePlainTextItem')

    for item in ImagePlainTextItem.objects.all(): 
        item.text = json.dumps({"html": item.text, "delta": ""})
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0098_auto_20250121_1140'),
    ]

    operations = [
        migrations.RunPython(convert_to_quill, migrations.RunPython.noop)
    ]
