# Generated by Django 4.2.20 on 2025-03-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0099_auto_20250225_1504'),
        ('cms', '0100_person_phone_number'),
    ]

    operations = [
    ]
