# Generated by Django 4.2.17 on 2025-03-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0101_merge_20250311_1244'),
        ('cms', '0102_merge_20250312_0936'),
    ]

    operations = [
    ]
