# Generated by Django 4.2.20 on 2025-09-12 12:14

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_alter_organization_options'),
        ('cms', '0103_merge_20250312_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteplatformsettings',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organisation this platform belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization'),
        ),
    ]
