# Generated by Django 4.2.20 on 2025-09-26 14:04

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0001_initial'),
        ('cms', '0103_merge_20250312_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.contentitem')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'News items',
                'db_table': 'contentitem_cms_newscontent',
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
