# Generated by Django 4.2.20 on 2025-11-17 00:00

from django.db import migrations, connection

from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)

    with LocalTenant(tenant):
        cms_permissions = {
            'Staff': {
                'perms': (
                    'add_homepage', 'change_homepage', 'delete_homepage',
                    'add_resultpage', 'change_resultpage', 'delete_resultpage',
                    'add_quotescontent', 'change_quotescontent', 'delete_quotescontent',
                    'add_peoplecontent', 'change_peoplecontent', 'delete_peoplecontent',
                    'add_newscontent', 'change_newscontent', 'delete_newscontent',
                    'add_statscontent', 'change_statscontent', 'delete_statscontent',
                    'add_homepagestatisticscontent', 'change_homepagestatisticscontent', 'delete_homepagestatisticscontent',
                    'add_activitiescontent', 'change_activitiescontent', 'delete_activitiescontent',
                    'add_donatebuttoncontent', 'change_donatebuttoncontent', 'delete_donatebuttoncontent',
                    'add_projectscontent', 'change_projectscontent', 'delete_projectscontent',
                    'add_shareresultscontent', 'change_shareresultscontent', 'delete_shareresultscontent',
                    'add_projectsmapcontent', 'change_projectsmapcontent', 'delete_projectsmapcontent',
                    'add_supportertotalcontent', 'change_supportertotalcontent', 'delete_supportertotalcontent',
                    'add_slidescontent', 'change_slidescontent', 'delete_slidescontent',
                    'add_stepscontent', 'change_stepscontent', 'delete_stepscontent',
                    'add_locationscontent', 'change_locationscontent', 'delete_locationscontent',
                    'add_categoriescontent', 'change_categoriescontent', 'delete_categoriescontent',
                    'add_logoscontent', 'change_logoscontent', 'delete_logoscontent',
                    'add_linkscontent', 'change_linkscontent', 'delete_linkscontent',
                    'add_welcomecontent', 'change_welcomecontent', 'delete_welcomecontent',
                    'add_plaintextitem', 'change_plaintextitem', 'delete_plaintextitem',
                    'add_imageplaintextitem', 'change_imageplaintextitem', 'delete_imageplaintextitem',
                    'add_link', 'change_link', 'delete_link',
                    'add_quote', 'change_quote', 'delete_quote',
                    'add_person', 'change_person', 'delete_person',
                    'add_step', 'change_step', 'delete_step',
                    'add_logo', 'change_logo', 'delete_logo',
                    'add_siteplatformsettings', 'change_siteplatformsettings', 'delete_siteplatformsettings',
                )
            },
        }

        update_group_permissions('cms', cms_permissions, apps)




class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0104_newscontent'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions, migrations.RunPython.noop)
    ]

