# Generated by Django 4.2.20 on 2025-10-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0105_alter_imageplaintextitem_options_and_more'),
    ]

    operations = [
    ]
