# Generated by Django 4.2.20 on 2025-10-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0104_newscontent'),
        ('cms', '0105_add_share'),
    ]

    operations = [
    ]
