# Generated by Django 4.2.20 on 2025-10-22 09:18

from django.db import migrations

def set_terminated(apps, schema_editor):
    SitePlatformSettings = apps.get_model('cms', 'SitePlatformSettings')
    AnalyticsPlatformSettings = apps.get_model('analytics', 'AnalyticsPlatformSettings')

    analytics_settings = AnalyticsPlatformSettings.objects.get()
    settings = SitePlatformSettings.objects.get()

    settings.terminated = analytics_settings.terminated
    settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0105_alter_imageplaintextitem_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_terminated, migrations.RunPython.noop)
    ]
