# Generated by Django 4.2.20 on 2025-12-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0105_add_staff_content_permissions'),
        ('cms', '0106_merge_0104_newscontent_0105_add_share'),
    ]

    operations = [
    ]
