# Generated by Django 4.2.20 on 2025-12-08 11:24

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organization_options_organization_origin'),
        ('cms', '0107_merge_20251204_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteplatformsettings',
            name='share_activities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('supplier', 'Supplier'), ('consumer', 'Consumer')], default=[], help_text='Allow sharing and/or receiving activities with other connected partners.', max_length=100, verbose_name='Enable GoodUp Connect'),
        ),
    ]
