# Generated by Django 4.2.20 on 2025-12-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0104_siteplatformsettings_footer_banner_color_logo'),
        ('cms', '0107_merge_20251204_1003'),
    ]

    operations = [
    ]
