# Generated by Django 4.2.20 on 2025-12-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0107_merge_20251204_1003'),
        ('cms', '0108_alter_imageplaintextitem_options_and_more'),
    ]

    operations = [
    ]
