# Generated by Django 4.2.20 on 2025-12-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0105_rename_footer_banner_to_footer_banner_full'),
        ('cms', '0108_merge_20251211_1303'),
    ]

    operations = [
    ]
