# Generated by Django 5.2.13 on 2026-08-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0109_merge_20251212_0846'),
        ('organizations', '0022_merge_20251223_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteplatformsettings',
            name='platform_name',
            field=models.CharField(default='New tenant', max_length=255, verbose_name='Platform name'),
        ),
        migrations.AlterField(
            model_name='siteplatformsettings',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="This is the name other partners will see when you send connection requests or share activities. Use your organisation's official name to ensure partners recognise you.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='GoodUp Connect name'),
        ),
    ]
