# Generated by Django 5.2.13 on 2026-08-18 10:58

from django.db import migrations, connection

from bluebottle.clients.utils import LocalTenant
from bluebottle.clients.models import Client


def set_platform_name(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    SitePlatformSettings = apps.get_model('cms', 'SitePlatformSettings')

    with LocalTenant(tenant):
        settings = SitePlatformSettings.objects.get()
        settings.platform_name = tenant.name
        settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0110_siteplatformsettings_platform_name_and_more'),
    ]

    operations = [
        migrations.RunPython(set_platform_name, migrations.RunPython.noop)
    ]
