# Generated by Django 5.2.15 on 2026-09-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0104_alter_imageplaintextitem_options_and_more'),
        ('cms', '0111_platform_name'),
    ]

    operations = [
    ]
