# Generated by Django 5.2.15 on 2026-09-02 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0111_platform_name'),
        ('fluent_contents', '0002_poll'),
        ('voting', '0002_poll_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollContent',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.contentitem')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=400, null=True)),
                ('poll', models.ForeignKey(limit_choices_to={'status': 'open'}, on_delete=django.db.models.deletion.CASCADE, to='voting.poll', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'Poll',
                'db_table': 'contentitem_cms_pollcontent',
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
