# Generated by Django 5.2.15 on 2026-09-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0112_poll_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollcontent',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='pollcontent',
            name='title',
        ),
        migrations.AlterField(
            model_name='siteplatformsettings',
            name='platform_name',
            field=models.CharField(default='New platform', max_length=255, verbose_name='Platform name'),
        ),
    ]
