# Generated by Django 5.2.15 on 2026-10-01 09:14

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0115_merge_accessible_tint_and_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteplatformsettings',
            name='accessible_colours',
            field=models.BooleanField(default=False, help_text='Make sure the colours are WACG compliant.', verbose_name='Accesible colours'),
        ),
        migrations.AlterField(
            model_name='siteplatformsettings',
            name='action_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Automatically set to white or dark grey so text stays readable on the action colour', max_length=18, null=True, samples=None, verbose_name='Action text colour'),
        ),
        migrations.AlterField(
            model_name='siteplatformsettings',
            name='description_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Automatically set to white or dark grey so text stays readable on the description colour', max_length=18, null=True, samples=None, verbose_name='Description text colour'),
        ),
    ]
