# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybatch',
            name='status',
            field=models.CharField(choices=[(b'new', 'New'), (b'processing', 'Processing'), (b'Done', 'Done')], default=b'new', max_length=20),
        ),
    ]
