# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_donations', '0005_auto_20161004_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybatch',
            name='status',
            field=models.CharField(choices=[(b'new', 'New'), (b'processing', 'Processing'), (b'done', 'Processed')], default=b'new', max_length=20),
        ),
    ]
