# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-02 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding_pledge', '0002_pledgepaymentprovider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pledgepaymentprovider',
            options={'verbose_name': 'Pledge payment provider'},
        ),
    ]
