# Generated by Django 4.2.20 on 2025-12-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding_pledge', '0006_auto_20240917_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pledgepayment',
            options={'base_manager_name': 'objects'},
        ),
    ]
