# Generated by Django 5.2.15 on 2026-09-02 07:29

import bluebottle.fsm.triggers
import bluebottle.utils.fields
import bluebottle.utils.validators
import django.db.models.deletion
import django_quill.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('status', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'poll',
                'verbose_name_plural': 'polls',
                'ordering': ('-id',),
            },
            bases=(bluebottle.fsm.triggers.TriggerMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', bluebottle.utils.fields.ImageField(blank=True, max_length=255, null=True, upload_to='polls/options/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='image')),
                ('video_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='video URL')),
                ('sequence', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.poll', verbose_name='poll')),
            ],
            options={
                'verbose_name': 'poll option',
                'verbose_name_plural': 'poll options',
                'ordering': ['sequence'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PollOptionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', django_quill.fields.QuillField(blank=True, verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='voting.polloption')),
            ],
            options={
                'verbose_name': 'poll option Translation',
                'db_table': 'voting_polloption_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PollTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='subtitle')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='voting.poll')),
            ],
            options={
                'verbose_name': 'poll Translation',
                'db_table': 'voting_poll_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
