# Generated by Django 5.2.15 on 2026-09-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-id',), 'permissions': (('api_read_poll', 'Can view polls through the API'),), 'verbose_name': 'poll', 'verbose_name_plural': 'polls'},
        ),
    ]
