# Generated by Django 5.2.15 on 2026-09-02 11:20

from django.db import connection, migrations

from bluebottle.clients import properties
from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        group_perms = {
            'Anonymous': {
                'perms': ('api_read_poll',) if not properties.CLOSED_SITE else ()
            },
            'Authenticated': {
                'perms': ('api_read_poll',)
            },
        }
        update_group_permissions('voting', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_poll_content'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions, migrations.RunPython.noop),
    ]
