# Generated by Django 5.2.15 on 2026-09-02 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import connection, migrations, models

from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        group_perms = {
            'Authenticated': {
                'perms': (
                    'api_read_own_pollvote',
                    'api_add_own_pollvote',
                    'api_change_own_pollvote',
                    'api_delete_own_pollvote',
                )
            },
        }
        update_group_permissions('voting', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_poll_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.polloption', verbose_name='option')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.poll', verbose_name='poll')),
            ],
            options={
                'verbose_name': 'poll vote',
                'verbose_name_plural': 'poll votes',
                'ordering': ('-created',),
                'permissions': (('api_read_pollvote', 'Can view poll votes through the API'), ('api_read_own_pollvote', 'Can view own poll votes through the API'), ('api_add_own_pollvote', 'Can add own poll votes through the API'), ('api_change_own_pollvote', 'Can change own poll votes through the API'), ('api_delete_own_pollvote', 'Can delete own poll votes through the API')),
                'constraints': [models.UniqueConstraint(fields=('poll', 'owner'), name='unique_vote_per_poll_user')],
            },
        ),
        migrations.RunPython(add_group_permissions, migrations.RunPython.noop),
    ]
