# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-04 09:55
from bluebottle.clients.utils import LocalTenant

from bluebottle.clients.models import Client
from bluebottle.members.models import Member


def run():
    tenant = Client.objects.get(client_name='achmea-voor-elkaar')
    with LocalTenant(tenant):
        for member in Member.objects.filter(
            is_staff=True
        ).exclude(
            email__endswith='goodup.com'
        ).exclude(
            email='admin@example.com'
        ):
            member.set_unusable_password()
            member.save()
