# Generated by Django 4.2.17 on 2025-03-07 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0014_alter_deedparticipant_options'),
        ('pub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteDeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.URLField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('https://schema.org/EventScheduled', 'Scheduled'), ('https://schema.org/EventCancelled', 'Cancelled'), ('https://schema.org/EventPostponed', 'Postponed')], default='https://schema.org/EventScheduled', max_length=100)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('organizer_name', models.CharField(max_length=255)),
                ('organizer_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pub.platform')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPubRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.URLField()),
                ('inbox', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('https://schema.org/CompletedActionStatus', 'Completed'), ('https://schema.org/PendingActionStatus', 'Pending'), ('https://schema.org/CancelledActionStatus', 'Cancelled')], default='https://schema.org/PendingActionStatus', max_length=100)),
                ('participant_name', models.CharField(blank=True, max_length=255)),
                ('deed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitypub_registrations', to='deeds.deed')),
            ],
            options={
                'unique_together': {('deed', 'actor')},
            },
        ),
    ]
