# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 11:15
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_auto_20160523_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpayout',
            name='organization_fee_excl_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='organizationpayout',
            name='organization_fee_incl_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='organizationpayout',
            name='organization_fee_vat_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='organizationpayout',
            name='other_costs_excl_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='organizationpayout',
            name='other_costs_incl_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='organizationpayout',
            name='other_costs_vat_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='organizationpayout',
            name='payable_amount_excl_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='organizationpayout',
            name='payable_amount_incl_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='organizationpayout',
            name='payable_amount_vat_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='organizationpayout',
            name='psp_fee_excl_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='organizationpayout',
            name='psp_fee_incl_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='organizationpayout',
            name='psp_fee_vat_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='projectpayout',
            name='amount_payable_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='projectpayout',
            name='amount_raised_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='projectpayout',
            name='organization_fee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', b'Euro')], default=b'EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='organizationpayout',
            name='organization_fee_excl',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', max_digits=12, verbose_name='organization fee excluding VAT'),
        ),
        migrations.AlterField(
            model_name='organizationpayout',
            name='organization_fee_incl',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', max_digits=12, verbose_name='organization fee including VAT'),
        ),
        migrations.AlterField(
            model_name='organizationpayout',
            name='organization_fee_vat',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', max_digits=12, verbose_name='organization fee VAT'),
        ),
        migrations.AlterField(
            model_name='organizationpayout',
            name='other_costs_excl',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.00'), default_currency=b'EUR', help_text='Set either this value or inclusive VAT, make sure recalculate afterwards.', max_digits=12, verbose_name='other costs excluding VAT'),
        ),
        migrations.AlterField(
            model_name='organizationpayout',
            name='other_costs_incl',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.00'), default_currency=b'EUR', help_text='Set either this value or exclusive VAT, make sure recalculate afterwards.', max_digits=12, verbose_name='other costs including VAT'),
        ),
        migrations.AlterField(
            model_name='organizationpayout',
            name='other_costs_vat',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.00'), default_currency=b'EUR', max_digits=12, verbose_name='other costs VAT'),
        ),
        migrations.AlterField(
            model_name='organizationpayout',
            name='payable_amount_excl',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', max_digits=12, verbose_name='payable amount excluding VAT'),
        ),
        migrations.AlterField(
            model_name='organizationpayout',
            name='payable_amount_incl',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', max_digits=12, verbose_name='payable amount including VAT'),
        ),
        migrations.AlterField(
            model_name='organizationpayout',
            name='payable_amount_vat',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', max_digits=12, verbose_name='payable amount VAT'),
        ),
        migrations.AlterField(
            model_name='organizationpayout',
            name='psp_fee_excl',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', max_digits=12, verbose_name='PSP fee excluding VAT'),
        ),
        migrations.AlterField(
            model_name='organizationpayout',
            name='psp_fee_incl',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', max_digits=12, verbose_name='PSP fee including VAT'),
        ),
        migrations.AlterField(
            model_name='organizationpayout',
            name='psp_fee_vat',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', max_digits=12, verbose_name='PSP fee VAT'),
        ),
        migrations.AlterField(
            model_name='projectpayout',
            name='amount_payable',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', help_text='Payable amount; raised amount minus organization fee.', max_digits=12, verbose_name='amount payable'),
        ),
        migrations.AlterField(
            model_name='projectpayout',
            name='amount_raised',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', help_text='Amount raised when Payout was created or last recalculated.', max_digits=12, verbose_name='amount raised'),
        ),
        migrations.AlterField(
            model_name='projectpayout',
            name='organization_fee',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[(b'EUR', b'Euro')], decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', help_text='Fee subtracted from amount raised for the organization.', max_digits=12, verbose_name='organization fee'),
        ),
    ]
