# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_auto_20160719_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpayout',
            name='currency',
            field=models.CharField(choices=[(b'EUR', b'Euro')], default=b'EUR', max_length=10),
        ),
    ]
