# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-23 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payouts', '0006_rename_account_bic_20170705_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlainPayoutAccount',
            fields=[
                ('payoutaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payouts.PayoutAccount')),
                ('account_holder_name', models.CharField(max_length=200, blank=True, null=True)),
                ('account_number', models.CharField(max_length=200, blank=True, null=True)),
                ('account_details', models.CharField(max_length=200, blank=True, null=True)),
                ('account_holder_city', models.CharField(max_length=200, blank=True, null=True)),
                ('account_holder_country', models.CharField(max_length=200, blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('payouts.payoutaccount',),
        ),
        migrations.CreateModel(
            name='StripePayoutAccount',
            fields=[
                ('payoutaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payouts.PayoutAccount')),
                ('account_token', models.CharField(blank=True, max_length=100, null=True)),
                ('verified', models.DateField(blank=True, null=True)),
                ('verification_error', models.CharField(blank=True, help_text='Reason why verification has failed', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('payouts.payoutaccount',),
        ),
        migrations.AddField(
            model_name='payoutaccount',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_payouts.payoutaccount_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='payoutaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
