# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-29 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_auto_20181129_1451'),
        ('payouts', '0007_auto_20181123_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainpayoutaccount',
            name='account_bank_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_account_bank_country', to='geo.Country'),
        ),
        migrations.AddField(
            model_name='plainpayoutaccount',
            name='account_holder_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='account holder address'),
        ),
        migrations.AddField(
            model_name='plainpayoutaccount',
            name='account_holder_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='account holder postal code'),
        ),
        migrations.AlterField(
            model_name='plainpayoutaccount',
            name='account_details',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='account details'),
        ),
        migrations.AlterField(
            model_name='plainpayoutaccount',
            name='account_holder_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='account holder city'),
        ),
        migrations.AlterField(
            model_name='plainpayoutaccount',
            name='account_holder_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_account_holder_country', to='geo.Country'),
        ),
        migrations.AlterField(
            model_name='plainpayoutaccount',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='account holder name'),
        ),
        migrations.AlterField(
            model_name='plainpayoutaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Account number'),
        ),
    ]
