# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_auto_20181129_1451'),
        ('payouts', '0008_auto_20181129_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[(b'plain-payout', b'Plain'), (b'stripe-base', b'Stripe')], max_length=100)),
                ('countries', models.ManyToManyField(blank=True, null=True, to='geo.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutPlatformSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payoutmethod',
            name='payout_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payouts.PayoutPlatformSettings'),
        ),
    ]
