# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-30 11:48
from __future__ import unicode_literals

from django.db import migrations


def create_settings(apps, schema_editor):
    PayoutPlatformSettings = apps.get_model('payouts', 'PayoutPlatformSettings')
    if not PayoutPlatformSettings.objects.count():
        PayoutPlatformSettings.objects.create()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0009_auto_20181130_1246'),
    ]

    operations = [
        migrations.RunPython(create_settings, backward)
    ]
