# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-07 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0012_auto_20181205_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plainpayoutaccount',
            options={'verbose_name': 'Bank details', 'verbose_name_plural': 'Bank details'},
        ),
        migrations.AddField(
            model_name='plainpayoutaccount',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='Review the project documents before marking the account as reviewed.After setting the project to running, the account documents will be deleted.Also, make sure to remove the documents from your device after downloading them.', verbose_name='Reviewed'),
        ),
    ]
