# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-12 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0014_auto_20181211_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripepayoutaccount',
            old_name='account_token',
            new_name='account_id',
        ),
        migrations.RemoveField(
            model_name='payoutdocument',
            name='deleted',
        ),
        migrations.AddField(
            model_name='stripepayoutaccount',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='plainpayoutaccount',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payouts.PayoutDocument'),
        ),
    ]
