# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-24 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0019_auto_20190110_1155'),
        ('payouts', '0020_auto_20190123_1731'),
    ]

    operations = [
    ]
