# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-11 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0021_merge_20190124_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripepayoutaccount',
            name='country',
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='Review the project documents before marking the account as reviewed. After setting the project to running, the account documents will be deleted. Also, make sure to remove the documents from your device after downloading them. In case of Euro and USD projects the documents will be reviewed by Stripe.', verbose_name='Bank reviewed'),
        ),
    ]
