# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0095_auto_20201103_1028'),
        ('payouts', '0023_auto_20190705_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flutterwavepayoutaccount',
            name='payoutaccount_ptr',
        ),
        migrations.RemoveField(
            model_name='payoutaccount',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='payoutaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payoutdocument',
            name='author',
        ),
        migrations.RemoveField(
            model_name='plainpayoutaccount',
            name='account_bank_country',
        ),
        migrations.RemoveField(
            model_name='plainpayoutaccount',
            name='account_holder_country',
        ),
        migrations.RemoveField(
            model_name='plainpayoutaccount',
            name='document',
        ),
        migrations.RemoveField(
            model_name='plainpayoutaccount',
            name='payoutaccount_ptr',
        ),
        migrations.RemoveField(
            model_name='stripepayoutaccount',
            name='payoutaccount_ptr',
        ),
        migrations.DeleteModel(
            name='FlutterwavePayoutAccount',
        ),
        migrations.DeleteModel(
            name='PayoutAccount',
        ),
        migrations.DeleteModel(
            name='PayoutDocument',
        ),
        migrations.DeleteModel(
            name='PlainPayoutAccount',
        ),
        migrations.DeleteModel(
            name='StripePayoutAccount',
        ),
    ]
