# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterswitchPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.Payment')),
                ('product_id', models.CharField(blank=True, help_text='Product Identifier for PAYDirect.', max_length=200, null=True)),
                ('amount', models.CharField(blank=True, help_text='Transaction amount in small (kobo or cents) denomination. E.g., 200000 for 2,000.00', max_length=200, null=True)),
                ('currency', models.CharField(default=b'566', help_text='566 (For Naira)', max_length=200)),
                ('site_redirect_url', models.CharField(blank=True, help_text='URL of the page on your web site/portal user is to be redirected to after payment. You may want to add encrypted authentication information to allow a user renter the web site/portal transparently without being challenged', max_length=200, null=True)),
                ('txn_ref', models.CharField(blank=True, help_text='Transaction Reference Number. This Reference Number must be generated by your web site/portal and a unique value must be sent for each transaction', max_length=200, null=True)),
                ('hash', models.CharField(blank=True, help_text='A Hashed value of selected combined parameters. See How to compute the request hash.', max_length=200, null=True)),
                ('pay_item_id', models.CharField(blank=True, help_text='PAYDirect Payment Item ID', max_length=200, null=True)),
                ('site_name', models.CharField(blank=True, help_text='Internet site name of the web site/ portal from which http post is coming from. E.g. www.abc.com. This internet site name will be authenticated.', max_length=200, null=True)),
                ('cust_id', models.CharField(blank=True, help_text='Unique Customer Identification Number', max_length=200, null=True)),
                ('cust_id_desc', models.CharField(blank=True, help_text='Customer Identification Number description. A descriptive name/label for Customer Identification Number above.', max_length=200, null=True)),
                ('cust_name', models.CharField(blank=True, help_text='Customer Name', max_length=200, null=True)),
                ('cust_name_desc', models.CharField(blank=True, help_text='Customer Name Description. A descriptive name/label for Customer Name above.', max_length=200, null=True)),
                ('pay_item_name', models.CharField(blank=True, help_text='PAYDirect Payment Item Name', max_length=200, null=True)),
                ('local_date_time', models.CharField(blank=True, help_text='Local Transaction Date Time: DD-MMM-YY HH:MM:SS', max_length=200, null=True)),
                ('response', models.CharField(blank=True, help_text='Response from Interswitch', max_length=1000, null=True)),
                ('update_response', models.CharField(blank=True, help_text='Result from Interswitch (status update)', max_length=1000, null=True)),
            ],
            options={
                'ordering': ('-created', '-updated'),
                'verbose_name': 'Interswitch Payment',
                'verbose_name_plural': 'Interswitch Payments',
            },
            bases=('payments.payment',),
        ),
    ]
