# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments_interswitch', '0002_auto_20161006_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterswitchPaymentStatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments_interswitch.InterswitchPayment')),
            ],
        ),
    ]
