# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_flutterwave', '0002_auto_20170202_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='flutterwavepayment',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text=b'Flutterwave transaction reference', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flutterwavepayment',
            name='bvn',
            field=models.CharField(blank=True, default=b'', help_text=b'User BVN, required only for authModel=BVN', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flutterwavepayment',
            name='country',
            field=models.CharField(blank=True, default=b'NG', help_text=b'Country code (NG)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flutterwavepayment',
            name='pin',
            field=models.CharField(blank=True, default=b'', help_text=b'User PIN, required only for authModel=PIN', max_length=200, null=True),
        ),
    ]
