# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-10 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_flutterwave', '0007_flutterwavempesapayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flutterwavempesapayment',
            name='transaction_amount',
            field=models.CharField(blank=True, help_text=b'Transaction amount', max_length=200, null=True),
        ),
    ]
