# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-27 14:21
from __future__ import unicode_literals

import os

from django.db import migrations
from django.conf import settings
from django.core.management import call_command

from bluebottle.utils.utils import update_group_permissions


def create_report_views(apps, schema_editor):
    report_sql_path = os.path.join(settings.PROJECT_ROOT, 'bluebottle', 'analytics',
                                   'views', 'report.sql')
    call_command('create_report_views', file=report_sql_path)


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20171031_1209'),
        ('clients', '0001_initial'),
        ('projects', '0044_auto_20171110_1549'),
        ('tasks', '0035_merge_20170831_1449'),
        ('geo', '0004_auto_20160929_0817'),
    ]

    operations = [
        migrations.RunPython(create_report_views)
    ]
