# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-24 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20180404_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsplatformsettings',
            options={'verbose_name': 'analytics platform settings', 'verbose_name_plural': 'analytics platform settings'},
        ),
        migrations.AddField(
            model_name='analyticsplatformsettings',
            name='fiscal_month_offset',
            field=models.PositiveIntegerField(default=0, verbose_name='Fiscal year offset'),
        ),
    ]
