# Generated by Django 2.2.24 on 2021-11-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20201012_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsplatformsettings',
            name='engagement_target',
            field=models.PositiveIntegerField(blank=True, help_text='Target number of engaged users per year.', null=True, verbose_name='Engagement target'),
        ),
    ]
