# Generated by Django 2.2.24 on 2022-09-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20220920_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsplatformsettings',
            name='fiscal_month_offset',
        ),
        migrations.AlterField(
            model_name='analyticsplatformsettings',
            name='engagement_target',
            field=models.PositiveIntegerField(blank=True, help_text='Target for the number of people contributing to an activity or starting an activity per year.', null=True, verbose_name='Engagement'),
        ),
    ]
