# Generated by Django 3.2.20 on 2024-04-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0010_auto_20220920_0919"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsplatformsettings",
            name="plausible_embed_link",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Plausibe embed link",
            ),
        ),
    ]
