# Generated by Django 3.2.20 on 2025-01-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_analyticsplatformsettings_plausible_embed_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsplatformsettings',
            name='terminated',
            field=models.BooleanField(default=False, help_text='Is the platform terminated?', verbose_name='Terminated'),
        ),
        migrations.AlterField(
            model_name='analyticsplatformsettings',
            name='platform_type',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('civic', 'Civic'), ('society', 'Society'), ('programs', 'Programs')], default='corporate', max_length=10, verbose_name='platform type'),
        ),
    ]
