# Generated by Django 3.2.20 on 2025-01-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_auto_20250113_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsplatformsettings',
            name='platform_type',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('civic', 'Civic'), ('society', 'Society')], default='corporate', max_length=10, verbose_name='platform type'),
        ),
    ]
