# Generated by Django 4.2.20 on 2025-05-26 14:06

import bluebottle.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_analyticsplatformsettings_amount_raised_target_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsplatformsettings',
            options={'verbose_name': 'reporting settings', 'verbose_name_plural': 'reporting settings'},
        ),
        migrations.AddField(
            model_name='analyticsplatformsettings',
            name='acts_of_impact_target',
            field=models.PositiveIntegerField(blank=True, help_text='How many total contributions do you aim to reach this year, regardless of how many people made them?', null=True, verbose_name='Contribution goal (actions)'),
        ),
        migrations.AlterField(
            model_name='analyticsplatformsettings',
            name='amount_raised_target',
            field=bluebottle.utils.fields.MoneyField(blank=True, currency_choices=[('EUR', 'Euro')], decimal_places=2, default=None, default_currency='EUR', help_text='Total value of donations you aim to raise this year.', max_digits=12, null=True, verbose_name='Donation goal'),
        ),
        migrations.AlterField(
            model_name='analyticsplatformsettings',
            name='engagement_target',
            field=models.PositiveIntegerField(blank=True, help_text='How many unique people do you want to engage this year through contributions like volunteering, donations, or good deeds?', null=True, verbose_name='Contributor goal (people)'),
        ),
        migrations.AlterField(
            model_name='analyticsplatformsettings',
            name='hours_spent_target',
            field=models.PositiveIntegerField(blank=True, help_text='How many total hours do you aim to spend on contributions this year.', null=True, verbose_name='Hours goal'),
        ),
        migrations.AlterField(
            model_name='analyticsplatformsettings',
            name='user_base',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of people who could potentially visit the platform (e.g. employees, citizens).', null=True, verbose_name='Potential reach'),
        ),
    ]
