# Generated by Django 4.2.20 on 2025-10-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_alter_analyticsplatformsettings_options_and_more'),
        ('cms', '0106_auto_20251022_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsplatformsettings',
            name='terminated',
        ),
    ]
