# Generated by Django 2.2.24 on 2023-03-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quotes', '0004_merge_20170124_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
