# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('sequence', models.IntegerField(help_text='For ordering phases.', unique=True)),
                ('active', models.BooleanField(default=True, help_text='Whether this phase is in use or has been discarded.')),
                ('editable', models.BooleanField(default=True, help_text='Whether the project owner can change the details of theproject.')),
                ('viewable', models.BooleanField(default=True, help_text='Whether this phase, and projects in it show up at the website')),
                ('owner_editable', models.BooleanField(default=False, help_text='The owner can manually select between these phases')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('name_nl', models.CharField(max_length=100, unique=True, verbose_name='name NL')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('disabled', models.BooleanField(default=False, verbose_name='disabled')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'project theme',
                'verbose_name_plural': 'project themes',
            },
        ),
    ]
