# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttheme',
            name='name_nl',
        ),
    ]
