# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0004_add_project_continued_phase'),
    ]

    operations = [
    ]
