# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 14:14
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.management import create_permissions


from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Anonymous': {
            'perms': ('api_read_projectphase', 'api_read_projecttheme',)
        },
        'Authenticated': {
            'perms': ('api_read_projectphase', 'api_read_projecttheme',)
        }
    }
    update_group_permissions('bb_projects', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0005_add_api_permissions'),
    ]

    operations = [
            migrations.RunPython(add_group_permissions)
    ]
