# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 14:36
from __future__ import unicode_literals

from django.db import migrations


def create_refunded_phase(apps, schema_editor):
    ProjectPhase = apps.get_model('bb_projects', 'ProjectPhase')
    ProjectPhase.objects.get_or_create(
        id=13, slug='refunded', name='Refunded', viewable=True, editable=False,
        sequence=11, description='The project was refunded'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0006_add_group_permissions'),
    ]

    operations = [
        migrations.RunPython(create_refunded_phase),
    ]
