# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-23 15:02
from __future__ import unicode_literals

from django.db import migrations


def set_done_complete_not_editable(apps, schema_editor):
    ProjectPhase = apps.get_model('bb_projects', 'ProjectPhase')
    done_complete = ProjectPhase.objects.get(slug='done-complete')
    done_complete.editable = False
    done_complete.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0006_add_group_permissions'),
    ]

    operations = [
        migrations.RunPython(set_done_complete_not_editable),
    ]
