# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0006_add_group_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectThemeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('_description', models.TextField(blank=True, verbose_name='description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bb_projects.ProjectTheme')),
            ],
            options={
                'managed': True,
                'db_table': 'bb_projects_projecttheme_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'project theme Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectthemetranslation',
            unique_together=set([('language_code', 'master'), ('language_code', 'name')]),
        ),
    ]
