# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-04 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0008_merge_20180328_1504'),
        ('bb_projects', '0008_merge_20180404_1500'),
    ]

    operations = [
    ]
