# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, connection
from django.utils.translation import activate, _trans, ugettext as _

from tenant_extras.middleware import tenant_translation

from bluebottle.clients.utils import LocalTenant
from bluebottle.utils.utils import get_languages


def translate_phases(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    Phase = apps.get_model('bb_projects', 'ProjectPhase')
    PhaseTranslation = apps.get_model('bb_projects', 'ProjectPhaseTranslation')

    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)

    with LocalTenant(tenant):
        languages = get_languages()
        for object in Phase.objects.all():
            for (language, _long_language) in languages:
                activate(language)
                _trans._active.value = tenant_translation(language, tenant.client_name)
                PhaseTranslation.objects.create(
                    master_id=object.pk,
                    language_code=language,
                    name=_(object.name),
                    _description=_(object.description),
                )


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0010_translate_phases'),
    ]

    operations = [
        # migrations.RunPython(translate_phases)
    ]
