# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-30 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0011_migrate_phase_translations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectphasetranslation',
            old_name='_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='name',
        ),
    ]
