# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-12 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0007_auto_20180323_1602'),
        ('bb_projects', '0012_remove_translated_fields'),
    ]

    operations = [
    ]
