# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0015_auto_20190329_1101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectphasetranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectphasetranslation',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='projecttheme',
            options={'permissions': (('api_read_projecttheme', 'Can view theme through API'),), 'verbose_name': 'theme', 'verbose_name_plural': 'themes'},
        ),
        migrations.AlterModelOptions(
            name='projectthemetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'theme Translation'},
        ),
    ]
