# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-02 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0016_auto_20210302_1338'),
        ('initiatives', '0030_auto_20210302_1405'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectphasetranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectphasetranslation',
            name='master',
        ),
    ]
