# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailPlatformSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_now=True)),
                ('email_logo', models.ImageField(blank=True, null=True, upload_to=b'mails/')),
            ],
            options={
                'verbose_name': 'mail platform settings',
                'verbose_name_plural': 'mail platform settings',
            },
        ),
    ]
