# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 09:38
from __future__ import unicode_literals
from future import standard_library
standard_library.install_aliases()
import urllib.request, urllib.error, urllib.parse

from django.db import migrations


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
    ]
