# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20171211_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[(b'member.created', b'Member Created'), (b'donation.success', b'Donation Success'), (b'task_member.applied', b'Task Member Applied'), (b'task_member.accepted', b'Task Member Accepted'), (b'task_member.rejected', b'Task Member Rejected'), (b'task_member.withdrew', b'Task Member Withdrew'), (b'task_member.realized', b'Task Member Realised')], max_length=200)),
                ('recipients', models.CharField(max_length=600)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='mailplatformsettings',
            name='email_logo',
            field=models.ImageField(blank=True, null=True, upload_to=b'site_content/'),
        ),
    ]
