# Generated by Django 3.2.20 on 2024-11-25 14:26

import bluebottle.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_auto_20180727_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailplatformsettings',
            name='address',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mailplatformsettings',
            name='footer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailplatformsettings',
            name='reply_to',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='mailplatformsettings',
            name='sender',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mailplatformsettings',
            name='email_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection]),
        ),
    ]
