# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-28 08:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_beyonic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beyonicpayment',
            name='new_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text=b'Meta data', blank=True, null=True),
        ),
    ]
