# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-28 08:10
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def migrate_json(apps, schema_editor):
    BeyonicPayment = apps.get_model('payments_beyonic', 'BeyonicPayment')
    for payment in BeyonicPayment.objects.all():
        payment.new_metadata = payment.metadata
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payments_beyonic', '0002_beyonicpayment_new_metadata'),
    ]

    operations = [
        migrations.RunPython(migrate_json)
    ]
