# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-28 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_beyonic', '0003_auto_20181128_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beyonicpayment',
            name='metadata',
        ),
    ]
