# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-28 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_beyonic', '0004_remove_beyonicpayment_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beyonicpayment',
            old_name='new_metadata',
            new_name='metadata',
        ),
    ]
