# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-12 13:09
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bb_accounts', '0002_useraddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
