# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 11:42
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True, verbose_name='created'),
        ),
    ]
