# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 14:42
from __future__ import unicode_literals

import bluebottle.bb_projects.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', bluebottle.bb_projects.fields.MoneyField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('user_reference', models.CharField(blank=True, max_length=100, verbose_name=b'user reference')),
                ('description', models.CharField(blank=True, max_length=400)),
                ('date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPaymentJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', bluebottle.bb_projects.fields.MoneyField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('user_reference', models.CharField(blank=True, editable=False, max_length=100, verbose_name=b'user reference')),
                ('description', models.CharField(blank=True, max_length=400)),
                ('date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationPayoutJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', bluebottle.bb_projects.fields.MoneyField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('user_reference', models.CharField(blank=True, max_length=100, verbose_name=b'user reference')),
                ('description', models.CharField(blank=True, max_length=400)),
                ('date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPayoutJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', bluebottle.bb_projects.fields.MoneyField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('user_reference', models.CharField(blank=True, max_length=100, verbose_name=b'user reference')),
                ('description', models.CharField(blank=True, max_length=400)),
                ('date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
