# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-01 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_lipisha', '0004_auto_20190918_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lipishapaymentprovider',
            options={'verbose_name': 'Lipisha payment provider'},
        ),
        migrations.AddField(
            model_name='lipishabankaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lipishabankaccount',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lipishabankaccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lipishabankaccount',
            name='branch_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lipishabankaccount',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lipishabankaccount',
            name='swift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lipishabankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
