# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-08 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_lipisha', '0006_auto_20191001_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lipishabankaccount',
            options={'verbose_name': 'Lipisha bank account', 'verbose_name_plural': 'Lipisha bank accounts'},
        ),
        migrations.AddField(
            model_name='lipishabankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
