# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-23 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_lipisha', '0007_auto_20191008_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipishabankaccount',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text=b'Create a channel here: https://app.lypa.io/account and copy the generated `Number`.', max_length=50, null=True, unique=True, verbose_name=b'MPESA code'),
        ),
    ]
