# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 14:42
from __future__ import unicode_literals

import bluebottle.utils.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[(b'created', 'Created'), (b'locked', 'Locked'), (b'pledged', 'Pledged'), (b'pending', 'Pending'), (b'success', 'Success'), (b'failed', 'Failed')], default=b'created', max_length=50, protected=True)),
                ('order_type', models.CharField(default=b'one-off', max_length=100)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Updated')),
                ('confirmed', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Confirmed')),
                ('completed', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Completed')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Amount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, bluebottle.utils.utils.FSMTransition),
        ),
    ]
