# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 13:34
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Anonymous': {
            'perms': ('api_add_order',)
        },
        'Authenticated': {
            'perms': ('api_add_order', 'api_read_own_order', 'api_change_own_order', )
        }
    }

    update_group_permissions('orders', group_perms, apps)




class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170823_1533'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
