# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 09:12
from __future__ import unicode_literals
import datetime

from django.db import migrations
from django.utils import timezone


def mark_as_failed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_group_permissions'),
    ]

    operations = [
        migrations.RunPython(mark_as_failed)
    ]
