# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 12:36
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20171003_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMField(choices=[(b'created', 'Created'), (b'locked', 'Locked'), (b'pledged', 'Pledged'), (b'pending', 'Pending'), (b'success', 'Success'), (b'refunded', 'Refunded'), (b'failed', 'Failed'), (b'cancelled', 'CANCELLED')], default=b'created', max_length=50, protected=True),
        ),
    ]
