# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 12:37
from __future__ import unicode_literals

from django.db import migrations




def set_refund_status(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180509_1436'),
        ('payments', '0005_auto_20170919_1621'),
    ]

    operations = [
        migrations.RunPython(set_refund_status)
    ]
