# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-04 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180509_1437'),
        ('donations', '0011_auto_20191101_1046'),
        ('projects', '0091_project_to_initiatives'),
        ('funding', '0001_initial'),
        ('funding_flutterwave', '0003_flutterwavepayoutaccount'),
        ('funding_stripe', '0001_initial'),
        ('wallposts', '0019_auto_20191017_2204'),
        ('activities', '0009_auto_20191007_1506'),
        ('rewards', '0009_auto_20191104_1230')
    ]

    operations = [
    ]
