# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_voucher', '0002_auto_20201103_1028'),
        ('donations', '0012_auto_20201103_1028'),
        ('payments', '0007_auto_20201103_1028'),
        ('orders', '0009_remove_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
