# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='language',
            field=models.CharField(default=b'en', max_length=10, verbose_name='suggestion language'),
        ),
    ]
