# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_auto_20160718_1811'),
        ('suggestions', '0003_auto_20160720_1140'),
    ]

    operations = [
    ]
