# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-02 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0004_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='project',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
