# Generated by Django 3.2.20 on 2024-12-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('nlcares', 'NLCares'), ('onepercent', '1%Club'), ('voor_je_buurt', 'Voor je buurt')], help_text='Name of platform you want to receive activities from. For now use schema_name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SharedActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('platform', models.CharField(choices=[('nlcares', 'NLCares'), ('onepercent', '1%Club'), ('voor_je_buurt', 'Voor je buurt')], max_length=100)),
            ],
        ),
    ]
