# Generated by Django 3.2.20 on 2024-12-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0078_activity_remote_id'),
        ('sharing', '0002_sharedactivity_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedactivity',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity'),
        ),
    ]
