# Generated by Django 3.2.20 on 2024-12-23 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_sharedactivity_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedactivity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
