# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPayoutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='date')),
                ('old_status', models.CharField(blank=True, choices=[(b'new', 'New'), (b'in_progress', 'In progress'), (b'settled', 'Settled')], max_length=20, null=True, verbose_name='old status')),
                ('new_status', models.CharField(choices=[(b'new', 'New'), (b'in_progress', 'In progress'), (b'settled', 'Settled')], max_length=20, verbose_name='new status')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
                'get_latest_by': 'created',
                'verbose_name': 'state change',
                'verbose_name_plural': 'state changes',
            },
        ),
        migrations.CreateModel(
            name='ProjectPayoutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='date')),
                ('old_status', models.CharField(blank=True, choices=[(b'new', 'New'), (b'in_progress', 'In progress'), (b'settled', 'Settled')], max_length=20, null=True, verbose_name='old status')),
                ('new_status', models.CharField(choices=[(b'new', 'New'), (b'in_progress', 'In progress'), (b'settled', 'Settled')], max_length=20, verbose_name='new status')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
                'get_latest_by': 'created',
                'verbose_name': 'state change',
                'verbose_name_plural': 'state changes',
            },
        ),
    ]
