# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:16
from __future__ import unicode_literals

from django.db import migrations


def set_payout_status(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Member = apps.get_model('members', 'Member')
    Group = apps.get_model('auth', 'Group')

    Project.objects.filter(
        projectpayout__status='new'
    ).update(
        payout_status='needs_approval'
    )

    try:
        accounting_member = Member.objects.get(email='devteam+accounting@onepercentclub.com')
        accounting_member.is_active = True
        group = Group.objects.get(name='Financial')
        accounting_member.groups.add(group)
        accounting_member.save()
    except Member.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20170106_1657')
    ]

    operations = [
        migrations.RunPython(set_payout_status, lambda apps, schema_editor: None)
    ]
