# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 12:12
from __future__ import unicode_literals

import bluebottle.utils.fields
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payouts_dorado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='remote_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices="[('EUR', u'Euro')]", decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payout',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
    ]
