# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-17 08:24
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions

def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Staff': {
            'perms': (
                'add_category', 'change_category', 'delete_category',
                'add_categorycontent', 'change_categorycontent', 'delete_categorycontent',
            )
        },
    }

    update_group_permissions('categories', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20170731_1327'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
