# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-22 08:58
from __future__ import unicode_literals

from django.db import migrations

from bluebottle.utils.utils import update_group_permissions


def add_group_permissions(apps, schema_editor):
    group_perms = {
        'Authenticated': {
            'perms': ('api_read_category', )
        }
    }
    update_group_permissions('categories', group_perms, apps)


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20180907_1131'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
