# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-21 09:50


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_authenticated-permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'managed': True,
                'db_table': 'categories_category_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'category Translation',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('api_read_category', 'Can view categories through API'),), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='description_old',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='title_old',
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.CreateModel(
            name='CategoryContentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='Max: 60 characters.', max_length=60, verbose_name='title')),
                ('description', models.TextField(blank=True, default=b'', help_text='Max: 190 characters.', max_length=190, verbose_name='description')),
                ('link_text', models.CharField(blank=True, default='Read more', help_text='The link will only be displayed if an URL is provided. Max: 60 characters.', max_length=60, verbose_name='link name')),
                ('link_url', models.CharField(blank=True, max_length=300, verbose_name='link url')),
            ],
            options={
                'managed': True,
                'db_table': 'categories_categorycontent_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'content block Translation',
            },
        ),
        migrations.RenameField(
            model_name='categorycontent',
            old_name='description',
            new_name='description_old',
        ),
        migrations.RenameField(
            model_name='categorycontent',
            old_name='link_text',
            new_name='link_text_old',
        ),
        migrations.RenameField(
            model_name='categorycontent',
            old_name='link_url',
            new_name='link_url_old',
        ),
        migrations.RenameField(
            model_name='categorycontent',
            old_name='title',
            new_name='title_old',
        ),
        migrations.AddField(
            model_name='categorycontenttranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.CategoryContent'),
        ),
        migrations.AlterUniqueTogether(
            name='categorycontenttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
