# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-21 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_authenticated-permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryContentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='Max: 60 characters.', max_length=60, verbose_name='title')),
                ('description', models.TextField(blank=True, default=b'', help_text='Max: 190 characters.', max_length=190, verbose_name='description')),
            ],
            options={
                'managed': True,
                'db_table': 'categories_categorycontent_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'content block Translation',
            },
        ),
        migrations.RenameField(
            model_name='categorycontent',
            old_name='description',
            new_name='description_old',
        ),
        migrations.RenameField(
            model_name='categorycontent',
            old_name='title',
            new_name='title_old',
        ),
        migrations.AddField(
            model_name='categorycontenttranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.CategoryContent'),
        ),
        migrations.AlterUniqueTogether(
            name='categorycontenttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
