# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-22 06:21


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_migrate_content_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_old',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_old',
        ),
        migrations.RemoveField(
            model_name='categorycontent',
            name='description_old',
        ),
        migrations.RemoveField(
            model_name='categorycontent',
            name='link_text_old',
        ),
        migrations.RemoveField(
            model_name='categorycontent',
            name='link_url_old',
        ),
        migrations.RemoveField(
            model_name='categorycontent',
            name='title_old',
        ),
    ]
