# Generated by Django 3.2.19 on 2023-07-06 13:39

import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_category_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='video',
        ),
        migrations.RemoveField(
            model_name='categorycontent',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=bluebottle.utils.fields.ImageField(blank=True, help_text='Category image', max_length=255, null=True, upload_to='categories/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_logo',
            field=bluebottle.utils.fields.ImageField(blank=True, help_text='Category Logo image', max_length=255, null=True, upload_to='categories/logos/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='categorycontent',
            name='image',
            field=bluebottle.utils.fields.ImageField(blank=True, help_text='Accepted file format: .jpg, .jpeg & .png', max_length=255, null=True, upload_to='categories/content/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='categorycontenttranslation',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Max: 190 characters.', max_length=190, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='categorycontenttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.categorycontent'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.category'),
        ),
    ]
