# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

import bluebottle.files.validators
import bluebottle.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_category_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='video',
            field=models.FileField(blank=True, help_text='This video will autoplay at the background. Allowed types are mp4, ogg, 3gp, avi, mov and webm. File should be smaller then 10MB.', max_length=255, null=True, upload_to=b'banner_slides/', validators=[bluebottle.files.validators.validate_video_file_size, bluebottle.utils.validators.FileMimetypeValidator([b'video/ogg', b'video/mp4', b'video/webm', b'video/3gpp', b'video/x-msvideo', b'video/quicktime'], None, b'invalid_mimetype')], verbose_name='video'),
        ),
    ]
