# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
