# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20170816_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('api_read_member', 'Can view members through the API'), ('api_read_full_member', 'Can view full members through the API'), ('api_add_member', 'Can add members through the API'), ('api_change_member', 'Can change members through the API'), ('api_delete_member', 'Can delete members through the API'), ('api_read_own_member', 'Can view own members through the API'), ('api_change_own_member', 'Can change own members through the API'), ('api_delete_own_member', 'Can delete own members through the API')), 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
    ]
