# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 13:11
from __future__ import unicode_literals

from django.db import migrations, connection
from django.contrib.auth.models import Group

from bluebottle.clients import properties
from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant


def remove_closed_site_permissions(apps, schema_editor):
    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        if properties.CLOSED_SITE:
            anonymous = Group.objects.get(name='Anonymous')
            anonymous.permissions.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20170822_1104'),
        ('tasks', '0034_more_owner_permissions'),
        ('projects', '0039_add_project_image_group_permissions'),
        ('wallposts', '0014_set_owner_permissions'),
        ('rewards', '0006_set_owner_permissions'),
        ('bb_projects', '0006_add_group_permissions'),
        ('orders', '0004_add_group_permissions'),
    ]

    operations = [
        migrations.RunPython(remove_closed_site_permissions)
    ]
