# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20171031_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='partner_organization',
            field=models.ForeignKey(blank=True, help_text='When a partner is selected with the drop down or a new one is added, that member profile is shown whenever that member does something on the platform.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_organization_members', to='organizations.Organization', verbose_name='Partner Organization'),
        ),
    ]
