# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-13 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20171207_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='require_consent',
            field=models.BooleanField(default=False, help_text='Require users to consent to cookies'),
        ),
    ]
