# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-19 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_auto_20190208_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='scim_external_id',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='external SCIM id'),
        ),
    ]
