# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-22 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20190219_1024'),
        ('members', '0028_merge_20190215_1441'),
    ]

    operations = [
    ]
