# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-06 14:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0003_auto_20200706_1630'),
        ('members', '0036_auto_20200406_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='segments',
            field=models.ManyToManyField(related_name='users', to='segments.Segment', verbose_name='Segment'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='anonymization_age',
            field=models.IntegerField(default=0, help_text='The number of days after which user data should be anonymised. 0 for no anonymisation'),
        ),
    ]
