# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-03-02 13:16
from __future__ import unicode_literals

import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_auto_20210302_0836'),
        ('initiatives', '0030_auto_20210302_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='favourite_themes',
            field=models.ManyToManyField(blank=True, to='initiatives.Theme'),
        ),
    ]
