# Generated by Django 2.2.20 on 2021-05-27 09:28

import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0041_auto_20210302_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='submitted_initiative_notifications',
            field=models.BooleanField(default=False, help_text='Staff member receives a notification when an initiative is submitted an ready to be reviewed.', verbose_name='Submitted initiatives'),
        ),
    ]
