# Generated by Django 2.2.20 on 2021-05-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_auto_20210519_1619'),
        ('members', '0042_auto_20210527_1128'),
    ]

    operations = [
    ]
