# Generated by Django 2.2.20 on 2021-07-08 08:20

import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_auto_20210708_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='enable_address',
            field=models.BooleanField(default=False, help_text='Show address question in profile form'),
        ),
    ]
