# Generated by Django 2.2.24 on 2021-10-12 10:42

import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_auto_20210708_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='campaign_notifications',
            field=models.BooleanField(default=True, help_text='Updates from initiatives and activities that this person follows', verbose_name='Updates'),
        ),
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Location', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=bluebottle.utils.fields.ImageField(blank=True, upload_to='profiles', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='member',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='users', to='segments.Segment', verbose_name='Segment'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subscribed',
            field=models.BooleanField(default=False, help_text="Monthly overview of activities that match this person's profile", verbose_name='Matching'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_type',
            field=models.CharField(choices=[('person', 'Person'), ('company', 'Company'), ('foundation', 'Foundation'), ('school', 'School'), ('group', 'Club / association')], default='person', max_length=25, verbose_name='Member Type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='verified',
            field=models.BooleanField(blank=True, default=False, help_text='Was verified for voting by recaptcha.'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection]),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='consent_link',
            field=models.CharField(default='/pages/terms-and-conditions', help_text='Link more information about the platforms policy', max_length=255),
        ),
    ]
