# Generated by Django 2.2.24 on 2021-10-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0027_auto_20211012_1203'),
        ('members', '0046_auto_20211012_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Place'),
        ),
    ]
