# Generated by Django 2.2.24 on 2022-02-15 09:27

from django.db import migrations

def set_consent_link(apps, schema_editor):
    MemberPlatformSettings = apps.get_model('members', 'MemberPlatformSettings')
    settings = MemberPlatformSettings.load()
    settings.consent_link = "https://goodup.com/cookie-policy"
    settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0049_auto_20220124_0938'),
    ]

    operations = [
        migrations.RunPython(set_consent_link, migrations.RunPython.noop)
    ]
