# Generated by Django 2.2.24 on 2022-02-15 14:21

import bluebottle.bb_accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0026_auto_20220215_1521'),
        ('members', '0050_auto_20220215_1027'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
             database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE members_member_segments RENAME TO members_usersegment',
                    reverse_sql='ALTER TABLE members_usersegment RENAME TO members_member_segments',
                ),
            ],

            state_operations=[
                migrations.CreateModel(
                    name='UserSegment',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                        ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segments.Segment')),
                    ],
                ),
                migrations.AlterField(
                    model_name='member',
                    name='segments',
                    field=models.ManyToManyField(blank=True, related_name='users', through='members.UserSegment', to='segments.Segment', verbose_name='Segment'),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='consent_link',
            field=models.CharField(default='"https://goodup.com/cookie-policy"', help_text='Link more information about the platforms cookie policy', max_length=255),
        ),
    ]
