# Generated by Django 2.2.24 on 2022-02-15 14:38

import bluebottle.bb_accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0051_auto_20220215_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersegment',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
