# Generated by Django 2.2.24 on 2022-02-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0052_auto_20220215_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='require_office',
            field=models.BooleanField(default=False, help_text='Required office location'),
        )
    ]
