# Generated by Django 2.2.24 on 2022-02-25 12:44

import bluebottle.bb_accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0053_auto_20220221_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='location_verified',
            field=models.BooleanField(default=False, help_text='Office location is verified by the user'),
        ),
        migrations.AddField(
            model_name='memberplatformsettings',
            name='verify_office',
            field=models.BooleanField(default=False, help_text='Let users verify their office location'),
        ),
    ]
