# Generated by Django 2.2.24 on 2022-03-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0054_auto_20220225_1344'),
        ('members', '0055_auto_20220301_1336'),
    ]

    operations = [
    ]
