# Generated by Django 2.2.24 on 2022-05-16 12:12

import bluebottle.bb_accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0056_merge_20220301_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='display_member_names',
            field=models.CharField(choices=[('full_name', 'Full name'), ('first_name', 'First name')], default='full_name', help_text='How names of members will be displayed for visitors and other members.If first name is selected, then the names of initiators and activity manager will remain displayed in full and Activity managers and initiators will see the full names of their participants. And staff members will see all names in full.', max_length=12, verbose_name='Display member names'),
        ),
    ]
