# Generated by Django 2.2.24 on 2022-06-07 07:34

import bluebottle.bb_accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0057_auto_20220516_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='require_address',
            field=models.BooleanField(default=False, help_text='Require members to enter their address once after logging in.', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='memberplatformsettings',
            name='require_birthdate',
            field=models.BooleanField(default=False, help_text='Require members to enter their date of birth once after logging in.', verbose_name='Birthdate'),
        ),
        migrations.AddField(
            model_name='memberplatformsettings',
            name='require_phone_number',
            field=models.BooleanField(default=False, help_text='Require members to enter their phone number once after logging in.', verbose_name='Phone number'),
        ),
    ]
