# Generated by Django 2.2.24 on 2022-08-15 15:51

import bluebottle.bb_accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0061_auto_20220808_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='create_initiatives',
            field=models.BooleanField(default=True, help_text='Members can create activities'),
        ),

    ]
