# Generated by Django 2.2.24 on 2022-08-25 06:40

import bluebottle.bb_accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0063_auto_20220818_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='reminder_q1',
            field=models.BooleanField(default=False, help_text='This activation mail is send on January 15th.'),
        ),
        migrations.AddField(
            model_name='memberplatformsettings',
            name='reminder_q2',
            field=models.BooleanField(default=False, help_text='This activation mail is send on April 15th.'),
        ),
        migrations.AddField(
            model_name='memberplatformsettings',
            name='reminder_q3',
            field=models.BooleanField(default=False, help_text='This activation mail is send on September 1st.'),
        ),
        migrations.AddField(
            model_name='memberplatformsettings',
            name='reminder_q4',
            field=models.BooleanField(default=False, help_text='This activation mail is send on October 15th.'),
        ),
    ]
