# Generated by Django 2.2.24 on 2022-08-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0064_auto_20220825_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='receive_reminder_emails',
            field=models.BooleanField(default=True, help_text='User receives emails reminding them about their do good hours', verbose_name='Receive reminder emails'),
        ),
    ]
