# Generated by Django 2.2.24 on 2022-09-20 09:39

import bluebottle.bb_accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0066_auto_20220920_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='fiscal_month_offset',
            field=models.IntegerField(default=0, help_text='Use this if the fiscal years starts later or earlier then January. If the year starts September (so earlier) then this value should be 4.', verbose_name='Fiscal year offset'),
        ),
    ]
