# Generated by Django 2.2.24 on 2022-09-23 10:12

import bluebottle.bb_accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0066_auto_20220920_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='do_good_hours',
            field=models.IntegerField(blank=True, help_text="Leave empty if this feature won't be used.", null=True, verbose_name='Impact hours'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='fiscal_month_offset',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Set the number of months your fiscal year will be offset by. This will also take into account how the impact metrics are shown on the homepage. e.g. If the year starts from September (so earlier) then this value should be -4.', null=True, verbose_name='Fiscal year offset'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='reminder_q1',
            field=models.BooleanField(default=False, verbose_name='Reminder Q1'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='reminder_q2',
            field=models.BooleanField(default=False, verbose_name='Reminder Q2'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='reminder_q3',
            field=models.BooleanField(default=False, verbose_name='Reminder Q3'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='reminder_q4',
            field=models.BooleanField(default=False, verbose_name='Reminder Q4'),
        ),
    ]
