# Generated by Django 2.2.24 on 2022-09-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0067_auto_20220920_1139'),
        ('members', '0068_auto_20220923_1420'),
    ]

    operations = [
    ]
