# Generated by Django 2.2.24 on 2022-12-02 12:57

import bluebottle.bb_accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0069_merge_20220928_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='retention_anonymize',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Set the number of months after which user data will be anonymised.', null=True, verbose_name='Anonymise'),
        ),
        migrations.AddField(
            model_name='memberplatformsettings',
            name='retention_delete',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Set the number of months after which user data will be deleted.', null=True, verbose_name='Delete'),
        ),
    ]
