# Generated by Django 2.2.24 on 2023-05-09 08:35

import bluebottle.bb_accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0070_auto_20221202_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='any_search_distance',
            field=models.BooleanField(default=False, verbose_name='Any distance'),
        ),
        migrations.AddField(
            model_name='member',
            name='include_online',
            field=models.BooleanField(default=False, verbose_name='Include online activities'),
        ),
        migrations.AddField(
            model_name='member',
            name='search_distance',
            field=models.IntegerField(default=50, verbose_name='Distance'),
        ),
    ]
