# Generated by Django 3.2.19 on 2023-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0031_auto_20230503_1524'),
        ('members', '0073_auto_20230710_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='search_distance',
            field=models.CharField(blank=True, default='50km', max_length=10, null=True, verbose_name='Distance'),
        ),
    ]
