# Generated by Django 3.2.20 on 2024-05-13 12:08

import bluebottle.bb_accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0034_location_alternate_names"),
        ("members", "0076_auto_20240115_1106"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberplatformsettings",
            name="create_locations",
            field=models.BooleanField(
                default=False,
                help_text="Create new office locations when a user logs in. Leave unchecked if only priorly specified ones should be used.",
            ),
        ),
    ]
