# Generated by Django 3.2.20 on 2024-11-12 11:35

import bluebottle.bb_accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_add_permissions_20230130_1255'),
        ('geo', '0035_set_alternate_names'),
        ('members', '0080_auto_20241014_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='can_do_bank_transfer',
            field=models.BooleanField(default=False, help_text='User can do a donation through bank transfers (for supported countries).', verbose_name='Can do bank transfer'),
        ),
    ]
