# Generated by Django 3.2.20 on 2025-01-03 08:27

import bluebottle.bb_accounts.models
import bluebottle.files.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_relatedimage_image'),
        ('offices', '0004_add_permissions_20230130_1255'),
        ('members', '0082_auto_20241106_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberplatformsettings',
            name='anonymization_age',
        ),
    ]
