# Generated by Django 3.2.20 on 2024-11-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0081_auto_20241112_1235'),
        ('members', '0082_auto_20241106_1527'),
    ]

    operations = [
    ]
