# Generated by Django 4.2.17 on 2025-03-05 15:20

import bluebottle.bb_accounts.models
import bluebottle.files.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_add_permissions_20230130_1255'),
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('members', '0085_auto_20250203_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subregion_manager',
            field=models.ManyToManyField(blank=True, help_text="Select one or more regions to filter the user's view to only see data relevant to those regions. Leave empty for full access to all data.", to='offices.officesubregion'),
        ),
        migrations.AlterField(
            model_name='member',
            name='region_manager',
            field=models.ForeignKey(blank=True, help_text="Select a region to filter the user's view to only see data relevant to that region. Leave empty for full access to all data.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_regions', to='offices.officesubregion'),
        ),
    ]
