# Generated by Django 4.2.20 on 2025-03-06 16:48

import bluebottle.bb_accounts.models
import bluebottle.files.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_add_permissions_20230130_1255'),
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('members', '0088_alter_member_managers_remove_member_region_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', bluebottle.bb_accounts.models.BlueBottleUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=bluebottle.files.fields.ImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='can_do_bank_transfer',
            field=models.BooleanField(default=False, help_text='Bank transfers are only available to selected regions.', verbose_name='Can do bank transfer'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Non-binary'), ('none', 'I would rather not say')], max_length=8, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='primary_language',
            field=models.CharField(choices=[('en', 'English')], default='en', help_text='Language used for website and emails.', max_length=7, verbose_name='primary language'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subregion_manager',
            field=models.ManyToManyField(blank=True, help_text='Select one or more groups to filter on. The user will only see data related to those selected groups. Leave empty to show all data.', to='offices.officesubregion', verbose_name='Office groups managed'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='closed',
            field=models.BooleanField(default=False, help_text='Require login before accessing the platform', verbose_name='closed'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='confirm_signup',
            field=models.BooleanField(default=False, help_text="Require verifying the user's email before signup", verbose_name='confirm signup'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='consent_link',
            field=models.CharField(default='"https://goodup.com/cookie-policy"', help_text='Link more information about the platforms cookie policy', max_length=255, verbose_name='consent link'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='create_initiatives',
            field=models.BooleanField(default=True, help_text='Members can create initiatives', verbose_name='create initiatives'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='create_locations',
            field=models.BooleanField(default=False, help_text='Create new office locations when a user logs in. Leave unchecked if only priorly specified ones should be used.', verbose_name='create locations'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='create_segments',
            field=models.BooleanField(default=False, help_text='Create new segments when a user logs in. Leave unchecked if only priorly specified ones should be used.', verbose_name='create segments'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='disable_cookie_consent',
            field=models.BooleanField(default=False, help_text='Handle cookie consent externally (e.g. Cookiebot) - (Required when GTM is added.)', verbose_name='disable cookie consent'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='email_domain',
            field=models.CharField(blank=True, help_text='Domain that all email should belong to', max_length=256, null=True, verbose_name='email domains'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='enable_address',
            field=models.BooleanField(default=False, help_text='Show address question in profile form', verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='enable_birthdate',
            field=models.BooleanField(default=False, help_text='Show birthdate question in profile form', verbose_name='enable birthday'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='enable_gender',
            field=models.BooleanField(default=False, help_text='Show gender question in profile form', verbose_name='enable gender'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='fiscal_month_offset',
            field=models.IntegerField(default=0, help_text='Set how many months earlier your fiscal year starts compared to January. For example, if your fiscal year starts in September (which is 4 months before January), enter 4. This also affects how impact metrics are displayed on the homepage.', verbose_name='Fiscal year offset'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='gtm_code',
            field=models.CharField(blank=True, help_text='Adding the GTM script to your platform allows you to manage and deploy third-party tools.', max_length=255, verbose_name='gtm code'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='login_methods',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('password', 'Email/password combination'), ('SSO', 'Company SSO')], default=['password'], max_length=100, verbose_name='login methods'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='require_address',
            field=models.BooleanField(default=False, help_text='Require members to enter their address.', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='require_birthdate',
            field=models.BooleanField(default=False, help_text='Require members to enter their date of birth.', verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='require_office',
            field=models.BooleanField(default=False, help_text='Require members to enter their office location.', verbose_name='Office location'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='require_phone_number',
            field=models.BooleanField(default=False, help_text='Require members to enter their phone number.', verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='required_questions_location',
            field=models.CharField(choices=[('login', 'After log in'), ('contribution', 'When making a contribution')], default='login', help_text='When should the user be asked to complete their required profile fields?', max_length=12, verbose_name='required questions location'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='retention_anonymize',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Set the number of months after which user data will be anonymised. Leave the field empty or with ‘0’ if you do not wish to anonymise user data.', null=True, verbose_name='Anonymise'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='retention_delete',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Set the number of months after which user data will be deleted. Leave the field empty or with ‘0’ if you do not wish to delete user data.', null=True, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='session_only',
            field=models.BooleanField(default=False, help_text='Limit user session to browser session', verbose_name='session only'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='verify_office',
            field=models.BooleanField(default=False, help_text='Require members to verify their office location once if it is filled via SSO.', verbose_name='Verify SSO data office location'),
        ),
    ]
