# Generated by Django 4.2.20 on 2025-11-03 14:33

import bluebottle.files.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_add_permissions_20230130_1255'),
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('members', '0089_alter_member_managers_member_segment_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='translate_user_content',
            field=models.BooleanField(default=True, verbose_name='Translate user content'),
        ),
    ]
