# Generated by Django 4.2.20 on 2025-10-27 07:43

import bluebottle.files.fields
import bluebottle.utils.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0089_alter_member_managers_member_segment_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='email_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, help_text='List of domains that emails should belong to', null=True, size=None, verbose_name='email domains'),
        ),
    ]
