# Generated by Django 4.2.20 on 2025-11-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('offices', '0004_add_permissions_20230130_1255'),
        ('members', '0090_member_translate_user_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='translate_user_content',
            field=models.BooleanField(default=False,
                                      help_text='Give users the option to translate user generated content.',
                                      verbose_name='translate user content'),
        ),
    ]
