# Generated by Django 4.2.20 on 2025-10-27 07:43

from django.db import migrations

def migrate_email_domains(apps, schema_editor):
    MemberPlatformSettings = apps.get_model('members', 'MemberPlatformSettings')

    member_platform_settings = MemberPlatformSettings.objects.first()
    if member_platform_settings and member_platform_settings.email_domain:
        member_platform_settings.email_domains = [dom.strip() for dom in member_platform_settings.email_domain.split(",")]
        member_platform_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0090_memberplatformsettings_email_domains_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_email_domains, migrations.RunPython.noop),
    ]
