# Generated by Django 4.2.20 on 2025-10-14 14:11

from django.db import migrations, connection
from bluebottle.clients import properties

from bluebottle.clients.models import Client
from bluebottle.clients.utils import LocalTenant


def import_settings(apps, schema_editor):
    MemberPlatformSettings = apps.get_model('members', 'MemberPlatformSettings')
    SocialLoginSettings = apps.get_model('members', 'SocialLoginSettings')

    tenant = Client.objects.get(schema_name=connection.tenant.schema_name)
    with LocalTenant(tenant):
        (settings, _created) = MemberPlatformSettings.objects.get_or_create()

        if (
            hasattr(properties, 'SOCIAL_AUTH_FACEBOOK_KEY') and 
            hasattr(properties, 'SOCIAL_AUTH_FACEBOOK_SECRET')
        ):
            SocialLoginSettings.objects.create(
                secret=properties.SOCIAL_AUTH_FACEBOOK_SECRET,
                client_id=properties.SOCIAL_AUTH_FACEBOOK_KEY,
                backend='facebook',
                settings=settings
            )


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0091_socialloginsettings_backend_alter_member_avatar_and_more'),
    ]

    operations = [
        migrations.RunPython(import_settings, migrations.RunPython.noop)
    ]
