# Generated by Django 4.2.20 on 2025-10-27 08:04

import bluebottle.files.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('offices', '0004_add_permissions_20230130_1255'),
        ('members', '0091_auto_20251027_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='moderate_signup',
            field=models.BooleanField(default=False, help_text="Require verifying the user's email before signup. This does not apply to white-listed domains.", verbose_name='moderate signup'),
        ),
    ]
