# Generated by Django 4.2.20 on 2025-10-27 09:51

import bluebottle.files.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0092_memberplatformsettings_moderate_signup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='accepted',
            field=models.BooleanField(default=True, help_text='Was approved by platform manager.', verbose_name='Accepted'),
        ),
    ]
