# Generated by Django 4.2.20 on 2025-11-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0091_memberplatformsettings_translate_user_content'),
        ('members', '0092_auto_20251014_1611'),
    ]

    operations = [
    ]
