# Generated by Django 4.2.20 on 2025-11-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0092_auto_20251014_1611'),
        ('members', '0093_member_accepted_alter_member_avatar_and_more'),
    ]

    operations = [
    ]
