# Generated by Django 4.2.20 on 2025-11-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0093_merge_20251117_1032'),
        ('members', '0093_merge_20251117_1552'),
    ]

    operations = [
    ]
