# Generated by Django 4.2.20 on 2025-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('offices', '0004_add_permissions_20230130_1255'),
        ('members', '0094_merge_20251119_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberplatformsettings',
            name='moderate_signup',
        ),
        migrations.AddField(
            model_name='memberplatformsettings',
            name='account_creation_rules',
            field=models.CharField(choices=[('anyone', 'Anyone can create an account'), ('whitelist',
                                                                                         'Only people with a whitelisted email domain can create an account'),
                                            ('whitelist_and_request',
                                             'People with a whitelisted domain can create an account; all others can request access')],
                                   default='anyone', help_text='This rule only applies to email + password sign-ups.',
                                   verbose_name='account create rules'),
        ),
    ]
