# Generated by Django 4.2.20 on 2025-11-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('offices', '0004_add_permissions_20230130_1255'),
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('members', '0095_remove_memberplatformsettings_moderate_signup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='request_access_email',
            field=models.EmailField(blank=True,
                                    help_text='Enter the email address where people should send their access request.',
                                    max_length=254, null=True, verbose_name='Request access mail to address'),
        ),
        migrations.AddField(
            model_name='memberplatformsettings',
            name='request_access_instructions',
            field=models.CharField(blank=True, help_text='Explain how people can request access to the platform.',
                                   max_length=2000, null=True, verbose_name='request access instructions'),
        ),
        migrations.AddField(
            model_name='memberplatformsettings',
            name='request_access_method',
            field=models.CharField(choices=[('email', 'People request access by entering their email address'),
                                            ('instructions', 'People request access by following your instructions')],
                                   default='email',
                                   help_text='This rule only applies when requesting access is allowed.',
                                   verbose_name='request access method'),
        ),
    ]
