# Generated by Django 4.2.20 on 2025-11-19 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('offices', '0004_add_permissions_20230130_1255'),
        ('members', '0096_memberplatformsettings_request_access_email_and_more'),
    ]

    operations = [

    ]
