# Generated by Django 4.2.20 on 2025-11-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0097_alter_member_avatar_and_more'),
    ]

    operations = [
    ]
