# Generated by Django 4.2.20 on 2025-11-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0098_auto_20251120_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplatformsettings',
            name='request_access_code',
            field=models.CharField(blank=True,
                                   help_text='With this code people can sign-up without a white-listed email address.',
                                   max_length=255, null=True, verbose_name='Request access code'),
        ),
    ]
