# Generated by Django 4.2.20 on 2025-11-24 15:09

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('offices', '0004_add_permissions_20230130_1255'),
        ('members', '0100_merge_20251124_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberplatformsettings',
            name='request_access_instructions',
        ),
        migrations.CreateModel(
            name='MemberPlatformSettingsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('request_access_instructions',
                 models.CharField(blank=True, help_text='Explain how people can request access to the platform.',
                                  max_length=2000, null=True, verbose_name='request access instructions')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True,
                                                                on_delete=django.db.models.deletion.CASCADE,
                                                                related_name='translations',
                                                                to='members.memberplatformsettings')),
            ],
            options={
                'verbose_name': 'member platform settings Translation',
                'db_table': 'members_memberplatformsettings_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
