# Generated by Django 4.2.20 on 2025-11-24 15:09

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models
from django.db.migrations.operations.base import Operation
from django.db.migrations.state import ModelState
from parler.models import TranslatableModel


class AlterModelBases(Operation):
    """
    State-only operation: change model bases in the migration state,
    but don't touch the database.
    """

    reduces_to_sql = False
    reversible = True

    def __init__(self, name, bases):
        self.name = name
        self.bases = bases  # tuple of strings

    def state_forwards(self, app_label, state):
        key = (app_label, self.name.lower())
        model_state = state.models[key]

        state.models[key] = ModelState(
            app_label=model_state.app_label,
            name=model_state.name,
            fields=model_state.fields,
            options=model_state.options,
            bases=self.bases,
            managers=model_state.managers,
        )

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # No DB changes
        pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # If you ever need to reverse, you could restore the old bases here
        pass

    def describe(self):
        return f"Alter bases for {self.name}"

    def deconstruct(self):
        return (
            self.__class__.__name__,
            [],
            {"name": self.name, "bases": self.bases},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('offices', '0004_add_permissions_20230130_1255'),
        ('members', '0100_merge_20251124_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberplatformsettings',
            name='request_access_instructions',
        ),
        AlterModelBases(
            name="MemberPlatformSettings",
            bases=(
                TranslatableModel,
            ),
        ),
        migrations.CreateModel(
            name='MemberPlatformSettingsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('request_access_instructions',
                 models.CharField(blank=True, help_text='Explain how people can request access to the platform.',
                                  max_length=2000, null=True, verbose_name='request access instructions')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True,
                                                                on_delete=django.db.models.deletion.CASCADE,
                                                                related_name='translations',
                                                                to='members.memberplatformsettings')),
            ],
            options={
                'verbose_name': 'member platform settings Translation',
                'db_table': 'members_memberplatformsettings_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
