# Generated by Django 4.2.20 on 2025-11-25 12:20

import bluebottle.files.fields
import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_add_permissions_20230130_1255'),
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('members', '0101_remove_memberplatformsettings_request_access_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='User has explicitly accepted the terms', verbose_name='Terms accepted'),
        ),
        migrations.AddField(
            model_name='memberplatformsettings',
            name='explicit_terms',
            field=models.BooleanField(default=False, help_text='Users have to explicitly accept terms when logging in', verbose_name='Explicit terms'),
        ),
    ]
