# Generated by Django 4.2.20 on 2025-12-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0094_merge_20251118_1411'),
        ('members', '0102_remove_memberplatformsettings_email_domain'),
    ]

    operations = [
    ]
