# Generated by Django 4.2.20 on 2025-12-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0102_member_terms_accepted_and_more'),
        ('members', '0102_remove_memberplatformsettings_email_domain'),
    ]

    operations = [
    ]
