# Generated by Django 4.2.20 on 2026-01-15 11:12

import bluebottle.files.fields
import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('geo', '0036_alter_location_options_alter_location_country_and_more'),
        ('offices', '0005_alter_officeregion_options_and_more'),
        ('members', '0103_merge_20251203_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialloginsettings',
            options={'verbose_name': 'Social login settings', 'verbose_name_plural': 'Social login settings'},
        ),
        migrations.AddField(
            model_name='memberplatformsettings',
            name='support_business_unit',
            field=models.CharField(choices=[('civic', 'Civic'), ('corporate', 'Corporate'), ('society', 'Corporate')], help_text='Select a business unit that has support access to this platform', null=True, verbose_name='Support login business unit'),
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=bluebottle.files.fields.ImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='can_do_bank_transfer',
            field=models.BooleanField(default=False, help_text='Bank transfers are only available to selected regions.', verbose_name='Can do bank transfer'),
        ),
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.location', verbose_name='Work location'),
        ),
        migrations.AlterField(
            model_name='member',
            name='location_verified',
            field=models.BooleanField(default=False, help_text='Work location is verified by the user'),
        ),
        migrations.AlterField(
            model_name='member',
            name='submitted_initiative_notifications',
            field=models.BooleanField(default=False, help_text='Receive a notification via email when new activities and initiatives get submitted or published. This depends on the review setting of the platform.', verbose_name='New activities/initiatives notification'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subregion_manager',
            field=models.ManyToManyField(blank=True, help_text='Select one or more groups to filter on. The user will only see data related to those selected groups. Leave empty to show all data.', to='offices.officesubregion', verbose_name='Work location groups managed'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='account_creation_rules',
            field=models.CharField(choices=[('anyone', 'Anyone can create an account'), ('whitelist', 'Only people with a whitelisted domain can create an account'), ('whitelist_and_request', 'People with a whitelisted domain can create an account; all others can request access')], default='anyone', help_text='This rule only applies to the email + password method.', verbose_name='account creation rules'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='background',
            field=models.ImageField(blank=True, help_text='This image will be displayed on the sign up and log in pages.', null=True, upload_to='site_content/', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='Sign up image'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='closed',
            field=bluebottle.utils.fields.CheckboxField(default=False, help_text='Only logged-in users can view the platform.', inline_label='Require log in before accessing the platform', verbose_name='Platform access'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='confirm_signup',
            field=bluebottle.utils.fields.CheckboxField(default=False, help_text='This rule only applies to the email + password method.', inline_label='Require users to verify their email on sign-up', verbose_name='verify email on sign up'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='consent_link',
            field=models.CharField(default='"https://goodup.com/cookie-policy"', help_text='Link more information about the platforms cookie policy', max_length=255, verbose_name='consent link'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='create_initiatives',
            field=models.BooleanField(default=True, help_text='Members can create initiatives', verbose_name='create initiatives'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='create_locations',
            field=models.BooleanField(default=False, help_text='Create new work locations when a user logs in. Leave unchecked if only priorly specified ones should be used.', verbose_name='create locations'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='create_segments',
            field=models.BooleanField(default=False, help_text='Create new segments when a user logs in. Leave unchecked if only priorly specified ones should be used.', verbose_name='create segments'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='disable_cookie_consent',
            field=models.BooleanField(default=False, help_text='Handle cookie consent externally (e.g. Cookiebot) - (Required when GTM is added.)', verbose_name='disable cookie consent'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='email_domains',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, null=True, size=None, verbose_name='Whitelisted email domains'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='enable_address',
            field=models.BooleanField(default=False, help_text='Show address question in profile form', verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='enable_birthdate',
            field=models.BooleanField(default=False, help_text='Show birthdate question in profile form', verbose_name='enable birthday'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='enable_gender',
            field=models.BooleanField(default=False, help_text='Show gender question in profile form', verbose_name='enable gender'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='fiscal_month_offset',
            field=models.IntegerField(default=0, help_text='Set how many months earlier your fiscal year starts compared to January. For example, if your fiscal year starts in September (which is 4 months before January), enter 4. This also affects how impact metrics are displayed on the homepage.', verbose_name='Fiscal year offset'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='gtm_code',
            field=models.CharField(blank=True, help_text='Adding the GTM script to your platform allows you to manage and deploy third-party tools.', max_length=255, verbose_name='gtm code'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='login_methods',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SSO', 'Company SSO'), ('password', 'Email + password')], default=['password'], help_text='People can use any selected method to sign up or log in. For social log in options, see the ‘Social log in’ tab.', max_length=100, verbose_name='login methods'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='require_address',
            field=models.BooleanField(default=False, help_text='Require members to enter their address.', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='require_birthdate',
            field=models.BooleanField(default=False, help_text='Require members to enter their date of birth.', verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='require_office',
            field=models.BooleanField(default=False, help_text='Require members to enter their work location.', verbose_name='Work location'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='require_phone_number',
            field=models.BooleanField(default=False, help_text='Require members to enter their phone number.', verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='required_questions_location',
            field=models.CharField(choices=[('login', 'After log in'), ('contribution', 'When making a contribution')], default='login', help_text='When should the user be asked to complete their required profile fields?', max_length=12, verbose_name='required questions location'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='retention_anonymize',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Set the number of months after which user data will be anonymised. Leave the field empty or with ‘0’ if you do not wish to anonymise user data.', null=True, verbose_name='Anonymise'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='retention_delete',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Set the number of months after which user data will be deleted. Leave the field empty or with ‘0’ if you do not wish to delete user data.', null=True, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='session_only',
            field=models.BooleanField(default=False, help_text='Limit user session to browser session', verbose_name='session only'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='verify_office',
            field=models.BooleanField(default=False, help_text='Require members to verify their work location once if it is filled via SSO.', verbose_name='Verify SSO data work location'),
        ),
        migrations.AlterField(
            model_name='socialloginsettings',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_login_methods', to='members.memberplatformsettings'),
        ),
    ]
