# Generated by Django 4.2.20 on 2025-12-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0013_alter_document_owner_alter_image_owner_and_more'),
        ('offices', '0004_add_permissions_20230130_1255'),
        ('members', '0103_merge_20251203_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='display_member_names',
            field=models.CharField(choices=[('full_name', 'Full name'), ('first_name', 'First name (members)'),
                                            ('first_name_strict', 'First name (also activity managers)')],
                                   default='full_name',
                                   help_text='How names of members will be displayed for visitors and other members.If first name is selected, then the names of initiators and activity manager will remain displayed in full and Activity managers and initiators will see the full names of their participants. And staff members will see all names in full.',
                                   max_length=50, verbose_name='Display member names'),
        ),
    ]
