# Generated by Django 4.2.20 on 2026-01-26 12:24

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0105_remove_memberplatformsettings_support_business_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='support_groups',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(), default=['Engineering Team', 'Support'], help_text='Groups that can login in using support accounts', size=None, verbose_name='Support login groups'),
        ),
    ]
