# Generated by Django 4.2.20 on 2026-02-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0105_auto_20260210_1340'),
        ('members', '0106_alter_member_gender_alter_member_primary_language_and_more'),
    ]

    operations = [
    ]
