# Generated by Django 4.2.20 on 2026-04-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('offices', '0005_alter_officeregion_options_and_more'),
        ('members', '0107_merge_20260224_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='office_manager',
            field=models.ManyToManyField(blank=True,
                                         help_text='Select one or more work locations to filter on. The user will only see data related to those selected office locations. Leave empty to show all data.',
                                         to='geo.Location', verbose_name='Work locations managed'),
        ),
    ]
