# Generated by Django 5.2.15 on 2026-07-03 10:46

import bluebottle.members.models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0039_merge_20260116_1155'),
        ('members', '0110_merge_20260703_0913'),
        ('offices', '0005_alter_officeregion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlesignonprovider',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='singlesignonprovider',
            name='requested_authn_context_comparison',
        ),
        migrations.RemoveField(
            model_name='singlesignonprovider',
            name='security_overrides',
        ),
        migrations.RemoveField(
            model_name='singlesignonprovider',
            name='sp_name_id_format',
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Non-binary'), ('none', 'I would rather not say')], max_length=8, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='office_manager',
            field=models.ManyToManyField(blank=True, help_text="Filter this user's view to specific work locations. Leave empty to show data from all locations.", to='geo.location', verbose_name='Work locations managed'),
        ),
        migrations.AlterField(
            model_name='member',
            name='primary_language',
            field=models.CharField(choices="[('en', 'English')]", default='en', help_text='Language used for website and emails.', max_length=7, verbose_name='primary language'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subregion_manager',
            field=models.ManyToManyField(blank=True, help_text="Filter this user's view to one or more location groups. Leave empty to show data from all locations.", to='offices.officesubregion', verbose_name='Work location groups managed'),
        ),
        migrations.AlterField(
            model_name='memberplatformsettings',
            name='support_groups',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(), default=bluebottle.members.models.default_support_groups, help_text='Groups that can login in using support accounts', size=None, verbose_name='Support login groups'),
        ),
        migrations.AlterField(
            model_name='singlesignonprovider',
            name='admin_login',
            field=models.BooleanField(default=True, help_text='When enabled, staff can log in to the admin via SSO.', verbose_name='Admin login'),
        ),
        migrations.AlterField(
            model_name='singlesignonprovider',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_providers', to='members.memberplatformsettings'),
        ),
        migrations.AlterField(
            model_name='singlesignonprovider',
            name='sp_acs_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='SP assertion consumer URL'),
        ),
        migrations.AlterField(
            model_name='singlesignonprovider',
            name='sp_sls_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='SP single logout URL'),
        ),
    ]
