# Generated by Django 4.2.20 on 2025-12-11 15:29

import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentplugins', '0005_auto_20170818_1441'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pictureitem',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='pictureitem',
            name='align',
            field=models.CharField(choices=[('float-left', 'Float left'), ('center', 'Center'), ('float-right', 'Float right')], max_length=50, verbose_name='Align'),
        ),
        migrations.AlterField(
            model_name='pictureitem',
            name='image',
            field=bluebottle.utils.fields.ImageField(upload_to='content_images', validators=[bluebottle.utils.validators.FileMimetypeValidator(['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml'], None, 'invalid_mimetype'), bluebottle.utils.validators.validate_file_infection], verbose_name='Picture'),
        ),
    ]
